### ISSUE TITLE
redoc-cli bundle couldn't make introduction headnings into side menu

### ISSUE THREAD

**Issue by robindou** [Redocly/redoc#1001]
As the title says, when i use redoc-cli bundle command, headings in introductions couldn't appear in side menu. Here are two cases:

1. If i use redoc standalone (instead of redoc-cli bundle),  headings (example, ## I AM HEADING) in descriptions of tags will appear in left side menu of the tags.
![111](https://user-images.githubusercontent.com/49221973/62459184-4f5b7900-b7b1-11e9-842a-1c4e40b17d94.png)

2. If i use 'redoc-cli bundle' command to generate a static html file, headings (example, ## I AM HEADING) in descriptions of tags will appear in left side menu of the tags.
![222](https://user-images.githubusercontent.com/49221973/62459333-b4af6a00-b7b1-11e9-8ad4-111399ae040e.png)

Thanks team for your work!

**Comment by nanov** [comment]
Are you using the latest version of redoc-cli?

**Comment by RomanHotsiy** [comment]
Can't reproduce using latest cli.

Try to use headings with different names though.

**Comment by nanov** [comment]
I assume he didn’t update his **global** redoc-cli.

**Comment by robindou** [comment]
> 
> 
> Are you using the latest version of redoc-cli?

Hello Nanov, I was using redoc-cli version 0.8.4

**Comment by nanov** [comment]
@robindou the latest version is 0.8.6, did updating the version solved your problem?
