### ISSUE TITLE
Time series doc showing Object label instead of Internal and External Ids

### ISSUE THREAD

**Issue by hhenriques** [Redocly/redoc#1003]
The API documentation for the Time Series has a minor label bug when choosing between `TimeseriesInternalId `or `TimeSeriesExternalId`:

![image](https://user-images.githubusercontent.com/48646777/62467153-52e00780-b793-11e9-922f-f2e9fe13c679.png)

As a reference, this is the same context but in the Assets section:

![image](https://user-images.githubusercontent.com/48646777/62467233-86229680-b793-11e9-8e8a-ca029b21d9b6.png)

**Comment by RomanHotsiy** [comment]
Could you share corresponding schemas?

**Comment by hhenriques** [comment]
Sorry, I actually created an issue on the wrong repo! It's an internal issue.
