### ISSUE TITLE
What is the best way to render vendor extenstions?

### ISSUE THREAD

**Issue by ZsZs** [Redocly/redoc#1004]
Hi,
We have a bunch of OpenAPI 3.0 extensions, like x-outbound-servers or x-outbound-security or x-outbound-path. We'd like to display these extensions in various points of the generated HTML. Basically, near to the relevant "normal" interface property.
2 years back @RomanHotsiy, suggested using before/afterMarkdownRender hooks for displaying diagrams. See: https://github.com/Redocly/redoc/issues/266; Is this still the proposed way to write a kinda plugin? If yes, how can I find, configure these hooks?

Thank you for your help.

**Comment by RomanHotsiy** [comment]
It was just a proposal. It was not implemented since then.

Check out https://github.com/Redocly/redoc/pull/552. I think it can fit your needs.

**Comment by ZsZs** [comment]
Thank you for the promt feedback, I'll look at that solution today.

**Comment by lornajane** [comment]
I'm going to assume this suggestion answered the question, and close the issue.
