### ISSUE TITLE
allowReserved on parameters does not prevent percent-encoding

### ISSUE THREAD

**Issue by shawndibble** [Redocly/redoc#1010]
So I have some query parameters where a get request can look like `/categories/?id=in:5,8,12`. I am trying to figure out how I can get the example to look like the above or at least `id=in:5,8,12`. I see that `allowReserved` is suppose to prevent percent-enconding, however on my output, I get `id=in%3A5%2C8%2C12`.

How do I get it so that my example look as desired?

```
"CategoriesListing_id": {
  "name": "id",
  "in": "query",
  "required": false,
  "allowReserved": true,
  "schema": {
    "type": "string"
  },
  "example": "in:5,8,12"
},
```

**Comment by TheM1984** [comment]
I am looking for the same thing.
We are currently using an old version 2.0.0-alpha.41, which doesn't do the formatting.

Looking into the repo I have the feeling that allowReserved is present in that models, however never used.

[rfc3986](https://tools.ietf.org/html/rfc3986#page-50) states: 

> query           = *( pchar / "/" / "?" )
> 
> pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
> 
> unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
> pct-encoded   = "%" HEXDIG HEXDIG
> sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"  / "*" / "+" / "," / ";" / "="

**Comment by TheM1984** [comment]
I just tested some versions of redoc and found that the following does work:
```
"redoc": "2.0.0-rc.14",
"redoc-cli": "0.8.4",
```

So you can use the latest redoc version only not the latest version of redoc-cli.

**Comment by shawndibble** [comment]
Thanks for that solution. I do hope that this gets corrected soon so I can get back to pulling in redoc@next instead of an older version from May.

**Comment by TheM1984** [comment]
I have looked at the code and found that in that change, the uri-template-lite is used.

However the uri-template-lite has a different spec on what is allowed.

A quick and dirty fix would mean to use the allowReserved parameter and skip the template in that case. However as OpenAPI allows not only for one string example, but also or an array, it still requires some interpretation.


So far I couldn't create a good complete working solution, and with my own current time constraints I will not be able to do so in the next 3 months. Hopefully somebody else will pick this up before that.

**Comment by rafapaulin** [comment]
I am not sure if i am producing the schema correctly, but this 
```
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "$ref": "#/components/schemas/updateLabel"
                            },
                            "example": {
                                "name": "Awesome Label",
                                "trackingNumberId": "1,2,3"
                            },
                            "encoding": {
                                "name": {
                                    "allowReserved": true
                                },
                                "trackingNumberId": {
                                    "allowReserved": true
                                }
                            }
                        }
                    }
                },
```
is not working to avoid encoding those params.. 
it should be ok, considering the specs: https://swagger.io/docs/specification/describing-request-body/
anyone have any idea? (i am using the docker mode)

**Comment by TheM1984** [comment]
As stated in the comments above, the allowReserved is currently ignored by Redoc.

If it is comma's you are worried about, than there is an easy fix, namely put in a correct Example.
Your current example is a single string with comma's, that is something that should be encoded, you should create an array example and let ReDoc insert the comma's for you.

```
"example": {
  "name": "Awesome Label",
  "trackingNumberId": [1,2,3]
}
```
