### ISSUE TITLE
Server urls default variables displaying has been removed doing so confused the servers section

### ISSUE THREAD

**Issue by antherkiv** [Redocly/redoc#1012]
Server urls default variables displaying has been removed doing so confused the servers section, a better way to handle it I guess it's doing the behavior optional. To me, the current behavior means nothing at all, doing the whole documentation pointless. Because urls are so confused and doesn't have enough information to know nothing about the endpoint, the default value allows me to know where I can do a test request for example.

**Comment by antherkiv** [comment]
Hello there, the feature to render the default values in server variables has been removed, is it something wrong with the old behavior?

**Comment by RomanHotsiy** [comment]
Why you ever use the server URLs like this `{protocol}.{server}/{version}/blogs`.

Can your protocol, server or version can be configurable? If yes, how should the users of your documentation learn it if Redoc replaces those variables with default values?

If they are not configurable, why you ever use server variables? Could you please explain it.

**Comment by antherkiv** [comment]
Hi @RomanHotsiy  I recovered the functionality and made it optional in #1006 . Best regards.

**Comment by RomanHotsiy** [comment]
Resolved in https://github.com/Redocly/redoc/pull/1014

Thanks for the PR

New version is coming today.
