### ISSUE TITLE
Lazy Rendering for React Standalone

### ISSUE THREAD

**Issue by jared-jackson** [Redocly/redoc#1013]
I am using Docusaurus V2.0 to serve my OpenAPI specification file. Everything works great, but the load times are slower for one of our files that is rather large ~ 500 api.

I am currently using the Redoc ReactStandalone, as Docusaurus is written in React. 

Is it possible to add the lazy rendering that was introduced with this beta build into the react standalone? https://rebilly.github.io/ReDoc/releases/v1.6.0-beta.perf/redoc.min.js

Also open to alternative solutions.

Thanks.

**Comment by adamaltman** [comment]
That lazy loading didn't really solve the problem, and we abandoned that approach.  We've put a lot of effort into performance; however, so much that it's in our commercial version.  

https://www.youtube.com/watch?v=NcEHOlnAY6A&feature=youtu.be

**Comment by RomanHotsiy** [comment]
Lazy rendering added too much complexity and didn't solve the real issue.
