### ISSUE TITLE
HTML title generated is always "ReDoc documentation"

### ISSUE THREAD

**Issue by mfillon-ikentoo** [Redocly/redoc#1015]
I generate an HTML doc with **redoc-cli** based on an **openapi 3.0** yaml file.

The HTML page always have the title **ReDoc documentation**, even though the `info.title` element in openapi spec is filled with something else.

```
openapi: 3.0.0
info:
  version: '3'
  title: 'My title'
```

Is it possible to generate the HTML with the title from the openapi spec?

**Comment by RomanHotsiy** [comment]
`redoc-cli bundle <spec> --title "My Title"`
