### ISSUE TITLE
Left panel uses wrong font-family for HTTP method names

### ISSUE THREAD

**Issue by mtamme** [Redocly/redoc#1020]
The left panel uses font-family Verdana for HTTP method names and ignores the theme typography options. Verdana is not normally not available under Linux-Distros so the browser falls back to Time New Roman.

**Comment by lornajane** [comment]
This probably relates to an older version of the tool, so I'm closing this issue BUT if there's something in your Redoc font handling that doesn't look right with the current version, please open a new issue and show us your configuration (I'm on Linux so I can test it, if you can show what you're trying to do)
