### ISSUE TITLE
Operation doesn't show if tag groups are enabled and it does not have a tag.

### ISSUE THREAD

**Issue by afkoziol** [Redocly/redoc#1022]
I'm trying to use x-tagGroups and I understand that "...add all tags to a group, since a tag that is not in a group, will not be displayed at all!"  However, what about operations that aren't tagged?  Seems they don't appear either.  This forces all operations to have a tag and be in a tag group.  What if a bunch of operations can't be logically grouped and stand alone?

Thanks

**Comment by RomanHotsiy** [comment]
> What if a bunch of operations can't be logically grouped and stand alone?

You can always group those into `Other` group/tag.

But I'm wandering, what is your suggestion? Where to show those operations? If Redoc just puts them at the bottom of the menu it may be confused to belong to the last group.

**Comment by afkoziol** [comment]
I would expect them to be thrown at the bottom as you say.  It's similar to how they get thrown at the bottom when there are no groups defined.  They just appear after the last tag.  To avoid confusion, a horizontal rule could be added.  

![image](https://user-images.githubusercontent.com/29458248/63694746-209b5600-c7e5-11e9-9ece-f781d0f61cab.png)

I would think the same would apply to tags that are not grouped as well.  Basically anything that is left over (not tagged or tag not in a group) would be put at the end, after a HR, just as it would look without tagGroups defined.

This does a couple things.
First, it makes it easier to develop a large doc.  Perhaps one is adding a new api to an existing large document.  It may not be apparent at first where to group it but it still allows the api to be rendered and inspected.  I don't see any output in the CLI that indicates apis that won't be shown, by rendering them, it makes it easier to find these "rogue" apis when previously, they would just be missing.  

Second, as originally stated, not everything can be logically grouped.  Forced grouping may not make sense in all documents.  The "other" group would be an alternative but would now require an other tag as well.  Then this can lead to the problems noted above.

Thanks

**Comment by adamaltman** [comment]
I think the `Other` tag is the best solution for this issue. To show them would break existing use cases in the wild. And, if you need, you can lint your API definition to make sure each path has a tag.
