### ISSUE TITLE
Proposal: use apicurio-data-models library to parse/analyze OpenAPI content

### ISSUE THREAD

**Issue by EricWittmann** [Redocly/redoc#1023]
This is an update related to https://github.com/Redocly/redoc/issues/359 ::

For reference, I work on the [Apicurio Studio](https://www.apicur.io/) project, which is an open source API Designer.  One of the outputs of that work is a standalone library called **apicurio-data-models**.  It's a library that implements a data model for OpenAPI and AsyncAPI and includes the following useful features:

* Reading/writing OpenAPI/AsyncAPI documents
* Full visitor pattern for analyzing the data model
* Transform OpenAPI 2 documents into OpenAPI 3
* Validation of the data model
* Command layer (with basic operational transformation capabilities) to apply changes to the data model (probably not useful to ReDoc)

The source can be found here:  
https://github.com/Apicurio/apicurio-data-models

The library is here in NPM:
https://www.npmjs.com/package/apicurio-data-models

It's is written in Java but transpiled into TypeScript/JavaScript - this is useful for us because Apicurio Studio's back-end is written in Java while the front-end is Angular ... and the same code powers both.

It has no dependencies and it replaces/deprecates the older **oai-ts-core** library.

Previously (in #359) you mentioned that **oai-ts-core** lacked some features you need.  Regardless of whether **apicurio-data-models** is something useful to Redoc, I'd love to hear what those missing features are, since that might help us evolve the library to make it more useful broadly.

Either way, keep up the good work!

**Comment by lornajane** [comment]
Thanks @EricWittmann! I don't have anything particularly in mind right now so I'll tidy the issue away (and this has been open a while), but I really appreciate the reach out :)
