### ISSUE TITLE
DropdownLabel text color / visibility

### ISSUE THREAD

**Issue by drjonnicholson** [Redocly/redoc#1024]
The dropdown label added to the content type looks horrid in our case where we use white text on grey backgrounds.

Example:
![image](https://user-images.githubusercontent.com/7688837/63871128-3199c200-c9b3-11e9-8f87-ee7a020c7e09.png)

I see that the label is a styled div, which has a colour hard coded to be a slightly transparent version of the text colour on the right panel (https://github.com/Redocly/redoc/blob/master/src/components/PayloadSamples/styled.elements.ts#L16). I've tried changing the colour, but not found one where the `Response samples` text and the `Content type` text both look good and are readable.

I can see that the component allows for these labels to be turned off, but it's always enabled (https://github.com/Redocly/redoc/blob/master/src/components/PayloadSamples/PayloadSamples.tsx#L23)

Can these labels be a config option please?

**Comment by verstratenbram** [comment]
This is still an issue on version 2.0.0-rc.25
[https://imgur.com/a/fB3JBAK](https://imgur.com/a/fB3JBAK)
