### ISSUE TITLE
Request body schema is dissapearing

### ISSUE THREAD

**Issue by PCiszewski** [Redocly/redoc#1025]
This is a part of my YAML file. The issue is that when I am using allOf parameter to example list (on the right screen sight) don't know from where redoc is adding digit "2". When I delete one of examples to the list redoc is adding digit "1". When I choose it from the list in the "center" screen JSON Object is hiding :/ and I can only done f5 refresh to repair it. 
In my opinion something is not correct here. 

  /v1/paymentMethod/blik/chargeByAlias:
    post:
      tags:
        - BLIK API
      summary: BLIK one click transactions (UID)
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BlikOneClick"
			  

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:			  
    BlikOneClick:
      type: object
      discriminator:
        propertyName: type
        mapping:
          - alias: '#/components/alias'
          - alternativekey: '#/components/alternativekey'
          - blikCode: '#/components/blikCode'
    alias:
      type: object
      allOf:
        - $ref: '#/components/schemas/BlikOneClick'
        - type: object
          properties:
            token:
              type: string
              description: Token obtained from transaction registration
              example: 1A2B3C4D5E-A1B2C3-A1B2C3-1A2B3C4D5E
            type:
              type: string
              description: Set value „alias”
              example: alias
          required:
            - token
            - type   
    alternativekey:
      type: object
      allOf:
        - $ref: '#/components/schemas/BlikOneClick'
        - type: object
          properties:
            token:
              type: string
              description: Token obtained from transaction registration
              example: 1A2B3C4D5E-A1B2C3-A1B2C3-1A2B3C4D5E
            type:
              type: string
              description: Send value „alternativekey”
              example: alternativekey
            alternativeKey:
              type: string
              description: Value obtained as a response from chargeByCode 
          required:
            - token
            - type  
            - alternativeKey
    blikCode:
      type: object
      allOf:
        - $ref: '#/components/schemas/BlikOneClick'
        - type: object      
          properties:
            token:
              type: string
              description: Token obtained from transaction registration
              example: 1A2B3C4D5E-A1B2C3-A1B2C3-1A2B3C4D5E
            type:
              type: string
              description: Send value „blikCode”
              example: blikCode
            blikCode:
              type: string
              description: Value T6 entered by Customer
          required:
            - token
            - type             
            - blikCode     
			

![pic1](https://user-images.githubusercontent.com/53740634/63943954-ef36ba80-ca70-11e9-8535-21bcbc322a77.PNG)
![pic2](https://user-images.githubusercontent.com/53740634/63943955-ef36ba80-ca70-11e9-9683-57ca2c2e6494.PNG)
![pic3](https://user-images.githubusercontent.com/53740634/63943956-efcf5100-ca70-11e9-8e1f-b295fb483e8c.PNG)

**Comment by adamaltman** [comment]
This is probably an issue with your API definition.  It's hard to tell from what you pasted.

**Comment by PCiszewski** [comment]
The solve of the problem was to delete "-" character before **mapping** alias, alternativekey and blikCode. See code below:


    BlikOneClick:      
      type: object
      required:
        - token
        - type            
      discriminator:
        propertyName: type
        mapping:
          alias: '#/components/schemas/Alias'
          alternativekey: '#/components/schemas/Alternativekey'
          blikCode: '#/components/schemas/Blik_Code'
      properties:
        token:
          type: string
          description: Token obtained from transaction registration
        type:
          type: string
    Alias:
      description: alias description
      type: object
      allOf:
        - $ref: '#/components/schemas/BlikOneClick'
        - type: object
          properties:
            token:
              type: string
              description: Token obtained from transaction registration
              example: 1A2B3C4D5E-A1B2C3-A1B2C3-1A2B3C4D5E
            type:
              type: string
              description: Set value „alias”
          required:
            - token
            - type   
    Alternativekey:              
      type: object
