### ISSUE TITLE
The deprecated field does not apply if the `ref` field exists

### ISSUE THREAD

**Issue by Diarselimi** [Redocly/redoc#1026]
When I set a field as deprecated but it contains a `$ref` in it, then it won't show it as deprecated in the docs.
```
SomeResponse:
      title: 'Some Title'
      properties:
        reasons:
          nullable: true
          deprecated: true //<------ this wont show because of the $ref line.
          $ref: '#/components/schemas/OrderDeclineReason' //<------ if I remove this then it works
```

**Comment by knidarkness** [comment]
@Diarselimi , 

In the OpenAPI 3.0.x $ref is treated as [JSON Reference](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#referenceObject). And as it is stated in JSON (Reference docs)[https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3] 

> The "$ref" string value contains a URI [RFC3986], which identifies
>    the location of the JSON value being referenced.  It is an error
>    condition if the string value does not conform to URI syntax rules.
>    **Any members other than "$ref" in a JSON Reference object SHALL be
>    ignored.**
(bold is mine)

fields other then '$ref' are ignored.
