### ISSUE TITLE
Authentication shows up no matter what

### ISSUE THREAD

**Issue by martincognite** [Redocly/redoc#1030]
[This example](https://redocly.github.io/redoc/) does a good job showing how an openapi spec is rendered through redoc. However, it makes an attempt to "manually" explain the Authentication section by sneaking in `<SecurityDefinitions />`. However, it appears twice as it's also implicitly added it seems like.

Is it possible to _not_ show the `securityDefinitions` by default if `<SecurityDefinitions />` is present?

**Comment by RomanHotsiy** [comment]
Oh, that looks like a bug. I will check it up

**Comment by theoephraim** [comment]
+1

**Comment by RomanHotsiy** [comment]
This looks to be fixed already. Sorry, I forgot to close the bug.

**Comment by atruskot** [comment]
> Is it possible to not show the securityDefinitions by default if <SecurityDefinitions /> is present? 

@RomanHotsiy , it seems that the default behavior has not changed and the bug still exists?  Is there any documentation on how to control the automatic display of the authentication section?

**Comment by ezrapagel** [comment]
You can suppress the `Authentication` section by adding an unused `security-definitions` component:
```markdown
  version: 1.2.3
  contact: {}
  description: '<!-- ReDoc-Inject: <security-definitions> -->'
``` 
That breaks if you have actual security schemes or definitions. You can also source the definition from another ref'd markdown; if it's unused, it won't render the `Authentication` header.
