### ISSUE TITLE
Colapse subsections in left navigation menu

### ISSUE THREAD

**Issue by PCiszewski** [Redocly/redoc#1032]
Left menu, when you click an element section is opening subsections. After that I want to click once more on the same section to colapse/closed it. 
Is this functionality could be realized?

**Comment by TheM1984** [comment]
This is already possible, please check the readme before posting a question.

Take a look at:
https://github.com/Redocly/redoc#redoc-options-object

And look for menuToggle

**Comment by PCiszewski** [comment]
My mistake, thanks for quick reply.
