### ISSUE TITLE
Left menu not working properly.

### ISSUE THREAD

**Issue by PCiszewski** [Redocly/redoc#1033]
On 
https://redocly.github.io/redoc/#section/Authentication site:
I am clicking link after link and :
Introduction is highlighted
OpenAPI Specification is highlighted
Cross-Origin Resource Sharing is highlighted
Authentication faild - isn't highlighted 

I have the same problem on my site. The problem exist also on the other parts of left menu. 

This problem doesn't exist on https://rebilly.github.io/RebillyAPI/#section/Introduction
so you probably know how to fix it, am I right?

**Comment by PCiszewski** [comment]
Still waiting for some answer here.

**Comment by adamaltman** [comment]
![image](https://user-images.githubusercontent.com/1161871/65422125-380d3500-ddcb-11e9-9b7a-ff228e78a647.png)

It seems very sensitive, but in this case I was able to see the highlight with an abundance of caution.
