### ISSUE TITLE
Another problem with left navigation menu

### ISSUE THREAD

**Issue by PCiszewski** [Redocly/redoc#1034]
On https://rebilly.github.io/RebillyAPI/#tag/Custom-Fields site:
When I clicked on "Contact" links in left menu and after that I clicked on "CUSTOMERS" that cause the "Contact" link is not working anymore. 

The same you can done with clicking Bank Account after that PAYMENT INSTRUMENTS and after that Bank Acount link is not working anymore.

**Comment by adamaltman** [comment]
Video demo of bug:

https://www.loom.com/share/906c22815f4d4ec7a8cb9296e0ae004a

**Comment by PCiszewski** [comment]
Yes, this video is confirmed my observation of this bug. Thanks also for a little bit work around of this. :)
