### ISSUE TITLE
Chrome 77 & Redoc@1.22.2 - Method Promise.prototype.then called on incompatible receiver

### ISSUE THREAD

**Issue by yadue** [Redocly/redoc#1036]
Redoc@1.22.2 does not work with the lastest Chrome 77

It throws an error:
Uncaught (in promise) TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]

With that Chrome version and Redoc it doesnt work completly.

**Comment by RomanHotsiy** [comment]
Sorry for the long reply. I was traveling.
Checking it right now.

Meanwhile, I recommend switching to `2.0.0-rc.14`

**Comment by yadue** [comment]
@RomanHotsiy To quickly fix our live docs we tried to switch to 2.0.0-rc14 but it required additional migration to be done we didn't know how long could it possibly take. But we downgraded our version to 1.19.3 and it works again.

**Comment by RomanHotsiy** [comment]
@yadue thanks for extra information.

**Comment by RomanHotsiy** [comment]
@yadue 	have you tried `v1.20.0` or other versions before `v1.19.3`. Is `v1.19.3` the first version that works?

**Comment by yadue** [comment]
v1.19.3 is the last version from v1.x which works with latest chrome

**Comment by RomanHotsiy** [comment]
Fixed in `v1.23.3`

**Comment by rossdeane** [comment]
> Fixed in `v1.23.3`

v1.22.3?

**Comment by ArthurShvetsov** [comment]
@RomanHotsiy seems like `v1.22.3` version build failed and fix has not published to NPM

**Comment by RomanHotsiy** [comment]
Ah, I see. I just published it manually.

**Comment by ChrisTitos** [comment]
Thanks for the fix. Could you also make it available via this url?
https://rebilly.github.io/ReDoc/releases/v1.22.3/redoc.min.js

Thanks

**Comment by RomanHotsiy** [comment]
> Could you also make it available via this url?
Done

**Comment by phoenixgao** [comment]
It might be related to https://github.com/angular/angular/issues/32802
