### ISSUE TITLE
Adding a second spec file

### ISSUE THREAD

**Issue by kervinpierre** [Redocly/redoc#1038]
Hi,

I have a spec that has external references to other YAML files like this:

`'202':
          description: >-
            Accepted for [asynchronous processing](https://jsonapi.org/recommendations/#asynchronous-processing).
          content:
            'application/vnd.api+json':
              schema:
                $ref: 'jsonapi.yaml#/components/schemas/datum'`

This works with other document generators if I include the `jsonapi.yaml` file in the same folder as my main `openapi.yaml` source.

How can I include these external YAML files using ReDoc?

**Comment by knidarkness** [comment]
How do you run the ReDoc for this case? If you use redoc-cli either with bundle or serve commands it should be able to process such $refs just fine.

**Comment by lornajane** [comment]
I can't replicate this, so I'll close it. Please open a new issue with small file examples to show the problem if you run into it again?
