### ISSUE TITLE
How to show/tag that an API is in Beta version?

### ISSUE THREAD

**Issue by thanks92** [Redocly/redoc#1041]
Hi,

We do normally document APIs by using Redoc before it is released. Therefore I am wondring if it is possible to add a tag that shows the API is in Beta/New (or shows the API is avaliable in f.eks. version 1.2).

Something like this:
![image](https://user-images.githubusercontent.com/8996276/65328865-98c42400-dbb7-11e9-9f4d-56a6424d1a66.png)

**Comment by adamaltman** [comment]
Easiest:  add "Beta" to your summary text.

The summary supports strings but not markdown.  

The description on the other hand, supports markdown.  So you have options to implement that there.

Here are showing a few options (you would probably only choose one):

![image](https://user-images.githubusercontent.com/1161871/65390918-874e5980-dd28-11e9-85a8-92b8352cdac8.png)

```
      summary: >
        Beta: Add a new pet to the store
      description: >
        <mark>Beta:</mark> Add a new pet to the store.
        ![Beta](https://img.shields.io/badge/Status-Beta-yellow)
```
It's important to note that the summary also appears in the sidebar nav.  So, if it's important for someone to know as they head into it on the sidebar, then you should add that to the summary.
