### ISSUE TITLE
Support for spec versioning

### ISSUE THREAD

**Issue by vedavidhbudimuri** [Redocly/redoc#1042]
Is there any plan for API spec versioning? Just like the versioning, we have in apidocjs [http://apidocjs.com/#example-versioning]

**Comment by adamaltman** [comment]
Do you mean specifically displaying a diff? 

Or just toggling between versions?

**Comment by jaskinn** [comment]
For me, toggling between versions.

**Comment by vedavidhbudimuri** [comment]
@adamaltman yeah showing the diff you be really great and helpful for communication between developers and API consumers. Toggling will also be really helpful. 

Right now I felt http://apidocjs.com/#example-versioning is a good one.


Sorry for the delayed response.

**Comment by vedavidhbudimuri** [comment]
Any update on this?

**Comment by hasufell** [comment]
I'm also interested in *versioning* and *diffs*.

Right now, the only options for diffs I could find are:

* https://github.com/OpenAPITools/openapi-diff
* https://github.com/Azure/openapi-diff
* https://www.npmjs.com/package/openapi-diff
* https://bump.sh/ (proprietary service)

None of them worked really well for me. The bump.sh service is paid and basically a replacement for redoc. You either like it or you don't.

**Comment by gabrielmaldi** [comment]
Would love to be able to switch the API version using a dropdown or similar.

**Comment by samrae7** [comment]
I'd like this feature and would be willing to help implement

**Comment by Ikdemm** [comment]
Any updates regarding this? We'd love to see it happen

**Comment by lornajane** [comment]
The versions feature is available on our commercial hosted tools, but isn't planned for open source Redoc I'm afraid.

**Comment by benzkji** [comment]
Sorry, but this is not completed at all... LOL

**Comment by benzkji** [comment]
Redocly is not redoc, ins't it?

**Comment by brettgoss** [comment]
@lornajane Considering this is the repository for Redoc, which is the open source tool, should this issue really be closed as completed? As far as I know, Redoc doesn't support what is being requested here, besides using markdown with hardcoded links in the input spec.

I believe this feature would mostly entail providing redoc with a list of possible versions and the specs associated with each, and then a redoc generates dropdown to switch between them.

**Comment by lornajane** [comment]
Redoc is built, maintained and released as open source by Redocly. We do have other (excellent and much appreciated) contributors and we are open to code and documentation contributions from everyone. That said, we're making more of an effort to communicate well with you all about what is and is not likely to be worked on, and to give more clarity. There are many long-term issues open with people hoping for updates, and we'd like to be open about when those aren't likely to be coming any time soon. By closing this issue and others like it, Redocly is making it clear about our focus - meaning that anyone who would rely on this feature doesn't need to wait and hope that it might land one day.

(the point about "closed as completed" is a good one though, I'm changing the status!)

**Comment by hades200082** [comment]
The answers given as to why this is closed basically amounts to "you're not getting that feature for free - pay us for our hosted version instead" which is BS for an open source project.

**Comment by benzkji** [comment]
@lornajane would recommend to close conversations on this issue. @hades200082 every OS project is free to decide what features will be builtin, not? There are many projects going the "hybrid" way, some give all their functionality with OS versions, some keep back some features for their paid services. Nobody to blame here, IMHO.
