### ISSUE TITLE
Redoc React component errors out when used with Bootstrap

### ISSUE THREAD

**Issue by MikeChristensen** [Redocly/redoc#1043]
I'm trying to use [Redoc][1] as a React component.  I'm starting with the basic ASP.NET Core with React template in Visual Studio 2019, with all the default options.  I've followed the instructions on the Redoc page, and first ran:

> npm install redoc --save

And then ran:

> npm i react react-dom mobx@^4.2.0 styled-components

Both complete without errors.  Next, in home.js I add:

    import { RedocStandalone } from 'redoc';

When I go to the homepage on the app, I get the following error:

[![enter image description here][2]][2]

In the Chrome debugger I get the following stack trace:

[![enter image description here][3]][3]

The actual line is crashes on is:

    var ThemeContext = createContext();

Right now, my best guess is that there's some sort of incompatibility between Bootstrap and Redoc, but I don't know how to investigate or where to go from here.  Any ideas?

  [1]: https://www.npmjs.com/package/redoc
  [2]: https://i.stack.imgur.com/Zy1ZQ.png
  [3]: https://i.stack.imgur.com/qUrt0.png

**Comment by RomanHotsiy** [comment]
What do you use for bundling dependencies?

**Comment by MikeChristensen** [comment]
Not sure.  How do I check?

**Comment by lornajane** [comment]
This is pretty stale at this point, so I'm going to go ahead and close the issue. Happy to hear any feedback on current versions of the tool though.
