### ISSUE TITLE
SVG logo not displayed in Firefox

### ISSUE THREAD

**Issue by Trane9991** [Redocly/redoc#1048]
Hello.
We are having issue when SVG logo is missing when docs opened in Firefox (in Chrome and Safari everything is fine), see [api link](https://docs.getsocial.im/api/).

The current version is v2.0.0-rc.14, however, I tried locally on rc15 and issue is still present.

Thanks!

**Comment by RomanHotsiy** [comment]
Looks like this is issue with your SVG. Try setting width and height in you svg: https://stackoverflow.com/questions/21738612/svg-img-has-zero-dimensions-when-floated-in-firefox
