### ISSUE TITLE
ReDoc displayed differently under Linux to Windows

### ISSUE THREAD

**Issue by nathanjwtx** [Redocly/redoc#1052]
I have been using NSwag to generate my ReDoc page but have noticed that the resulting page displays differently depending upon whether I am in Windows 10 or Linux. 

![required_Swagger](https://user-images.githubusercontent.com/1558027/66050313-9b494680-e4f2-11e9-8b2f-9ca1e6932ae2.png)

The red "required" and the question mark don't appear in either Firefox or Chrome under Windows.

**Comment by RomanHotsiy** [comment]
Looks like you are using 1.x version of Redoc. It is in maintenance mode so only security issues will fixed there.

Please, consider upgrading to `2.x` release candidates.

**Comment by nathanjwtx** [comment]
Is this something I can do directly or does this require something done internally to the NSwag project?
