### ISSUE TITLE
code samples wrong theme

### ISSUE THREAD

**Issue by acidmk** [Redocly/redoc#1054]
![image](https://user-images.githubusercontent.com/12675793/66193799-91c00a00-e6bd-11e9-8e60-9657d049b57c.png)

Code samples block has weird theme

React code

```        
<RedocStandalone
    specUrl="http://rebilly.github.io/RebillyAPI/openapi.json"
    options={{
        hideDownloadButton: true,
    }}
/>
```

redoc version is ```^2.0.0-rc.16"```

**Comment by RomanHotsiy** [comment]
You must have external css affecting `pre` block background
