### ISSUE TITLE
New/Refreshed style for 2020

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redoc#1066]
Redoc's style was designed in 2015.  Is it time for a refresh?

This issue is a placeholder for people to comment on ideas for style or layout improvements or evaluation criteria.

Please participate by commenting below.

**Comment by SebastianStehle** [comment]
I have seen many failed projects where a redesign destroyed UX or/and conversion. So...why??? What do you want to improve? The issues are full with useful ideas for more features, the design should have a lower priority IMHO as it is already very good.

**Comment by lornajane** [comment]
Closing, no immediate action needed.
