### ISSUE TITLE
DependencyNotFoundError Could not find dependency: 'styled-components' relative to '/node_modules/redoc/bundles/redoc.lib.js'

### ISSUE THREAD

**Issue by Angelk90** [Redocly/redoc#1080]
I wanted to try redoc, with react js, but I'm having the following problem, here's an example:
[codesandbox](https://codesandbox.io/s/sad-visvesvaraya-tp6r4)

**Comment by gileswells** [comment]
In case anyone else comes along this issue, you needed to install peer dependencies. 

https://github.com/Redocly/redoc#usage-as-a-react-component

**Comment by jirutka** [comment]
Why is it defined as a peer dependency!

**Comment by RomanHotsiy** [comment]
@jirutka this is a recommended way to use styled-components in a library: https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

Thanks, @gileswells 🙏
