### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [Redocly/redoc#1081]
Hi @RomanHotsiy : I'm trying redoc with react js, there are some that I would like to understand better.

Based on the following example: https://codesandbox.io/s/aged-dream-sqwjr

1. I wanted to hide the Download button, through the hideDownloadButton props, but it doesn't seem to work.
2. When an element of cascading elements is opened to the right, it is no longer possible to close it, the only way to close it is to open another.
3. There is a way to customize the components, for example I would like to use the material design for the search field, with for example the following field: https://material-ui.com/components/text-fields/#textfield
4. In the part of the response for example it would be interesting to be able to put the numbers in the lines of code or even have a greater customization using the following module: https://www.npmjs.com/package/react-json-view

**Comment by lornajane** [comment]
Thanks for this feedback, @Angelk90 ! This issue has been open a while and we have released newer versions of Redoc since then, so I'll close this one but please upgrade and let us know how you get on?
