### ISSUE TITLE
Problem Ui menu server cascade

### ISSUE THREAD

**Issue by Angelk90** [Redocly/redoc#1083]
Hi @RomanHotsiy , 

I found the following problems here are some examples of images, and an example on codesandbox where you can verify everything.
Having only a response as a message, the space for the cascading server menu is restricted, so you can't see the menu completely.

Then the menu is cut as you can see.

Link: [codesandbox](https://codesandbox.io/s/wispy-leftpad-u2m23)

Smaller screen:
![open2](https://user-images.githubusercontent.com/20476002/67188069-e9fc4900-f3eb-11e9-809a-17a426cccf0c.png)

Full screen:
![Open](https://user-images.githubusercontent.com/20476002/67188068-e963b280-f3eb-11e9-9332-d0ebbc5092b3.png)

**Comment by AlexVarchuk** [comment]
@Angelk90 Hi, thank you for the issue and sorry for the vast delay 🙈 .
We try to reproduce it. It seems the problem was fixed. If not, please, add an additional step to produce.
