### ISSUE TITLE
Something went wrong... Error downloading http://localhost:8080/com.hendisantika.springbootrestswaggerexample.swagger.ui/v2/swagger.json NetworkError when attempting to fetch resource. 

### ISSUE THREAD

**Issue by TARIEPEACE** [Redocly/redoc#1084]
![image](https://user-images.githubusercontent.com/32386612/67292509-58700280-f4e3-11e9-9d99-6bf19a2999ef.png)

Something went wrong...
Error downloading http://localhost:8080/com.hendisantika.springbootrestswaggerexample.swagger.ui/v2/swagger.json NetworkError when attempting to fetch resource.

Stack trace

s/<@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:49:5301
e/</<@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:93:36105
K/<@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:61:130862
r@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:61:134422

ReDoc Version: 2.0.0-rc.18
Commit: 

The Error im getting after i run my html and starting my spring server anyone to help on location of my html file for redoc as well the spec url for SpringBoot.

**Comment by RomanHotsiy** [comment]
Most likely you don't have CORS enabled on your http://localhost:8080/com.hendisantika.springbootrestswaggerexample.swagger.ui/v2/swagger.json endpoint. This prevents Redoc from downloading it.

There is nothing that can be done on our side. Enable CORS for your swagger.json endpoint.

**Comment by TARIEPEACE** [comment]
@RomanHotsiy would you mind helping on adding the CORS and the structure of my files as well where i can put the html

THanks

**Comment by RomanHotsiy** [comment]
Sorry but I can't as I don't know any details about your setup.

**Comment by TARIEPEACE** [comment]
Awesome i managed to setup man thanks it was a link problem  i added the
api-docs link and it worked .

Now working on Customizing the interface any documentations you have on
that one



Regards.
Mango Tariro
