### ISSUE TITLE
Support for lazyRendering

### ISSUE THREAD

**Issue by imissyouso** [Redocly/redoc#1093]
Hi. Do you have a plan to add support of lazyRendering? 
We cannot use this pretty doc in reason of slow loading :(

**Comment by moodmosaic** [comment]
Any updates on this? IIRC, this was available in *Swashbuckle.AspNetCore.ReDoc 4.** and then it was removed in version 5.

**Comment by bendapkiewicz** [comment]
Any update on this? The performance is just not good.

**Comment by moodmosaic** [comment]
Yeah, or have *Swashbuckle.AspNetCore.ReDoc 4.** just work with ASP.NET Core 3?

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/redoc/issues/1615
