### ISSUE TITLE
Media Type Object Example does not accept Boolean

### ISSUE THREAD

**Issue by mitchs91** [Redocly/redoc#1095]
When attempting to use a boolean the example property of the Media Type Object, you are unable to use Boolean values as a valid example.

For example, this valid yml throws an error in Redoc, but is fine in other OpenAPI validators.

```yaml      
responses:
 '200':
   description: Success
   content:
     text/plain:
       schema:
         type: boolean
         example: true
```
Currently if you change example to a string or an object it will parse correctly.

Our use case is with Redoc Standalone.

**Comment by lornajane** [comment]
Sorry for the slow response on this one, I am pretty sure this is better when linting with the new [Redocly CLI](https://github.com/Redocly/redocly-cli/). I'll close this issue but do please let us know if there's anything else you need to sort this out.
