### ISSUE TITLE
Click on menu methods not scolling to section

### ISSUE THREAD

**Issue by gabrielspiteri-highlight** [Redocly/redoc#1101]
When clicking on the various methods nested underneath the tags, the URL updates correctly, however the page doesn't scroll to the section clicked. Clicking on the tag is fine, just not the methods.

**Comment by brucekaufman** [comment]
also seeing this.

**Comment by RomanHotsiy** [comment]
Could you provide more details? Maybe screen recording showing this or detailed steps of how to reproduce

**Comment by brucekaufman** [comment]
https://www.loom.com/share/d01691471a57448fbbb13ce4ef68215d

This video demonstrates the issue.  Clicking onto a tab brings me to the right section, but clicking on one of the methods takes me to the top of the file

**Comment by RomanHotsiy** [comment]
It's strange. Could you share you OpenAPI Definition or the redoc-cli output file.

**Comment by brucekaufman** [comment]
see attached.  sorry for delay I had to get permission to post

[Archive.zip](https://github.com/Redocly/redoc/files/3965054/Archive.zip)

**Comment by RomanHotsiy** [comment]
@brucekaufman you have tons of `operationId`s with the same value, while they MUST to be unique per specification.

Please, validate your OpenAPI Definition before rendering with Redoc.
