### ISSUE TITLE
Wrong precedence in release order: v2.0.0-rc.8-1

### ISSUE THREAD

**Issue by ehotting** [Redocly/redoc#1103]
We use [Renovate Bot](https://github.com/renovatebot) to automatically upgrade dependencies in our project. Renovate now suggests a Redoc upgrade that is actually a downgrade. [It proposes](https://gitlab.com/commonground/nlx/nlx/merge_requests/1074) to upgrade from version 2.0.0-rc.18 to 2.0.0-rc.8-1.

I believe the reason is to be found in [Semver spec item 11](https://semver.org/#spec-item-11):

`(..) Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. (..)`

The problem seems to be that creating `2.0.0-rc.8-1`  did not take into account the rule `Numeric identifiers always have lower precedence than non-numeric identifiers`. 

The one release with `rc.8-1` ([link](https://github.com/Redocly/redoc/releases?after=v2.0.0-rc.9)) now takes precedence over every release with just `rc.$number`

If my analysis is correct, is there something that can be done about it? Since right now, upgrading Redoc dependency with any form of automated tool that decides which release to use by ordering via Semver spec is broken - we had to blacklist redoc in the Renovate bot configuration.

**Comment by RomanHotsiy** [comment]
Hey @ehotting,

Thanks for bringing it up!

I now deprecated `2.0.0-rc.8-1` on npm so hopefully it will fix the issue.

Feel free to reopen this if it doesn't.
