### ISSUE TITLE
Markdown table description issue

### ISSUE THREAD

**Issue by coderbec** [Redocly/redoc#1113]
I'm having an issue with getting my table to render correctly. I am using this markdown: 

      | Name and preview | Template ID |
      |------------------|-------------|
      | ![image](Https://developers.messagemedia.com/wp-content/templates/Template1.png) | 7614456e-844f-4d83-bdfe-20c17ce0f97c |
      | ![image](Https://developers.messagemedia.com/wp-content/templates/Template2.png) | f56b5806-f732-4693-b87a-90b66a7d7bfc |
      | ![image](Https://developers.messagemedia.com/wp-content/templates/template3.png) | c9d7ce1d-20c4-4228-9ba1-6da2a3b4e5e0 |

with new line before and after. However, it's rendering half as a table and half not. What am I missing?

**Comment by huksley** [comment]
I can confirm @RomanHotsiy that table parsing are not working according to the documentation https://github.github.com/gfm/#tables-extension-

**Comment by huksley** [comment]
Solved by using 
```yaml
description: |
  multiline description with tables
```
instead of
```yaml
description: >-
  multiline description with tables
```
in YAML

**Comment by coderbec** [comment]
thanks this worked
