### ISSUE TITLE
Since 2.0.0-rc.11 - python markdown does not render correctly

### ISSUE THREAD

**Issue by vfalco02** [Redocly/redoc#1116]
I have python code in my markdown that was rendering fine until redoc@2.0.0-rc.11.

If I have the following code snippet in my markdown: 

```python
print('hello')
# Now print goodbye
print('goodbye')
```

It will not render past the comment, it just ignores the rest of the snippet and continues with the markdown.

I see 

```python
print('hello')
```

I tested with versions of redoc 2.0.0 from rc.4 to rc.18 and pinpointed to rc.11 as the breaking release.

Tried building using redoc-cli 0.8.3 and 0.9.2 (hard pinned redoc version)

**Comment by mipearson** [comment]
Confirmed here too -I've had to downgrade to redoc-cli 0.8.4

**Comment by djMax** [comment]
This still seems to be an issue...
