### ISSUE TITLE
labels for alternate sub-object definitions

### ISSUE THREAD

**Issue by freddrake** [Redocly/redoc#1125]
I have a specification that includes an array with a ``oneOf`` items:

~~~~~~ yaml
      type: array
      items:
        oneOf:
          - $ref: "schemas.yaml#/first-alternative"
          - $ref: "schemas.yaml#/second-alternative"
~~~~~~

The rendered results show:

![Screenshot from 2019-12-04 16-09-03](https://user-images.githubusercontent.com/588792/70181753-8767bf80-16b0-11ea-8adf-271066c43679.png)

Is there a way to provide more descriptive labels instead of ``object``?  It's accurate at the JSON level, but not particularly helpful for a reader.  I tried using ``x-displayName`` in the referenced YAML nodes, but that wasn't picked up.

**Comment by freddrake** [comment]
Not sure if it matters, but I'm using **redoc-cli** to generate static HTML.

**Comment by RomanHotsiy** [comment]
Add `title` to the referenced YAML nodes.

**Comment by freddrake** [comment]
Thank you!
