### ISSUE TITLE
scrollYOffset with floating point number

### ISSUE THREAD

**Issue by m-mohr** [Redocly/redoc#1129]
I've got a ReDoc instance running with scrollYOffset set to an header element. It seems that if the height of the header element is not a integer, but a floating point number the menu gets blurred a bit.

The problem occurs if you specify an element for the scrollYOffset which el.getBoundingClientRect().bottom returns a non-integer number for. It seems that in some places it works on integers and in some on floating point numbers and this leads to imprecision when calculation the scrolling position for the menu. Using Math.ceil or Math.round in normalizeScrollYOffset solved the problem for me. So I'd suggest only allowing integers as scrollYOffset and ensure in code that it is always an integer.

Hope this can be solved soon, thanks in advance!

Seems similar to #748

**Comment by RomanHotsiy** [comment]
What do you mean by `blurred`? Could you share a screenshot?

**Comment by m-mohr** [comment]
Sure, left is "blurred", right is "normal". Blurring only takes place after you scroll down at least one pixel.

![image](https://user-images.githubusercontent.com/8262166/70795459-2327b880-1da0-11ea-9455-b3399e91631d.png)

Fixed it for now for me by setting scrollYOffset to `() => Math.round(document.querySelector('header').getBoundingClientRect().bottom)` instead of just specifying the element `header`.

**Comment by m-mohr** [comment]
Interestingly, today I had a very similar issue on StackOverflow. Having seen that, I realized that this only happens in my Chrome instance, not in Firefox.

**Comment by lornajane** [comment]
I can't replicate this problem with the current version of Redoc and this issue has been open for a while, so I'm closing it. If that seems incorrect and things still don't look right, open a new issue and let us know what version of Redoc you're using now, and what seems wrong.
