### ISSUE TITLE
minItems and maxItems are not renders for array in request body

### ISSUE THREAD

**Issue by weismantelf** [Redocly/redoc#1131]
Hello,

I am using the following definition to define an array of objects in the request body:

`               "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                  "type" : "array",
                                  "minItems" : 1,
                                  "maxItems" : 10,
                                  "items" : {
                                         "$ref": "#/components/schemas/gpsProfileUpdate"
                                   }
                            }
                        }
                    }
                }
 `

The minItems and maxItems were not rendered in the generated documentation.

![image](https://user-images.githubusercontent.com/58665051/70393838-ef8b0e00-19ee-11ea-9263-94fd62166a42.png)

**Comment by RomanHotsiy** [comment]
Oh. I see.
Do you have any ideas on where to put this info?

**Comment by m-mohr** [comment]
Either 

1. above "One Of" with respective labels 
    > Minimum number of items: 1
    > Maximum number of items: 10

  or

2. something inspired by programming languages where you specify the number of items in brackets (e.g. C: `array[5]` or Java: `new ArrayList(5)`):
    > Array (1 - 10) [
    > Array (no. of items: 1 - 10) [

Of course, if it's minItems = maxItems it would be better to just render 
> Array (5)

Just some ideas...

**Comment by adamaltman** [comment]
I think option 1 would be the most clear to understand as a reader.

**Comment by adamaltman** [comment]
Although, option 2 could be nice.  It may be more clear with the "items" word added to it:

range:
```
Array (1-5 items)
[
```

max == min (exact number)
```
Array (2 items)
```

max-only:
```
Array (5 or less items)
```

min-only:
```
Array (1 or more items)
```
It may be a pain though.  You have to worry about pluralizing "item" depending on the number of items.

**Comment by AntonKozachuk** [comment]
Fixed by https://github.com/Redocly/redoc/pull/1308.
