### ISSUE TITLE
Response with no content isn't rendered

### ISSUE THREAD

**Issue by TheodoorP** [Redocly/redoc#1132]
I've got a delete endpoint that returns a 204 when the request was processed succesfully, however this response isn't actually rendered in redoc. See the following example:
```
responses:
  '204':
    description: 'Ok: Successfully processed the request.'
  default:
    description: 'Error: Something went wrong'
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'
```
![image](https://user-images.githubusercontent.com/17050455/70394271-dafd4480-19f3-11ea-84d5-8d0ed399d174.png)

Shouldn't redoc display that there's more than just an error response?

**Comment by RomanHotsiy** [comment]
This is Response Samples section. This response doesn't have nor example nor content so I there is no content to show there.

The 204 response is shown in the middle panel though.
