### ISSUE TITLE
docker "redoc-cli" WARN dependecy issue 

### ISSUE THREAD

**Issue by abhikt48** [Redocly/redoc#1133]
Hi Team,

I am getting below **WARN** message while installing docker "redoc-cli". I am new into this, so i am not sure what could be the impact of below WARN messages, but definitely it will be great to avoid below WARN messages.

`npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`

`npm WARN react-hot-loader@4.12.18 requires a peer of @types/react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/redoc-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

**Used DockerFile script**
`FROM node:alpine

RUN npm install -g redoc-cli

WORKDIR /data
EXPOSE 8080

ENTRYPOINT ["redoc-cli"]
CMD []`

Regards,
Abhishek Kumar

**Comment by RomanHotsiy** [comment]
This is not important. I will fix `react-hot-loader` but I can't do anything about core-js warning for now unfortunately
