### ISSUE TITLE
Can the download button generate a swagger 2.0 json file?

### ISSUE THREAD

**Issue by darkantoine** [Redocly/redoc#1137]
Hello,

I wrote an api spec using swagger 2.0 version. I then generated the HTML specs file using redoc-cli. When I use the download button, the file generated is  an OAS 3.0 file. Is there a way to keep it as a swagger 2.0 file?

**Comment by RomanHotsiy** [comment]
You can specify alternative url to the definition using `specUrl` option when using redoc-cli:

`redoc-cli ... --options.specUrl='https://yoursite.com/swagger.json`
