### ISSUE TITLE
org.webjars.npm-redoc  taking too much memory, JAVA IDE hangs

### ISSUE THREAD

**Issue by abhikt48** [Redocly/redoc#1139]
Hi Team,

We want to use redoc with java for **redoc-cli**, so i started exploring redoc webjars and realised that it is taking too much memory , more than 8GB RAM. Mostly java IDE (Studio - eclipse compatible) hangs while using this dependency. It hangs most time, so not able to proceed further. I am not sure, using  **redoc-cli** with  redoc webjars is best option or not.

Could you please suggest your opinion on this issue.

`<dependency>
	<groupId>org.webjars.npm</groupId>
	<artifactId>redoc</artifactId>
	<version>2.0.0-rc.18</version>
</dependency>`

Regards,
Abhishek Kumar

**Comment by RomanHotsiy** [comment]
Please, contact developers of `org.webjars.npm-redoc`. I have no idea about this module.
