### ISSUE TITLE
how to use 'org.webjars.npm-redoc' (maven-java) as redoc-cli ?

### ISSUE THREAD

**Issue by abhikt48** [Redocly/redoc#1140]
Hi Team,

Can anyone please provide me any guidance/clue for - How to use 'org.webjars.npm-redoc' as **redoc-cli** ?

i need to convert api specification into HTML file with the use of **redoc-cli**.  We want to use 'org.webjars.npm-redoc' (maven-java) for HTML file conversion.

If anyone provide me any guidance/clue, that will be highly appreciated. Thanks in advance!!

Regards,
Abhishek Kumar

**Comment by RomanHotsiy** [comment]
Please, contact developers of `org.webjars.npm-redoc`. I have no idea about this module.

**Comment by abhikt48** [comment]
@RomanHotsiy  Thanks for information. Do you have any contact details/issue_url to report issue about
`org.webjars.npm-redoc`  ? If yes, could you please share contact details/issue_url to report this issue. I tried to find out, but i haven't found yet. 

Thanks in advance.
