### ISSUE TITLE
Missing Parameters with redoc 2.0.0rc19

### ISSUE THREAD

**Issue by AnthonyPorthouse** [Redocly/redoc#1142]
Query parameters are no longer appearing in rendered docs.

Repoduction case:

```yaml
openapi: 3.0.0
info:
  title: example
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /example:
    get:
      summary: list
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-example
      parameters:
        - schema:
            type: string
          in: query
          name: Example Parameters
          required: true
          description: ''
components:
  schemas: {}
```

Generated Output:

![Screenshot_2019-12-13 example](https://user-images.githubusercontent.com/5079595/70818581-fdb0a400-1dcb-11ea-8632-4c8e427b767e.png)

**Comment by RomanHotsiy** [comment]
😱

**Comment by RomanHotsiy** [comment]
Thanks! Just published rc.20

**Comment by RomanHotsiy** [comment]
Please, let me know if this fixes the issue

**Comment by AnthonyPorthouse** [comment]
Hey @RomanHotsiy thanks for the quick turn around! Yeah that seems to have resolved the issue for me!
