### ISSUE TITLE
query parameters not rendering anymore

### ISSUE THREAD

**Issue by jy95** [Redocly/redoc#1143]
Hello,

As the tile said, I think I discover a bug between the latest version of the cli (v0.9.4) and the previous versions (0.9.2-0.9.3) : 

**Expected result :** 

![image](https://user-images.githubusercontent.com/9306961/70872490-cf3bf000-1fa8-11ea-9efe-fc46a0ff1127.png)

**Got :** 

![image](https://user-images.githubusercontent.com/9306961/70872560-6012cb80-1fa9-11ea-8d9e-60e44be4b99f.png)

**To reproduce that :** 

1. Use this api.yml : https://raw.githubusercontent.com/SourceCodeOER/sourcecode_api/delete_exercises_and_tags/api.yml
2. Generate the documentation
```
npx redoc-cli bundle api.yml -o docs/index.html
```
3. Check if the query parameter of this endpoint ( add `#operation/getTags` for faster access )

PS: I checked that the file follows specification : 

![image](https://user-images.githubusercontent.com/9306961/70872553-496c7480-1fa9-11ea-92fb-f716c539b50f.png)

**Comment by RomanHotsiy** [comment]
Make sure you are using latest version of `redoc-cli`. npx may use cache.

I just tried running: 

    npx redoc-cli@0.9.4 bundle https://redocly.github.io/redoc/openapi.yaml

and I can't see the bug.

**Comment by RomanHotsiy** [comment]
0.9.3 was broken btw

**Comment by jy95** [comment]
Thanks : it seems you were right : npx used the broken version even if I specified la dernière version ...
