### ISSUE TITLE
Use `AND` instead of `OR` for multiple authentication options

### ISSUE THREAD

**Issue by milosmns** [Redocly/redoc#1147]
Hi,

I see this was already reported in #577, but it seems like it's not fixed.

I have the following code:

```yaml
"security": [
  {
    "AppID": []
  },
  {
    "AppSecret": []
  }
]
```

But it still generates:

![Generated](https://i.imgur.com/Ofl9xYK.png)

So, I get **OR** there instead of **AND**. Even if this is intentional, I'd like to change to **AND** instead (at least with a configuration option).

This is my full HTML:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>My API</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='my-api-on-gist.json' hide-download-button></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"></script>
  </body>
</html>
```

**Comment by milosmns** [comment]
I believe it's here: https://github.com/Redocly/redoc/blob/41a9b3c18228d236d182d3c15c9abc35ae72a0d5/src/components/SecurityRequirement/SecurityRequirement.tsx#L46

**Comment by RomanHotsiy** [comment]
This is per OAS spec, to get `AND` change your code to:

```json
"security": [
  {
    "AppID": [],
    "AppSecret": []
  }
]
```
See here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-requirement-object

**Comment by milosmns** [comment]
@RomanHotsiy interesting, I'll take a look! Thanks!
