### ISSUE TITLE
The ability to disable tags

### ISSUE THREAD

**Issue by bsramin** [Redocly/redoc#1149]
It would be convenient to have the possibility to deactivate in visualisation all calls of one or more tags. 
Use case: I have two views for the same documentation: a small one for a "quick start" and a full one. The endpoints will have more tags and depending on the view will be organized differently.

**Comment by RomanHotsiy** [comment]
You can run it as a preprocessing step before feeding you definition to Redoc.

Download your definition with your own js code, remove tags and then pass definition to `Redoc.init` (https://github.com/Redocly/redoc#advanced-usage-of-standalone-version)

This is out of scope for core Redoc.
