### ISSUE TITLE
Items formatted as headers render twice

### ISSUE THREAD

**Issue by coderbec** [Redocly/redoc#1152]
Item in tag description - i.e. section description sections, which are formatted as second order headers, such that they appear in the navigation, get rendered twice in the actual viewport. 

tag with name "development tools" in the description, has a part with this markdown

`## Postman Collections` - this then appears in navigation menu as desired, but gets rendered twice in the viewable screen

![Screen Shot 2020-01-09 at 2 06 13 pm](https://user-images.githubusercontent.com/9004716/72034649-ba255900-32e9-11ea-9c8b-83d9920ce051.png)

**Comment by m-mohr** [comment]
I have the same issue here: https://open-eo.github.io/openeo-api/draft/index.html#tag/Process-Graphs

**Comment by RomanHotsiy** [comment]
@m-mohr I can't see the issue in your docs. Could you point me to it?

@coderbec could you share you description?

**Comment by m-mohr** [comment]
@RomanHotsiy Have you scrolled down quite a bit? Several chapters are duplicated. For example, search for the heading 'Processes (Process Nodes)' in your browser and you'll see it twice with its following text although it is only once in the OpenAPI file.

First (correct) occurance:
![image](https://user-images.githubusercontent.com/8262166/72154346-b3154e00-33b0-11ea-8316-408fe99c345e.png)

Second (wrong) occurance:
![image](https://user-images.githubusercontent.com/8262166/72154358-ba3c5c00-33b0-11ea-9964-f2131486ad87.png)

**Comment by RomanHotsiy** [comment]
Thanks! Found it. Will fix it today.

**Comment by coderbec** [comment]
How do I get this to work with the github deployment option? https://github.com/Redocly/create-openapi-repo#generator-openapi-repo--

**Comment by thomasplevy** [comment]
@coderbec by default you'll load the "latest" release as tagged in GitHub, it looks like this fix was included rc.21 (https://github.com/Redocly/redoc/releases/tag/v2.0.0-rc.21). You can use the "redocUrl" in your redoc-config.yaml file located in the "web" directory:

```yml
# Use a specific build version
redocURL: https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.21/bundles/redoc.standalone.js
```

You can see how I've implemented for my api docs for a full working example here: 

https://github.com/gocodebox/lifterlms-rest/blob/278b74ad237d09ed035a6b115ba91fe5cd8d61f5/web/redoc-config.yaml#L23


Hope that helps
