### ISSUE TITLE
How to expend all on Response and Request Schema?

### ISSUE THREAD

**Issue by thanks92** [Redocly/redoc#1153]
I have a deeply nested schema for request and response. Is it possible to expend all elements on request and response shchema as a default?

Do you have any extensions for this? Like "x-extension"?

Picture: 
![image](https://user-images.githubusercontent.com/8996276/72064414-197c6c80-32dc-11ea-8fda-d276da3363fe.png)

**Comment by RomanHotsiy** [comment]
Dup of #211
