### ISSUE TITLE
Official docker image for redoc-cli

### ISSUE THREAD

**Issue by 414004738** [Redocly/redoc#1158]
I found the official docker image for redoc here: https://hub.docker.com/r/redocly/redoc. However, I was not able to find an official docker image for redoc-cli (although I did find a Dockerfile for it here: https://github.com/Redocly/redoc/blob/master/cli/Dockerfile). It would be nice if there was an official docker image for redoc-cli that could be used during a CI build to generate static API documentation.

**Comment by FeepingCreature** [comment]
Yes please!

**Comment by RomanHotsiy** [comment]
PR would be much appreciated!

**Comment by broothie** [comment]
> I found the official docker image for redoc here: https://hub.docker.com/r/redocly/redoc. However, I was not able to find an official docker image for redoc-cli (although I did find a Dockerfile for it here: https://github.com/Redocly/redoc/blob/master/cli/Dockerfile). It would be nice if there was an official docker image for redoc-cli that could be used during a CI build to generate static API documentation.

Built and pushed a docker image for redoc-cli from that Dockerfile. It's not official, but works for me for now. https://hub.docker.com/r/broothie/redoc-cli

**Comment by kierans** [comment]
> Built and pushed a docker image for redoc-cli from that Dockerfile. It's not official, but works for me for now. https://hub.docker.com/r/broothie/redoc-cli

Why not PR the Dockerfile into the repo?

**Comment by j616** [comment]
> > Built and pushed a docker image for redoc-cli from that Dockerfile. It's not official, but works for me for now. https://hub.docker.com/r/broothie/redoc-cli
> 
> Why not PR the Dockerfile into the repo?

As the author said, the Dockerfile already exists in the repo. It's just not being built and pushed to Dockerhub

**Comment by kierans** [comment]
@j616 Thanks for pointing that out. I clearly didn't read the comment properly 😆

**Comment by elsewhat** [comment]
Assume this issue can be closed now due to https://github.com/Redocly/redoc/pull/1614

Latest docker image is now pushed to github package and available at 
https://github.com/Redocly/redoc/pkgs/container/redoc%2Fcli

**Comment by RomanHotsiy** [comment]
@skadinna can we add the link to thee image above to the readme somewhere? Then we can close this issue.

**Comment by ericslandry** [comment]
In a directory where `swagger.yaml` exists, run:

```docker run --rm -v $(pwd):/api --workdir /api ghcr.io/redocly/redoc/cli:v2.0.0-rc.63 bundle swagger.yaml```

Which will create `redoc-static.html`.  Woot! 🎉 Thanks @elsewhat !

**Comment by osavchenko** [comment]
Now it works with a `latest` tag as well

**Comment by lornajane** [comment]
Please use the new CLI version, the instructions for Docker are here: https://redocly.com/docs/cli/installation/#a-iddockerarun-commands-inside-docker
