### ISSUE TITLE
Multiple response headers references not working

### ISSUE THREAD

**Issue by krystof-k** [Redocly/redoc#1162]
When I have

```yaml
…
  /endpoint:
    post:
      responses:
        201:
          headers:
            $ref: ./response-headers.yaml
        202:
          headers:
            $ref: ./response-headers.yaml
…
```

only the first headers are resolved correctly. I've tested it in Swagger UI and it renders fine there.

**Comment by RomanHotsiy** [comment]
This is a known limitation of the bundler we use right now in redoc. Bundle your definition before using with Redoc with [@redocly/openapi-cli](https://github.com/Redocly/openapi-cli)

**Comment by krystof-k** [comment]
This did help, thanks, but breaks the recursion even more than described in #1154.
