### ISSUE TITLE
Left menu is not visible in Chrome v80

### ISSUE THREAD

**Issue by eriolo** [Redocly/redoc#1170]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Steps to reproduce:**

- Browser: Chrome Version 80.0.3987.87 (Official Build) (64-bit)
- OS: macOS Version 10.14.6
- Redoc 2.x

Open html-file:

```
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    ReDoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>
```

At page load, the left menu expands and all seems fine.

![image](https://user-images.githubusercontent.com/5053464/74153067-01b44300-4c10-11ea-85a6-8d17e6d7fd81.png)

Navigating to one item in the expanded list also works.

![image](https://user-images.githubusercontent.com/5053464/74153112-21e40200-4c10-11ea-8504-9d095cd9ee11.png)

When scrolling up or down in the main content area the left menu disappears out of the view.

![image](https://user-images.githubusercontent.com/5053464/74153183-5061dd00-4c10-11ea-8c85-3a8ee61ca288.png)

The left menu works as expected in Safari v13.0.2, Firefox v72.0.2, and Chrome v79.

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/redoc/issues/1167?

**Comment by eriolo** [comment]
@RomanHotsiy Yes, sorry I missed that one. #1167 is marked as closed though, but I have verified locally that the problem still persists when using `redoc@2.0.0-alpha.23` https://github.com/Redocly/redoc/issues/1167#issuecomment-584197499

**Comment by RomanHotsiy** [comment]
Use rc.23 😄

**Comment by eriolo** [comment]
@RomanHotsiy thanks! 😅
