### ISSUE TITLE
RedocStandalone pass params example access token

### ISSUE THREAD

**Issue by Angelk90** [Redocly/redoc#1171]
Hi, I would need to pass parameters such as access token when the request is made to the web page, for security reasons.
Is there a way to do this?

**Comment by RomanHotsiy** [comment]
You can fetch you openapi definition yourself in js code and then init Redoc manually.

See [advanced usage](https://github.com/Redocly/redoc#advanced-usage-of-standalone-version)

E.g.:

```js
async function init() {
	const req = await fetch('https://example.com/openapi.yaml', { headers: {
	  'Authorization': 'Blah blah'
	}})
	const definition = await req.json();
	
	Redoc.init(definition, {}, document.getElementById('redoc-container'))
}

init();
```
