### ISSUE TITLE
Missing base path in example URL

### ISSUE THREAD

**Issue by lafrech** [Redocly/redoc#1172]
My API is hosted in a server subpath.

    https://domain.tld/api/v0/

More precisely, the docs and resources paths are

    https://domain.tld/api/v0/openapi.json  -> spec
    https://domain.tld/api/v0/  -> redoc page
    https://domain.tld/api/v0/pets/  -> pet list

However, the URL example for the pet resource is missing `/api/v0`:

    https://domain.tld/pets/

This happens since rc21. It was introduced in ed1db0c9027087ae0ae923e390e3e1d638a647ae, which was a fix for #1151.

There is no "server" property in the spec.

---------------------------------------------------------------

I'm not sure `/api/v0` should be stripped out.

https://swagger.io/specification/#oasObject

> An array of Server Objects, which provide connectivity information to a target server. If the servers property is not provided, or is an empty array, the default value would be a Server Object with a url value of /.

https://swagger.io/docs/specification/api-host-and-base-path/

> Relative URLs
> The URLs in the servers array can be relative, such as /v2. In this case, the URL is resolved against the server that hosts the given OpenAPI definition. This is useful in on-premises installations hosted on your customer’s own servers. For example, if the definition hosted at http://localhost:3001/openapi.yaml specifies url: /v2, the url is resolved to http://localhost:3001/v2.

My understanding is that `/` is a relative url. It "is resolved against the server that hosts the given OpenAPI definition". It is not clear to me whether this is `https://domain.tld/` or `https://domain.tld/api/v0/`.

I guess Redoc cannot know which part of the path is specific to the doc itself, so it can not discriminate those cases:

    https://domain.tld/api/v0/  <-- redoc + API go here, let's keep /api/v0

    https://domain.tld/api/v0/docs/  <-- redoc goes here, API one level higher, let's strip /docs

From my use case perspective, the current behaviour (stripping everything) is a regression, but I'm not certain the OAS spec agrees with me. Perhaps my use case is meant to be addressed by passing an explicit base path in `server`. That would be a pity but oh well.

**Comment by RomanHotsiy** [comment]
https://github.com/Redocly/redoc/commit/ed1db0c9027087ae0ae923e390e3e1d638a647ae fixed the behaviour to be spec-compliant

>  It is not clear to me whether this is https://domain.tld/ or https://domain.tld/api/v0/

The spec specifies that "Relative URL resolution rules follow RFC 3986", per RFC 3986 any relative reference starting with `/` is absolute-path reference and is resolved against authority which in your examples is `https://domain.tld/`, so:

```js
URL.resolve('https://domain.tld/api/v0/', '/') === 'https://domain.tld/'
```

A workaround for you may be setting empty relative URL in servers:

```yaml
servers:
  - url: ''
```

**Comment by lafrech** [comment]
Thanks for the clarification, the advice, and sorry for the noise.
