### ISSUE TITLE
redoc-cli styles are minified and the names change each version

### ISSUE THREAD

**Issue by hariustrk** [Redocly/redoc#1174]
We are trying to restyle the redoc output from a redoc-cli bundle output but the class names seem to change every version, which messes up our display everytime one of our devs takes an update of redoc-cli.

Anything we can do about this? Any option we could use to disable minification?

**Comment by RomanHotsiy** [comment]
This is per design. Use `theme` options to customize Redoc. Open a feature request if there are no theme options you need.
