### ISSUE TITLE
bundle/render bug, no background, giant letters

### ISSUE THREAD

**Issue by adamdecaf** [Redocly/redoc#1175]
I was trying out the latest RC `2.0.0-rc.23` and ran into a display bug. The problem looked like this (scrolled down a bit from the top).

<img width="1351" alt="Screen Shot 2020-02-14 at 12 05 50 PM" src="https://user-images.githubusercontent.com/120951/74563953-c02edb00-4f22-11ea-9b71-a25279d813a8.png">

The specification file is here: https://github.com/moov-io/api/blob/b9454ac70bc2b3e48a2030a46659ddc582fea21b/openapi.yaml 

I reverted to `2.0.0-rc.19` and everything works as expected. `npm install` grabbed the latest RC automatically.

**Comment by adamdecaf** [comment]
This was with Chromium: 80.0.3987.87 and Safari 13.0.5 (14608.5.12) on macOS 10.14.6.

**Comment by RomanHotsiy** [comment]
Do you see any errors in redoc-cli output? Maybe some in chrome dev-console ?

Could you consistently reproduce this issue?

Could you attach resulting `redoc-static.html` file here?

Thanks!

**Comment by adamdecaf** [comment]
Here's what the Chrome console reported, I think a sourcemap failed to parse? 

<img width="1438" alt="Screen Shot 2020-02-17 at 10 45 32 AM" src="https://user-images.githubusercontent.com/120951/74679464-c2877400-5172-11ea-9276-c812e2412598.png">

I can consistently reproduce this issue with a newer redoc. 

Here's [redoc-static.tar.gz](https://github.com/Redocly/redoc/files/4215635/redoc-static.tar.gz)

**Comment by RomanHotsiy** [comment]
Unfortunately I can't reproduce it locally.

Could you provide me with more detailed steps and env (node version, etc).
Also CLI output would help.

**Comment by adamdecaf** [comment]
I pushed up `moov/api:issue1175` to Docker Hub where this is broken. It's off the latest commit of the upstream repo. All I did was drop the `@v2.0.0-rc.19` constraint with `npm install -g redoc`. 

```
$ docker run --read-only -p '8000:8080' -v $(shell pwd)/nginx/cache/:/var/cache/nginx -v $(shell pwd)/nginx/run/:/var/run -it moov/api:issue1175
``` 

npm@6.14.2
redoc@2.0.0-rc.8-1 (`redoc@v2.0.0-rc.19` works)

**Comment by RomanHotsiy** [comment]
`redoc@2.0.0-rc.8-1` is indeed broken and it is deprecated on npm and it shouldn't be installed.

> All I did was drop the @v2.0.0-rc.19 constraint with npm install -g redoc.

I don't know where you drop it from.

> Maybe this isn't an issue (except for npm install -g redoc installing a pre-release version).

**Comment by adamdecaf** [comment]
I was installing `redoc` in this Dockerfile: https://github.com/moov-io/api/blob/b9454ac70bc2b3e48a2030a46659ddc582fea21b/Dockerfile#L2 

It only rendered properly when I forced `redoc` past rc.8-1: https://github.com/moov-io/api/blob/master/Dockerfile#L2 

I'll keep the `rc.19` pin in place for now, as `npm install -g redoc` gives you `rc.8-1` which is broken.

**Comment by RomanHotsiy** [comment]
`npm install -g redoc` shouldn't give `rc.8-1`. It's may be some caching on your system.

I was fixing it a while ago.

**Comment by adamdecaf** [comment]
Agreed. Thanks for the help on this. 👍
