### ISSUE TITLE
Scrolling is glitchy on Chrome 80

### ISSUE THREAD

**Issue by mkalam-alami** [Redocly/redoc#1177]
When opening a long spec on Chrome 80 / Windows, scrolling is broken, randomly jumping back to the top of the page. The sidebar also disappears while scrolling. See gif below for an example

Another PC using Chrome 79 did not present the issue. Firefox is OK as well.

* Reproduction spec: [openapi.zip](https://github.com/Redocly/redoc/files/4218399/openapi.zip)
* Reproduced using the default ReDoc HTML (latest CDN version, no custom settings)

![test2](https://user-images.githubusercontent.com/694508/74723300-a3ecb000-523a-11ea-98c7-04afe35ee4fc.gif)

(NB. I'm using the middle button scrolling for a smooth gif but the bug also occurs when scrolling normally).

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/redoc/issues/1170 ?

**Comment by Debbus72** [comment]
Don't know if this helps anyone, but on my machine with a long api the navigation-bar glitches when an item gets highlighted that is not completely visible. Tested with multiple sizes of the browser-window and each time an 'offscreen' item should be highlighted the page scrolls back to the top.

Browser: Microsoft Chromium/Edge Version 80.0.361.56 (Official build) (64-bit)
OS: Windows 10 Pro 64bit
ReDoc: 2.0.0-rc.22

**Comment by mkalam-alami** [comment]
@RomanHotsiy I confirm it is fixed with the rc.23. The bug is present in the `next` release, but not with an explicit `rc.23`, I'm not sure if that means the bug is back or the CDN is not up-to-date?

CDN link for the lazy:

```html
<script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"></script>
```

**Comment by mkalam-alami** [comment]
After checking the JS returned by `next` it's definitely a CDN issue, closing.
