### ISSUE TITLE
Failed to Fetch - CORS

### ISSUE THREAD

**Issue by MikeGriffinReborn** [Redocly/redoc#1181]
I have tried this in the most simplest setting, even with the pet store swagger.   It would seem to me that in the Redoc.js file the call to

<pre>
  redoc spec-url='http://petstore.swagger.io/v2/swagger.json'
</pre>

should be made with COR's headers? I might be confused on this. The only way I can get this to work is hit a REST API that adds those headers and returns the JSON in string form.

The standard html file on the Redoc site always yeilds ...

<pre>
Something went wrong...

Error downloading http://petstore.swagger.io/v2/swagger.json Failed to fetch
Stack trace
Error: Error downloading http://petstore.swagger.io/v2/swagger.json 
Failed to fetch
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:49:5419
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:108:36105

TypeError: Failed to fetch

ReDoc Version: 2.0.0-rc.22
Commit: 4289eb0
</pre>

Shouldn't the ReDoc.js make the request via javascript adding the CORS headers?

**Comment by crazyshot** [comment]
@MikeGriffinReborn Why did you close the issue? Did you find the solution? I have a similar issue, and would like to know what was wrong in your case.

**Comment by tancred27** [comment]
I'm using the RedocStandalone react component and I'm getting the same error. Can I know the solution?

**Comment by sayanthk-perfagents** [comment]
@tancred27 Did you fixed the issue ? If yes then please tell me how.

**Comment by ruimelodev** [comment]
If someone stumbles accross the same problem, my case was because my pages were producing HTTP URLs while my website was enforcing HTTPS URLs.
For me the fix was just using relative URLs.
Changed this:
```php
@extends('templates.redoc')

@section('content')
    <redoc spec-url="{{ asset('swagger/ecommerce.json') }}"
           hide-download-button
           lazy-rendering theme='{"logo": {"gutter": "20px"}}'></redoc>
@endsection
```
to this:
```php
@extends('templates.redoc')

@section('content')
    <redoc spec-url="swagger/ecommerce.json"
           hide-download-button
           lazy-rendering theme='{"logo": {"gutter": "20px"}}'></redoc>
@endsection
```
