### ISSUE TITLE
Main menu scroll fails with standalone

### ISSUE THREAD

**Issue by pauljohnston2009** [Redocly/redoc#1182]
on chrome (Version 80.0.3987.116 (Official Build) (64-bit)) the main panel does not stay in place when scrolling to the bottom of the page

**Reproduction**

using the example code in the readme for standalone

```
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    ReDoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>
```

scroll to the bottom of the page (without opening any of the menu items), the main menu moves off the page, and leaves white space when scrolling back to the top

![image](https://user-images.githubusercontent.com/21235196/74995659-41471e80-549d-11ea-80e0-ad16e9dbeb96.png)

tried a few different versions, and could not find one without the issue

It seems to be an issue with the transition from one menu item to the next (menu will disappear at transitions, and than begin moving to the top of the screen, and off the page)

**Comment by hugh-barclay** [comment]
I have the same issue. 

This started happening after upgrading to google chrome version 80.0.3987.116. It was previously working fine on an older 79.x chrome version.

**Comment by RomanHotsiy** [comment]
Dup of #1170 and #1177
