### ISSUE TITLE
redoc-cli side menu is not compatible with chrome Version 80.0.xxxx browser

### ISSUE THREAD

**Issue by novicesamurai** [Redocly/redoc#1183]
hi, I'm finding an issue with chrome browser using redoc-cli  produced .html file.

here is the screen capture

original
![image](https://user-images.githubusercontent.com/61443615/75212513-4678d600-57db-11ea-8d1e-59057dde606e.png)

and scroll down...
![image](https://user-images.githubusercontent.com/61443615/75212098-f9e0cb00-57d9-11ea-80d2-ddb05cfde775.png)

as you can see, side bar is not following the contents, #operation, #tag etc...
I am producing this issue with google chrome (Version 80.0.3987.116 (Official Build) (64-bit))

please let me know if need more information to assist.

**Comment by RomanHotsiy** [comment]
Dup of #1177 and #1168 ?

**Comment by novicesamurai** [comment]
yes, and sorry... as jpinkster commened on #1168 upgrading to 0.9.6 fixes the chrome issue
