### ISSUE TITLE
'next' tag is behind

### ISSUE THREAD

**Issue by ZimbiX** [Redocly/redoc#1184]
The [latest release](https://github.com/Redocly/redoc/releases) is now `2.0.0-rc.23`, but the `next` tag still points to the previous one.

However, I am only *assuming* that it's supposed to point to the latest one; I could not find a description for the tag.

Updating the tag that most people would be using is particularly important given the fix is in `2.0.0-rc.23` to the recent critical scrolling/sidebar breakage described in several recent issues:

- https://github.com/Redocly/redoc/issues/1182
- https://github.com/Redocly/redoc/issues/1183
- https://github.com/Redocly/redoc/issues/1177
- https://github.com/Redocly/redoc/issues/1170
- https://github.com/Redocly/redoc/issues/1168
- https://github.com/Redocly/redoc/issues/1167

This tag issue is present on both jsdelivr and unpkg, so does not appear to be a CDN issue as has been previously thought:

https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js
https://unpkg.com/redoc@next/bundles/redoc.standalone.js

The above URLs should instead be returning the same as this:

https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.23/bundles/redoc.standalone.js

**Comment by RomanHotsiy** [comment]
Updated `next` tag. Thanks for pointing out!

**Comment by RomanHotsiy** [comment]
It should be updated soon, depends on CDN providers
