### ISSUE TITLE
How can I provide a custom Loading screen?

### ISSUE THREAD

**Issue by caffeinatedMike** [Redocly/redoc#1187]
I would like to replace the current "Loading..." screen with an animated version of my company's logo. Is this easily done? And if so, how can I go about doing it? I'm utilizing the CDN method of loading Redoc, but I'm willing to use a different method if it means being able to (conveniently) modifying the loading screen.

**Comment by sagarpatel8384** [comment]
Also interested in this but have not found a way.

**Comment by caffeinatedMike** [comment]
@sagarpatel8384 Digging into the code, I think we'll have to override the default Loading component found [here](https://github.com/Redocly/redoc/tree/e2d0cd5b18e9f39ce28c743bc04ca4f7ba499f8e/src/components/Loading). But, I don't know how to yet. So, I'm hoping @RomanHotsiy or someone else to be able to offer some insight and/or a small code sample of how we can accomplish this 🤞

**Comment by hverlin** [comment]
You can hide the built-in loader with `hideLoading: true`. 
Add your custom loader component (e.g.`<div id='my-loader'></div>`)
Then, use the `onLoaded` callback to remove your custom loader

See https://github.com/Redocly/redoc#advanced-usage-of-standalone-version
```js
Redoc.init('http://petstore.swagger.io/v2/swagger.json',
 {  hideLoading: true },
 document.getElementById('redoc-container'),
 () => document.getElementById('my-loader').remove()
)
```

**Comment by RomanHotsiy** [comment]
@hverlin thanks for your answer. Closing this.

**Comment by neeerajtk** [comment]
Adding to @hverlin , For react functional component using redoc standalone we can achieve it using onLoaded functionality. 

Example:

    <>
      <RedocStandalone
        specUrl={dataSource}
        options={configuration}
        onLoaded={() => setLoading(false)}
      />
      {loading ? <Loader /> : ""}
    </>

`Note: ` Ensure `hideLoading ` is set to true in options
