### ISSUE TITLE
no rendering of example in components/schemas

### ISSUE THREAD

**Issue by m4sterbunny** [Redocly/redoc#1195]
components:
  schemas:
      MySchemaName:
          type: object
          properties:
                currency:
                      type: string
                      pattern: '^[A-Z]{2}$'
                      example: US
         required:
            - currency
renders as:
![image](https://user-images.githubusercontent.com/20266893/75784317-b6063c80-5d6a-11ea-8570-ba81776511e8.png)

**Comment by RomanHotsiy** [comment]
https://github.com/Redocly/redoc/pull/1058

**Comment by lornajane** [comment]
This was fixed in #1832 so it should be available in the most recent Redoc release. Please let us know if you need anything else though!
