### ISSUE TITLE
no rendering of required in response body

### ISSUE THREAD

**Issue by m4sterbunny** [Redocly/redoc#1196]
requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MySchemaName'

The required==true does not render into information for the user:
![image](https://user-images.githubusercontent.com/20266893/75784611-244aff00-5d6b-11ea-9c18-4d03ad6eef7f.png)

**Comment by RomanHotsiy** [comment]
What does "required" in response body mean? You may need `nullable` if you want to mark nullable fields.

**Comment by m4sterbunny** [comment]
i.e. the request body is required in the GET
hence boolean
required: true

How is this information presented to the user?
