### ISSUE TITLE
x-server looks for url field rather than a x-url field

### ISSUE THREAD

**Issue by amycen** [Redocly/redoc#1199]
The bug is due to the vendor extension `x-server` that are included in some of the spec files:
`
"x-servers": [
          {
            "x-description": "Alternative external URL",
            "x-url": "/api/demo/services/v1/"
          }
        ]
`
specs without x-servers renders properly.  But when x-servers is included it throws the below error:
```
Cannot read property 'startsWith' of undefined
```

When this field exists, is redoc about to pick up the `x-url` field instead of url?

**Comment by RomanHotsiy** [comment]
> is redoc about to pick up the x-url field instead of url

Redoc does correctly look for `x-url`. This is vendor extension and there is no specification for it. And you don't have to prefix all the internal fields with `x-` In Redoc we decided to support `servers` from OpenAPI 3 under `x-servers` vendor extension: https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-servers

**Comment by amycen** [comment]
Thanks for the response.  We noticed that when this field exists, the redoc mistakenly looks for a `url` field rather than a `x-url` field. The culprit is this line of code in the /node_modules/redoc/bundles/redoc.lib.js file:

`this.servers = normalizeServers(parser.specUrl, operationSpec.servers || pathInfo && pathInfo.servers || parser.spec.servers || []);`

I do not have the above error when `x-url` is renamed to `url` and it renders properly.

Should we rename all `x-url` to `url` under `x-servers`?

**Comment by RomanHotsiy** [comment]
> Should we rename all x-url to url under x-servers?

Exactly!

**Comment by amycen** [comment]
got it. thanks!
