### ISSUE TITLE
Chrome issues?

### ISSUE THREAD

**Issue by sluceno** [Redocly/redoc#1202]
We've been experiencing issues visualizing documentation in Google Chrome for the last 2 or 3 weeks

If we switch to Firefox or different browser, everything works as expected.

We are having issues on chrome, the sidebar is not shown properly and some components either.

Someone has had the same issues lately? We believe the issue is not in our side due it works on Firefox, but who knows.

**Comment by RomanHotsiy** [comment]
Dup of #1177, #1170, #1167, #1182
