### ISSUE TITLE
Response Samples Missing

### ISSUE THREAD

**Issue by dennis-luke** [Redocly/redoc#1205]
See the fairly simple example below where examples for each field are provided but when you look at the redoc page no response sample for 200 appears in the column on the right hand side. If you put the same underlying yml file through the swagger UI documentation generator you do get an example response defined for 200.

https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/dennis-luke/redoc-openapi-recursion/master/openapi-no-recursion.yml

There doesn't seem to be any explanation of why the sample doesn't appear, this might be helpful if it is a problem with the yml file.

Really love redoc and particularly how the response samples give you a very quick idea of what the endpoint returns.

**Comment by RomanHotsiy** [comment]
You are using OpenAPI 2 and we convert it internally to OpenAPI 3.
You definition is missing `produces` keyword which converts to `*/*` mime-type.

Check the fixed definition here: https://redocly.github.io/redoc/?url=https://gist.githubusercontent.com/RomanHotsiy/21e51225a31b55bf7e97a11e410508da/raw/7d015261a2ee5f9628d03d74643922c432b11463/another-test.yaml
