### ISSUE TITLE
Remove Console API from roadmap

### ISSUE THREAD

**Issue by louwers** [Redocly/redoc#1207]
The README states that a Console API is still on the roadmap.

However, it [was announced](https://github.com/Redocly/redoc/issues/53#issuecomment-576377856) that this is now a closed-source hosted thing and no longer on the roadmap for this version.

**Comment by wobeng** [comment]
I was very excited about this project until the console API was removed :(

**Comment by baboonmaj** [comment]
Me too,
Found out abt [RapiDoc](https://mrin9.github.io/RapiDoc/ ) from the issue #53 where it was announced to remove API console 

If anyone had any pros and cons to share ?

**Comment by raha1923** [comment]
maybe you can take a watch at my forked project to find a proper solution.

**Comment by fryck** [comment]
I don't understand this choice to remove this feature from the roadmap, it's a key feature and It's really heartbreaking to know that !

**Comment by louwers** [comment]
> I don't understand this choice to remove this feature from the roadmap, it's a key feature and It's really heartbreaking to know that !

It's a paid offering now.

**Comment by fryck** [comment]
> > I don't understand this choice to remove this feature from the roadmap, it's a key feature and It's really heartbreaking to know that !
> 
> It's a paid offering now.

Yeah ok, but I try on redoc.ly and I didn't see the "Try it out" feature

**Comment by RomanHotsiy** [comment]
@fryck it's disabled by default. You can enable it on Api Reference Settings -> Live Configuration

**Comment by lornajane** [comment]
This is no longer listed on the Roadmap, and as discussed, is available in the hosted tools.
