### ISSUE TITLE
How to use redoc to view a local API .json file

### ISSUE THREAD

**Issue by CDahmsCellarEye** [Redocly/redoc#1222]
I'm attempting to get this repository working with a local .json file in OpenAPI specification.  I'm using Ubuntu 18.04 if that matters.  First I cloned the repository:

```
cd ~
git clone https://github.com/Redocly/redoc.git
```

Then per the readme I made an html file:

```
cd redoc
touch index.html
```

Then I copy/pasted this HTML from the readme:

```
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    ReDoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>
```
into the index.html I just made.  Next I changed the line:
`<redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc>`
to
`<redoc spec-url='file://home/cdahms/MyApi.json'></redoc>`

Then upon opening `index.html` (I'm using Chrome) I get the error:

```
Something went wrong...
Unable to resolve $ref pointer "file://home/cdahms/MyApi.json"
Stack trace

ReDoc Version: 2.0.0-rc.26
Commit: 5bd2e62
```
Next I found issue https://github.com/Redocly/redoc/issues/149 and started trying some of the suggestions there.  1st I tried making my own server:

```
cd ~/redoc
python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```

So in Chrome I go to http://127.0.0.1:8000/ and get the error:

```
Something went wrong...
Unable to resolve $ref pointer "file://home/cdahms/MyApi.json"
Stack trace
SyntaxError: Unable to resolve $ref pointer "file://home/cdahms/MyApi.json"
    at Function.syntax (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:63:6628)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:75:35889

ReDoc Version: 2.0.0-rc.26
Commit: 5bd2e62
```
Next I went to the bottom of https://github.com/Redocly/redoc/issues/149 and tried the redoc-cli:

```
cd ~/redoc
redoc-cli bundle --help
```

I get:

`redoc-cli: command not found`

Then I tried:

```
cd ~/redoc/cli/
redoc-cli bundle --help
```

I still get:

`redoc-cli: command not found`

How can I use this repository to view a locally saved OpenAPI .json file?  Suggestions?

**Comment by c3rajkaramchedu** [comment]
@CDahmsCellarEye If you are still having this issue, this might help. I manually installed `redoc-cli` by executing this on my Macbook:
`npm install -g redoc-cli`
After that, it installed and I confirmed it by going: `which redoc-cli` and it gave me its path as `/usr/local/bin/redoc-cli`. This should set you free :- )

**Comment by RomanHotsiy** [comment]
@CDahmsCellarEye as @c3rajkaramchedu pointed, you have to install redoc-cli first or use `npx`:

```
npx redoc-cli bundle --help
```

**Comment by yassineabada** [comment]
Hi everyone,
you can use Redoc to documente an API using local .json file. You use Visual Studio Code to create html file for Redoc, and to unclude all APIs json file in Visual Studio code, after that you can install a server namely a Live server on Visual SCode, and run html file on local Server.

**Comment by drux007** [comment]
Is there yet a way to view a local API .json file? Besides having a web server.

**Comment by evgenia-rudenkova** [comment]
> Is there yet a way to view a local API .json file? Besides having a web server.

If you don't mind using Docker there is a way described in the repo as follows. So if you put .yaml or .json file in the folder "/usr/share/nginx/html" it is available for Redoc to build documentation.

docker run -it --rm -p 80:80 \
  -v $(pwd)/demo/swagger.yaml:/usr/share/nginx/html/swagger.yaml \
  -e SPEC_URL=swagger.yaml redocly/redoc

**Comment by tbebekis** [comment]
It's too late, but... here is my solution.

Rename `swagger.json` to `swagger.js`

Add the following line into the `swagger.js` as its first line
  `var spec = `

Use the following HTML page in the same folder as the `swagger.js`

```<!DOCTYPE html>
<html>
  <head />
  <body>
    <h1>Redoc in action</h1>
    <script src='swagger.js' type="text/javascript"></script>
    <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"> </script>
    <div id="redoc-container"></div>
    <script>
      Redoc.init(spec, {
        "expandResponses": "200,400"
      }, document.getElementById('redoc-container'))
    </script>
  </body>
</html>```
