### ISSUE TITLE
Badly need to split /paths into several files

### ISSUE THREAD

**Issue by bvn13** [Redocly/redoc#1227]
It is really hard to maintain /paths in one yaml file containing over 1500+ lines. Especially for a team. 

Here is a solution how to split it into several files: https://github.com/swagger-api/swagger-editor/issues/233#issuecomment-152661887

Is there a plan to implement such functionality?

**Comment by gamezfreak** [comment]
I've been using $ref in a top level OpenAPI yaml file to include the details from others.
See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#path-item-object

This is valid in the spec and works well in redoc and all the other OpenAPI tools I've been using.

>paths:
>  '/foo':
>    $ref: "./foo.openapi.yaml#/paths/~1foo"
>  '/foo/{id}':
>    $ref: "./foo.openapi.yaml#/paths/~1foo~1{id}"
>  '/bar':
>    $ref: "./bar.openapi.yaml#/paths/~bar"
>  '/bar/{id}':
>    $ref: "./bar.openapi.yaml#/paths/~bar~1{id}"

**Comment by RomanHotsiy** [comment]
@bvn13 the solution you linked is not spec-compliant so we won't support it in Redoc.

Check out https://github.com/Redocly/create-openapi-repo
