### ISSUE TITLE
Navigation issues in Safari

### ISSUE THREAD

**Issue by lucie-docs** [Redocly/redoc#1228]
Hi, 
The left side panel of our API reference seems to have become unusable in Safari: 
http://api-documentation.relayr.io/ 

Several co-workers reported not being able to click the options in the panel at all or having their location reset in the UI when they click an option. Scrolling up and down the panel is still possible though. 
I have opened the website in Safari myself to see what's happening and I cannot click the options.

Another colleague mentioned having his location reset in Chrome too when interacting with the panel. Everything seems to be working on my side in Chrome but I thought maybe this is worth mentioning. 

Anyone else with the same issue? Can someone help? Thanks :)

**Comment by RomanHotsiy** [comment]
Looks related to Content Security Policy header your server adds:

![image](https://user-images.githubusercontent.com/3975738/78870430-caff7b00-7a4e-11ea-9014-bc60073a9561.png)

Looks like worker-src is not supported by Safari, see for fallback options here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src

> Another colleague mentioned having his location reset in Chrome too when interacting with the panel.

Most likely related to #1177, #1170, #1167, #1182

Closing this as non-actionable on our side.

Feel free to continue the conversation here.

**Comment by lucie-docs** [comment]
Thank you! :)

**Comment by rajangdavis** [comment]
Hey, so I am running into the same issue with the Content-Security-Policy header; what do I need to do to get around this issue?

**Comment by RomanHotsiy** [comment]
CSP is configured on the your server so you need to update it there too to allow worker from blobs.

Alternativelly you can try adding this meta tag: 

```
<meta http-equiv="Content-Security-Policy" content="worker-src 'self' blob:">
<meta http-equiv="Content-Security-Policy" content="child-src 'self' blob:">
```
