### ISSUE TITLE
Forcing two-column layout

### ISSUE THREAD

**Issue by gaborcsardi** [Redocly/redoc#1234]
I think the layout looks great by default. However, I want to embed the API docs into another page, and that already has two columns, so it would be great to have a way to force a two-column layout in redoc. Is that possibe? Thanks!

**Comment by c3rajkaramchedu** [comment]
I am using `redoc-cli`. To remove the right panel I tried below approach, not working:

- Set the rightPanel width to 0% like this: `redoc-cli bundle -o test.html spec-tst.yaml --options.expandSingleSchemaField --options.expandResponses="all" --options.hideDownloadButton=true --options.theme.rightPanel.width="0%" ` but it did not remove it, but pushed the right panel further into the right side of the Chrome browser, giving me a horizontal scroll bar. Not what I wanted.

I thought I could modify the https://github.com/Rebilly/ReDoc/blob/master/src/theme.ts and remove the rightPanel object and any references to it, save it with a new filename, like mytheme.ts. But how do I include this "mytheme.ts" file as an option for the `redoc-cli bundle -o test.html spec-tst.yaml` command? Appreciate any insight! Thanks!

**Comment by RomanHotsiy** [comment]
This is not supported and is not planned in the near future.
Maybe we add an alternative layout in v3. But we still haven't released v2.0.0. Still in RC stage.

**Comment by ernestomonroy** [comment]
Just adding a +1

Our docs have two things that make the 3 column layout much inferior than the two column layout:

- Long paths that get trimmed (image below)
- A long introduction (in the description section as a MD file) which means there is a long empty right panel

**Comment by jrub** [comment]
This would be useful for `x-traitTag`s loading the typical API features explanations at the beginning (Auth, Pagination, Errors, versioning, that kind of stuff that complements and OpenAPI reference site)
