### ISSUE TITLE
Problem with swagger.json

### ISSUE THREAD

**Issue by b-dabrowski** [Redocly/redoc#1239]
Hi, 

I am using Redoc for a few swagger.json and it doesn't work correctly only with one of them.
I am trying to figure out what is wrong with the swagger.json file but I have no idea :/ 
All swagger.json files are generated in the same way.
Meaby you will be able to see what is the problem?

The swager.json that doesn't work:
https://pastebin.com/raw/AKeBbc9t

The error in Redoc:
https://redocly.github.io/redoc/?url=https://pastebin.com/raw/AKeBbc9t

**Comment by RomanHotsiy** [comment]
I get 404 for your URLs

**Comment by b-dabrowski** [comment]
@RomanHotsiy I fixed links :)

**Comment by RomanHotsiy** [comment]
![image](https://user-images.githubusercontent.com/3975738/79979125-ae7d2d00-84a9-11ea-980d-fa22f6a4beab.png)

`required` must an array in Schema Object: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#model-with-example
