### ISSUE TITLE
When using CDN, getting 66d14429db4e18077079.worker.js.map not found

### ISSUE THREAD

**Issue by harsh-sri** [Redocly/redoc#1240]
NodeJS version: 12.13.0
CDN Url: https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js

Note: I haven't installed the redoc using either npm or yarn.

**Comment by RomanHotsiy** [comment]
Any other details?

**Comment by harsh-sri** [comment]
Let me explain.

I've integrated redoc in HapiJs and loading the redoc from CDN only. So whenever i'm trying to access the API Docs, I'm getting 404 on console however i can access the doc and there is no issue with doc except 404. When i tried to debug this i found redoc is looking for 66d14429db4e18077079.worker.js.map locally.

**Comment by RomanHotsiy** [comment]
`js.map` is requested only when someone opens dev console. This is a source map to simplify debugging. There is nothing to worry about.
