### ISSUE TITLE
Automatically show valid UUID in example for correct 'format' member

### ISSUE THREAD

**Issue by cmeeren** [Redocly/redoc#1246]
I propose that if

```yaml
type: string
format: uuid
```

then ReDoc automatically shows a valid UUID as an example, e.g.

```
4eb92575-dab5-4fd9-9771-1552e676b966
```

ReDoc already does this for e.g. URIs (it shows `http://example.com`). Currently, there is no special handling for `uuid`, and the automatic example just shows `string`, similar to if there was no `format: uuid`.

~Similarly, I propose to show e.g. `user@example.com` if `format: email`.~

**Comment by gazoakley** [comment]
I think the example generation is handled in https://github.com/Redocly/openapi-sampler - it probably needs a PR there.

**Comment by gazoakley** [comment]
@cmeeren: Support for `email` should already be working - it generates examples for me correctly already (using `user@example.com`)

**Comment by cmeeren** [comment]
I can confirm `email` is working.

`uuid`, then :)
