### ISSUE TITLE
Download button opens new tab instead of downloading

### ISSUE THREAD

**Issue by kgemmert-r7** [Redocly/redoc#1247]
we have noticed an issue when moving to openApi 3.0 that the download button does not download but just opens the data in a new tab. 

we are using openApi 3.0 and https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js for the build script.

when using the local redoc-cli client to build, the download works fine.

I can see the same happening in your redoc page when downloading the docs: http://redocly.github.io/redoc/

To re-create you can try our api docs
https://help.rapid7.com/insightAccount/en-us/api/v1/docs.html

The download works fine with docs using openApi 2.0
https://help.rapid7.com/insightappsec/en-us/api/v1/docs.html

**Comment by c3rajkaramchedu** [comment]
I had the same issue and I fixed it by doing the following. See https://c3.ai/covid-19-api-documentation/ for example (the page might ask you to accept some terms but these are COVID-19 public docs, so no harm in accepting and getting to the page, methinks.)
- In your <a>...</a> tags, remove "https://<domainname>" and simply use the relative path to the file that you are expecting to download. Something to do with browsers not liking the cross domain and hence preventing download and instead opening it in a tab.
- Use the "download" parameter in the <a>...</a> like this: <a href="/folder/file.txt" download="file.txt">Download Txt file</a>

See our OpenApi spec to see how I did it. Hope it helps! 

Raj

**Comment by kgemmert-r7** [comment]
Thanks Raj, I manually changed that in the page and that worked and finally downloaded.

```<a target="_blank" download="insightAccount-api-v1.json" class="sc-tilXH jIdpVJ">Download</a>```

Do you know how this gets set though? Is it done by the redoc build script and I need to change arguments?

**Comment by c3rajkaramchedu** [comment]
> Do you know how this gets set though? Is it done by the redoc build script and I need to change arguments?
I don't know that, and glad it worked for you. I'll keep digging when I have a moment and post here anything new I learned.

**Comment by kgemmert-r7** [comment]
thank you for fixing so quickly @RomanHotsiy ! works like a treat :)

**Comment by jybp** [comment]
Is there any way after this change to have the open api YAML file open in a tab? 

Sharing a link to the yml file (like `https://api.myapi.com/openapi.yml` ) to API consumers who wants the specs and having it download is not a great UX. 
The UX of having it open in a tab is simply better, anyone can right click download.

Maybe a compromise could be having some GET flag like: `https://api.myapi.com/openapi.yml?in-browser=true`
