### ISSUE TITLE
CLI Generated Content has Console Errors in Safari

### ISSUE THREAD

**Issue by PeaceInColour** [Redocly/redoc#1249]
Did not see anything similar so creating a new issue.

**Bug:**
When loading a ReDoc CLI page the following two errors appear in Safari:

> Failed to load resource: the server responded with a status of 404 (Not Found) {path}/redoc.standalone.js.map
> Failed to load resource: the server responded with a status of 404 (Not Found) {path}/{uuid}.worker.js.map

Firefox does not have any errors or warnings while Chrome/Edge have warnings for the same source maps (this is likely due to a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1052872) in Chromium).

Loading [the live demo site](https://redocly.github.io/redoc/) in Safari did not produce these errors.

**Steps to Reproduce:**
- Install version 0.9.7 of redoc-cli from NPM
- Run `redoc-cli bundle some_open_api_file.json`
- Load generated HTML file in Safari 13 in Catalina
- Check Safari console

**Comment by RomanHotsiy** [comment]
`.js.map` resources are loaded by browser ONLY when you open a developer console. These are source maps to help with debugging and we don not ship it via CDN.

Just ignore these errors.

**Comment by adifelice-godaddy** [comment]
Sure. But it crashes the watcher on `serve --watch` mode which makes it annoying when testing different `--options`. I think there should be a way to disable source map references in the bundle file.
