### ISSUE TITLE
Embed images in self-contained html

### ISSUE THREAD

**Issue by ringgelerch** [Redocly/redoc#1250]
Hi,

I use redoc-cli to create a self-contained html file. If I don't miss anything the term 'self-contained' is only valid if you don't use any images. In my case I've to ship the images with the html file. Is it possible to embed these images into the html file?

Best regards
Christian

**Comment by RomanHotsiy** [comment]
There is no way you can embed images into text HTML file. Just place your images next to html file and link them.

**Comment by ringgelerch** [comment]
Could this be a solution:
http://www.websiteoptimization.com/speed/tweak/inline-images/

**Comment by RomanHotsiy** [comment]
So use it. In you md in openapi definition use such URLs:

```md
![some image](data:image/gif;base64,R0lGODlhEAAOALMAAOazToeHh0tLS/7LZv/0jvb29t/f3//Ub/
/ge8WSLf/rhf/3kdbW1mxsbP//mf///yH5BAAAAAAALAAAAAAQAA4AAARe8L1Ekyky67QZ1hLnjM5UUde0ECwLJoExKcpp
V0aCcGCmTIHEIUEqjgaORCMxIC6e0CcguWw6aFjsVMkkIr7g77ZKPJjPZqIyd7sJAgVGoEGv2xsBxqNgYPj/gAwXEQA7)
```

You can use custom-script for this before passing openapi definition to redoc-cli.

We won't add automatic images inlining into redoc-cli.
