### ISSUE TITLE
2.0.0-rc.28 t.required.indexOf is not a function

### ISSUE THREAD

**Issue by cnizzardini** [Redocly/redoc#1261]
Getting the following error with 2.0.0-rc.28. This same schema loads into Swagger just fine.

> t.required.indexOf is not a function
> Stack trace
> TypeError: t.required.indexOf is not a function
>     at http://localhost/redoc.standalone.js:130:54204
>     at Array.map (<anonymous>)
>     at http://localhost/redoc.standalone.js:130:54018
>     at e.init (http://localhost/redoc.standalone.js:130:54727)
>     at new e (http://localhost/redoc.standalone.js:130:51696)
>     at new e (http://localhost/redoc.standalone.js:130:59448)
>     at http://localhost/redoc.standalone.js:130:60804
>     at Array.map (<anonymous>)
>     at new e (http://localhost/redoc.standalone.js:130:60752)
>     at new Gt (http://localhost/redoc.standalone.js:130:61517)
> 
> ReDoc Version: 2.0.0-rc.28
> Commit: 18dbd62

**Comment by RomanHotsiy** [comment]
`required` should be an array in Schema objects. You probably use `required: true`

See example here, boolean in parameters, `array` in the schema:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operation-object-example

![image](https://user-images.githubusercontent.com/3975738/82322043-85838580-99de-11ea-9641-808db7dd4e8f.png)

**Comment by cnizzardini** [comment]
Yes, this was the issue. I thought I had run it through the schema validator before posting this. Thanks.
