### ISSUE TITLE
Response chevron color

### ISSUE THREAD

**Issue by BBlowers** [Redocly/redoc#1262]
When using the default theme 3xx response schema chevrons are black.
![image](https://user-images.githubusercontent.com/19273139/82345851-a8696600-99ed-11ea-9415-677a6a003e84.png)

The chevron and the response code text use different parts of the theme prop for their colors.
Chevron:
src/common-elements/shelfs.tsx:46
(`theme.colors.redirect`)

Response code:
src/components/Responses/styled.elements.ts:9
(`theme.colors.responses.redirect`)

The `theme.colors.redirect` section of the theme doesn't exist by default which is why the chevron is black.

**Comment by RomanHotsiy** [comment]
Thanks for so detailed issue. PRs are welcome!
