### ISSUE TITLE
Need to track event onClick of copy button 

### ISSUE THREAD

**Issue by vishals9711** [Redocly/redoc#1265]
- Is there any way to track the click event of the copy button when it is clicked in the response sample?

Help wanted on this.

**Comment by RomanHotsiy** [comment]
could you explain your use case?

**Comment by vishals9711** [comment]
I am using analytics to track user actions.
Hence I wanted a way to communicate if the copy button has been clicked on the right nav.

**Comment by RomanHotsiy** [comment]
This is out of the scope of this project.
