### ISSUE TITLE
[OAS3] when summary is empty, use $request_type $path

### ISSUE THREAD

**Issue by mariusa** [Redocly/redoc#1270]
When summary is empty, the generated docs have 'no summary'

Instead, use '$request_type $path' as a summary, eg
GET /users/{username}

Thanks

**Comment by hyzyla** [comment]
Created pull request with improvement

![Selection_477](https://user-images.githubusercontent.com/7952949/116601178-dca21200-a932-11eb-8ea8-1af278605810.png)
