### ISSUE TITLE
Search can find any text

### ISSUE THREAD

**Issue by anupsingh-anup** [Redocly/redoc#1272]
sidebar search box should be used to search only tags,groups and information displayed in sidebar.
I don't see a option where i can change search functionality and can be used for my purpose.
![image](https://user-images.githubusercontent.com/57786405/83053631-a9923700-a06e-11ea-827b-550954e159d5.png)

you can see in the above image that i did a search for "pet" . it has spotted in multiple places and user might not interested to do a search in a complete content. 
For my case, i just want to do a search with tags,groups. please provide a option to do search high level on tags,summary and not on whole content which served over api.

**Comment by RomanHotsiy** [comment]
What version of Redoc is this?

**Comment by anupsingh-anup** [comment]
redoc": "2.0.0-rc.29" . we are using **rc.29**

**Comment by RomanHotsiy** [comment]
It actually doesn't search across whole content, just through menu items. Not sure why it highlights all the occurrences. I will check.

**Comment by anupsingh-anup** [comment]
@RomanHotsiy  Please can you confirm what's behaviour in your side.

**Comment by RomanHotsiy** [comment]
We should remove highlighting all occurrences.

**Comment by dyeam-bw** [comment]
> It actually doesn't search across whole content, just through menu items. Not sure why it highlights all the occurrences. I will check.

@RomanHotsiy What if _do_ we want it to highlight all occurrences, which would imply that the search is actually searching all the content? That is how all of our users expect it to behave but they have been misled when there is a lack of results, not understanding that there is only a partial search being performed. We, ourselves, did not understand this until some investigating was done. We thought our search was broken.

**Comment by lornajane** [comment]
I know this has been open for a while, and since then it's been decided that we'll keep search as it is in the current version. I'll therefore close this issue, but thanks everyone for your input - it was helpful!
