### ISSUE TITLE
Cannot read property scrollIntoViewIfNeeded

### ISSUE THREAD

**Issue by bkarvas** [Redocly/redoc#1273]
I was trying to embed ReDoc Standalone (2.0.0-rc.30) into our API portal.
It looks that ReDoc initialization failed and getting the following error:

Uncaught TypeError: Cannot read property 'scrollIntoViewIfNeeded' of undefined
    at Module.<anonymous> (dom.ts:23)
    at n (bootstrap:19)
    at Object.<anonymous> (redoc.standalone.js:90)
    at n (bootstrap:19)
    at bootstrap:83
    at redoc.standalone.js:7
    at universalModuleDefinition:9
    at universalModuleDefinition:1

There is probably some javascript conflict with js libraries used by API Portal.
Any ideas how to fix it?

**Comment by RomanHotsiy** [comment]
It's strange. We have polyfill for it, maybe it is not added in your case:

https://github.com/Redocly/redoc/blob/a87440113b1a212c33be272421488ead1276a946/src/utils/dom.ts#L29-L74

**Comment by RomanHotsiy** [comment]
@bkarvas have you managed to resolve it?

**Comment by bkarvas** [comment]
Not yet. This week or week after we will upgrade our API Portal, so I will try it again and see if the issue persist.

**Comment by RomanHotsiy** [comment]
Ping me here if this is still relevant and I will reopen.

Thanks
