### ISSUE TITLE
Search gets invoked when at least min 3 character is keyed.

### ISSUE THREAD

**Issue by anupsingh-anup** [Redocly/redoc#1275]
![image](https://user-images.githubusercontent.com/57786405/83130261-abeea280-a0fb-11ea-884a-884c3595c1bb.png)

search functionality doesn't work on less than 3 characters. Minimum 3 characters required to do search and it shouldn't be a case. user should  be allowed to do search with any number of characters.

**Comment by RomanHotsiy** [comment]
We can make it a configuration option. PR would be welcome!

**Comment by beatfreaker** [comment]
@RomanHotsiy can you please check if changes done in PR [#1402](https://github.com/Redocly/redoc/pull/1402) are good, to make this as configurable option ?
