### ISSUE TITLE
Cache generated output for standalone version?

### ISSUE THREAD

**Issue by benwiley4000** [Redocly/redoc#1277]
I'm using RedocStandalone (the react component) mostly because I want to be able to have the page auto-update when we re-deploy our swagger.json without needing to re-build the html as an extra step. I'm really happy with the runtime performance but I checked the network log and saw that the thing that takes awhile every time I reload the page is the re-generation of the redoc blob based on the swagger.json. I think it would be really nice if we could do some kind of local caching of the result so that the next time we load the page, if nothing has changed, the docs can load much faster. Does this sound possible and can you imagine any challenges?

**Comment by benwiley4000** [comment]
I was totally wrong about the blob being what took a long a long time - that was just the time it took for the blob fetch to resolve because React took 5-6 seconds to finish rendering.

I guess what I ought to do is pregenerate the HTML when we update our spec, although I would keep it in the browser if I could reduce the time to render.

**Comment by RomanHotsiy** [comment]
You can try building your own SPA using RedocStandalone react component.
Unfortunately this kind of functionality is out of scope.

**Comment by benwiley4000** [comment]
To be honest I'm way less concerned about the load time now that I've tried it with the React production build. Takes about half the time it did before, and with the loading wheel it feels fast enough.

**Comment by RomanHotsiy** [comment]
Great you are satisfied! 🎉
