### ISSUE TITLE
Expand all and Collapse all should be disabled for flat structures

### ISSUE THREAD

**Issue by anupsingh-anup** [Redocly/redoc#1286]
What if a case that my example or schema model doesn't contains a array and my object is pure single dimensional.

For example:
![image](https://user-images.githubusercontent.com/57786405/83254636-c3499080-a1cc-11ea-9956-d0c386cfa92d.png)

we should disable expand all,collapse all options for flat objects. **Expand All**, **Collapse All** doesn't work in some cases and above is best example. user may feel that something wrong and not working.

**Comment by RomanHotsiy** [comment]
Nice suggestion! PR would be appreciated!

**Comment by AvroraPolnareff** [comment]
I want to help with this issue! Can it be assigned to me?

**Comment by lornajane** [comment]
This was merged already, thanks @AvroraPolnareff !

(closing this issue now)
