### ISSUE TITLE
Malformed HTML generated when using the --cdn option with redoc-cli bundle

### ISSUE THREAD

**Issue by mihirkothari25** [Redocly/redoc#1289]
I am using Redoc version 2.0.0-rc.24 and when running the `redoc-cli bundle --cdn` command on my OpenAPI yaml file it generates html that does not render properly in any browser. It html file generated without that option renders perfectly. My specification is OpenAPI 3.0.0.

**Comment by JSSAggie** [comment]
2.0.0-rc23 looks to still be working
