### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redoc#1291]
The README is outdated in many areas. Update it. Include the new roadmap for the official release of v2.

Other ideas:
- comparison of features of the community edition vs. premium
- helpful links to people just getting started writing their openapi definition (e.g. create-openapi-repo tool)
- careers available mentions (link to Redoc.ly/careers)
- mention of SaaS-hosted product and benefits

**Comment by fakela** [comment]
@adamaltman I would love to work on this

**Comment by lornajane** [comment]
README updated along side the config docs refresh.
