### ISSUE TITLE
 Date values are formatted in ISO datetime format

### ISSUE THREAD

**Issue by margaritamoritz** [Redocly/redoc#1293]
following to thread that was open by Sharon:
https://github.com/Redocly/redoc/issues/295

A bug with formatted dates is still exist:

example: 
{"name": "Name", "start_date": 2018-02-20, "end_date": 2018-02-21} (dates without quotes)

Outputs looked like:
"start_date": "2018-02-20T00:00:00.000Z", "end_date": "2018-02-21T00:00:00.000Z".

Dates are string typed, adding quotes, 'yyyy-MM-dd' or 'date' formats have the same results.

The example of the issue can be found on our API documentation page (URL is navigating to the issue):
https://developers.kenshoo.com/#tag/Ad-Groups/paths/~1api~1v1~1ad_groups/post

_Originally posted by @SharonHart in https://github.com/Redocly/redoc/issues/295#issuecomment-616088544_

**Comment by RomanHotsiy** [comment]
You should add quotes to the date itself. By default, js yaml parser parses data-strings without quotes as Date objects. If you put quotes around - it will parse it as a string:

```yaml
      example:
        template_name: 'Fusion: Ads'
        start_date: '2018-02-20'
        end_date: '2018-02-21'
```

https://redocly.github.io/redoc/?url=https://gist.githubusercontent.com/RomanHotsiy/79c4b5720d2b0f349274dd6ad8a2c476/raw/9d8601a66bf259aa7e5af640fb164e75536c455e/kenshoo.yaml#tag/Ad-Groups/paths/~1api~1v1~1ad_groups/post

**Comment by SharonHart** [comment]
Kooiooklli7killilliull8o9ikklikik9iko97kulo9ik9olkoo9uluklkoio7uikoli8o7koolollikk
kikol8

**Comment by RomanHotsiy** [comment]
@SharonHart what?

**Comment by margaritamoritz** [comment]
@RomanHotsiy 
Hi, maybe I wasn't clear enough - we pass data-string **with** quotes in our yml file:

**example**
openapi: "3.0.0"
components:
  schemas:
    asyncReportRequest:
      example: {"template_name": "Fusion: Ads", "start_date": "2018-02-20", "end_date": "2018-02-21"}

But they "disappear" once it uploaded to redocly, this why you saw the dates without quotes:

example:
        template_name: 'Fusion: Ads'
        start_date: 2018-02-20
        end_date: 2018-02-21

Any idea how to resolve it?

**Comment by RomanHotsiy** [comment]
@margaritamoritz I don't know what are you talking about when you say "once it uploaded to redocly":

I just checked your API documentation page again (https://developers.kenshoo.com/#tag/Ad-Groups/paths/~1api~1v1~1ad_groups/post).

From the page source, I can see it is powered by the following OpenAPI definition from your s3 account, not from redocly: https://api-gateway-documentation-production.s3.amazonaws.com/api-gateway/docs

![image](https://user-images.githubusercontent.com/3975738/89396180-e76aa600-d716-11ea-8b1b-63ef52dc209d.png)

When I download this file and open in my editor I see the following:
![image](https://user-images.githubusercontent.com/3975738/89396307-0ec17300-d717-11ea-9fed-21ec0cbca98e.png)
