### ISSUE TITLE
Using path paramter as value for request body

### ISSUE THREAD

**Issue by Alwyn2000** [Redocly/redoc#1298]
Hi,

  G'day. @RomanHotsiy 
Use path parameter **petId** as field value for **id** in request body. How can we do it?

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets/{petId}:
    put:
      summary: Info for a specific pet
      operationId: UpdatePetInfoById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      requestBody:
          description: Info about a new pet
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
      responses:
        '200':
          description: Expected response to a valid request
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id: _{$request.path.petId}_
        name:
          type: string
        tag:
          type: string
  ```

**Comment by RomanHotsiy** [comment]
I don't understand. This looks like not an issue but a general OpenAPI question. Better use StackOverflow for this.

I'm closing this issue.

Feel free to continue the discussion here though.

**Comment by Alwyn2000** [comment]
Hi @RomanHotsiy ,

    I think this is valid question, have you ever encountered such requirement or request?

**Comment by RomanHotsiy** [comment]
I don't understand the requirement or requests at all. Can you explain it more detailed?

**Comment by Alwyn2000** [comment]
Basically, I want to use the paramter petId's value as the Id's value in the Pet JSON object of request body, so both Ids always have the same value

**Comment by RomanHotsiy** [comment]
I don't understand how do you want Redoc to show display this information? Can you send some mockup?

**Comment by Alwyn2000** [comment]
That's my question, I am not sure if Redoc can do that. Something similar to: 

https://swagger.io/docs/specification/links/#requestBody
