### ISSUE TITLE
JSON Schema?

### ISSUE THREAD

**Issue by abrown945** [Redocly/redoc#1301]
I can't find all of the available keys for the JSON schema. Where is it in this repo?

**Comment by abrown945** [comment]
I suggest a link from the README or a clearer indication of where it is as it should be easy to find

**Comment by adamaltman** [comment]
I wonder what you mean? Redoc renders OpenAPI.  Here is the spec:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md

Let us know if that helps.
