### ISSUE TITLE
enum with one choice doesn't display as enum

### ISSUE THREAD

**Issue by mkrajew** [Redocly/redoc#1307]
When you have an enum that only has a single value, it shows as a string value instead of an enum with set values.

```
"eTest": {
        "enum": [
          "SoloValue"
        ],
        "type": "string",
        "description": "Test enum with a single possible value"
      }
```
```
"test": {
            "allOf": [
              {
                "$ref": "#/components/schemas/eTest"
              }
            ],
            "description": "Test enum with a single possible value"
          }
```
Displays as:
![SoloEnum](https://user-images.githubusercontent.com/2152742/85429305-2a483400-b544-11ea-9f43-11745f26d212.png)

If you add a second choice, it displays properly:
```
"eTest": {
        "enum": [
          "SoloValue",
          "SecondValue"
        ],
        "type": "string",
        "description": "Test enum with a single possible value"
      },
```
![SoloEnum_2](https://user-images.githubusercontent.com/2152742/85429480-667b9480-b544-11ea-803c-f91cb012a800.png)

**Comment by adamaltman** [comment]
This is an intentional feature. OAS 2 and 3 do not have a constant value. An enum with one choice is the closest simulation.

**Comment by RomanHotsiy** [comment]
Closing as "not an issue".

**Comment by mkrajew** [comment]
Thanks for the explanation. I wish this could at least be configurable though if you're changing how a "real" enum with a single item looks to the documentation just for the sake of constants not being in the openAPI spec. 

Our API has callers selecting from available options in an enum. When we start off, there will only be a single option and then we add more over time. At the beginning, our documentation looks like a bunch of strings instead of enums that will have new values added later.

**Comment by RomanHotsiy** [comment]
You can configure the label using the `labels` setting. It is not documented yet but here are default settings: https://github.com/Redocly/redoc/blob/master/src/services/Labels.ts#L16-L24

Via cli:

```
--options.labels.enumSingleValue = "Enum"
```

**Comment by mkrajew** [comment]
Thank you, that should solve this problem for us!
