### ISSUE TITLE
scroll-y-offset doesn't offset api content

### ISSUE THREAD

**Issue by stanleynguyen** [Redocly/redoc#1310]
I'm trying to offset using a selector of my navbar element. However, only menu-content seems to be offset by redoc js script

<img width="1440" alt="Screenshot 2020-06-29 at 11 58 10 AM" src="https://user-images.githubusercontent.com/12974927/85971523-f49dc200-b9ff-11ea-9a8c-dae55293fdfc.png">

<img width="1440" alt="Screenshot 2020-06-29 at 11 58 19 AM" src="https://user-images.githubusercontent.com/12974927/85971532-f798b280-b9ff-11ea-84bf-c93e3e64c95a.png">

**Comment by RomanHotsiy** [comment]
Add padding-top to the redoc parent element, see example here https://redocly.github.io/redoc/

**Comment by paololazzari** [comment]
@RomanHotsiy could you add an example for how that works?
