### ISSUE TITLE
Flexible redoc layouting

### ISSUE THREAD

**Issue by leimig** [Redocly/redoc#1312]
Hi every, first I would like to thank you for the hard work on this repo. It's helping us a lot with our project.

Now, my UX designer wants to move the search box from the left menu to our custom app header. I didn't find any way of doing that other than decomposing the `RedocStandalone` component in my code. I had to copy some of the Redoc code to our component so I had access to the `store` and use the `SearchBox` component in our header.

I'm not too happy with that solution as I'm not sure if these components are supposed to be used publicly and if they will be changed or not (and to which extension) in the future.

Could you help me? Is there any way other than copying a big chunk of code out of the library? Are these components supposed to be used publicly?

Thanks

**Comment by RomanHotsiy** [comment]
Hey @leimig.

There is no other way and unfortunately this is out of the scope of this project.
