### ISSUE TITLE
Issue with multiple examples

### ISSUE THREAD

**Issue by dodlhuat** [Redocly/redoc#1315]
while a single response example renderes perfectly fine, in the moment I change to multiple examples, it only renders "null" for any example. The first one works, the second one does not. I couldn't find any clue why it shouldn't be working. Any help is appreciated.
```
example:
   $ref: ../items/audit_example.yaml
```
VS
```
examples:
   exampleName:
      $ref: ../items/audit_example.yaml
```

**Comment by dodlhuat** [comment]
Nevermind. I finally found out that examples need another key "value" to work.

**Comment by adamaltman** [comment]
@dodlhuat this exact problem has happened to thousands of people. We have a new tool to help point out the issue, but it isn't integrated to Redoc yet:  https://github.com/Redocly/openapi-cli (and our recommended rule set would note the issue).
