### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by HectorIX** [Redocly/redoc#1325]
**Ubuntu 18.04**

1. git clone the project to my local machine. 
2. Naviate to  `redoc/config/docker` directory. 
3. Run `docker build -t redoc .`

Then Im getting the following error message:

> Sending build context to Docker daemon  11.78kB
Step 1/22 : FROM node:alpine
 ---> 5d97b3d11dc1
Step 2/22 : RUN apk update && apk add --no-cache git
 ---> Using cache
 ---> 5817a8b70a31
Step 3/22 : WORKDIR /build
 ---> Using cache
 ---> 69c878ee03b0
Step 4/22 : COPY package.json package-lock.json /build/
COPY failed: stat /var/lib/docker/tmp/docker-builder709588059/package.json: no such file or directory

Did I make something wrong?

**Comment by RomanHotsiy** [comment]
> Did I make something wrong?

You don't have to navigate to `redoc/config/docker` directory.

Run it from the root of the repo:

`docker build -t redoc -f config/docker/Dockerfile .`
