### ISSUE TITLE
Permalink invalid (spaces)

### ISSUE THREAD

**Issue by ArtFlag** [Redocly/redoc#1326]
Hello and thanks for this great tool. 

I just started using it and I noticed that the permalinks to methods are the exact same as the method names, meaning we preserve the spaces and that creates issues with many linkcheckers. 

Here is an example:
```html
<h2 class="sc-dnqmqq ioYTqA">
    <a class="sc-VigVT kGvRyb" href="#operation/Create stock location"></a>Create stock location<!-- -->
</h2>
```
The `href` contains spaces. 

Would it be possible to replace them by another character? 

_Tested with Redoc-cli version 0.9.8 (this might apply to openapi-cli too)_

**Comment by RomanHotsiy** [comment]
Can you rename your operationId?

From the spec:

> Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.

**Comment by ArtFlag** [comment]
My bad, I was using operationId to give titles to my endpoints instead of `summary`. Thanks for the answer!
