### ISSUE TITLE
Redoc with large data

### ISSUE THREAD

**Issue by ngthtung** [Redocly/redoc#1337]
Hi guys,

I have a problem, I got 40.000 line in a file json, and Redoc extremely render not smooth.
Any idea to solving this problem?

Thank you.

**Comment by adamaltman** [comment]
We have a [premium product](https://redoc.ly) which can render it into smaller sections. I don't have an idea to recommend otherwise: We have seen people break one API into multiple APIs, but I don't think we would recommend that.

**Comment by ngthtung** [comment]
Hm.. thank you for your support @adamaltman . I will consider reduce data when loaded
