### ISSUE TITLE
uniqueItems: true is not exposed in generated docs

### ISSUE THREAD

**Issue by freddrake** [Redocly/redoc#1353]
For arrays, setting uniqueItems to true is not reflected in the documentation, but should generally be considered important for a reader.

~~~~~~~ yaml
    type: array
    items:
      type: string
      enum:
        - "one"
        - "two"
        - "three"
    minItems: 1
    uniqueItems: true
~~~~~~~

![Screenshot from 2020-08-18 12-27-05](https://user-images.githubusercontent.com/588792/90539680-27d21700-e14e-11ea-923f-a0eff81fe304.png)

Leaving this to the description leads to inconsistent and insufficient documentation.

**Comment by RomanHotsiy** [comment]
Thanks for the issue!

PR would be appreciated!

**Comment by freddrake** [comment]
The new version works perfectly for me; thank you!
