### ISSUE TITLE
Discriminator not mapping correctly if schema's type is an enum of a single value

### ISSUE THREAD

**Issue by acote-coveo** [Redocly/redoc#1358]
Hi,

Here's what we are trying to do:

```yaml
  SortCriteria:
      oneOf:
        - $ref: "#/components/schemas/SortCriteriaByRelevance"
        - $ref: "#/components/schemas/SortCriteriaByFields"
      discriminator:
        propertyName: by
        mapping:
          relevance: "#/components/schemas/SortCriteriaByRelevance"
          fields: "#/components/schemas/SortCriteriaByFields"

    SortCriteriaByRelevance:
      type: object
      properties:
        by:
          type: string
          # Specifying an enum of single values causes some issues.
          enum: [relevance]
      required:
        - by
```

Notice the for the mapped schemas, we define the `by` property as the discriminator. We also specify those fields as being an enum of single value (This is pretty useful when we generate clients code from our spec because we can infer that there's only one value possible for that field). 

Therefore, it's causing some issues with redoc. When we select the `fields` discriminator value, the `relevance` schema is shown and vice-versa.

If we comment the single enum value, the dropdown work correctly.

Code example: https://codesandbox.io/s/redocdiscriminatorbugenum-xzsr3?file=/package.json

Tested with: Redoc 2.0.0-rc.37

**Comment by RomanHotsiy** [comment]
This was fixed in https://github.com/Redocly/redoc/commit/be07197e6d1e85a3fd3e61189a36b288751c077d
