### ISSUE TITLE
Out of date "some real life usages"

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [Redocly/redoc#1359]
[Some Real-life usages](https://github.com/Redocly/redoc#some-real-life-usages)

* [Rebilly](https://rebilly-api.redoc.ly/) link is broken
* [FastAPI](https://github.com/tiangolo/fastapi) goes to the standard Github project page for the project and not to a redoc-generated page

**Comment by tillkolter** [comment]
To make the link to FastAPI more concise linking to the section with the reference would be sufficient, I guess?

https://github.com/tiangolo/fastapi#alternative-api-docs

**Comment by skadinna** [comment]
The README has been updated several times since this issue was reported, and no longer contains those problematic links. Closing this now - thanks for the report :+1:
