### ISSUE TITLE
How can I display error code description in sample code section?

### ISSUE THREAD

**Issue by Hamzablm** [Redocly/redoc#1361]
I have an error code description displayed in the main section:
![image](https://user-images.githubusercontent.com/32052228/91046807-fd320380-e610-11ea-813e-51d5227786f6.png)

But I'd like also to display those code in the example section here:
![image](https://user-images.githubusercontent.com/32052228/91047299-bc86ba00-e611-11ea-809e-b088a549b2d3.png)

I saw some API docs that can generate those descriptions in the example section:
![image](https://user-images.githubusercontent.com/32052228/91048003-e42a5200-e612-11ea-9ef5-109a1c4176dc.png)

How can I do such a thing?

**Comment by lornajane** [comment]
Redoc separates the examples (right hand pane) from the examples (middle section), there isn't support for mixing the two.
