### ISSUE TITLE
Docker: Failed to load yaml file 

### ISSUE THREAD

**Issue by weismantelf** [Redocly/redoc#1364]
Hello,
I have installed Docker on my Windows 10 PC and using the official ReDoc Docker Image.
I follow the instruction on docker hub to use a local file:

```
docker run -it --rm -p 80:80 \
  -v $(pwd)/demo/swagger.yaml:/usr/share/nginx/html/swagger.yaml \
  -e SPEC_URL=swagger.yaml redocly/redoc

```

Because I am working on a windows PC, I changed it to:

```
docker run -it --rm -p 80:80 \
  -v /temp/demo/swagger.yaml:/usr/share/nginx/html/swagger.yaml \
  -e SPEC_URL=swagger.yaml redocly/redoc

```

When I am now try to open the url http://localhost, I see:
Something went wrong...
Error downloading http://localhost/swagger.yaml HTTP ERROR 403

**Stack trace

s/<@http://localhost/redoc.standalone.js:44:26651
e/</<@http://localhost/redoc.standalone.js:95:36080

s/<@http://localhost/redoc.standalone.js:44:26651
e/</<@http://localhost/redoc.standalone.js:95:35658

ReDoc Version: 2.0.0-rc.40
Commit:** 

And in the console, where I have start the docker command I get:

2020/08/26 11:12:52 [error] 11#11: *3 directory index of "/usr/share/nginx/html/swagger.yaml/" is forbidden, client: 172.17.0.1, server: localhost, request: "GET /swagger.yaml/ HTTP/1.1", host: "localhost", referrer: "http://localhost/"

Can you tell me what I am doing wrong?

**Comment by lysenko-sergey-developer** [comment]
Try
`docker run -it --rm -p 80:80 \
  -v "C:\Users\user\temp\demo\swagger.yaml"/temp/demo/swagger.yaml:/usr/share/nginx/html/swagger.yaml \
  -e SPEC_URL=swagger.yaml redocly/redoc`

Where **C:\Users\user\temp\demo\swagger.yaml** is correct absolute path to your yaml file
