### ISSUE TITLE
Relative Markdown Links in Description fail when Remote Included

### ISSUE THREAD

**Issue by perlboy** [Redocly/redoc#1368]
We use the markdown include syntax to provide detailed descriptions of enumerations. We do this, at the moment, using a relatively link of `$ref: ./File.md`.

For instance (assuming I haven't changed it since this ticket) from [EnumBankingProductCategoryV1.yaml](https://github.com/bizaio/dsb-standards/blob/master/openapi/components/schemas/EnumBankingProductCategoryV1.yaml) we include [EnumBankingProductCategoryV1.md](https://github.com/bizaio/dsb-standards/blob/master/openapi/components/schemas/EnumBankingProductCategoryV1.md) and this works great [for the published  Redocs](https://bizaio.github.io/dsb-standards/#section/EnumBankingProductCategory/EnumBankingProductCategoryV1) however, when we include this yaml file remotely it does not attempt to use the base path for the $ref.

For example within a (private) yaml definition in a separate redoc repository:
```
  productCategory:
    $ref: https://github.com/bizaio/dsb-standards/blob/master/openapi/components/schemas/EnumBankingProductCategoryV1.yaml
```

Results in:
```
https://github.com/bizaio/dsb-standards/blob/master/openapi/components/schemas/EnumBankingProductCategoryV1.yaml:
2:3 resolve-scalars      Reference does not exist.
1:0 oas3-schema/schema   This field must be of string type.
```

In essence, the first $ref is resolving correctly but the description $ref is always considered local.

Update: When setting the Enum include to a full URL to the md file, the base repository fails with file not found, ie. $ref for md files **only** works for local refs **and** local redocly.

Is there any way around this or is it a bug?

**Comment by adamaltman** [comment]
This is not a bug. It's an invalid place to include a reference. I did open a feature request over here:

https://github.com/Redocly/openapi-cli/issues/189

**Comment by lornajane** [comment]
No further action needed on this one, so I'll close.
