### ISSUE TITLE
some pattern regex fails to render

### ISSUE THREAD

**Issue by delanym** [Redocly/redoc#1372]
Not quite the same as #245
I'm trying to set a pattern for my uuid datatype, but sometimes they don't render

```
fail: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
fail: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}$"
pass: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}$"
fail: "^[0-9a-f]{8}-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]$"
pass: "^[0-9a-f]{8}-[0-9a-f][0-9a-f][0-9a-f]$"
```

**Comment by RomanHotsiy** [comment]
Oh, yes. We recently made a change to hide all patterns longer than 45 characters. We found it overly complicated and not very useful to the end-users.

Probably we should have added it as a configuration option.

**Comment by delanym** [comment]
These docs are a great way of visually checking the completeness of a spec. So i would at least expect some indication that a pattern property exists. As well as setting the threshold length of the pattern, perhaps have the option to generated a truncated pattern with a UTF8 ellipsis
`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a …`

or better still, have a drop-down like you have for nested elements
