### ISSUE TITLE
Authorization links don't work when noAutoAuth is true

### ISSUE THREAD

**Issue by alexibz** [Redocly/redoc#1383]
![image](https://user-images.githubusercontent.com/54906681/92953777-4d420000-f430-11ea-8e86-85df7486a510.png)

When `noAutoAuth: true`, the links would be pointing to a non-existant anchor `#section/Authentication/basicAuth`.

**Comment by lornajane** [comment]
If your description does need authentication, we'd recommend leaving `noAutoAuth` set to false - exactly for the reason you describe. I hope that helps, but let us know if you have more questions.
