### ISSUE TITLE
Why is there discrepancy with peerDependencies?

### ISSUE THREAD

**Issue by callado4** [Redocly/redoc#1387]
We are using redoc on my team but I have noticed that when I do an npm-install with just a dependency of redoc-cli, I get a warning of 
```npm WARN redoc@2.0.0-rc.40 requires a peer of styled-components@^4.1.1 but none is installed. You must install peer dependencies yourself.```

But if I look at the dependencies for both redoc and redoc-cli, they both include a dependency for `"styled-components": "^5.1.1"` - so if I add a dependency for `styled-components@^4.1.1` I get a warning saying that `5.1` is needed but then when I add the `5.1` version then I get the warning above.

With these devDependencies I get the warning above:
```
  "devDependencies": {
    "mobx": "^4.2.0",
    "styled-components": "~5.1.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "redoc": "^2.0.0-rc.40"
  }
```

And then changing it to the `4.1.1` version:
```
  "devDependencies": {
    "mobx": "^4.2.0",
    "styled-components": "^4.1.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "redoc": "^2.0.0-rc.40"
  }
```

I get this warning:
```
npm WARN @redocly/react-dropdown-aria@2.0.11 requires a peer of styled-components@^5.1.1 but none is installed. You must install peer dependencies yourself.
```

**Comment by tomgreen98** [comment]
we are having a similar problem with this discrepancy when running:

```
 /usr/local/cpanel/3rdparty/bin/yarn check --cwd /usr/local/cpanel/build-tools/openapi 
yarn check v1.17.3
```

We get:
```
...
error "redoc-cli#redoc#styled-components@^4.1.1" doesn't satisfy found match of "styled-components@5.1.1"
error Found 1 errors.
...
```

which breaks some conditional logic in our build system.  Please update this `peerDependency` to match the requirement in `devDependencies`.
