### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by webkulDev** [Redocly/redoc#1388]
it causing internal server error if someone send null in line_items .
{"err":"INTERNAL_SERVER_ERROR","message":"Cannot convert undefined or null to object"}

**Comment by adamaltman** [comment]
I don't quite understand this issue. Is this about Redoc?

**Comment by AlexVarchuk** [comment]
Closed. Reason: can not reproduce. 
If you have a question or this still happens add more steps to reproduce and reopen this issue.
