### ISSUE TITLE
Header parameters  are not brought into Send

### ISSUE THREAD

**Issue by tm731531** [Redocly/redoc#1392]
https://ehsnb2bapi.redoc.ly/#operation/TokenPost

This is one of my reDoc

When I click "TRYIT"
The authoriztation of my header parameter is not brought into my POST

I kind of opened F12 to see the NETWORK inside

Didn't bring it in. What the setting is wrong?

Note
This Redoc is build by swagger Json ,I can shot it by swagger UI 
But I can't use it by reDoc

Thanks

**Comment by adamaltman** [comment]
Hi @tm731531 — this sounds like a Redocly support issue. Please contact Redocly for support here. It sounds like you may need to have CORS enabled on your server to accept the Authorization header. You may benefit from a CORS proxy?

**Comment by rbruggem** [comment]
Could you please share how this got fixed?
