### ISSUE TITLE
redocly.github.io/redoc broken -> Error downloading https://cors.apis.guru/...

### ISSUE THREAD

**Issue by ajmas** [Redocly/redoc#1397]
When trying the demo with the following swagger files:

  - https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/swagger.yaml
  - https://api.apis.guru/v2/specs/slack.com/1.2.0/swagger.yaml

The following error is generated:

```
Error downloading https://cors.apis.guru/https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/swagger.yaml HTTP ERROR 404
Stack trace
Error: Error downloading https://cors.apis.guru/https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/swagger.yaml 
HTTP ERROR 404
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:48:1501
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:21:86584

Error: HTTP ERROR 404
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:48:1501
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:21:86162

ReDoc Version: 2.0.0-rc.40
Commit: 17b9873
```

Additionally, when the error happens clicking 'try it' with a new URL results in no apparent action, even the URL in the address bar is updated. No error in the console either.

Note, it works with:

  - https://api.apis.guru/v2/specs/zoom.us/2.0.0/swagger.yaml
  - https://docs.graphhopper.com/openapi.json

Testing with Chome 86.0.4240.55 on MacOS X 10.15.6

**Comment by ajmas** [comment]
Further investigation reveals that the following pages are returning a 404:

- https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/swagger.yaml
- https://api.apis.guru/v2/specs/slack.com/1.2.0/swagger.yaml

Error handling should be updated to test for a 404.

**Comment by adamaltman** [comment]
Thanks for the report. We have a fix in the works.

**Comment by adamaltman** [comment]
@pshenok did you open a PR?

**Comment by RomanHotsiy** [comment]
@adamaltman yes, but the demo was not redeployed for some reason. I just redeployed it manually.
