### ISSUE TITLE
Redoc docker image cannot run on OpenShift

### ISSUE THREAD

**Issue by Xendar** [Redocly/redoc#1407]
I am trying to deploy the redocly/redoc image in OpenShift.
When I'm preparing the deployment I'm getting this warning:

`Image redocly/redoc runs as the root user which might not be permitted by your cluster administrator. `

And indeed when the pod is starting, I get this error, hence the deployment fails:

`sed: can't create temp file '/usr/share/nginx/html/index.htmlXXXXXX': Permission denied`

Is there a custom image for OpenShift? Or should the Docker image be updated to run as non-root / not modify files at startup time?

**Comment by mik-laj** [comment]
OpenShift/Heroku has quite a few different restrictions on images. It is described here: https://docs.openshift.com/enterprise/3.0/creating_images/guidelines.html

Would you like to contribute the fix?

**Comment by Xendar** [comment]
> 
> 
> OpenShift/Heroku has quite a few different restrictions on images. It is described here: https://docs.openshift.com/enterprise/3.0/creating_images/guidelines.html
> 
> Would you like to contribute the fix?

Thanks for your swift reply! I can give it a try :)
