### ISSUE TITLE
redoc taking 5 or more minutes to open my documentation

### ISSUE THREAD

**Issue by danilocastelhano1** [Redocly/redoc#1417]
Hi everyone, i have an huge API with many endpoints, and these endpoints have a lot of fields, and the redoc is taking 5 min or more to open my documentation, is there anything i can do to make it faster? thank you.

**Comment by stueynz** [comment]
We had similar problems; 47 data objects x 7 endpoints each (POST + GET, PUT & PATCH (single & multiple) ... and that's  just covering the CRUD operations; we'll have a bunch more for  more RPC based endpoints.   

In the end we chopped the spec up into seven sections, used redoc-cli to produce seven matching static HTML files, and then glued them back together with links across the boundaries.

https://sifnzmodel.azurewebsites.net/OpenAPI-v3.2-rc2-2020-10-07/TeRito-OpenAPI-organisation.html

**Comment by danilocastelhano1** [comment]
When i try to run redoc-cli bundle on my spec, i got this error: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by lornajane** [comment]
Since this issue has been open a while, it's difficult to reproduce. Please let us know if you're still seeing performance problems after upgrading to the newest Redoc release.
