### ISSUE TITLE
Query parameters missing in request sample.

### ISSUE THREAD

**Issue by ghost** [Redocly/redoc#1418]
In the right pane the query parameters are missing in the request.

For the `findByStatus` example at https://redocly.github.io/redoc/#operation/findPetsByStatus 
the URL looks like this:
```
https://petstore.swagger.io/v2/pet/findByStatus
```
The query parameter `status` is required, so the URL should look like this:
```
https://petstore.swagger.io/v2/pet/findByStatus?status={status}
```

For path parameters this is currently possible too (see https://redocly.github.io/redoc/#operation/getOrderById). Here the URL is: 
```
https://petstore.swagger.io/v2/store/order/{orderId}
```

**Comment by adamaltman** [comment]
Those URLs aren't request samples. 

You can add request samples with the `x-codeSamples` extension. Alternatively, in our premium version, we can generate some code samples for you automatically.

Here is what that looks like when code samples are provided (or in this case generated):

![image](https://user-images.githubusercontent.com/1161871/97869885-c5fa6580-1cd7-11eb-8161-09a0ac1500c4.png)

**Comment by lornajane** [comment]
I'm assuming the question in this issue was answered, since it's been inactive for a while - so I'm closing it.
