### ISSUE TITLE
Refused to execute inline script

### ISSUE THREAD

**Issue by r37r0m0d3l** [Redocly/redoc#1427]
Trying `redoc-cli` to generate static documentation. No luck with these errors. It looks like `Content-Security-Policy` don't allow JS code at all.

```Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-g6NjhUYDGd6SXSIYkvuQkZhdbtqx8hqNKVM8JKvqpy4='), or a nonce ('nonce-...') is required to enable inline execution.```

```html
<meta
    http-equiv="Content-Security-Policy"
    content="
base-uri;
connect-src *;
default-src * 'unsafe-inline' 'unsafe-eval' data: gap: https://ssl.gstatic.com;
font-src * data:;
form-action;
img-src * data:;
manifest-src *;
media-src;
object-src *;
report-to;
script-src * 'unsafe-inline' 'unsafe-eval';
script-src-attr * 'unsafe-inline' 'unsafe-eval';
script-src-elem * 'unsafe-inline' 'unsafe-eval';
style-src * data: 'unsafe-inline';
style-src-attr * data: 'unsafe-inline';
style-src-elem * data: 'unsafe-inline';
    ">
```

**Comment by mshiltonj** [comment]
Was this issue fixed? How do I provide a nonce in a way the redoc js can consume it for when it creates the style elements?

**Comment by r37r0m0d3l** [comment]
> 
> 
> Was this issue fixed? How do I provide a nonce in a way the redoc js can consume it for when it creates the style elements?

Yes and no. URL `/api/docs-json` in my case send unsafe headers.
```javascript
response.header("Access-Control-Allow-Origin", "*");
response.header("Content-Security-Policy", "script-src blob:");
response.header("Content-Security-Policy", "worker-src blob:");
```

So now we can use any kind of HTML code.

```html
<redoc
  spec-url="/api/docs-json"
  suppress-warnings
></redoc>
<script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"></script>
```

**Comment by din-prajapati** [comment]
Could you let me know why above fix is not working for Chrome and Edge browser.  However it is working in IE Browser.

Below is the issue i am getting for my documentation website. 

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src *". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.


Could you please provide me solution for this. As i can not change CSP header of production server.

**Comment by VILATTI** [comment]
@din-prajapati 

For the Rails action, I just added headers to the response:
```ruby
def index
  response.set_header("Access-Control-Allow-Origin", "*");
  response.set_header("Content-Security-Policy", "script-src blob:");
  response.set_header("Content-Security-Policy", "worker-src blob:");
end
```
