### ISSUE TITLE
hide-hostname option adds a slash - openapi 3.0

### ISSUE THREAD

**Issue by codyaray** [Redocly/redoc#1428]
Either a regression or a miss on the fix for #201. My guess is that this may be specific to openapi 3.0, as that's what I'm using and 3.0 wasn't yet supported when #201 was closed.

I'm seeing this using redoc-cli@0.9.12 (which [uses redoc 2.0.0-rc40](https://github.com/Redocly/redoc/commit/4e7c7228aadf56b4b73d2f68a3140c707fbf5bd7#diff-8f2f2c6de2bad1783500e34d29b4f24fb7a11ed1c482210edd80a9f47fe8e73aR1453)) with an openapi 3.0 spec with a single server.

Reproduction steps:
```
---
openapi: 3.0.0
info:
  title: Test API
  version: 0.0.1

servers:
  - url: https://api.example.com

paths:
  /some/example/path:
    get:
      responses:
        '204':
          description: No Content.
```

Then bundle it
```
$ redoc-cli --version
0.9.12

$ redoc-cli bundle openapi.yaml --options.hideHostname
$ open redoc-static.html
```

This is what you see when you click the dropdown:
![Screen Shot 2020-10-22 at 8 21 33 PM](https://user-images.githubusercontent.com/44062/96945797-4df49a00-14a4-11eb-9965-335a79563e8b.png)

**Comment by codyaray** [comment]
Quick investigation looks like it was independently re-introduced here: https://github.com/Redocly/redoc/blob/4db5bc470b0b9e7758e17741e0c7d6df1e691e5c/src/components/Endpoint/Endpoint.tsx#L76

Note that the `pathname` defaults to `"/"` instead of `""` when its empty, causing this issue again. Validation:
![Screen Shot 2020-10-22 at 8 32 48 PM](https://user-images.githubusercontent.com/44062/96946437-f22b1080-14a5-11eb-9b0f-3070d52e002a.png)

**Comment by adamaltman** [comment]
Thanks for the bug report.

**Comment by RomanHotsiy** [comment]
This will be released with the new rc later this week.
