### ISSUE TITLE
Redoc-cli cannot serve local files referenced in `externalValue`

### ISSUE THREAD

**Issue by ktunkiewicz** [Redocly/redoc#1430]
Redoc supports `externalValue`, but when you serve it via `redoc-cli` it only works files hosted on external web server.

This means that when developing locally, you cannot use local files like in example below. You can however copy the generated single-page HTML plus all the JSON assets to a web server, and it will work.

```
"examples": {
    "example1": {
        "summary": "First example",
        "externalValue": "resources/examples/firstExample.json"
    },
    "exampl2": {
        "summary": "Second example",
        "externalValue": "resources/examples/secondExample.json"
    }
}
```

That's because these `externalValue` references are resolved on client-side, and **redoc-cli doesn't serve local files**.

Instead you have to do an out-of-spec thing like this:
```
"examples": {
    "exampl1": {
        "summary": "First example",
        "value": {
          "$ref": "resources/examples/firstExample.json"
        }
    },
    "pending": {
        "summary": "Second example",
        "value": {
          "$ref": "resources/examples/secondExample.json"
        }
    }
}
```

I made a pretty simple PR that adds local file serving to redoc-cli:
https://github.com/Redocly/redoc/pull/1422

Would be nice to have that feature.

**Comment by delanym** [comment]
Im doing the suggestion, but index.html displays as

```
Something went wrong...
Unable to resolve $ref pointer "file:///etc/etc/etc/etc/etc/etc/target/redoc/openapi.json"

Stack trace

s/<@file:///etc/etc/etc/etc/etc/etc/target/redoc/redoc.js:50:5303
e.exports/</</<@file:///etc/etc/etc/etc/etc/etc/target/redoc/redoc.js:62:36174

ReDoc Version: 2.0.0-rc.18
Commit: cd9fd618
```

**Comment by adamaltman** [comment]
@delanym you seem to be on an older version? https://www.npmjs.com/package/redoc I see it's on 2.0.0-rc.45 now.

**Comment by delanym** [comment]
@adamaltman yes, the latest version works

**Comment by lornajane** [comment]
Looks like this was already fixed, I'll close the issue.
