### ISSUE TITLE
BaseDTO 

### ISSUE THREAD

**Issue by agustin-tecso** [Redocly/redoc#1439]
Hi! I'm implementing a simple backend in Java with Micronaut framework.
All my controllers returns a java POJO (DTO object). All DTO's objects extends from the same BaseDTO class.

![explicacion](https://user-images.githubusercontent.com/70208597/97353808-430a8280-1873-11eb-9d13-1af363f59b6d.png)

I have an object A that have an object B inside.

The problem is that the swagger plugin generate the following  yml file:

![yml](https://user-images.githubusercontent.com/70208597/97353523-e9a25380-1872-11eb-8fc0-fa0c7d3ff343.png)

When I generate the html view with redoc, the fields of object B don't appears in the schema (in the example its ok). There is a tag "Recursive" in object B.

![html](https://user-images.githubusercontent.com/70208597/97353721-253d1d80-1873-11eb-9e78-19092a650b03.png)

I try to generate html view with Swagger-ui and rapidoc and works fine. It's this behavior a bug? I understand that recursivity is a problem, but there is no real recursion in this example.

Thanks!

**Comment by alejandrojuarez675** [comment]
I have the same problem.

**Comment by RomanHotsiy** [comment]
This is dup of https://github.com/Redocly/redoc/issues/1154
