### ISSUE TITLE
Request: Option to add class names to extensions elements or to display extensions dynamically

### ISSUE THREAD

**Issue by neffnet** [Redocly/redoc#1447]
I would like to add class names to the elements that display vendor extensions. The reason I want to do this is because I want to hide `x-extension1` from the display if more user friendly `x-extension2` also exists for that endpoint, and I could take of this in the redoc init callback. Alternatively, the `showExtensions` options might be able to accept an object with functions to determine whether the extension should be displayed.

**Comment by adamaltman** [comment]
Thanks for the feature request.

Here is a workaround you could use today...

We publish a tool, [`openapi-cli`](https://github.com/Redocly/openapi-cli), that can decorate your OpenAPI definition during the `bundle` command. The output of the command is your manipulated OpenAPI definition...

Here is an article with an example of using a decorator:

https://redoc.ly/docs/resources/hide-apis/

**Comment by lornajane** [comment]
The decorator is the best way to achieve what's outlined here, so I'll close this issue.
