### ISSUE TITLE
feat: option to resolve references

### ISSUE THREAD

**Issue by delanym** [Redocly/redoc#1453]
Add an option to resolve references before generating HTML

**Comment by adamaltman** [comment]
This may be handled better with `openapi-cli bundle` probably. What do you think @RomanHotsiy ?

**Comment by RomanHotsiy** [comment]
There is no enough context from @delanym. I don't understand.

References are resolved before generating HTML already.

I will close this issue for now.

@delanym feel free to continue the discussion here.

**Comment by delanym** [comment]
Thanks, it was an issue with a downstream project
