### ISSUE TITLE
Support for Angular 10?

### ISSUE THREAD

**Issue by PranavBhatia** [Redocly/redoc#1454]
How to integrate a Redoc in an Angular application?

**Comment by mackaelb** [comment]
I'm interested too

**Comment by jbloem9** [comment]
I also want to integrate this in an angular app and managed to get this working as follows;

1) You cannot do this via installing the package as it does not appear to work with the higher versions of angular.
2) Add the following to your index.html page in the body section;- <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"></script>
3)  In the html page of your component add the following;- <div id="redoc"></div>
4)  In the component.ts file add the following under the imports;- declare var Redoc: any;
5)  Create a method to initialize the documentation and call this method from within the ngOnInit method.  I called my method initDocs. 
ngOnInit(): void {
    this.initDocs();
  }
6) Lastly add the initDocs method.
initDocs(){
   Redoc.init('https://path to your swagger.json', {
      scrollYOffset: 60,
      hideDownloadButton: true
    }, document.getElementById('redoc'))}

Working for me by doing the above.

**Comment by RomanHotsiy** [comment]
Thanks @jbloem9
