### ISSUE TITLE
h1 and h2 tags duplicated twice

### ISSUE THREAD

**Issue by rankery** [Redocly/redoc#1456]
So i found an issue.
![Screenshot from 2020-11-09 19-31-29](https://user-images.githubusercontent.com/19314785/98575707-2f730900-22c2-11eb-9984-106c71e4635f.png)

As u can see **h1** and **h2** headers and duplicated. **h3** working well but sadly when i put 
```<!-- ReDoc-Inject: <security-definitions> -->```
under it.

So HTR (easy way):
1. Download ur own demo ssr (https://github.com/Redocly/redoc/blob/master/demo/ssr/index.ts)
2. Get a copy of file and provide a link (i did it with https://www.npoint.io/)
3. Add to description something like that 
```\n # Random```
4. 
![Screenshot from 2020-11-09 19-53-39](https://user-images.githubusercontent.com/19314785/98577910-48c98480-22c5-11eb-9a2c-36fbf62d845d.png)

P.S. Also text under the tags duplicated too

**Comment by kikofernandez** [comment]
Same issue here.

**Comment by kikofernandez** [comment]
To get around it, you can use h3 instead.
I think this issue should probably open again #1150

**Comment by skalecki-imblox** [comment]
We also have this bug. Is it regression or it was never fixed?

**Comment by lpaderiAltravia** [comment]
We have the same issue here. That would simply require a swap of h1 -> h2

**Comment by osamaramihafez** [comment]
> I think this issue should probably open again #1150

Yes

**Comment by jaltin** [comment]
We are also getting bitten by this bug. We are using 2.0.0-rc.63.

**Comment by AlexVarchuk** [comment]
It seems fixed [here](https://github.com/Redocly/redoc/pull/2119). If it still reproduces please add a definition which not work.
