### ISSUE TITLE
Add arbitrary markdown files as pages to docs

### ISSUE THREAD

**Issue by cbetta** [Redocly/redoc#1473]
I searched for this extensively but I can't find anything about this. Is it possible to add arbitrary markdown files as pages to Redoc? It would be cool to combine API reference and some basic guidance into one.

**Comment by adamaltman** [comment]
1. You can build a full (what we call) developer portal using a premium product of Redocly called the [Developer portal](https://redoc.ly/developer-portal/). You write markdown and it integrates the premium Redocly reference docs too (which includes things like the "try it" console, code sample generation, and pagination for improved performance).

2. Redoc renders an OpenAPI definition. The OpenAPI definition can contain markdown. You can put markdown in a lot of places which gives you an opportunity to add a lot of contextual documentation like guides. The primary place used for that purpose is the `info.description` field. And using a tool like our openapi-cli you can keep that description in a separate file and bundle it together using `openapi bundle` command. Other places common for contextual docs include each tags description. 

Here is a good example of contextual docs included inside of an OpenAPI definition (using the same $ref technique I mention). One note is they are using the premium version of Redocly Reference docs so you do see a `<PullRight>` (content in the right from the info.description section). 

https://docs.checkr.com

https://redoc.ly/docs/api-reference-docs/embedded-markdown/ (Pay attention only to the first part. The three special markdown features are premium features available in reference docs.)

**Comment by lornajane** [comment]
Thanks @cbetta and @adamaltman , I feel like this was well answered at the time, so I'll close this issue.
