### ISSUE TITLE
Discriminator support: Missing example dropdown with nested object

### ISSUE THREAD

**Issue by TimoMur** [Redocly/redoc#1474]
Hi, I am trying to get a request example on my project using a discriminator. The project uses the json:api spec. that's why the data has to be wrapped inside the data.attributes-object. 

The example looks like:

    openapi: 3.0.0
    info:
      version: 1.0.0
      title: Swagger Petstore
      license:
        name: MIT
    paths:
      /pets:
        post:
          summary: Create Pet
          operationId: createPet
          tags:
            - pets
          requestBody:
            $ref: '#/components/requestBodies/Pet'
          responses:
            "201":
              description: Created
    components:
      schemas:
        Pet:
          required:
            - name
          type: object
          discriminator:
            propertyName: petType
            mapping:
              Dog: '#/components/schemas/Dog'
              Cat: '#/components/schemas/Cat'
          properties:
            name:
              type: string
            petType:
              type: string
        Cat:
          allOf:
            - $ref: '#/components/schemas/Pet'
            - type: object
              properties:
                cat_exclusive:
                  type: string
        Dog:
          allOf:
            - $ref: '#/components/schemas/Pet'
            - type: object
              properties:
                dog_exclusive:
                  type: string
      requestBodies:
        Pet:
          required: true
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      attributes:
                        $ref: '#/components/schemas/Pet'

The pet store example shows what I am trying to accomplish:

![pet_store_with_example](https://user-images.githubusercontent.com/35068484/100472516-adb21680-30dc-11eb-9ac6-aa5698ebecf4.PNG)

That is my result, the left side is correct but the request example dropdown is missing:

![pet_store_without_example](https://user-images.githubusercontent.com/35068484/100472535-b60a5180-30dc-11eb-94da-9fef1fd0172f.PNG)

It seems like the discriminator has to be the top attribute to be shown as an example request. That would mean, you couldn't use it with a common standard like json:api. I haven't found any example or description of this use case or someone with the same issue. Did I miss anything or is it not supported?

Thanks in advance,
Timo

**Comment by ivanchurkin** [comment]
@TimoMur, hi!

I don't understand why, but it's work (transfer discriminator from Pet scheme to Pet request body).

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
paths:
  /pets:
    post:
      summary: Create Pet
      operationId: createPet
      tags:
        - pets
      requestBody:
        $ref: '#/components/requestBodies/Pet'
      responses:
        "201":
          description: Created
components:
  schemas:
    Pet:
      required:
        - name
      type: object
      properties:
        name:
          type: string
        petType:
          type: string
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            cat_exclusive:
              type: string
    Dog:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            dog_exclusive:
              type: string
  requestBodies:
    Pet:
      required: true
      content:
        application/vnd.api+json:
          schema:
            type: object
            discriminator:
              propertyName: petType
              mapping:
                Dog: '#/components/schemas/Dog'
                Cat: '#/components/schemas/Cat'
            properties:
              data:
                type: object
                properties:
                  attributes:
                    $ref: '#/components/schemas/Pet'
```

**Comment by TimoMur** [comment]
@ivanchurkin Thanks for your response, I tried that already but then the data and attributes are missing in the description and in the example. Redoc ignores both attributes and only displays the Cat and Dog object.

**Comment by adamaltman** [comment]
Hi @TimoMur I believe you'll need to generate the examples yourself. You can supply request body examples as part of the description and make one for Dog and Cat.

**Comment by TimoMur** [comment]
@adamaltman That's the solution I was looking for, thank you.
