### ISSUE TITLE
Fix github readme toggleMenu

### ISSUE THREAD

**Issue by witekblach** [Redocly/redoc#1476]
Hi, I tried making a PR but failed so here we are :)

In the README.md on line `243` we see `menuToggle - if true clicking second time on expanded menu item will collapse it, default false.`, but according to your [SAAS Documentation](https://redoc.ly/docs/cli/configuration/reference-docs/) `menuToggle: true  # CE # if true clicking second time on expanded menu item will collapse it.`

When I tried to check it out it really seemed to be enabled by default (or maybe there is another feature I don't know about), so it should be fixed in the readme too :)

PS. Over the last 2-3 days I had to search for a nice template to generate docs from OAS yaml file, yours was the best - love it out of the box <3
If there is one thing I would improve its the features we can enable/disable/specify for the documentation. It would be really cool to see a comparison on what each option really does. 
Either way - thanks for making this, kudos to you all <3

**Comment by RomanHotsiy** [comment]
Thanks, I updated the README 👍
