### ISSUE TITLE
Cannot escape single backslash `foo\@bar`

### ISSUE THREAD

**Issue by ctselepidas-cp** [Redocly/redoc#1479]
I want to produce an example displaying: `foo\@bar`

OpenApi spec: `example: "foo\\@bar"`
Result:

![Screen Shot 2020-12-07 at 16 06 25](https://user-images.githubusercontent.com/74337628/101411357-7692f080-38a6-11eb-9f3c-427d9662e1e7.png)

`\@` results in unknown escape sequence
`\\` results in `\\`
`\u005C` results in `\\`

**Comment by RomanHotsiy** [comment]
This is a JSON example. To represent the string `foo\@bar` in JSON you have to use `"foo\\@bar"`.

This is the correct behavior. Otherwise, the JSON won't be valid.

Let me know if I am missing something.

**Comment by lornajane** [comment]
I think this was already answered, I'll close the issue.
