### ISSUE TITLE
0.10.2: ReferenceError: name is not defined

### ISSUE THREAD

**Issue by mmattb** [Redocly/redoc#1485]
ReferenceError: name is not defined
    at /ifs/home/mbryan/.npm/_npx/3518/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:9404:124
    at mapValues (/ifs/home/mbryan/.npm/_npx/3518/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:7269:24)
    at new FieldModel (/ifs/home/mbryan/.npm/_npx/3518/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:9404:29)
    at /ifs/home/mbryan/.npm/_npx/3518/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:9741:50
    at Array.map (<anonymous>)
    at OperationModel.get (/ifs/home/mbryan/.npm/_npx/3518/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:9741:15)
    at OperationModel.get (/ifs/home/mbryan/.npm/_npx/3518/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:8600:42)
    at Object.children (/ifs/home/mbryan/.npm/_npx/3518/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:14129:97)
    at ReactDOMServerRenderer.render (/ifs/home/mbryan/.npm/_npx/3518/lib/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3635:55)
    at ReactDOMServerRenderer.read (/ifs/home/mbryan/.npm/_npx/3518/lib/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)

It appears this happens on 0.10.2 and not 0.10.1.  It happens with some YAML files and not others, and presumably that is why I'm the first to report it.  Probably I have a weird edge-case of a YAML file, though: the repro below is pretty minimal.

I've made a semi-minimalist version of the file that reproduces the issue. The 'examples' clause seems to be a crucial part of it.
```
---
openapi: "3.0.3"
info:
  description: "Hello"
  version: "2.0"
  title: "Hello"
  contact:
    email: "hello@dell.com"
servers:
  - url: http://hello.com/2/query
paths:
  /query:
    get:
      summary: "Hello"
      description: "Hello"
      parameters:
        - in: query
          name: sumfing
          schema:
            type: string
          examples:
            some_example:
              value: something
```

**Comment by StephaneLambert** [comment]
Same trouble for me with NodeJS 12.19 et **redoc-cli 0.10.2**, not with 0.10.1.
Clarification: `redoc-cli serve` is OK while `redoc-cli bundle` is NOT.

My YAML sample : 
```
openapi: 3.0.2
info:
  title: Test Redoc Bundle
  version: 1.0.0
  description: Redoc Bundle fail if headers are used ?
paths:
  /entities:
    summary: '...'
    description: '...'
    get:
      parameters:
        - examples:
            all:
              value: 0-5/6
            page2:
              value: 20-39/258
          name: Content-Range
          description: |-
            Content-Range: `offset`–`limit`/`count`
              * offset : ...
              * limit : ...
              * count : ...
          schema:
            type: string
          in: header
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/entities'
          description: Successful response - returns an array of `entities` entities.
      operationId: getentities
      summary: List All entities
      description: Gets a list of all `entities` entities.
components:
  schemas:
    entities:
      description: ''
      type: object
      properties:
        property1:
          description: property1 description
          type: string
        property2:
          description: property2 description
          type: integer
```

**Comment by dowy** [comment]
That line:
.../node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:9404:124
points to the variable "name" but there is no such variable.
It should refer to the "this.name" assigned on line 9391.

My javascript isn't strong enough to figure out how "name" on line 9404 can refer to "this.name" on line 9391 so I added a local variable:

line 9391:
- this.name = infoOrRef.name || info.name;
+ var name;
+ name = this.name = infoOrRef.name || info.name;

I leave it to someone who knows what they're doing to raise a patch for this.

**Comment by EvanCarroll** [comment]
@RomanHotsiy why was this issue closed?

**Comment by EvanCarroll** [comment]
@dowy I'm confused how this isn't broken for everyone.

**Comment by RomanHotsiy** [comment]
@EvanCarroll because It was fixed.

Could you specify more details? Which version of openapi-cli do you use? What node version?

**Comment by RomanHotsiy** [comment]
@EvanCarroll I just tested it again and it works for me on the latest redoc-cli@0.10.4 version.
