### ISSUE TITLE
Support Hierarchical Tags

### ISSUE THREAD

**Issue by kael-shipman** [Redocly/redoc#1489]
There's growing momentum for a string-based, backward-compatible way of hierarchicalizing tags in OAS documents; see OAI/OpenAPI-Specification#1367 and swagger-api/swagger-ui#5969 for discussion and support for the idea.

I'd love to see an implementation of this in redoc. I propose something like the screenshot below:

![redoc-target](https://user-images.githubusercontent.com/3475586/103246582-a1aeb400-4929-11eb-8ef8-46c657e908d9.png)

Note that we can use the well-established "nested collapsible list" pattern for arbitrary depth under the first item in the hierarchy. It would be great if there were additionally a "collapse/expand all" link for each level.

For reference, the current version of redoc renders this screen like so:

![Screenshot_2020-12-28_16-05-49](https://user-images.githubusercontent.com/3475586/103246611-bee38280-4929-11eb-9d03-f5e76f57a0ca.png)

**Comment by SteveNay-vz** [comment]
Have you tried using x-tagGroups? It's already supported by Redoc and lets you group tags.

**Comment by kael-shipman** [comment]
Ah! Thank you for the tip! I didn't know about that, and it looks like it'll work great. I remain convinced that hierarchical tags will be a well-used feature going forward and that it's worth supporting them natively, but perhaps it doesn't make sense to do so until the discussion leads to a more centralized convention in the OAS community. For now, the `x-tagGroups` field will probably work splendidly.

**Comment by kael-shipman** [comment]
Hey again all,

There's been some progress over on the SwaggerUI version of this feature request ([here](https://github.com/swagger-api/swagger-ui/issues/5969)) and it made me wonder if ReDoc has any kind of plugin infrastructure similar to Swagger's. I just did a cursory look and it appears that there's some very limited functionality, but not nearly enough to produce changes to the way the interface renders.

The x-tagGroups is a good lead, but I see a few problems with it:

1. Tags must still be uniquely named. For example, `Users:View` and `Transactions:View` would go into groups `Users` and `Transactions` respectively, but would still need a redundant or useless prefix to distinguish them from one another.
2. Hierarchy is limited to just 2 levels.

**Comment by rishagit** [comment]
any update on this? really need this.
