### ISSUE TITLE
Potential Bug Risks and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [Redocly/redoc#1495]
## Description 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/redoc/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point of time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

Some of the notable issues are: 

- Direct Mutation of `this.state` [here](https://deepsource.io/gh/HarshCasper/redoc/issue/JS-0444/)
- `var` used instead of `let` and `const` [here](https://deepsource.io/gh/HarshCasper/redoc/issue/JS-0239/)
- Missing displayName in React Component Definition [here](https://deepsource.io/gh/HarshCasper/redoc/issue/JS-0393/)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

**Comment by lornajane** [comment]
Closing issue as outdated.
