### ISSUE TITLE
redocly.github.io/redoc broken (again)

### ISSUE THREAD

**Issue by remram44** [Redocly/redoc#1496]
See also #935
See also #1397

`cors.apis.guru` seems completely gone, causing the rendering of any doc to fail with:

> Something went wrong..
>
> Error downloading http://cors.apis.guru/https://.../restapi.json NetworkError when attempting to fetch resource. "

**Comment by RomanHotsiy** [comment]
That was an issue with cors.apis.guru. It's back now.
