### ISSUE TITLE
Improvement: dark theme

### ISSUE THREAD

**Issue by ungarson** [Redocly/redoc#1498]
Hi, I guess it would be useful to switch to the dark theme just with a one option `isDarkTheme: true | false` or something like this. Right now I see plenty of options in the `theme` option but it's very 🤯.
Anyway, thanks for the redoc, very helpful!

**Comment by reesericci** [comment]
any progress on this?

**Comment by Bitz** [comment]
It was rejected last time it was suggested #987, so it may once again be rejected.

**Comment by ungarson** [comment]
Closed, since no feedback was given 😓

**Comment by AustEcon** [comment]
So is there a workaround? What settings do I plug in to get dark theme?

**Comment by dilanx** [comment]
I created a dark theme for redoc called [redark](https://github.com/dilanx/redark) where I tried to darken as much of the UI as I could! There were a few limitations because it looks like redoc wasn't built to support a quality dark mode 😭 but you can find a demo [here](https://docs.dilanxd.com/redark/)!

**Comment by nathan-fiscaletti** [comment]
@dilanx can you elaborate on which parts of it are limited? I'm curious what isn't covered by the dark theme.

**Comment by dilanx** [comment]
@nathan-fiscaletti clicking on "authorizations" shows white text on a white background. Many of the colors in redoc are hard-coded, but I was able to use CSS to override them. This one is a styled component, and I wasn't sure if the generated class name will always be consistent. I just looked and it seems like other examples have the same generated class name though, so maybe this could be fixed.

**Comment by cosmolux** [comment]
@dilanx Your dark theme is beautiful.  I hope redocly adds support for [automatic dark scheme choice](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) as it is now implemented in all modern browsers.

**Comment by jasonm23** [comment]
A couple of notes from mdn:

https://developer.mozilla.org/en-US/docs/Web/CSS/important

> [Inline styles](https://developer.mozilla.org/en-US/docs/Web/CSS/important#inline_styles)
>
> Inline styles are styles defined using the [style](https://developer.mozilla.org/en-US/docs Web/HTML/Global_attributes/style) attributes. They can also be normal or important. Inline normal styles take precedence over all normal declarations, no matter the origin. Inline important styles take precedence over all other important author styles, no matter the layer, but important styles from user's or user-agent's style sheets and transitions override them.

So in other words, unless ReDoc is using inline `!important` styles (which would be bizarre frankly) it should be possible to theme everything.

If `!important` is being used inline, I think it's a good idea to push a PR to get those replaced with normal styles.

**Comment by Thykof** [comment]
Hi, I was able to get a nice dark mode by injecting this style in the template `index.hbs`

```html
    <style>
      body {
        padding: 0;
        margin: 0;
      }
      .redoc-wrap {
        background-color: black;
      }
      .redoc-wrap,
      .redoc-wrap * {
        color: #fafafa;
      }
      .redoc-wrap h5 {
        color: #d4d4d8 !important;
      }
    </style>
```

and this to the config file `redocly.yaml` thanks to @dilanx :
```yaml
theme:
    theme:
      logo:
        gutter: "1rem"
        maxWidth: "120px"
      codeBlock:
        backgroundColor: "#18181b"
      colors:
        error:
          main: "#ef4444"
        border:
          light: "#27272a"
          dark: "#a1a1aa"
        http:
          basic: "#71717a"
          delete: "#ef4444"
          get: "#22c55e"
          head: "#d946ef"
          link: "#06b6d4"
          options: "#eab308"
          patch: "#f97316"
          post: "#3b82f6"
          put: "#ec4899"
        primary:
          main: "#71717a"
        responses:
          error:
            backgroundColor: "rgba(239,68,68,0.1)"
            borderColor: "#fca5a5"
            color: "#ef4444"
            tabTextColor: "#ef4444"
          info:
            backgroundColor: "rgba(59,131,246,0.1)"
            borderColor: "#93c5fd"
            color: "#3b82f6"
            tabTextColor: "#3b82f6"
          redirect:
            backgroundColor: "rgba(234,179,8,0.1)"
            borderColor: "#fde047"
            color: "#eab308"
            tabTextColor: "#eab308"
          success:
            backgroundColor: "rgba(34,197,94,0.1)"
            borderColor: "#86efac"
            color: "#22c55e"
            tabTextColor: "#22c55e"
        secondary:
          main: "#d4d4d8"
          light: "#d4d4d8"
        success:
          main: "#22c55e"
        text:
          primary: "#fafafa"
          secondary: "#d4d4d8"
          light: "#d4d4d8"
      fab:
        backgroundColor: "#52525b"
        color: "#67e8f9"
      rightPanel:
        backgroundColor: "#27272a"
      schema:
        linesColor: "#d8b4fe"
        typeNameColor: "#93c5fd"
        typeTitleColor: "#1d4ed8"
      sidebar:
        activeTextColor: "#ffffff"
        backgroundColor: "#18181b"
        textColor: "#a1a1aa"
      typography:
        code:
          backgroundColor: "#18181b"
          color: "#fde047"
        links:
          color: "#0ea5e9"
          hover: "#0ea5e9"
          textDecoration: "none"
          hoverTextDecoration: "underline"
          visited: "#0ea5e9"
```
