### ISSUE TITLE
Google Fonts cannot be disabled

### ISSUE THREAD

**Issue by unikitty37** [Redocly/redoc#1501]
According to #1045, I should be able to pass the `disableGoogleFont` parameter to redoc-cli and have the generated HTML not make calls to Google Fonts. However, it does not appear to work.

```
npx redoc-cli serve api_spec.yml --options.disableGoogleFont
```

produces a webpage which makes a request to https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700

https://google-webfonts-helper.herokuapp.com/fonts allows fonts to be downloaded from Google Fonts for self-hosting — could Redoc not simply bundle the font files?

Failing that, is there a way to get the `disableGoogleFont` parameter to work as expected? I really do not want to have to rewrite the privacy policy as the site is now sending requests to Google where it previously did not…

```
└─▷ npx redoc-cli --version
0.10.2
```

(I assume that npx is returning an up-to-date version here :)

**Comment by adamaltman** [comment]
I thought the option was for the `bundle` command: `npx redoc-cli bundle ...`

**Comment by unikitty37** [comment]
Ah — could it be added to `serve` as well? It seems a bit of a waste of bandwidth to override the fonts and still have it trying to load things from Google even though they're not used…

**Comment by RomanHotsiy** [comment]
Yes, we can add the same option to the `serve` command. PR would be appreciated.

**Comment by patrickdemers6** [comment]
I'll take this.
