### ISSUE TITLE
Spec js file 

### ISSUE THREAD

**Issue by khaledosama999** [Redocly/redoc#1517]
### Problem 
Why can't the spec file be a js file not necessarily a json or yaml file as sometimes you want to include variables or arrays as enums that are used in other areas in the application

**Comment by AlexVarchuk** [comment]
@khaledosama999 Hi! Thanks for the question.
You can use some preprocessing for creating definitions.


PS: In my own view if we start supporting different languages we will spend time on it, not important things related to the specification.
