### ISSUE TITLE
[question] Possible to use/add hash-less URLs to Redoc?

### ISSUE THREAD

**Issue by mikemaccana** [Redocly/redoc#1522]
I notice Redoc uses the older style hash-based URLs

`https://example.com/docs#operation/create_user_users_post`

rather than the more modern:

`https://example.com/docs/operation/create_user_users_post`

I was going to patch this in just now, but I can see `src/services/HistoryService.ts` is using `history.pushState()` so obvious you know about about the history API. I'm sure you have your reasons for sticking with hashless URLs - is it browser support or something else?

Are you OK if I send a PR with an option to use hashless URLs?

Thanks!

**Comment by lornajane** [comment]
Sorry for the slow response, this really has been hanging around for a while. We're not planning to support a change in URL format, no. But thanks for participating in the project, we appreciate your input regardless!
