### ISSUE TITLE
"Try It" body only appears after click

### ISSUE THREAD

**Issue by ArtFlag** [Redocly/redoc#1525]
The `body` in the "try it" tab is always empty until I first click in the text field.  

It's the same behaviour in FF and Chrome, and it looks/feels like a bug (?)

![click to display](https://user-images.githubusercontent.com/25686502/107213331-8646c680-6a08-11eb-8f95-75d972bce1a8.gif)

**Comment by ge-gao** [comment]
Hi,

I'm testing Redoc as a possible solution for our OpenAPI renderer. Interesting is I can't see in the demo page the "Try it" (https://redocly.github.io/redoc/?url=https://petstore.swagger.io/v2/swagger.json) feature. Does it require extra configuration?

**Comment by beatcracker** [comment]
> Interesting is I can't see in the demo page the "Try it"

+1, I'm using Swagger-UI exactly because I couldn't find `Try it` feature in the Redoc.

**Comment by hoangddt** [comment]
Hi @ArtFlag, how to activate the Try It feature, I am using `v2.0.0-alpha.15` but dont know how to activate it.

**Comment by baboonmaj** [comment]
ReDoc's `Try It` is a premium feature https://redoc.ly/reference-docs , not available in free version.

The only other free option for Try It is [Swagger](https://swagger.io/tools/swagger-ui/) UI and [RapiDoc](https://mrin9.github.io/RapiDoc/index.html)

**Comment by beatcracker** [comment]
@baboonmaj I see, thanks for clearing this up.

**Comment by RomanHotsiy** [comment]
@ArtFlag please, report this to the team@redocly.com

The issue should be resolved now too btw.

Thanks!
