### ISSUE TITLE
Ability to define a default body for the "Try It" feature

### ISSUE THREAD

**Issue by ArtFlag** [Redocly/redoc#1526]
It would be great to add a feature to set a different default body for the try it feature instead of only using the operation example. 

This could be useful to use the OAS example to show the full capacity of an operation, and use a different try it example that is tailored to the server and more didactic than the OAS example.  

Maybe the try it example could even allow to create a dropdown list of values that the user can try to submit.

**Comment by lornajane** [comment]
Thanks for the suggestion and sorry for the slow response! Try it is not part of Redoc, so I'm closing this issue.
