### ISSUE TITLE
Chrome sourceMappingURL

### ISSUE THREAD

**Issue by oliveirajoabe** [Redocly/redoc#1527]
When i access the console through Google Chrome version: 88.0.4324.150 on windows 10 pro version: 1909. I get this warning: 
![image](https://user-images.githubusercontent.com/43959705/107406636-6934f500-6ae7-11eb-9bde-6695baf2489d.png)

And its causing some fail2ban issues. I managed to supress this error by removing this comment on the file node_modules/redoc/bundles/redoc.standalone.js
![image](https://user-images.githubusercontent.com/43959705/107406873-b4e79e80-6ae7-11eb-907a-98ad36333ef5.png)
I wonder if its safe to do it or if there is any reason to this being commented out.

**Comment by kaklang98** [comment]
Good

**Comment by CristopherVidalMachado** [comment]
Waiting with the same problem.

**Comment by lornajane** [comment]
I think this was fixed in the newer versions of Redoc, so please update. I'll close the issue, assuming this isn't a current problem - but please let us know if I'm wrong about that and you still see something that isn't quite right!
