### ISSUE TITLE
Suggestion: Automated code generator using Postman libraries

### ISSUE THREAD

**Issue by benedictjohannes** [Redocly/redoc#1529]
Currently, Postman Documenter has the excellent ability to generate code examples from various libraries, powered by [postman-code-generators](https://github.com/postmanlabs/postman-code-generators) that they kindly open-sourced.

This is a very nice feature to be made available in ReDoc. 

One of the way to achieve it is to reuse Postman's libraries to convert OpenAPI to Postman collections (use [openapi-to-postman](https://github.com/postmanlabs/openapi-to-postman) then afterwards use [postman-code-generators](https://github.com/postmanlabs/postman-code-generators) to generate the code examples. Both of these are Apache licensed, so using it shouldn't be a problem. However, this would likely require server side coding as the dependencies includes `newman` and `postman-runtime`

The ability to instantly generate code examples without hand-coding it using `x-codeSamples` is a very nice addition. Also, this would address the long standing issue #15.

**Comment by theslyone** [comment]
+1

**Comment by lornajane** [comment]
Thanks for the suggestion! I am sorry to say that we do not plan to include this in open source Redoc (at the risk of sounding like an advert, if you do need this feature then it's available in our commercial API reference docs products https://redocly.com/docs/api-reference-docs/guides/generate-code-samples/) and I am therefore closing the issue.
