### ISSUE TITLE
Problem installing 'redoc-cli@latest'

### ISSUE THREAD

**Issue by CommCody** [Redocly/redoc#1537]
Hi all,

trying to run `redoc-cli` fails since yesterday with the below error:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/20637/lib/node_modules/redoc-cli/node_modules/@scarf/scarf/report.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @scarf/scarf@1.1.0 postinstall: `node ./report.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @scarf/scarf@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-16T09_42_01_888Z-debug.log
Install for [ 'redoc-cli@latest' ] failed with code 1
```

We use this command: `npx redoc-cli bundle ./openapi/openapi.yaml --output ./openapi/openapi.html`

Node version:  `node 14.15.5 x64`

Do you know what we can do to fix this error?

**Comment by Dextorr** [comment]
Having exactly the same issue with a similar command, managed to get it to run by fixing to previous version:
`npx redoc-cli@0.10.3 bundle ./openapi/openapi.yaml --output ./openapi/openapi.html`

**Comment by RomanHotsiy** [comment]
I downgraded the `latest` version in npm to 0.10.2 as a temporary solution.

I'll dig into this issue later this week.

Thanks for report!

**Comment by jandppw** [comment]
I have a, possibly related, issue with `npm ci`.

We added redoc-cli as 4th dev dependency: 

```
  "devDependencies": {
    "@redocly/openapi-cli": "^1.0.0-beta.29",
    "npm-watch": "^0.7.0",
    "prettier-standard": "^16.4.1",
    "redoc-cli": "^0.10.3"
  },
```

Everything works locally and in Bitbucket pipelines.

Yet, through a mishap, this addition was not applied to `package-lock.json` initially.

So:

```
>rm -Rf node_modules/ package-lock.json 
>npm install

added 808 packages, and audited 809 packages in 17s

56 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

No problem.

`0.10.4` got installed in `node_modules`:

```
>ls node_modules/redoc-cli/
Dockerfile          index.js            node_modules        package.json
README.md           index.ts            npm-shrinkwrap.json template.hbs
```

Then, on commit, Bitbucket Pipelines failed:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /opt/atlassian/pipelines/agent/build/node_modules/redoc-cli/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/opt/atlassian/pipelines/agent/build/node_modules/redoc-cli/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-21T20_16_46_634Z-debug.log
Last command "npm ci" command exited with code 254.
```

This could be reproduced locally:

```
>npm ci
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/[…]/node_modules/redoc-cli/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/[…]/node_modules/redoc-cli/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[…]/.npm/_logs/2021-02-21T20_54_17_135Z-debug.log
```

And indeed, the file no longer exists.

```
>ls node_modules/redoc-cli/
node_modules
```

Seeing this issue, I fixed the `redoc-cli` version to `0.10.3`, and then `0.10.2`, and retried.

I get the same problem in all 3 cases, locally, and on Bitbucket pipelines. Using Node >= 15.5.1.

There might be a broader issue?

**Comment by rsegeda** [comment]
> I have a, possibly related, issue with `npm ci`.
> 
> We added redoc-cli as 4th dev dependency:
> 
> ```
>   "devDependencies": {
>     "@redocly/openapi-cli": "^1.0.0-beta.29",
>     "npm-watch": "^0.7.0",
>     "prettier-standard": "^16.4.1",
>     "redoc-cli": "^0.10.3"
>   },
> ```
> 
> Everything works locally and in Bitbucket pipelines.
> 
> Yet, through a mishap, this addition was not applied to `package-lock.json` initially.
> 
> So:
> 
> ```
> >rm -Rf node_modules/ package-lock.json 
> >npm install
> 
> added 808 packages, and audited 809 packages in 17s
> 
> 56 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> ```
> 
> No problem.
> 
> `0.10.4` got installed in `node_modules`:
> 
> ```
> >ls node_modules/redoc-cli/
> Dockerfile          index.js            node_modules        package.json
> README.md           index.ts            npm-shrinkwrap.json template.hbs
> ```
> 
> Then, on commit, Bitbucket Pipelines failed:
> 
> ```
> npm ERR! code ENOENT
> npm ERR! syscall chmod
> npm ERR! path /opt/atlassian/pipelines/agent/build/node_modules/redoc-cli/index.js
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, chmod '/opt/atlassian/pipelines/agent/build/node_modules/redoc-cli/index.js'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-02-21T20_16_46_634Z-debug.log
> Last command "npm ci" command exited with code 254.
> ```
> 
> This could be reproduced locally:
> 
> ```
> >npm ci
> npm ERR! code ENOENT
> npm ERR! syscall chmod
> npm ERR! path /Users/[…]/node_modules/redoc-cli/index.js
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/[…]/node_modules/redoc-cli/index.js'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/[…]/.npm/_logs/2021-02-21T20_54_17_135Z-debug.log
> ```
> 
> And indeed, the file no longer exists.
> 
> ```
> >ls node_modules/redoc-cli/
> node_modules
> ```
> 
> Seeing this issue, I fixed the `redoc-cli` version to `0.10.3`, and then `0.10.2`, and retried.
> 
> I get the same problem in all 3 cases, locally, and on Bitbucket pipelines. Using Node >= 15.5.1.
> 
> There might be a broader issue?

same here - travis-ci

**Comment by RomanHotsiy** [comment]
This is caused by npm@7 updated module resolution algorithm. We have to fix dependencies.

Please, use node@14 if possible. We're working on a fix.

**Comment by RomanHotsiy** [comment]
Should be fixed on the latest version.

Please let me know here if it's not.

Closing the issue.

**Comment by ndemianc** [comment]
@RomanHotsiy Unfortunately, it is not fixed and I'm still getting same problem on the version `"redoc-cli": "^0.13.11"`
