### ISSUE TITLE
Display contracts

### ISSUE THREAD

**Issue by mristin** [Redocly/redoc#1542]
Hi,
I am working on a FastAPI extension ([fastapi-icontract]) that documents contracts (as in [design-by-contract]) in the OpenAPI specification.

I currently put the contracts as extensions (`x-*`) to a path like the following snippet in the schema. Is there any way how I could make redoc document the contracts (*e.g.*, by making an extension to Redoc and include it somehow in FastAPI)? Or does this functionality needs to go directly into Redoc code?

```json
"/upsert_book": {
    "post": {
      ...,
      "x-contracts": {
        "preconditions": [],
        "snapshots": [
          {
            "name": "book_count",
            "enabled": true,
            "text": "book_count()"
          },
          {
            "name": "has_book",
            "enabled": true,
            "text": "has_book(book.identifier)"
          }
        ],
        "postconditions": [
          {
            "enforced": true,
            "text": "awaited_to(\n        lambda a_book_count: (\n                OLD.book_count + 1 == a_book_count if not OLD.has_book\n                else OLD.book_count == a_book_count),\n        book_count())",
            "status_code": 500
          },
          {
            "enforced": true,
            "text": "has_book(book.identifier)",
            "status_code": 500
          }
        ]
      }
    }
  }
```

[fastapi-icontract]: https://github.com/mristin/fastapi-icontract/
[design-by-contract]: https://en.wikipedia.org/wiki/Design_by_contract

**Comment by lornajane** [comment]
There isn't a way to do that, and I'm so sorry this issue was open so long without a response. I'll close it as it seems unlikely we can add anything useful at this point, but please open another issue if you'd like any more help on this or anything else Redoc-related.
