### ISSUE TITLE
[Q] Is it possible to add text above the Documentation Powered by Redoc?

### ISSUE THREAD

**Issue by yujinyuz** [Redocly/redoc#1544]
Is it possible? If so, then how?

I'm currently using open api

<img width="260" alt="Screen Shot 2021-02-23 at 10 59 28 PM" src="https://user-images.githubusercontent.com/10972027/108861995-ca51e200-762a-11eb-9f54-8c6b982dc147.png">

**Comment by lornajane** [comment]
Sorry for the slow response. No, there's no customisation of that section available.
