### ISSUE TITLE
Invalid array schema with missing items property causes ReDoc to crash

### ISSUE THREAD

**Issue by lgellrich** [Redocly/redoc#1546]
We just upgraded from ReDoc 2.0.0-rc.29 to 2.0.0-rc.50 today and found that some of our OpenAPI specifications failed to render.
ReDoc generated a stack-trace that states _Cannot read property schema of undefined_

While comparing working specifications with the broken ones I got to the point that we use invalid array schemas.
We were lacking the items property, which is required by OpenAPI (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schemaObject):
> items - Value MUST be an object and not an array. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. items MUST be present if the type is array.

<details>
  <summary>Example demonstrating the invalid spec</summary>

```yaml
openapi: 3.0.0
info:
  description: |
    A small OpenAPI specification with invalid array schema.

    The items property is mandatory for type: array
  version: 1.0.0
  title: Invalid Array Schema
paths:
  /test:
    get:
      summary: Test
      operationId: testArray
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
```
</details>

I am aware that an invalid OpenAPI specification is probably not something that ReDoc should support 😄 
But due to the fact that it worked prior, I still feel like ReDoc should at least not crash giving people the opportunity to spot their mistake. 

While searching for the source within ReDoc I got to this block of code that was introduced with https://github.com/Redocly/redoc/pull/1308:
https://github.com/Redocly/redoc/blob/6086c6c89f58003131e6afcbb300420afdeeb091/src/components/Schema/ArraySchema.tsx#L15-L21

I found that changing the code as follows avoids the crash and restores previous behavior:
```typescript
const itemsSchema = this.props.schema.items;
...
const minMaxItems = humanizeConstraints(itemConstraintSchema(itemsSchema?.schema.minItems, itemsSchema?.schema.maxItems));
```

How do you feel about making this or a similar change?

**Affected Versions**

ReDoc: 2.0.0-rc.32 until 2.0.0-rc.50 (tested with 2.0.0-rc.49, 2.0.0-rc.50)
redoc-cli:  0.9.9 until 0.10.4 (tested with 0.10.2)

**Result prior to #1308**
![image](https://user-images.githubusercontent.com/1510470/109063493-7d811080-76e9-11eb-9a0d-64ca8f70db88.png)

**Result with workaround:**
![image](https://user-images.githubusercontent.com/1510470/109063380-5f1b1500-76e9-11eb-85cd-a53615f56880.png)

**Comment by lornajane** [comment]
Thanks for the bug report, we've agreed not to prioritise the work to support the invalid schema - most of our users are linting their API descriptions before generating documentation, so we see limited benefit in supporting this use case (sorry!).
