### ISSUE TITLE
Support OAS 3.1?

### ISSUE THREAD

**Issue by hilary** [Redocly/redoc#1547]
I don't see an item on Roadmap for support for OAS 3.1, which was released on February 15th. Version 3.1 is really important as it brings full compliance with JSON schema and radically improves the situation for generating clients. I do see some scattered tasks for particulars w/re 3.1 support.

Do you have a plan somewhere for migrating to 3.1? If we need particular features from 3.1 supported should we follow the path of others and submit specific patches? 

Thanks,
Hilary

**Comment by Marshevskyy** [comment]
Yeah, sure. We are about to start working on it.
Sorry about Roadmap, we will update it. 

I'll keep you posted.

**Comment by adamaltman** [comment]
We have basic support now (in the master branch -- not released yet).

**Comment by timbunce** [comment]
> We have basic support now (in the master branch -- not released yet).

Thanks for the update.

Any idea when the next release candidate might be? (I see the regular flow of [releases](https://github.com/Redocly/redoc/releases) stopped back in April.)

**Comment by RomanHotsiy** [comment]
OpenAPI 3.1 was added in the [the RC.54](https://github.com/Redocly/redoc/blob/master/CHANGELOG.md#200-rc54-2021-06-09)

We track issues with it in this umbreall issue: https://github.com/Redocly/redoc/issues/1715
