### ISSUE TITLE
How to add a new tag in the navigation bar?

### ISSUE THREAD

**Issue by diegospinedi** [Redocly/redoc#1569]
Hello! I have an React Application, and i used a RedocStandalone, and i need a new tag in the navigation bar for add especific documentation (eg. state diagrams for pays),  and it was impossible for me. can someone help me with an example?  This is a my component
const FirstComponent =() => {
  var spec="https://XXXXXXXX/v1/swagger.json";

  const options = {
    scrollYOffset: '.navbar', // makes the fixed sidebar and scrolling play nicey with docusaurus navbar
    theme: {
        sidebar: {
            width: '300px' // about the same as the sidebar in the docs area, for consistency
        }
    },
    showExtensions:true
};
 
    return <RedocStandalone specUrl={spec} options={options}/>

    
}
       
export  default FirstComponent

**Comment by adamaltman** [comment]
You could add a tag to your tags definitions inside of the OpenAPI definition. Tags allows for a markdown description which can include your state diagram.

**Comment by diegospinedi** [comment]
could youu get an exámenes? and.....if chance me api definition?? shouk be rewrite?

**Comment by diegospinedi** [comment]
example sorry

**Comment by RomanHotsiy** [comment]
Here is the example: https://github.com/Redocly/redoc/blob/master/demo/openapi.yaml#L8-L31
