### ISSUE TITLE
upgrade breaks redoc from 2.0.0-rc.48 to 2.0.0-rc.51

### ISSUE THREAD

**Issue by beatrizoliveiira** [Redocly/redoc#1575]
My site with docusaurus version 2.0.0-alpha.72 breaks with this update:

Failed to compile
```
/home/beatriz/projects/feedback/feedback-front/node_modules/@redocly/openapi-core/lib/resolve.js
Module not found: Can't resolve 'fs' in '/home/beatriz/projects/feedback/feedback-front/node_modules/@redocly/openapi-core/lib'
```

**Comment by andriyl** [comment]
@beatrizoliveiira added fix, version: 2.0.0-rc.53 (latest).
Could you confirm, please?

**Comment by mfaux** [comment]
I'm getting similar errors with 2.0.0-rc.54:

```
Module not found: Error: Can't resolve 'fs' in 'C:\git\myrepo\doc\node_modules\redoc\bundles'
Module not found: Error: Can't resolve 'process/browser' in 'C:\git\myrepo\doc\node_modules\yaml\browser\dist'
```

**Comment by tm1000** [comment]
This is still an issue in 54

**Comment by RomanHotsiy** [comment]
Must be related to webpack 5 specifics. We'll try to check this. Any help would be appreciated.

It works at least with create react app.

**Comment by MihaiSandor** [comment]
It's still in issue in react-static

**Comment by tm1000** [comment]
@RomanHotsiy Its something in webpack 5 yes as its an issue when Im using NextJS specifically

**Comment by CodeFarmer** [comment]
Can confirm this is a problem with recent Gatsby as well (Webpack 5). rc.55 still broken, can't roll back to .48 because it's gone?

**Comment by RomanHotsiy** [comment]
Webpack 5 issue here: https://github.com/Redocly/redoc/issues/1584

**Comment by useafterfree** [comment]
> Can confirm this is a problem with recent Gatsby as well (Webpack 5). rc.55 still broken, can't roll back to .48 because it's gone?
> 
> EDIT: current workaround in webpack config
> 
> ```
>     resolve: {     
>       fallback: {
>         "fs": false
>       }
>     }
> ```

This also fixes Next.js (in next.config.js):

```
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      // config.node = { fs: 'empty' };
      config.resolve.fallback.fs = false;
    }

    return config
  }
```

**Comment by glintik** [comment]
BTW, for all who are still using Webpack 4(like me):
```
node: {
    fs: 'empty',
},
```
