### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by villerdex** [Redocly/redoc#1584]
Hi will there be any Webpack 5 support anytime soon?

**Comment by rohit-gohri** [comment]
This is what you'll need to add to webpack config to fix build for webpack 5 or for use with latest docusaurus beta:

```js
import webpack from 'webpack';
import NodePolyfillPlugin from 'node-polyfill-webpack-plugin';

const webpackConfig = {
  plugins: [
    new webpack.DefinePlugin({
      'process.versions.node': JSON.stringify(
        process.versions.node || '0.0.0',
      ),
    }),
    new NodePolyfillPlugin({}),
  ],
};
```

If more errors pop up then this article was really helpful for debugging:
https://indepth.dev/posts/1166/this-will-make-you-more-efficient-at-debugging-webpack-unspecified-build-errors

**Comment by pglezen** [comment]
I ran into this trouble when I attempted to upgrade my Docusaurus installation to the [beta version](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta), which internally updates its webpack to v5.

**Comment by rohit-gohri** [comment]
> I ran into this trouble when I attempted to upgrade my Docusaurus installation to the [beta version](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta), which internally updates its webpack to v5.

@pglezen Off topic but I have made a redoc preset for docusaurus, might be useful to you: https://github.com/rohit-gohri/redocusaurus

**Comment by theophile-scrive** [comment]
If I understand correctly, the beta version is unusable because it switches to webpack5 (which is not supported)?

Is there a way to constrain the webpack version as an end-user?

**Comment by clarencedesmarais** [comment]
Tried the solution proposed by @rohit-gohri , unfortunately did not work for me with     "webpack": "5.62.1" , still getting : 
```
 Can't resolve 'fs' in ....
```

**Comment by rohit-gohri** [comment]
> Tried the solution proposed by @rohit-gohri , unfortunately did not work for me with "webpack": "5.62.1" , still getting :
> 
> ```
>  Can't resolve 'fs' in path-to-app/node_modules/redoc/bundles
> ```

Updated my answer above to add this:

```
  resolve: {
    fallback: {
      fs: false,
    },
  },
```
 to fix this error.

**Comment by pglezen** [comment]
> This is what you'll need to add to webpack config to fix build for webpack 5 or for use with latest docusaurus beta:
> 
> ...

I'm sorry for being dense.  But where does one find/create a `webpack.config.js` in a typical Docusaurus project?

**Comment by rohit-gohri** [comment]
> > This is what you'll need to add to webpack config to fix build for webpack 5 or for use with latest docusaurus beta:
> > ...
> 
> I'm sorry for being dense. But where does one find/create a `webpack.config.js` in a typical Docusaurus project?

I think that requires creating a plugin. 

You might be interested in https://github.com/rohit-gohri/redocusaurus for a prebuilt solution for adding redoc to Docusaurus.

Or if you want to do it yourself, then this gist gives an example: https://gist.github.com/rohit-gohri/59d0e6a9b4f51d1dd39f5e8894050f74

**Comment by 10thfloor** [comment]
Confirmed this works for Redoc + Gatsby as well.
