### ISSUE TITLE
Is there "exampleRefs" for "SchemaDefinition"?

### ISSUE THREAD

**Issue by N-Nagorny** [Redocly/redoc#1585]
Hi!
I use "SchemaDefinition" Markdown extension to describe a general schema which has two properties: "data" and "type". For each "type" there is an according subschema for "data", one of those described in "oneOf".
Is it possible to attach multiple examples to such schema?
Thanks in advance!

**Comment by lornajane** [comment]
Thank you for the question, and please accept our apologies for the slow response. It's not possible to attach multiple examples, no.
