### ISSUE TITLE
Problem with react dependency ?

### ISSUE THREAD

**Issue by Herrick19** [Redocly/redoc#1588]
Hi,

I am not too sure what the problem is, but when we install redoc-cli globally, react gets removed every time we do an update or reinstall redoc-cli.

Here is how to reproduce:
"npm install -g redoc-cli"
//Outputs added 276 package

If you run redoc-cli, it works

Now if you type again
"npm install -g redoc-cli"
//Outputs removed 275 packages, changed 1 package

Why are are dependent packages removed ? redoc-cli doesn't work anymore and I get a message about the react dependency not found...

Typing
"npm update -g" does the same thing, all 275 packages get removed

Any idea why this happens ? bug in your dependencies or bug with NPM ? Yarn does the same thing by the way

Thanks in advance

**Comment by RomanHotsiy** [comment]
What version of npm are you at?

**Comment by Herrick19** [comment]
Hi,

I am running the latest 7.10 version on windows:

>npm -v
7.10.0

Regards

**Comment by RomanHotsiy** [comment]
Should be fixed.
