### ISSUE TITLE
Redoc Standalone Not Working in IE 11

### ISSUE THREAD

**Issue by enots227** [Redocly/redoc#1589]
Hello, my company uses ReDoc standalone and we still supports IE11 for our customers. The ReDoc works completely fine for Google Chrome and all other browsers except for IE11.

I created https://github.com/Redocly/redoc/issues/1530 back in February to address this issue; however, it was never full fixed and it still display nothing. The error message I was getting changed. I see this error in the console when I tried using redoc.standalone.js 2.0.0-rc.53.

New error message:
```
SCRIPT1014: Invalid character
redoc.standalone.js (22,95458)
```

**Comment by enots227** [comment]
Looks like the compiled script has a grave accent, which IE doesn't support.

![grave_accent_error](https://user-images.githubusercontent.com/8800875/115604753-95fb4a80-a296-11eb-98ad-6c755a8b56cc.png)

**Comment by RomanHotsiy** [comment]
Fixed on the rc.54
