### ISSUE TITLE
Create a Table of Content for README.md file

### ISSUE THREAD

**Issue by roshnaeem** [Redocly/redoc#1590]
There are many benefits of having a table of content in the `README.md` file. 

1. The table of content will allow the users to go directly to the specific section. 
2. It will give users an overview of the `README.md` file.
3. More professional appearance.

**Comment by roshnaeem** [comment]
@swapnilogale I want to work on this issue! 
Can I start working on it if the issue seems reasonable?

**Comment by lornajane** [comment]
This is now a built-in GitHub feature, so I don't think we need to build it ourselves.
