### ISSUE TITLE
tag description from external markdown

### ISSUE THREAD

**Issue by damianobarbati** [Redocly/redoc#1591]
I honestly did not understand how to properly segment my content into multiple .md files and then include them in given tag description. 

- solution <https://redoc.ly/docs/resources/ref-guide/#yaml>: not working, as tag description cannot be an option and redoc throws:

```js
/**
 * @openapi
 * tags:
 *   - name: Lifecycle
 *     description: 
 *       $ref: _Lifecycle.md
 */
```

- solution <https://redoc.ly/docs/developer-portal/guides/reusing-content/>: it includes raw content, does not render the markdown
 
```js
/**
 * @openapi
 * tags:
 *   - name: Lifecycle
 *     description: |
 *       <embed src="_Lifecycle.md" />
 */
```

My goal is to not have a giant openpi.yml but have sections divided into .md files linked back in logical sections.

In combo with:
```yml
x-tagGroups:
  - name: Key concepts
    tags:
      - Lifecycle
```
which generates a sidebar section.

Something like `<SchemaDefinition />` component but `<Markdown src="" />` would be a solution.
I tried but it does not render.
What's the intended way?

**Comment by lornajane** [comment]
I'm not sure I understand your question, and it's been open for a long time. I'm sorry about that.

I think you are saying you don't want your openapi description in a single long file? Try using [Redocly CLI split command](https://redocly.com/docs/cli/commands/split/) to spread your description across manageable files and structure. You can still use this to generate your Redoc documentation. Hope this helps, I'll close this old issue for now, but do let us know if you have more questions about it.
