### ISSUE TITLE
Errors in redoc build from 0.11.0

### ISSUE THREAD

**Issue by karthikgooner** [Redocly/redoc#1595]
Hello there,

Thank you the redoc tool. It was working fabulously for us until 0.11.0 but since 0.11.0, our "redoc-cli bundle" command started failing with the following stack trace...

> 14:17:58  + redoc-cli bundle dtrt/src/main/resources/static/meta-data/swagger-expanded.json
14:17:59  Error: Cannot read property 'readFile' of undefined
14:17:59      at BaseResolver.<anonymous> (/home/piper/.npm-global/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:102:23)
14:17:59      at Generator.next (<anonymous>)
14:17:59      at /home/piper/.npm-global/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:8:71
14:17:59      at new Promise (<anonymous>)
14:17:59      at __awaiter (/home/piper/.npm-global/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:4:12)
14:17:59      at BaseResolver.loadExternalRef (/home/piper/.npm-global/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:91:16)
14:17:59      at BaseResolver.<anonymous> (/home/piper/.npm-global/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:130:30)
14:17:59      at Generator.next (<anonymous>)
14:17:59      at /home/piper/.npm-global/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:8:71
14:17:59      at new Promise (<anonymous>)

We tried to run it again with the 0.10.4, it is working fine again. Would you be able to help fix this problem for us please?

Best Regards,
KP

**Comment by AntonKozachuk** [comment]
@karthikgooner Could you possibly share your spec? This way I could try to reproduce this issue. Thanks.

**Comment by karthikgooner** [comment]
> @karthikgooner Could you possibly share your spec? This way I could try to reproduce this issue. Thanks.

Hi Anton, many thanks for the response. Please see the file here. (Renamed the extension to txt from json)

[swagger-expanded.txt](https://github.com/Redocly/redoc/files/6414605/swagger-expanded.txt)

**Comment by karthikgooner** [comment]
Hello Anton,

If I may ask, have you had a chance to look at this issue please?

Best Regards,
KP

**Comment by RomanHotsiy** [comment]
@karthikgooner could you tri on redoc-cli@0.12.0

**Comment by RomanHotsiy** [comment]
I believe it is fixed already. Feel free to reopen if it's not.

Thanks!

**Comment by karthikgooner** [comment]
Hello @RomanHotsiy, 

Yes, it's now been fixed. We had a problem with the npm because the npm -g installation would not have access to its base location and if we do local installation without "-g", container could not find the redoc-cli command. Took a bit to figure out the workaround to run the index.js using node directly. Would you guys know if that is something you could make it (redoc-cli command without -g installation) work? 

Many thanks for this fix nevertheless.

**Comment by samuelhgf** [comment]
I'm facing the same issue

```javascript
"dependencies": {
    "@redocly/openapi-cli": "^1.0.0-beta.44",
    "redoc": "^2.0.0-rc.54"
  },
  "devDependencies": {
    "redoc-cli": "^0.10"
  }
```
