### ISSUE TITLE
Bundle Command Wraps Text at 80 Characters. 

### ISSUE THREAD

**Issue by michaelcilibrasi** [Redocly/redoc#1601]
The Bundle command's output wraps text after 80 characters. For description tags, this produces output different than what the writer's author. It's more than just a cosmetic effect, it makes searches less reliable because of the unexpected line breaks.

Can this be fixed to not force a wrap at all? Or at least a length of my choosing instead?

**Comment by lornajane** [comment]
I think this was fixed as we moved from `redoc-cli` to [Redocly CLI](https://redocly.com/docs/cli/). Please update and give that a try.

I also want to apologise for how long this issue remained open without response! I'm closing it, kind of assuming you're probably not still worrying about this thing, but please let us know you have more information or questions for us on this.
