### ISSUE TITLE
Ability to hide tags / tag groups

### ISSUE THREAD

**Issue by nkavian** [Redocly/redoc#1609]
I'm using `x-tagGroups` and I have certain groups I need to hide. This is impossible on the server / openapi.json side as I'm using SpringDoc. I'm looking for a capability in JavaScript to tell Redoc to hide certain tag groups.

I could do this on my own easily with the left side bar, but the main content is not structured easily. The operations are not contained in a nested div of the tag, and the tags are not nested within the tag group.

Requesting an enhancement to natively support a method to hide groups, tags, and/or operations; or to at least nest their HTML divs properly so that I can use jQuery on my own.

**Comment by RomanHotsiy** [comment]
Can you preprocess openapi.json file before passing it to redoc? 
You should be able to download the openapi file remove the groups you don't need and then use [Redoc.init](https://github.com/Redocly/redoc#advanced-usage-of-standalone-version)

Let me know if this works.

**Comment by nkavian** [comment]
I can not, I'm using SpringDoc which generates the `openapi.json` file one time at load.

Probably worth detailing more context:

A) If I could hide content in `openapi.json` before it's cached, that would be analogous to showing/hiding features globally. I'm not looking for that, although that would still be a nice feature.

B) If I could hide content in Redoc using JavaScript, that would let me control showing hiding content based on who is logged into my application. Only when the user is logged in do I know which features (tags/tag groups) I want to show/hide.

**Comment by lornajane** [comment]
Redoc doesn't have this functionality, but you could use the parts you want to hide using a [filter decorator](https://redocly.com/docs/cli/decorators/filter-out/). I'll close the issue since we're not making changes to Redoc itself, but hopefully the filtering does what you need.
