### ISSUE TITLE
Is it possible to set no-cors on the <redoc> element?

### ISSUE THREAD

**Issue by StarfallProjects** [Redocly/redoc#1610]
I'm getting the following error:
_CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

Adding no-cors to the <redoc> element was my first guess, but doesn't help:
`<redoc no-cors spec-url='path-to-file'></redoc>`

Is there a way to set the request headers?

**Comment by darklynx** [comment]
This is not an issue with ReDoc library.

It seems like that in your case the `path-to-file` is hosted on a different domain than the page that uses redoc library. The server that hosts YAML/JSON documentation of API does not provide `Access-Control-Allow-Origin` headers. And **browser** (but not the redoc library) prevents this document from being loaded and rendered by ReDoc.
