### ISSUE TITLE
Feature Request: emoji support

### ISSUE THREAD

**Issue by mm-gmbd** [Redocly/redoc#1612]
It's a nice-to-have (especially with the existence of unicode emojis), but emoji syntax support would be a welcome feature (e.g. `:smile:`).

According to [this issue](https://github.com/markedjs/marked/issues/233), it doesn't look like Redoc's markdown parser ([marked](https://github.com/markedjs/marked)) supports emojis, but there's a nearly-one-liner suggestion using another node package in that same issue that seems worth considering:

```javascript
// parser.js
import marked from 'marked'
import emoji from 'node-emoji'

export function parse = (markdown) => {
  const replacer = (match) => emoji.emojify(match)
  markdown = markdown.replace(/(:.*:)/g, replacer)
	 
  return marked(markdown)
}
```

**Comment by RomanHotsiy** [comment]
This will increase bundle size with little value. I would not implement it.
