### ISSUE TITLE
Feature request: support for units in schema property

### ISSUE THREAD

**Issue by mm-gmbd** [Redocly/redoc#1617]
Though this feature [request was raised (and squashed) in OAS](https://github.com/OAI/OpenAPI-Specification/issues/2061), it would be great to be able to define a unit and have that displayed in some way in request parameters.

Something like `x-unit` or `x-units` seems like a straightforward way to define it, and I'd expect the output to look something like the following:

![image](https://user-images.githubusercontent.com/3329824/117873384-b737d100-b26d-11eb-8dad-0973b2ecdfec.png)

Given this schema snippet:

```jsonschema
  temperature:
    type: object
    description: Instantaneous...
    properties:
      val:
        description: The internal..
        type: number
        x-unit: °F
      min:
        description: Minimum...
        type: number
    required:
      - val
```

**Comment by RomanHotsiy** [comment]
You can add it in `description` or `format`.

`x-unit` is not implemented by any other openapi tooling.

**Comment by mm-gmbd** [comment]
Not being implemented by any other openapi tooling doesn't seem like much of a reason for not implementing it. 

AFAIK, `x-tagGroups` is only a vendor extension that Redoc supports, and the reason it's supported is because it's useful in organizing/viewing the generated documentation.

Any numeric value that's returned from an API presumably has some unit of measurement, so this seemed like a way to extend the capabilities of Redoc to enhance the understanding of someone reviewing the API documentation.

**Comment by mm-gmbd** [comment]
But, if it doesn't seem valuable because it can be added in the `description`, that's fine. I understand I'm asking for a free update to a free tool :)

**Comment by RomanHotsiy** [comment]
@mm-gmbd thanks for understanding! We just don't overpack Redoc with tons of functionality when the same or the very similar result could be achieved by just using markdown description.
