### ISSUE TITLE
Latest master not released

### ISSUE THREAD

**Issue by Shahaed** [Redocly/redoc#1628]
The latest release (and the cdn version) is `2.0.0-rc.53` which is not up to date with master. 

Interestingly it was the build before a failed build on master: 
![image](https://user-images.githubusercontent.com/4543437/119776627-c7b19380-be8a-11eb-93bc-b4b90cb3d2b0.png)

I'm guessing the failure on 4-13 stopped the release cycle.

**Comment by RomanHotsiy** [comment]
Released now!

Thanks for the reminder!
