### ISSUE TITLE
Plaintext examples are ignored

### ISSUE THREAD

**Issue by mpbzh** [Redocly/redoc#1632]
The following example is a reduced version of my (afaik) valid OpenApi 3 file defining a request body with both `application/json` and `text/plain` mimetypes:
```yaml
openapi: 3.0.3
info:
  title: 'Test API'
  version: 1.0.0
paths:
  /users:
    post:
      summary: 'Missing CSV examples'
      description: 'This demonstrates missing csv examples'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                records:
                  type: array
                  items:
                    $ref: '#/components/schemas/person'
          text/plain:
            schema:
              type: string
              example: "This is a Test"
        required: true
      responses:
        '200':
          description: 'Placeholder response'
components:
  schemas:
    person:
      required:
        - person_id
        - name
      type: object
      properties:
        person_id:
          type: integer
          description: 'Person identifier in source system'
        name:
          type: string
          description: 'Person name'
      example:
        person_id: 1
        name: 'Hello World'

```

The official [Swagger Editor](https://editor.swagger.io/) accepts the plaintext example:
![swagger-editor](https://user-images.githubusercontent.com/6039062/120283552-99351d80-c2bb-11eb-8140-a9a189d27001.png)

When I generate a standalone HTML file using `redoc-cli` (Version 0.11.4), the example is ignored:
![nosample](https://user-images.githubusercontent.com/6039062/120283573-9e926800-c2bb-11eb-978b-b52f076480de.png)

Also, but probably due to the same bug, when I remove the `application/json` 

This issue might be related to #371.

**Comment by rishagit** [comment]
Is there any update on this issue? how can we show example for text/plain type?

**Comment by edno** [comment]
@RomanHotsiy - Do you have an update on the [comment](https://github.com/Redocly/redoc/issues/371#issuecomment-343457602) you made in #371 
> ReDoc 2.0 will support all the mime samples correctly so I am not going to fix it properly for ReDoc 1.x

**Comment by aman2457** [comment]
Is there any update on this issue? 
I'm not able to show the examples of text/plain. 
@rishagit did you got any solution for this?

**Comment by lornajane** [comment]
This should be updated in Redoc >=2.0, so I'll close this issue - but please let us know if you're still seeing something that doesn't look right?
