### ISSUE TITLE
Wrong override on multi-external-reference parameters

### ISSUE THREAD

**Issue by JervNorsk** [Redocly/redoc#1636]
Informations
---
__Redoc-Cli Version__
```bash
└─➤ npm redoc-cli -v
6.14.11
```

__Command Usage__
```bash
npx redoc-cli bundle api.yaml -o api.html
```

Description
---
I encountered this problem in the parameters section.

Here I am adding an element in the parameters array referring to an external template that I want to override with some additional data:
![image](https://user-images.githubusercontent.com/7672360/120799823-82066200-c53f-11eb-9017-912dcc45d3b5.png)
![image](https://user-images.githubusercontent.com/7672360/120799892-977b8c00-c53f-11eb-9d9c-cf803f06f9aa.png)

These are only the templates defined in the external file:
![image](https://user-images.githubusercontent.com/7672360/120800374-2688a400-c540-11eb-8031-a8fe63706f4f.png)

When I try to add a new parameter of the same type this happens:
![image](https://user-images.githubusercontent.com/7672360/120800114-df021800-c53f-11eb-82f5-fec86e803c6a.png)
![image](https://user-images.githubusercontent.com/7672360/120800143-e9bcad00-c53f-11eb-8cae-1444edaa0b38.png)

![image](https://user-images.githubusercontent.com/7672360/120800214-fa6d2300-c53f-11eb-99b5-026333dd742b.png)
![image](https://user-images.githubusercontent.com/7672360/120800264-078a1200-c540-11eb-8636-66677eb24663.png)

**Comment by adamaltman** [comment]
In OAS 3.0 you aren't allowed to add sibling properties next to a $ref.

**Comment by RomanHotsiy** [comment]
As @adamaltman mentioned this is expected behavior. `$ref` next to other props is allowed in OAS 3.1. Redoc already has basic support for it.
