### ISSUE TITLE
Possibility to deref pointers in build-time?

### ISSUE THREAD

**Issue by vicary** [Redocly/redoc#1639]
# The Problem

Not sure where to start, my use case is that I don't want to expose my source YAML directly to the public.

My project is a Next.js website. Given a sample `openapi.yaml` below that I have a reference to an external file:

```yaml
# openapi.yaml
openapi: 3.0.0
paths:
  /test:
    $ref: 'paths.yaml#/test'
```

```yaml
# paths.yaml
test:
  get: # contents skipped for simplicity
```

I am importing the root YAML via `next-plugin-yaml` and renders the results as below

```jsx
// Home.jsx
import rootSpec from "openapi.yaml";
export default () => <RedocStandalone spec={rootSpec} />;
```

It throws `Error: Invalid JSON pointer: paths.yaml#/test` during render,
![image](https://user-images.githubusercontent.com/85772/121285942-be580a80-c911-11eb-8f3e-15266426a926.png)

# Proposed Solution

Add one more props/option to let me put all referenced files beforehand, for example:

```diff
// Home.jsx
import rootSpec from "openapi.yaml";
+ import pathsSpec from "paths.yaml";
- export default () => <RedocStandalone spec={rootSpec} />;
+ export default () => <RedocStandalone spec={rootSpec} refs={[pathsSpec]} />;
```

# Current Workaround

It works when I instead host all my source YAML files in the public, and use `specUrl` instead of the `spec` object, it will fetch `paths.yaml` runtime. But I don't want to directly expose my YAML sources.

**Comment by RomanHotsiy** [comment]
Try to use both `spec` and `specUrl` props. Spec URL is required so Redoc knows where to load the referenced files from.
I believe it tries loading `paths.yaml#/test` from a wrong location.

**Comment by vicary** [comment]
@RomanHotsiy I am inclined to believe that this method may make it fetch from my private directory.

Because I am keeping my source YAML as `private/*.yaml`, and I want to manually import them all in `Home.jsx` such that the final bundle contains all imported objects.

**Comment by RomanHotsiy** [comment]
You can protect your private *.yaml files instead. This feature seems to be too narrow and complicated.

Thanks for understanding.
