### ISSUE TITLE
Wrong name of object is shown when using $ref in OAS 3.1

### ISSUE THREAD

**Issue by ioki-klaus** [Redocly/redoc#1643]
We recently updated our documentation to OAS 3.1, previously, when we added a reference to another schema, we used:

```js
          "client": {
            "description": "Client configuration",
            "allOf": {
              "$ref": "#/components/schemas/passenger_api--client"
             }
          },
```

As no siblings next to `$ref` were allowed. Now with OAS 3.1 this changed and we updated our docs to the following:

```js
          "client": {
            "description": "Client configuration",
            "$ref": "#/components/schemas/passenger_api--client"
          },
```

This, also works, the docs are properly generated and the reference is loaded correctly, but instead of the correct object type, it displays `object (schemas)` instead of the expected `object (passenger_api--client)`:

![Bildschirmfoto 2021-06-10 um 10 54 26](https://user-images.githubusercontent.com/64834279/121495842-3c7fe400-c9da-11eb-9c04-5160f824e1fb.png)

For all other instances that we use `$ref` in (oneOf if it can also be nullable, or arrays), the correct schema name is displayed.

**Comment by Oprysk** [comment]
This issue was fixed in the scope of [PR](https://github.com/Redocly/redoc/pull/1766) and no longer reproduced.
If you face this again, please reopen the issue.
Thanks!
