### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/es/promise' in '/Users/me/project/node_modules/redoc/bundles'

### ISSUE THREAD

**Issue by josmithua** [Redocly/redoc#1645]
Redoc version: redoc@2.0.0-rc.54

Getting this error when running `next build`:

`ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/es/promise' in '/Users/me/project/node_modules/redoc/bundles'`

Resolved by downgrading to the last version we used (redoc@2.0.0-rc.48)

**Comment by tm1000** [comment]
This is technically a dup of #1575 which is related to webpack5 specifically.

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/redoc/issues/1584
