### ISSUE TITLE
Redoc does not work with nextjs

### ISSUE THREAD

**Issue by tm1000** [Redocly/redoc#1647]
Between release 53 and 54. Redoc suddenly broken with any system that is using webpack 5 and nextjs (https://github.com/Redocly/redoc/compare/v2.0.0-rc.53...v2.0.0-rc.54)

See:
- #1645
- #1575 

It looks like redoc is including webpack and perhaps being bundled twice. The "standalone" version of Redoc (used in React) should not be bundled/compiled. The bundling should be left to upstream. What appears to be happening is that the bundle is assuming "WEB" only while nextjs is both NODE and WEB

```
info  - Creating an optimized production build ..<w> [webpack.cache.PackFileCacheStrategy] Restoring pack from /app/.next/cache/webpack/client-production.pack failed: Error: No such label 'restore cache container' for WebpackLogger.timeEnd()
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/app/node_modules/redoc/bundles'
```

**Comment by tremby** [comment]
I was just about to open exactly the same ticket!

**Comment by tm1000** [comment]
@tremby you can sort of fix with with a NextJS Webpack5 workaround:

https://stackoverflow.com/a/67233156

Im not sure of the implications of doing so

For my specific usage I had to do this (next.config.js):

```
const settings = {
	webpack(config, options) {
		if (process.env.NODE_ENV !== 'development') {
			config.plugins.push(
				new UnusedWebpackPlugin({
					// Source directories
					directories: [path.join(__dirname, 'src')],
					// Exclude patterns
					exclude: [
						'clearlyip/**/*',
						'public/**/*',
						'*.test.js',
						'pages/_document.jsx',
					],
				})
			);
		}
		if (config.resolve.fallback) {
			config.resolve.fallback.fs = false;
		}

		return config;
	},
};
settings.future = {
	webpack5: true,
};

module.exports = settings;

```

**Comment by tremby** [comment]
Thanks. But I'm still using webpack 4 for now, and have worked around the problem in the mean time by using rc 53.

**Comment by tm1000** [comment]
For webpack 4 you do something like:

```
const settings = {
	webpack(config, options) {
		if (config.node.fs) {
			config.node.fs = false;
		}

		return config;
	},
};

module.exports = settings;
```

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/redoc/issues/1584
