### ISSUE TITLE
Opt out of particular styles

### ISSUE THREAD

**Issue by tremby** [Redocly/redoc#1648]
Is there some way to opt out of particular styles?

I'm embedding this in a website which already styles, for example, `<code>` elements. The default styles from Redoc clobber my own, and no matter what I set in the Redoc theme, unless I start throwing `!important` in my global stylesheet I can't undo particular styles which Redoc adds such as the border around `<code>` elements.

I'd prefer if it kept `code`, `h1`, `h2`, `h3`, `a`, and possibly a few other things unstyled.

**Comment by RomanHotsiy** [comment]
This is unfortunately not supported and we don't have immediate plans to resolve it.
