### ISSUE TITLE
Redoc - Pagination option to boost HTML loading in Community edition

### ISSUE THREAD

**Issue by ngo-minh-thang-nguyen** [Redocly/redoc#1660]
I would like to ask for a subject related to the Redoc tool used to generate API documentation.

In their reference page, there are an option called "pagination" (cf https://redoc.ly/docs/api-reference-docs/configuration/) which is used to control how the API documentation is paginated. This option is really helpful in order to boost the loading of documentation page. Unfortunately, this option is only activated in Commercial edition.

My question is : Do you know whether we can have a similar option in Community edition? Or how we can configure to boost the loading of documentation page ?

Thank you in advance

**Comment by ngo-minh-thang-nguyen** [comment]
Can anybody reply to this question ?

**Comment by adamaltman** [comment]
This is a premium edition feature. It won't be added to the community edition.
