### ISSUE TITLE
Loading spinner isn't shown

### ISSUE THREAD

**Issue by nkavian** [Redocly/redoc#1670]
If you set any boolean value at all, be it true or false, the 'Loading' animation is never shown. You have to completely remove `hideLoading` for it to show.

```
      var options = {
        hideLoading: false,
      };
```

Using version 2.0.0-rc.26

**Comment by RomanHotsiy** [comment]
Fixed in https://github.com/Redocly/redoc/pull/1709, will be released a bit later today.
