### ISSUE TITLE
Default Search on Loading

### ISSUE THREAD

**Issue by jbloem9** [Redocly/redoc#1674]
I am using https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js in an angular site to display some api documentation.  The user has a page with a detailed description and some examples.  We then have a link that opens the api documentation using redoc.standalone.js.  

We would like to open the documentation at a specific place so that the user can see the documentation for the item they were reading up on without having to search for it first.  Is this currently possible?

This could be achieved by giving a default search value when loading the page, so the user does not have to type it in.  Is this possible? 

Redoc.init('path_to_my_json', {
      scrollYOffset: 60,
      hideDownloadButton: true,
      -->would be good to have a option here to specify search value
     defaultSeachValue: 'CreatePet'
    }, document.getElementById('redoc'))}

**Comment by RomanHotsiy** [comment]
You should be able to use the hash based link, e.g. https://redocly.github.io/redoc/#operation/getInventory

The default search value doesn't make sense.

**Comment by pepa-linha** [comment]
> The default search value doesn't make sense.

The default search makes a lot of sense. The search query should be available in the URL. For example, I would like to link to an API with a given query, I do not want to search inside the loaded page.

Another problem is that it is not possible to send URL with the search results to someone else 👎🏼
