### ISSUE TITLE
High severity npm dependency security risk - prismjs

### ISSUE THREAD

**Issue by Leigh-M** [Redocly/redoc#1676]
### npm audit report

prismjs  <1.24.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1762
fix available via `npm audit fix`   // npm audit fix does not work for me
node_modules/redoc-cli/node_modules/prismjs

1 high severity vulnerability

**Comment by RomanHotsiy** [comment]
Fixed in 0.12.2
