### ISSUE TITLE
Array size constraints displayed when not defined

### ISSUE THREAD

**Issue by eyedealist** [Redocly/redoc#1677]
Array properties which have no maxItems defined are defaulting to a value of 2, which will display as either `2 items` or `<= 2 items`.

```json
"specialties": {
  "type": "array",
  "items": {
    "type": "string"
  }
}
```
![image](https://user-images.githubusercontent.com/3293629/124807454-6538c200-df23-11eb-9357-c1de90981189.png)

```json
"questionnaires": {
  "type": "array",
  "items": {
    "type": "string",
    "format": "uri"
  }
}
```
![image](https://user-images.githubusercontent.com/3293629/124807821-d2e4ee00-df23-11eb-9477-a55330982435.png)

**Comment by AlexVarchuk** [comment]
@eyedealist Hi, I need more data to reproduce them. Could you please share a reproducible sample?

**Comment by RomanHotsiy** [comment]
Closing. Feel free to reopen.
