### ISSUE TITLE
Docker Hub "latest" tag targets rc.53 instead of rc.54

### ISSUE THREAD

**Issue by TheWhite147** [Redocly/redoc#1682]
If I use the `latest` tag from Docker Hub, it targets `v2.0.0-rc.53` when I inspect my Redoc page.
Since `v2.0.0-rc.54` is the latest release on GitHub, can you please fix that, or push `v2.0.0-rc.54` as a tag on Docker Hub?

Thanks!

**Comment by RomanHotsiy** [comment]
Fixed in https://github.com/Redocly/redoc/commit/f7211ceb0829334b3b4661d9c6168403f2345ba4

Next release will appear on dockerhub

**Comment by TheWhite147** [comment]
Are you going to tag all the other versions soon in Docker Hub? Last tagged is rc.53...

**Comment by RomanHotsiy** [comment]
сс @AlexVarchuk

**Comment by TheWhite147** [comment]
Up 🆙

**Comment by TheWhite147** [comment]
Up!

**Comment by TheWhite147** [comment]
Up!

**Comment by RomanHotsiy** [comment]
We need to push to dockerhub from github actions. Automated build on docker hub need a pro plan nw.

**Comment by RomanHotsiy** [comment]
@TheWhite147 pushed manually for now latest and v2.0.0-rc.58

**Comment by TheWhite147** [comment]
@RomanHotsiy Thanks a lot! 👍
