### ISSUE TITLE
Content jumping when opening a Link to a specific Tag

### ISSUE THREAD

**Issue by fritzfr** [Redocly/redoc#1683]
Hey,

when linking to a specific section in the docs, the docs jump up to some completely different section.

Example: https://docs.fintecsystems.com/swagger/#tag/General-Information

The page opens, but then jumps to: https://docs.fintecsystems.com/swagger/#tag/XS2A.api.connections

Is there something I'm doing wrong?

**Comment by RomanHotsiy** [comment]
Is it still relevant? I can't reproduce it right now.

If it is, what browser and OS do you use?

**Comment by fritzfr** [comment]
Weirdly enough I also fail to reproduce it now. It has been an issue for quite a while though and was noticed multiple times by others too.

Anyway, I close it for now.
