### ISSUE TITLE
Discriminator dropdown too narrow

### ISSUE THREAD

**Issue by cmeeren** [Redocly/redoc#1689]
The width of the discriminator dropdown is equal to the width of the currently selected item. This makes it hard to use, since when selecting a short value you can't see the other values properly.

Long value selected:

![image](https://user-images.githubusercontent.com/7766733/125777474-172b4a23-6cdc-4254-a583-3acaa2ab4efc.png)

Short value selected, everything is clipped:

![image](https://user-images.githubusercontent.com/7766733/125777498-bfe2dd40-9ae2-4557-9356-33a769881738.png)

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/redoc/issues/451
