### ISSUE TITLE
Issue with Try it console <Works with Swagger UI>

### ISSUE THREAD

**Issue by manjunath-batakurki** [Redocly/redoc#1696]
We are seeing a weird behavior with Try it Console. 

The Data is displayed properly before clicking on `Try it` button, but few of the Request body content disappears post clicking `Try it` button

We tried the same through the Swagger UI. It works. looks like a basic issues not working in Redocly. Please help on this.

**Before Clicking on  Try it:**
![image](https://user-images.githubusercontent.com/78580773/125831068-1ed960f4-7e28-4494-bf30-42ba5049f272.png)

**After Clicking on Try it :**
![image](https://user-images.githubusercontent.com/78580773/125831284-300a7ada-524e-49bd-afc1-9a0ff0815e8b.png)

**The Same in Swagger UI works fine:**
![image](https://user-images.githubusercontent.com/78580773/125831125-2a3a5de5-5920-409c-8e34-7c68db2fc0dd.png)

**For your info, we are using redocly 1.0.0-beta.159**

**Comment by RomanHotsiy** [comment]
There is no Try it out in open-source version. Issues about reference docs product should be reported to team@redocly.com
