### ISSUE TITLE
Question: Limit doc to subset of routes?

### ISSUE THREAD

**Issue by joerg-walter-de** [Redocly/redoc#1704]
Is it possible to limit the routes used when generating the html to a specified subset?

**Comment by RomanHotsiy** [comment]
No, this is not supported. You should preprocess the openapi definition before passing it to Redoc.

You can try to use [openapi-cli](https://github.com/Redocly/openapi-cli) decorators for that: https://redoc.ly/docs/cli/guides/hide-apis/
