### ISSUE TITLE
theme options

### ISSUE THREAD

**Issue by sonalij18** [Redocly/redoc#1706]
Hi, 
        I'm trying to used redoc with theme option but in my documentation alignment(position) of elements are not proper.
<img width="1438" alt="Screenshot 2021-07-30 at 9 34 59 AM" src="https://user-images.githubusercontent.com/88176060/127598597-db50878f-fabc-44ff-a885-7f21d8441f26.png">
        Given me any option to change alignment(position) of content which is display in documentation.

**Comment by RomanHotsiy** [comment]
What exactly is not proper? I can't understand from screenshot.

**Comment by sonalij18** [comment]
Hi,

    Actually I want to change the position of rightPanel content in which have some text 'Content Type' & application/json.Also, some other text position from template.Can you given me solution for these?

**Comment by RomanHotsiy** [comment]
This is not customizable.
