### ISSUE TITLE
NPM clean install issue

### ISSUE THREAD

**Issue by nielsuit227** [Redocly/redoc#1712]
**Describe the bug**
Installing Redoc broke our npm clean install for deployment. The latest version (2.0.0-rc.55) does not seem to satisfy redoc@*. 
I'm not sure whether this is the right place for this bug, please forward me if not. 

**Expected behavior**
npm ci to complete. 

**Additional context**
Happens on a git action (ubuntu-latest).
```
 npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Invalid: lock file's redoc@2.0.0-rc.55 does not satisfy redoc@*
npm ERR! 
```

**Comment by adamaltman** [comment]
node version? npm version?

**Comment by nielsuit227** [comment]
I don't think the problem has anything to do with my node or npm version. When I ran `npm install redoc`, it put `"redoc": "*" in my `package.json` and `"redoc": "2.0.0-rc.55"` in my package lock. Upon running `npm ci`, this crashed the build. 
Anyhow, node 15.4.0, npm 7.20.3.

**Comment by RomanHotsiy** [comment]
This doesn't look like something we can fix.

> cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

Looks like you did some changes in package.json and not synced it to package-lock.json or something.
