### ISSUE TITLE
Experimental Web Platform features flag on chrome breaks scroll

### ISSUE THREAD

**Issue by milewski** [Redocly/redoc#1714]
This is a problem that I had first noticed on the Chrome Beta version, the sidebar menu is completely unusable, you can not click and it will randomly expand/collapse all by itself etc... 

At the time I had switched back to the normal stable chrome version and it worked as normal, however today I updated chrome to Version: `92.0.4515.131 (Official Build) (x86_64) on MAC` and it seems the Beta code has been pushed to stable.. which now breaks the redoc UI completely...

**Comment by RomanHotsiy** [comment]
Ouch! That sounds really bad.

Unfortunately I can't reproduce it on my machine, I'm on the latest chrome too.

Google Chrome Version 92.0.4515.131 (Official Build) (x86_64) on Mac

I tried it on:

- our demo here: https://redocly.github.io/redoc/
- redoc-cli latest build
- latest commit npm start 

What version of Redoc are you using? May it be related to https://github.com/Redocly/redoc/blob/master/CHANGELOG.md#200-rc23-2020-02-09?

**Comment by pnc** [comment]
Oh, what fun! I hope it's not some Chrome experiment causing it.

I can reproduce it on the latest master with `npm start` and on the demo. To reproduce (here on Linux, anyway):

1. Open the link in Chrome.
2. Using a mousewheel, scroll down all the way through "pet."
3. Near the end of pet, you will scroll down as you were doing, but it will jump to the very top of the page.

I'll try on my Mac with mousewheel and with trackpad to see if things differ!

Let me know if the video from my previous comment isn't clear or won't play.

**Comment by pnc** [comment]
Okay, this is quite varied. I asked my co-workers to see.

**Bug is present (reproduces) on:**
1. Debian Buster, Chrome Version 92.0.4515.131 (Official Build) (64-bit)
2. Windows 10 Home, Version: 20H2, OS build: 19042.1110, Version 92.0.4515.131 (Official Build) (64-bit)
3. Fedora 34, Chrome 92.0.4515.131

**Bug does not reproduce on:**
macOS 10.15.7, Chrome 92.0.4515.131

@milewski What OS and browser did you see this on?

 @RomanHotsiy If you have access to a Linux or Windows machine, you can probably reproduce.

Alternatively, if you can explain the execution flow of `item.activate();` beyond the trivial `this.active = true` implementation, I can try to fix this properly. I assume there is an observer or something else reacting to this change, but I cannot figure out where it lives, and the mobx `action` implementation is too complex to step through meaningfully in the Chrome debugger.

**Comment by milewski** [comment]
I just did some testing with some coworkers here which are also on Mac, and I was the only one that was facing this issue, I figured out that my chrome somehow had this flag enabled:

![image](https://user-images.githubusercontent.com/2874967/129137966-9859908c-4f52-4cd5-ab3e-ad60b394e09a.png)

By disabling it everything backs to normal...

**Comment by RomanHotsiy** [comment]
@milewski that's a great find! I can reproduce it with this flag too!

I'll debug it later today! Will keep you posted.

**Comment by RomanHotsiy** [comment]
I was able to track it down to `scrollIntoViewIfNeeded` on the sidebar menu items.

Looks like this scrolls the whole page to the top vs scrolling just the sidebar scroll container. Applies both to native scroll and perfrect scrollbar.

This seems to me a like a Chrome bug tbh. Trying to figure out how to workarund that.
