### ISSUE TITLE
Webhooks option to reverse readOnly/writeOnly properties

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redoc#1720]
**Describe the problem to be solved**

In a webhook, the request is more equivalent to the response in the APIs. So, in order to reuse schemas, people will often need to use the response schema (but make a new version of it where they reverse the `readOnly` and `writeOnly` property values, such as from true to false or the other way around).

**Describe the solution you'd like**

I would like a configuration option:

```
reverseWebhookReadOnlyProps: true
reverseWebhookWriteOnlyProps: true
```

(This issue is open to better naming suggestions, as I think callbacks are impacted by this as well.)

**Describe alternatives you've considered**

None

**Additional context**

https://api-reference.rebilly.com/tag/Customers/#operation/customer-created (in this sample you can see it is missing the readOnly properties from the webhook "request" like `createdTime` and `id` inside of the `_embedded.customer`.

**Comment by zzip** [comment]
This is related to #1540 and would be a possible solution.
