### ISSUE TITLE
OpenAPI 2.0 support gone in redoc-cli

### ISSUE THREAD

**Issue by tomascohen** [Redocly/redoc#1724]
Running the latest `redoc-cli` or the latest `redocly/redoc` Docker image to serve a 2.0 spec returns

`Error: Unsupported OpenAPI Version: 2`

or

```
Uncaught (in promise) Error: Unsupported OpenAPI Version: 2
    at Object.t.detectOpenAPI (oas-types.js:31)
```

respectively.

This can be considered a _feature_. But it would be nice to properly document the way/version to properly render 2.0 specs.

**Comment by RomanHotsiy** [comment]
@tomascohen can you share a snippet of your definition? Does it define `swagger: 2.0`?

**Comment by tomascohen** [comment]
> @tomascohen can you share a snippet of your definition? Does it define `swagger: "2.0"`?

Sure, look [here](https://git.koha-community.org/Koha-community/Koha/src/branch/master/api/v1/swagger/swagger.yaml).

**Comment by RomanHotsiy** [comment]
It is invalid, the top-level `swagger` field must be a string with a value `"2.0"`, you have a number here `2.0` which is parsed as integer `2` (this are quirks of yaml format).

![image](https://user-images.githubusercontent.com/3975738/129043588-6628a032-782b-4c92-915e-c58424945b05.png)
