### ISSUE TITLE
Showing the version of the OpenAPI specification

### ISSUE THREAD

**Issue by jfougere** [Redocly/redoc#1725]
What would you think about adding a visual indication of the version of the OpenAPI specification ? 

Below is an example of this in swagger-ui where both the version of the spec and the version of the api are shown as "tags":
<img width="811" alt="Capture d’écran 2021-08-12 à 15 20 52" src="https://user-images.githubusercontent.com/6061575/129154848-b17bd1fd-8675-43ca-8d57-e561e95c0e84.png">

**Comment by adamaltman** [comment]
The version is only relevant if you use the raw OpenAPI definition. It may only be relevant therefore on or around the "download" button.

**Comment by RomanHotsiy** [comment]
I wander what is a use-case for that? For me it seems this information is not valuable for API consumer.
