### ISSUE TITLE
posibility of a 2.0.0 release with updated marked

### ISSUE THREAD

**Issue by evansrobert** [Redocly/redoc#1726]
Hi, @RomanHotsiy,
### Issue Description

   I noticed that a vulnerability is introduced in **_redoc@2.0.0-rc.45_**:
     Vulnerability **SNYK-JS-MARKED-584281** affects package **_marked_** (versions:<1.1.1):  [https://snyk.io/vuln/SNYK-JS-MARKED-584281](https://snyk.io/vuln/SNYK-JS-MARKED-584281)
  The above vulnerable package is referenced by **_redoc@2.0.0-rc.45_** via:
`redoc@2.0.0-rc.45 ➔ marked@0.7.0`

Since **_redoc@2.0.0-rc.45_** ([13,275 downloads per week](https://www.npmjs.com/package/redoc/v/2.0.0-rc.45?activeTab=versions)) is referenced by **101** downstream projects (e.g.,redoc-cli 0.12.2, @adobe/parliament-ui-components 4.6.2, docusaurus-theme-redoc 0.4.4, redocusaurus 0.4.4, gh-openapi-docs-ts 0.3.6), the vulnerability [**SNYK-JS-MARKED-584281**](https://snyk.io/vuln/SNYK-JS-MARKED-584281) can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
 (1)`@ga4gh/gh-openapi-docs@0.2.2-rc3 ➔ redoc-cli@0.9.13 ➔ redoc@2.0.0-rc.45 ➔ marked@0.7.0`
(2)`@abios/abios-redoc-cli@0.13.2 ➔ redoc@2.0.0-rc.45 ➔ marked@0.7.0`
  **......**

If **_redoc@2.0.0-rc.45_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from redoc@2.0.0-rc.45 ?**

### Fixing suggestions

In **_redoc@2.0.0_**, maybe you can kindly try to perform the following upgrade :
`marked ^0.7.0 ➔ ^1.1.1`; 

**Note:**
_**marked@1.1.1**(>=1.1.1) has fixed the vulnerability [**SNYK-JS-MARKED-584281**](https://snyk.io/vuln/SNYK-JS-MARKED-584281)._

Thank you for your attention to this issue and welcome to share other ways to resolve the issue.^_^

**Comment by RomanHotsiy** [comment]
Great suggestion! 

Maybe there is a point to migrate to remark ecosystem at all.

**Comment by RomanHotsiy** [comment]
We're also considering markdown-it.

We can try to upgrade marked to the latest version in meantime.

cc @Oprysk
