### ISSUE TITLE
Adding discriminator causes spurious "recursive" notice in another schema

### ISSUE THREAD

**Issue by dpkirchner** [Redocly/redoc#1735]
**Describe the bug**
When adding a discriminator to one schema, the generated HTML indicates another schema is "recursive", despite no connection between the two schemas.

**Expected behavior**
I expected the two independent schemas to be rendered entirely.

**Minimal reproducible OpenAPI snippet(if possible)**

Here's the openapi.yaml and the file refs:

https://gist.github.com/dpkirchner/3e41497358e9890b70af42d704b7ec9e

**Screenshots**
![Screen Shot 2021-08-27 at 10 19 13 AM](https://user-images.githubusercontent.com/165134/131165231-09d4cd10-f725-471d-bbb5-f419c3f61887.png)

**Additional context**

`User` is not marked recursive if you remove the `discriminator` object from `item.yaml`.

redoc-cli: 0.12.3
redoc: 2.0.0-rc.56

Command line: `redoc-cli bundle -o web/index.html ./openapi.yaml`

A similar bug was closed in 2019: https://github.com/Redocly/redoc/issues/695

**Comment by petersamokhin** [comment]
The same issue, with the complicated structure of files and a discriminator used somewhere ruins the whole schema models.
