### ISSUE TITLE
npm ci in redoc hangs indefinitely during reify steps

### ISSUE THREAD

**Issue by dpkirchner** [Redocly/redoc#1736]
**Describe the bug**
Cloning the redoc repo and running `npm install` or `npm ci` hangs indefinitely, consumes 100% of a core.

**Expected behavior**
I expected to be able to install redoc from source so I could tinker with it.

**Additional context**
node v16.7.0
npm 7.21.1
redoc master branch 683eabbbf077a4275e9986dcb6492f237f83b476
Files copied in to a node:latest docker container, not running over a bind mount

`npm ci --timing` last few lines before it hang indefinitely (at least an hour):

```
npm timing reifyNode:node_modules/date-fns Completed in 22268ms
npm timing reifyNode:node_modules/lodash Completed in 22438ms
npm timing reifyNode:node_modules/prettier Completed in 22642ms
npm timing reifyNode:node_modules/core-js Completed in 23290ms
npm timing reifyNode:node_modules/typescript Completed in 25104ms
npm timing reifyNode:node_modules/rxjs Completed in 25146ms
[##################] - reify:rxjs: timing reifyNode:node_modules/rxjs Completed in 25146ms
```

The `npm install` child of `npm ci` that is hanging is in [`workerize-loader`](https://github.com/redocly/workerize-loader/tree/webpack-5-dist). (Found that in the container by running `top`, then looking at the processes's cwd (cat `/proc/$pid/cwd/package.json`))

The repro is simple: clone redoc, run `docker run -it -v $(pwd):/buildtmp --entrypoint bash node` then in the shell `cp -rp /buildtmp /build` (to ensure you're not building over a bind mount) and `cd /build && npm ci --timing`.

**Comment by AlexVarchuk** [comment]
I cannot it reproduce again. Seems it was fixed, if not please reopen this issue.
