### ISSUE TITLE
redoc-cli bundle to include local src/theme.ts changes

### ISSUE THREAD

**Issue by rishagit** [Redocly/redoc#1738]
**Describe the problem to be solved**
redoc-cli bundle [spec] to include changes done in the src/theme.ts file. I have made some changes in the src/theme.ts file which modifies the look and feel of my landing page. But i need to deploy it in github pages and am preparing a static html for it. But the cli bundle command is using the default formatting that comes out of the box. 

**Describe the solution you'd like**
there should be a command which can be used to use redoc cli bundle feature but not to use default formatting 

**Describe alternatives you've considered**
so far using the default formatting

**Additional context**
if you would like to see my updated theme.ts file - https://github.com/rishagit/cid-oas/blob/main/src/theme.ts

**Comment by adamaltman** [comment]
Related Idea: support using a .redocly.yaml file for redoc cli bundle.

**Comment by RomanHotsiy** [comment]
@rishagit you forked redoc and new theme doesn't work in the cli. That's because cli uses redoc from npm, not the forked version you have.

You can provide theme in options, see example here: https://github.com/Redocly/redoc/issues/754#issue-392494259
