### ISSUE TITLE
ERROR in ./node_modules/redoc/bundles/redoc.lib.js

### ISSUE THREAD

**Issue by GDownAdviseInc** [Redocly/redoc#1741]
**Describe the bug**
I have followed the instructions in [here](https://redoc.ly/docs/redoc/quickstart/react/) to try and get redoc working in my React app. In addition to step 1, I also ran `npm i redoc`. My `package.json` dependencies are:

```json
"devDependencies": {
    "@babel/core": "^7.14.6",
    "@babel/plugin-transform-runtime": "^7.14.5",
    "@babel/preset-env": "^7.14.7",
    "@babel/preset-react": "^7.14.5",
    "babel-loader": "^8.2.2",
    "eslint": "^7.31.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "prettier": "^2.3.2",
    "webpack": "^4.46.0",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.1.0"
  },
  "dependencies": {
    "@babel/runtime": "^7.14.8",
    "@reduxjs/toolkit": "^1.6.1",
    "axios": "^0.21.1",
    "core-js": "^3.17.2",
    "mobx": "^6.3.3",
    "prop-types": "^15.7.2",
    "query-string": "^7.0.1",
    "react": "^17.0.2",
    "react-alert": "^7.0.3",
    "react-alert-template-basic": "^1.0.2",
    "react-bootstrap": "^1.6.1",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.4",
    "react-router-dom": "^5.2.0",
    "react-spinners": "^0.11.0",
    "react-transition-group": "^4.4.2",
    "redoc": "^2.0.0-rc.56",
    "redux": "^4.1.0",
    "redux-devtools-extension": "^2.13.9",
    "redux-thunk": "^2.3.0",
    "styled-components": "^5.3.1"
  }
```

I haven't yet added the component itself, but simply included the `import { RedocStandalone } from 'redoc';` at the top of the appropriate file.

Originally I was trying to build it using webpack 5 but was getting a huge number of errors about missing packages, and discovered issue #1584 which talked about ways around it. They didn't work for me, so I decided to try webpack 4 as above.

However, now, when I try to run in development (`webpack --mode development --watch`) or build (`webpack --mode production`), I get the same error appearing:

```
ERROR in ./node_modules/redoc/bundles/redoc.lib.js
Module not found: Error: Can't resolve 'fs' in '/path/to/my/app/node_modules/redoc/bundles'
 @ ./node_modules/redoc/bundles/redoc.lib.js 2:121105-121118
 @ ./app/frontend/src/features/documentation/ApiDocumentation.js
 @ ./app/frontend/src/components/App.js
 @ ./app/frontend/src/index.js
 @ multi ./app/frontend/src/index.js
```

**Expected behavior**
Not to receive the error message, and the documentation to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/58338166/132107934-a5aff105-64c3-4310-8879-7aa547e52fc5.png)

**Additional context**
I am relatively inexperienced with React/webpack and this is my first time attempting to use redocs, so I may be doing/missing something basic, but any help you can provide to resolve this would be gratefully received. Google has not been able to help me this time 😞

**Comment by AlexVarchuk** [comment]
@GDownAdviseInc Try to add to your webpack 4 config:
`
node: {
    fs: "empty"
  }
  `

**Comment by GDownAdviseInc** [comment]
Thanks that's now not giving me the error any more 🎉
