### ISSUE TITLE
Definitions vs Components

### ISSUE THREAD

**Issue by osamaramihafez** [Redocly/redoc#1744]
It seems that there is some confusing definitions and components. In parts of the file we can reference using the term "definition", but in other parts, we can't. For example, inside of the tags section, we can't use #/definitions/ModelA. Instead, I get an error `Invalid reference token: definitions`. I have to use #/components/schemas/ModelA to refrence ModelA. This doesn't make sense because I haven't defined any components. However, if I want to reference another definition within the definition of ModelA, I should use #/definitions/ModelB. This doesn't make any intuitive sense to me, so I'm wondering if anyone else has experienced the same issue or if this is a bug that needs to be resolved.

I would have expected a reference error of some sort to be raised since components/schemas is not defined.

```
"definitions": {
        "ModelA": {
                    "title": "ModelA",
                    "type": "object",
                    "properties": {
                        "links": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ModelB"
                            }
                        }
                    },
                    "tags": [
                        "Models"
                    ]
                },
        },
"tags": [
        {
                "name": "modelName",
                "x-display": "modeDisplayName",
                "description": "<SchemaDefinition schemaRef=\"#/components/schemas/ModelA\" />\n"
        }
],
"x-tagGroups": [
        {
            "name": "Models",
            "tags": [
                "Models"
            ]
        }
]
```
Note: Assume ModelB is defined in definitions.

**Comment by adamaltman** [comment]
What version of OpenAPI are you using?

**Comment by osamaramihafez** [comment]
> What version of the OpenAPI specification are you using to describe your API? Possible answers include: 2.0, 3.0, 3.1

Currently 2.0

**Comment by lornajane** [comment]
I'm closing this inactive issue, I don't see any further work needed.
