### ISSUE TITLE
How can I generate code sample using redoc-cli

### ISSUE THREAD

**Issue by zcz3313** [Redocly/redoc#1746]
**Describe the problem to be solved**
How can I generate code sample using redoc-cli?
With which option?
I have seen 'x-code-samples' in README, but I still didn't know how to do it, can you give me an example, thx.

**Comment by skadinna** [comment]
For Redoc to show your code samples in the API documentation, you must add them first to your OpenAPI definition. This is done with the `x-codeSamples` specification extension. You can find a basic example here: https://redoc.ly/docs/api-reference-docs/specification-extensions/x-code-samples/

Note that Redoc can't automatically generate code samples from your API definition. It only shows the code samples you've manually inserted into your OpenAPI definition. Auto-generated code samples are supported [in Reference docs, our premium product](https://redoc.ly/docs/api-reference-docs/guides/generate-code-samples/).

Hope this helps! If you still can't get it to work, please share your OpenAPI definition here (or at least share the relevant section(s) where you're trying to insert code samples).

**Comment by zcz3313** [comment]
> You can find a basic example here: https://redoc.ly/docs/api-reference-docs/specification-extensions/x-code-samples/

this example really helps me！thank you！

> Auto-generated code samples are supported [in Reference docs, our premium product](https://redoc.ly/docs/api-reference-docs/guides/generate-code-samples/).

Yeah, I used it a few hours ago for trial which is really a nice solution.
