### ISSUE TITLE
Export Redoc CLI functionality

### ISSUE THREAD

**Issue by atzawada** [Redocly/redoc#1755]
**Describe the problem to be solved**
As a developer, I would like to create node scripts for my CI pipeline that automate Redoc functions across multiple OpenAPI specs.

**Describe the solution you'd like**
The action functions (`bundle`, `lint`, etc) and associated input interfaces could be exported for developers to use when developing scripts

**Comment by AlexVarchuk** [comment]
@atzawada Hi! You can try to use [openapi-cli](https://github.com/Redocly/openapi-cli) for it.

**Comment by MarcLevisse** [comment]
I'm currently using openapi-cli to lint and bundle OpenAPI specs within a Jenkins CI job (multibranch pipeline)
It's working like a charm ! ;)

**Comment by RomanHotsiy** [comment]
I believe it can be closed.
