### ISSUE TITLE
Response samples: example dropdown is not scrollable

### ISSUE THREAD

**Issue by dvemnt** [Redocly/redoc#1756]
**Describe the bug**
Example dropdown in response samples block is not scrollable.

**Expected behavior**
Expected to see all examples with scroll.

**Minimal reproducible OpenAPI snippet(if possible)**
```
openapi: "3.0.3"

paths:
  /sample:
    post:
      summary: Sample API

      responses:
        400:
          description: Client error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
              examples:
                "#1":
                  value:
                    code: 1
                "#2":
                  value:
                    code: 2
                "#3":
                  value:
                    code: 3
                "#4":
                  value:
                    code: 4
                "#5":
                  value:
                    code: 5
                "#6":
                  value:
                    code: 6
```

**Screenshots**
![samples](https://user-images.githubusercontent.com/4338636/134485256-a666f231-7538-4cac-85f9-5bf73b9f4a4f.png)

**Additional context**
Version: 2.0.0-rc.53 (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js)

**Comment by AlexVarchuk** [comment]
@dvemnt  Thank. We will fix it

**Comment by AlexVarchuk** [comment]
@dvemnt Hi, please provide additional context for reproducing e.g. browser version, OS

**Comment by dvemnt** [comment]
@AlexVarchuk, Hi, one of latest Chrome version on Ubuntu 20.04.3 LTS.

**Comment by whitelka** [comment]
Hi, there's the same bug in the body. Does this patch cover this area, too?
![test](https://user-images.githubusercontent.com/4556873/143847546-a91520c3-9ba5-44bd-b691-742659bf01ca.png)
@AlexVarchuk

**Comment by AlexVarchuk** [comment]
@whitelka Hi. Yes. We want to make performance tests deeply. We need more time for it.
