### ISSUE TITLE
Yarn 2 - Installation problems

### ISSUE THREAD

**Issue by GitProdEnv** [Redocly/redoc#1759]
I have issues to install `redoc-cli` on `Yarn 2`.

When I do `yarn add redoc-cli` , it outputs

➤ YN0060: │ redoc-cli@npm:0.12.3 provides mobx (p25635) with version 6.3.3, which doesn't satisfy what redoc and some of its descendants request

➤ YN0060: │ redoc-cli@npm:0.12.3 provides react (p9025a) with version 17.0.2, which doesn't satisfy what redoc and some of its descendants request

➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
`

Executing `redoc-cli serve --watch false openapi.yaml` results in an Error of:

```
Error: redoc tried to access call-me-maybe, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: call-me-maybe
Required by: redoc@virtual:d0bab8c0c448047c9694be72fc6f301dee6e4dbe8880fe2285d5c7da4748e98ee9b6dde65c53cdf5476a0a1935c1cea99556e76508e75f67d2e77e3912051398#npm:2.0.0-rc.56 (via {CWD}.yarn/__virtual__/redoc-virtual-20ef193cc3/0/cache/redoc-npm-2.0.0-rc.56-2814d04679-dd04f7b4c3.zip/node_modules/redoc/bundles/)
```

I tried it with Yarn 2's package extensions, but it didn't help:

```
packageExtensions:
  "redoc@*":
    dependencies:
      core-js: "*"    
      react: "*"
      react-dom: "*"
      mobx: "5.15.4"
```

**Expected behavior**
It should work with Yarn 2 as it does with NPM.

**Additional Information**
I use Yarn 2 with PNP.

**Comment by adamaltman** [comment]
Can you also share your node version and exact yarn version?

**Comment by GitProdEnv** [comment]
I created two new simple projects with:

1. Project
  - node version: v12.14.1
  - yarn version (PNP): 3.0.2 (berry)
2. Project
  - node version: v15.11.0
  - yarn version (PNP): 3.0.2 (berry)
 
The error is now:

```
/tmp/test/.pnp.cjs:13096
    throw firstError;
    ^

Error: styled-components tried to access react-is (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: react-is
Required by: styled-components@virtual:d0bab8c0c448047c9694be72fc6f301dee6e4dbe8880fe2285d5c7da4748e98ee9b6dde65c53cdf5476a0a1935c1cea99556e76508e75f67d2e77e3912051398#npm:5.3.1 (via /tmp/test/.yarn/__virtual__/styled-components-virtual-e191a62e30/0/cache/styled-components-npm-5.3.1-6cb43fe52b-2d833d573c.zip/node_modules/styled-components/dist/)
```

If I run `yarn add -D react-is` and call `yarn redoc-cli serve --watch false openapi.yaml` again it will return 
```
Error: redoc tried to access call-me-maybe, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: call-me-maybe
```
and so on...

```
/tmp/test/.pnp.cjs:13107
    throw firstError;
    ^

Error: redoc tried to access yaml, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: yaml
Required by: redoc@virtual:d0bab8c0c448047c9694be72fc6f301dee6e4dbe8880fe2285d5c7da4748e98ee9b6dde65c53cdf5476a0a1935c1cea99556e76508e75f67d2e77e3912051398#npm:2.0.0-rc.56 (via /tmp/test/.yarn/__virtual__/redoc-virtual-20ef193cc3/0/cache/redoc-npm-2.0.0-rc.56-2814d04679-dd04f7b4c3.zip/node_modules/redoc/bundles/)
```

**Comment by GitProdEnv** [comment]
I post this, if somebody has the same issue:

Adding this to .yarnrc.yml 

```yml
# .yarnrc.yml
packageExtensions:
  styled-components@*:
    dependencies:
      react-is: "*"
  redoc@*:
    dependencies:
      call-me-maybe: "*"
      yaml: "*"
      fast-safe-stringify: "*"
```

and `yarn install` again fixed my issue.
