### ISSUE TITLE
Response display differs between direct writing and reference

### ISSUE THREAD

**Issue by takumi-ricoh** [Redocly/redoc#1760]
**Describe the bug**
If you write it directly, the type will be displayed, but if you refer to it, the name will be displayed.

**Expected behavior**
redoc shows the same

**Screenshots**
**schema**
![image](https://user-images.githubusercontent.com/32160810/135606932-501ecdda-2769-401d-98be-ffdb830dc3df.png)

**result**
Only the directly written "string" is displayed by type
![image](https://user-images.githubusercontent.com/32160810/135606981-2a5d9c76-1c83-4bdf-86a7-231f8026ee95.png)

**Additional context**
OpenAPI v3.1
redoc-cli v0.12.3

**Comment by adamaltman** [comment]
This is the expected behavior.

You can control it with the title property.

![image](https://user-images.githubusercontent.com/1161871/136130740-1b620e99-e339-4415-bdd2-82438370a0fd.png)

**Comment by RomanHotsiy** [comment]
You can disable it by using `hideSchemaTitles`.
