### ISSUE TITLE
OpenAPI 3.1: $ref as sibling to required not working

### ISSUE THREAD

**Issue by madsodgaard** [Redocly/redoc#1773]
**Describe the bug**
#1766 fixed the issue where `description` was not correctly overriden, when it was a sibling to `$ref`. However, it still does not work for `required`.

Also, it looks like the field is completely missing from the schema overview? (see screenshot)

**Expected behavior**
I expect the property `field` in the response to be required.

**Minimal reproducible OpenAPI snippet(if possible)**
```yaml
openapi: 3.1.0
info:
  version: 1.0.0
  title: Example.com
paths:
  "/test":
    get:
      operationId: test
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
components:
  schemas:
    Response:
      $ref: "#/components/schemas/Test"
      required:
        - field
    Test:
      type: object
      properties:
        field:
          type: string
          description: test
```

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/1474121/136970770-fdb3080d-6b04-43bd-9961-b40555a4fa91.png">

**Additional context**
Tested with `openapi-cli v1.0.0-beta.63`

**Comment by AlexVarchuk** [comment]
@madsodgaard fixed. If you reproduce it again please reopen the issue.
