### ISSUE TITLE
x-enumDescriptions not working in CE

### ISSUE THREAD

**Issue by dstockhammer** [Redocly/redoc#1777]
This is maybe more of a question than a bug report: the `x-enumDescriptions` (as documented [here](https://redoc.ly/docs/api-reference-docs/specification-extensions/x-enum-descriptions/)) seems currently not to work when generating docs using `redoc-cli`. Is this extension only supported in the hosted/paid versions of redocly or is this a bug?

Cheers!

**Comment by skadinna** [comment]
The [documentation for this specification extension](https://redoc.ly/docs/api-reference-docs/specification-extensions/x-enum-descriptions/) now indicates that it's not supported for Redoc at the top of the page. We'll update the documentation again when this changes.
