### ISSUE TITLE
Whoever picks that up at Redocly. Keep in mind that at AsyncAPI Initiative we maintain a react component for that, and also make sure it is usable in other frameworks. Most important is that we want custom styling to be a core feature. So do not try to write everything on your own (AsyncAPI is more complex than OpenAPI) but rather join us in development and maintenance 🚀

### ISSUE THREAD

**Issue by dgs2019** [Redocly/redoc#1778]
Whoever picks that up at Redocly. Keep in mind that at AsyncAPI Initiative we maintain a react component for that, and also make sure it is usable in other frameworks. Most important is that we want custom styling to be a core feature. So do not try to write everything on your own (AsyncAPI is more complex than OpenAPI) but rather join us in development and maintenance 🚀 

Even if you decide you want to do it on your own, feel free to talk to us and consult so we can share our experience and make your life's easier 😄

_Originally posted by @derberg in https://github.com/Redocly/redoc/issues/1219#issuecomment-948378630_

**Comment by RomanHotsiy** [comment]
Thanks @dgs2019. We'll take it into account!
