### ISSUE TITLE
Support .redocly.yaml for options for redoc-cli

### ISSUE THREAD

**Issue by adeschamps** [Redocly/redoc#1785]
Hello,

When I preview docs with `openapi preview-docs`, it uses the theme defined in my `.redocly.yaml` file. Is there a way to render a static HTML file, much like `redoc-cli bundle`, that reads the theme from that file?

**Comment by federinik** [comment]
Same issue here, is there any plan to support `.redocly.yaml` file as input for `redoc-cli` anytime soon?

**Comment by RomanHotsiy** [comment]
Yes. We plan to add support.
