### ISSUE TITLE
Default value ignored on referenced objects

### ISSUE THREAD

**Issue by Herrick19** [Redocly/redoc#1788]
Hi,

When an object as a default value overridden, it doesn't show in the doc.

Here a small snippet to show the problem:
- Test is defined inline (Ok: default is shown in doc)
- Test2 is defined as a reference and the object has the default value inline (Ok: default is shown in doc)
- Test3 is defined as a reference and the object HAS NO default value, but the default value is documented in the referring object (NOT OK: default value NOT shown in doc)

```
description: A test Object
type: object
properties:
    test:
        type: integer
        default: 0
    test2:
        $ref: '#/components/schemas/test2'
    test3:
        $ref: '#/components/schemas/test3'
        default: false
```

Thanks in advance

**Comment by AlexVarchuk** [comment]
Thanks for the request. We have some problems with siblings in the `openapi: 3.1` version. We will fix it in nearest future.

**Comment by AlexVarchuk** [comment]
@Herrick19 I reproduced it on openAPI version 3.0. I think it is expected [behavior](https://spec.openapis.org/oas/v3.0.0#fixed-fields-18). Please check your definition version.

Maybe I miss something. If it is reproducing, please, reopen the issue. Thanks.
