### ISSUE TITLE
Maximum call stack size exceeded with self referencing schemas

### ISSUE THREAD

**Issue by SebastianStehle** [Redocly/redoc#1792]
**Describe the bug**
I have the following schema:

```
components:
    SelfComponentDto:
      type: object
      additionalProperties: false
      properties:
        self:
          type: object
          discriminator:
            propertyName: schemaId
            mapping:
              self: '#/components/schemas/SelfComponentDto'
          description: self
          nullable: true
          required:
            - schemaId
          properties:
            schemaId:
              type: string
              nullable: false
          oneOf:
            - $ref: '#/components/schemas/SelfComponentDto'
```

When I open a file with such a structure in Redoc I get the following exception:

`Maximum call stack size exceeded`

**Expected behavior**
Should just work of course.

**Minimal reproducible OpenAPI snippet(if possible)**
The full example can be found here: https://gist.github.com/SebastianStehle/120493bea981f95228484cb3b8d906b8

It is created by a tool, but I tried to be as minimalistic as possible.

**Additional context**
Used version: RC.57

**Comment by ezk84** [comment]
We are having this issue as well on a similarly recursive schema. SwaggerUI renders the schema correctly

```
ReDoc Version: 2.0.0-rc.63
Commit: b474d67
```
