### ISSUE TITLE
Add link below the Documentation Powered by ReDoc

### ISSUE THREAD

**Issue by gemitsio** [Redocly/redoc#1798]
Hello All,

 i have install the redoc to include/desribe/display my api infrastructure.

I have 2 redoc pages and i want to add below the Documentation Powered by ReDoc a link, but will be different for every page and will have different targets.

Which file should edit to do this pls?

**Comment by RomanHotsiy** [comment]
https://github.com/Redocly/redoc/blob/master/src/components/SideMenu/SideMenu.tsx#L27-L31
