### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by gemitsio** [Redocly/redoc#1804]
Hello,

is there any option to add favicon icon ? If yes, let me know which file should i edit.

Thanks in advance.

**Comment by AlexVarchuk** [comment]
@gemitsio Hi! you can use the HTML template with [standalone](https://github.com/Redocly/redoc#deployment) for it.

**Comment by RomanHotsiy** [comment]
You can use `--template path-to-tempalte.html` with redoc-cli too.

**Comment by RomanHotsiy** [comment]
Here is a default template: https://github.com/Redocly/redoc/blob/master/cli/template.hbs
