### ISSUE TITLE
Not able to embed markdown files in yaml 

### ISSUE THREAD

**Issue by testrest3** [Redocly/redoc#1807]
**Describe the bug**
Followed the instructions in the reference portal [1] to embed a description from the markdown file within a yaml file [2]. However, I am faced with the following error in the console [3]. Any idea on what I am doing wrong? 

[1] https://redoc.ly/docs/api-reference-docs/guides/embedded-markdown/

[2] -->
![try](https://user-images.githubusercontent.com/95199461/143856595-dbfe0fef-cfbe-4230-9558-bda9cdc1ab16.PNG)

[3] --> 
![error](https://user-images.githubusercontent.com/95199461/143855626-372ccc1e-5117-47d9-92c7-dfce243af2d1.PNG)

**Comment by AlexVarchuk** [comment]
@testrest3 Hi. I think the problem with your definition. Try to use only $ref or markdown text in the description.

You can validate your definition using [openapi-cli](https://www.npmjs.com/package/@redocly/openapi-cli), or write us to Redocly support chat. Thanks.
```
npx @redocly/openapi-cli lint path-to-root-file.yaml
```

**Comment by testrest3** [comment]
The official documentation gives a sample with the $ref and markdown text together, and that is the only sample available AFAIK. Also, this definition did work a few days ago.  

![embed](https://user-images.githubusercontent.com/95199461/143994694-bf227800-be1f-4700-ad80-f2661cb89a5c.PNG)

Not sure if something has changed since then. Either way, could you please let me know the correct definition to embed a markdown file with a description in a yaml file in redocly?

**Comment by RomanHotsiy** [comment]
@testrest3 your definition is invalid YAML. The example you shared and the one from our docs are different.

![image](https://user-images.githubusercontent.com/3975738/143995632-08444bfb-eb92-48c3-8d77-737de0968092.png)

Please contact team@redocly.com for support.

The issue you face is not related to the Redoc project.
