### ISSUE TITLE
oneOf Discriminator shows also implicit mappings when references are defined in a custom section

### ISSUE THREAD

**Issue by digEmAll** [Redocly/redoc#1815]
**Describe the bug**

When you define a `discriminator` for a `oneOf` with explicit mappings to references defined in a custom section, the discriminator dropdown shows implicit mappings as well.
 - the problem seems to be introduced in version `2.0.0rc.57`, previous version `2.0.0rc.50` works fine.
 - only `oneOf` seems affected, while `anyOf` works correctly

**Expected behavior**

Only the explicit mappings should appear

**Minimal reproducible OpenAPI snippet(if possible)**

```yml
openapi: "3.0.2"
info:
  title: My Title
  version: "1.0"
  description: my descr
servers:
  - url: https://api.server.test/v1
paths:
  /myapiname:
    post:
      summary: my summary
      description: my descr
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Record"
      responses:
        "200":
          description: OK
components:
  schemas:
    Record:
      type: object
      discriminator:
        propertyName: TYPE
        mapping:
          FOO: "#/x-baseschemas-container/schemas/FOOMDL"
          BAR: "#/x-baseschemas-container/schemas/BARMDL"
      oneOf:
        - $ref: "#/x-baseschemas-container/schemas/FOOMDL"
        - $ref: "#/x-baseschemas-container/schemas/BARMDL"
x-baseschemas-container:
  schemas:
    FOOMDL:
      type: object
      properties:
        TYPE:
          type: string
        FOOID:
          type: string
    BARMDL:
      type: object
      properties:
        TYPE:
          type: string
        BARID:
          type: string
```
**Screenshots**
![image](https://user-images.githubusercontent.com/13941545/144438851-2632d1af-8aa0-4327-99e0-a53f0e1e6590.png)

**Comment by AlexVarchuk** [comment]
Sorry for the long delay of it. This behavior is correct.
For showing only explicit mapping use `x-explicitMappingOnly: true`. Details you can find in `x-explicitMappingOnly` [documentation ](https://github.com/Redocly/redoc/blob/main/docs/redoc-vendor-extensions.md#x-explicitMappingOnly)
