### ISSUE TITLE
Redoc fails to fetch OAS file

### ISSUE THREAD

**Issue by etsyachristensen** [Redocly/redoc#1831]
**Describe the bug**
We've had this intermittent issue with ReDoc and our documentation. We have a generated JSON file for our OpenAPI. The URL to that file never changes. But we have developers complaining that on occasion when they go to open the ReDoc portion of our documentation site (https://developers.etsy.com/documentation/reference) it throws an error like the one in the screenshot below.

**Expected behavior**
I would expect that this wouldn't happen at all unless for some reason we changed the path to the file and forgot to update something.

**Minimal reproducible OpenAPI snippet(if possible)**
I can't reliably reproduce this. Most often, people just have to do a hard refresh and reload the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/83842847/145842804-de23b400-be4e-4fa5-8fd4-5842a98a6406.png)

**Comment by AlexVarchuk** [comment]
@etsyachristensen Hi! Thanks for the request. I can't reproduce it now. I'll try to investigate it.
If you can give more information it really helps us(OS, browser, logs, etc).
