### ISSUE TITLE
[{ 	"resource": "/c:/Inextlabsadmin/iNextPortalDocs/node_modules/@redocly/openapi-core/tsconfig.json", 	"owner": "typescript", 	"severity": 8, 	"message": "Cannot read file 'c:/Inextlabsadmin/iNextPortalDocs/node_modules/tsconfig.json'.", 	"source": "ts", 	"startLineNumber": 1, 	"startColumn": 1, 	"endLineNumber": 1, 	"endColumn": 2 }]

### ISSUE THREAD

**Issue by dev348** [Redocly/redoc#1833]
**Describe the bug**
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "lib"
  },
  "exclude": ["**/__tests__", "lib"]
}

**Expected behavior**

**Minimal reproducible OpenAPI snippet(if possible)**

**Screenshots**
![Screenshot 2021-12-14 170148](https://user-images.githubusercontent.com/47909485/145990463-ee54543d-7d56-4068-b861-4527d0a1a313.png)

**Additional context**

**Comment by AlexVarchuk** [comment]
@dev348 Hi! The problem can be in permissions access in your file system. Please try to remove your `node_modules` folder and reinstall your dependency again. If it reproduces again feel free to reopen this issue and attach additional data (npm version,  ts version, etc.)
