### ISSUE TITLE
Q: What is the license of the HTML file generated with 'redoc-cli' tool?

### ISSUE THREAD

**Issue by jonnydee** [Redocly/redoc#1835]
I couldn't find any explicit information about that matter. Can someone tell which license the generated HTML file will have? Or even better, can someone point me to corresponding information (if any) so I can link to it? (We'd like to ship such a generated HTML file together with our OpenAPI Spec but we need to make sure the license of the generated code does not pose any problems here...)

Thanks in advance.

**Comment by RomanHotsiy** [comment]
> In general, the license of the software used to create a file doesn't have any influence on the possible licenses you can distribute that file under.
> 
> For example, if you use Microsoft Word to write a document, or gcc to compile a program, then the license of Word/gcc doesn't affect the license you can use for the document/program.
>
> The reason that the license of a program usually doesn't affect the license of the output is because the output normally doesn't contain anything that can be seen as a copy of part of the program that created the output.

https://opensource.stackexchange.com/a/5483

**Comment by jonnydee** [comment]
@RomanHotsiy I think the Stack Exchange answer isn't appropriate for the ReDoc case:

> The reason that the license of a program usually doesn't affect the license of the output is because the output normally doesn't contain anything that can be seen as a copy of part of the program that created the output.

Because the output does contain JavaScript code within the generated HTML page which may be seen as a copy of (part of) the program that created the output.

Anyway, good to know this is not the case. Thank you!

**Comment by RomanHotsiy** [comment]
> the output does contain JavaScript code within the generated HTML page

Yeah, 100%. But the JavaScript code is licensed under MIT: https://github.com/Redocly/redoc/blob/master/LICENSE
