### ISSUE TITLE
Add support of mermaid diagrams

### ISSUE THREAD

**Issue by iShift** [Redocly/redoc#1847]
**Describe the problem to be solved**
Support of the diagrams in the markdown

**Describe the solution you'd like**
Add support of the mermaid

**Comment by adamaltman** [comment]
@iShift Mermaid is very heavy. We have it supported in our premium developer portal product, but I don't think it will be a good addition here because of the vast amount of dependencies required to support it.

**Comment by AlexVarchuk** [comment]
duplicate https://github.com/Redocly/redoc/issues/1459
