### ISSUE TITLE
Styling arrow circle at the bottom right of the screen

### ISSUE THREAD

**Issue by clarencedesmarais** [Redocly/redoc#1850]
**Describe the bug**
I am not exactly sure how to change the background color of the element that appears at the bottom right of the screen when screen is minimized. Here's a capture of what this looks like now : 

![image](https://user-images.githubusercontent.com/71276060/148121309-28dc409d-9265-4594-b8a4-ca6e4713ca62.png)

I would like the background there to be black for example. 

I've already customized the react component to adjust styling, but for this specific html element, I am at a loss. 

I've tried looking at : https://github.com/Redocly/redoc#redoc-theme-object

And tried adjusting the following: 
- menu: background-color
- menu: arrow : background-color
amongst other things. 

**Expected behavior**
Clear documentation on how to use the theme object for styling this html element. 

**Minimal reproducible OpenAPI snippet(if possible)**
- using react 17.0.2
- using redoc 2*0*0.rc.57
- building with webpack 5.62.1
- using the react component by passing a theme in the options such as : 
```js
<RedocStandalone
  specUrl={...}
  options={{ theme: { ...redocTheme, ...}
```

**Comment by Oprysk** [comment]
Hi @clarencedesmarais 

Currently, button arrows accept the `theme.colors.main` property, and the background color is not configurable yet

**Comment by clarencedesmarais** [comment]
Is there any way to work around this ? 

Maybe an option to hide the circle or something like that ?

**Comment by AlexVarchuk** [comment]
@clarencedesmarais Hi! We add class to this button. I hope it helps you customize the fab button.

**Comment by clarencedesmarais** [comment]
Thanks :)

**Comment by AlexVarchuk** [comment]
@clarencedesmarais Hi! Sorry for the long delay. We discussed it. And added options to the theme object and props for hiding the fab button. We plan to release it this week.
