### ISSUE TITLE
[Docs] Add information for using `-o / --output` in `redoc-cli bundle` command

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redoc#1853]
**Describe the problem to be solved**
`redoc-cli bundle` command appears to accept the `-o / --output` option but it's not documented anywhere. 

**Describe the solution you'd like**
Please provide docs on the behavior of this cli argument.   https://redoc.ly/docs/redoc/deployment/cli/#using-the-redoc-cli

**Comment by skadinna** [comment]
Good catch! Thanks for reporting this. I've added it to our docs project board, so it should be taken care of soon enough. If you notice any other issues in the docs, feel free to let us know :)

**Comment by Knowledgeissweet** [comment]
Has this issue bring resolved yet? I will like to handle it

**Comment by jeremyfiel** [comment]
@skadinna  friendly reminder  :)
