### ISSUE TITLE
[Help] `redoc-cli bundle` output verbosity

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redoc#1854]
**Describe the bug**
I'm using the `redoc-cli bundle` command but I'm not able to identify the problem in my schema. 

The output indicates `Incompatible types in allOf at "/oneOf/5":  "object" and "string"`

**Expected behavior**
I tried `--verbose` and `--debug` and I wasn't able to get any further output from the cli. 

How can I tell which line or model is causing this error?

**Screenshots**
![image](https://user-images.githubusercontent.com/32110157/149205019-d922f1fd-9917-413a-91c8-7434c4295a8f.png)
**Additional context**

**Comment by andriyl** [comment]
Hi @jeremyfiel, thanks for reporting the issue.
Could you please provide your definitions (yaml files) or just part of them where you have `allOf`.

**Comment by AlexVarchuk** [comment]
@jeremyfiel  If you have more questions about your problem please reopen this issue. Thanks
