### ISSUE TITLE
Changed path

### ISSUE THREAD

**Issue by fedch** [Redocly/redoc#1855]
**Describe the bug**
When building the documentation Redoc rewrites the paths adding "~1" characters in them.
For example, what should have been `https://hosting/#tag/endpoint/paths/users/me/get`
becomes `https://hosting/#tag/endpoint/paths/~1users~1me~1/get`

Is there a way to change that so the path remain the same?

**Comment by RomanHotsiy** [comment]
No, this is a JSON pointer URL encoding. We can't change this easily at the moment unfortunately.

You should try using operationId so URL will look like https://hosting/operation/operation-id
