### ISSUE TITLE
schemaExpansionLevel Support

### ISSUE THREAD

**Issue by david-l-weitz** [Redocly/redoc#1856]
**Describe the problem to be solved**
The documentation (https://redoc.ly/docs/api-reference-docs/configuration/functionality/) describes an option called `schemaExpansionLevel` included in Redoc CE, however it doesn't appear to be supported by this repo. 

**Describe the solution you'd like**
Support for `schemaExpansionLevel` :)

**Comment by AlexVarchuk** [comment]
@david-l-weitz Hi! Thanks for the request. You can always use a [free](https://redoc.ly/pricing) plan for it.

**Comment by RomanHotsiy** [comment]
@AlexVarchuk the docs say it's supported but it's not. We have to either add support or fix the docs before closing this issue.

https://github.com/Redocly/reference-docs/pull/541#issuecomment-1017395866

**Comment by david-l-weitz** [comment]
> @AlexVarchuk the docs say it's supported but it's not. We have to either add support or fix the docs before closing this issue.

If possible, I would prefer the adding support option.
