### ISSUE TITLE
Support for x-example vendor extension

### ISSUE THREAD

**Issue by manuc66** [Redocly/redoc#186]
Hi,

I think it would be nice to support the `x-example` vendor extension [from Apiary](https://help.apiary.io/api_101/swagger-extensions/#x-example)

Thanks

**Comment by nemenemsrouge** [comment]
+1

**Comment by philsturgeon** [comment]
Hey! Did this ever get done? I'm trying to work with Open API v2.0 and Dredd v4.1.1, and there is an impassible conflict. 

Dredd allows `x-example` but ReDoc requires `example`, so I can either use ReDoc _or_ Dredd.

**Comment by RomanGotsiy** [comment]
@philsturgeon, yes, this will definitely get done.
If you want to get this faster feel free to open PR. Let me know if you need any help.

**Comment by RomanGotsiy** [comment]
@philsturgeon, yes, this will definitely get done.
If you want to get this faster feel free to open PR. Let me know if you need any help.

**Comment by philsturgeon** [comment]
@RomanGotsiy right on. Scroll up your inbox a little further, already tried. 😅 https://github.com/Rebilly/ReDoc/issues/304

**Comment by adamaltman** [comment]
@philsturgeon Roman is on vacation.  He'll be able to help you out when he returns at the beginning of August.

**Comment by RomanGotsiy** [comment]
Thanks, @adamaltman for covering my back :)
Between ✈️ and 👜 I've found some time to look into this issue (#304) and just fixed it :)

**Comment by philsturgeon** [comment]
Thanks for the heads up @adamaltman, and thank you for the fix @RomanGotsiy!

**Comment by RomanGotsiy** [comment]
@philsturgeon so are you going or maybe in process of creating a PR? Or I should handle it?

**Comment by philsturgeon** [comment]
I've had a few brief attempts but not got very far. If you could knock this out I'd appreciate it!

**Comment by RomanGotsiy** [comment]
OK! I will try to include this feature in the next-week release as I've just published new version `v1.17.0`

**Comment by JonKohler** [comment]
This should have been closed when #297 got merged, here: https://github.com/Rebilly/ReDoc/commit/f792273be8460f2c6f96eda8135a31c8754b36cb

I checked the latest redoc 2.0 and this for sure works
