### ISSUE TITLE
Multiple presentations of the same API Definition

### ISSUE THREAD

**Issue by Herrick19** [Redocly/redoc#1860]
**Describe the problem to be solved**
On large API with hundreds or thousands of endpoints, the documentation can be overwhelming and complicated to use for end users. Often, a small percentage of endpoints will be used by 85% of the users and the remaining will be for internal use of power users. For sure, there is a possibility to have more than one api definition files, but lots of code repeat between the files and management complexity is involved

**Describe the solution you'd like**
It would be nice to be able to create custom "PRESENTATION" of the same openapi documentation. A user could named them as they want and we could render a subset of documentation only based on the selected PRESENTATION.

A user could build an openapi spec file with 100% of the internal API but "hide" some from the public documentation to not confuse clients. This is not a replacement for properly securing the API endpoints naturally lol.

**Describe alternatives you've considered**
- Multiple openapi Specification files but this become a nightmare to keep them synced.

- Modify open api specs file before rendering it with redoc. But there could be a better way for everyone to do this.

**Additional context**
I think the feature could be somewhat "easy" to implement by using vendor specific extension. For example you could have a global "X-Presentations" attribute where you could define some based needed presentations for example:
X-PRESENTATIONS: [
"Full",
"Simplified",
"Product A",
"Product B",
"Foo"
]

Then in every Endpoint you could have something like:
X-PRESENTATION: [
"Full",
"Product B"
]

Meaning that this endpoint will only be rendered in these two presentations, but not in all others.

Now to choose the presentation, you could either put a dropdown at the top To choose the available presentations.

While rendering, it would be a "simple" "IF" 

If (SelectedPresentation in_array(X-Presentation)) {
//Do as usual
}
else {
//Do Not Add The Endpoint To The Side Menu;
//Remove the the x-tagGroups from the left menu if all endpoints from the group were skipped in the presentation
}

**** Bonus:
When using redoc-cli bundle [spec] to "Bundles spec and Redoc into a zero-dependency HTML file", we could pass an extra parameter for the "Presentations" we want to include and possibly the generated file could be smaller if we were to skip some presentations. Not sure if this is possible or not.

Hopefully you'll find this feature request interesting and beneficial for users and implement it.

Thanks for the good work

Let me know if we could help.

Best Regards

**Comment by AlexVarchuk** [comment]
@Herrick19 Hello! Thanks for the suggestion. I think to resolve this problem better use some additional steps before you want to display your definition. I prefer using for it [openapi-cli](https://github.com/Redocly/openapi-cli). Not long ago released [x-internal](https://github.com/Redocly/openapi-cli/issues/396) decorator, which helps you hide the internal APIs. Documentation you can find [here](https://redoc.ly/docs/cli/resources/built-in-decorators/#remove-x-internal).

**Comment by Herrick19** [comment]
Hi Alex,

Thanks I've read the documentation but unfortunately it's not flexible enough for my needs. The solution you have in place allows 2 outputs. One full, and one version without the endpoints listed as "internal".

On my side, I was hoping for at least 3 versions
"Full including internal functions"
"Full"
"Most commonly used functions only"

But I might even need more than that. At term, we'll probably have between 1500-2000 endpoints so it explains the need ;) I'm just hoping the toolset and redoc will be able handle such big definition file efficiently.

I understand my need is probably uncommon so I will implement it in the steps BEFORE we render it. I will strip down the definition before asking redoc to render it using X-Presentation tags.

For most people, your solution with "x-internal" is good enough.

I guess you can close this feature request.

Thanks again for this project.

Best Regards

**Comment by Elmar42** [comment]
Hi,

I found out that your proposed solution now works with redocly

Use the „filter-in“ decorator:


Example (redocly-customer1.yaml)

apis:
  filter:
    root: openapi.yaml
    decorators:
      filter-in:
          property: x-presentations
              value: 
                   - "customer1"
      remove-x-internal:
          internalFlagProperty: "x-presentations"

Example-Command:

redocly bundle filter —remove-unused-components —config=redocly-customer1.yaml -o openapi_cusomer1.yaml



The flag —remove-unused-component filters out not referenced components.

„remove-x-internal“ filters out the x-presentations flag

Regards 

Elmar
