### ISSUE TITLE
openapi 3.1 components schemas ref issue

### ISSUE THREAD

**Issue by petersamokhin** [Redocly/redoc#1862]
**Describe the bug**
Using the `3.1.0` OpenAPI version, the multiple-files structure doesn't work with `SchemaDefinition`.

**Expected behavior**
The same as with the `3.0.0` version, the schema object should be rendered properly.

**Minimal reproducible OpenAPI snippet(if possible)**
Just two files: 

`openapi.yml`
```yml
openapi: 3.1.0

# ...

components:
  schemas:
    test:
      $ref: ./components/test.yml#/Test
```

`./components/test.yml`
```yml
Test:
  type: object
  properties:
    test:
      type: string
```

**Screenshots**
It's rendered as `any (test)` but is correct in the "pull right".
It works properly for `openapi: 3.0.0`.

Worths to mention in #1715

**Comment by AlexVarchuk** [comment]
@petersamokhin Hi. We merged PR which fix it. Next week we will have a release.

**Comment by AlexVarchuk** [comment]
relesed
