### ISSUE TITLE
Marked version requires bumping

### ISSUE THREAD

**Issue by Nanbob** [Redocly/redoc#1864]
**Describe the bug**
- NPM audit and the package of redoc  (https://github.com/Redocly/redoc/blob/master/package.json#L88) shows that the version of Marked being used is 4.0.1. I think this needs bumping to 4.0.10 (https://github.com/markedjs/marked/blob/master/package.json#L5)

**Comment by YunosukeY** [comment]
It seems to be resolved in #1863.
When will the version contains #1863 be released?
I'm looking forward to it!
