### ISSUE TITLE
`object` does not expand on click since `v2.0.0-rc.60`

### ISSUE THREAD

**Issue by Juneezee** [Redocly/redoc#1875]
**Describe the bug**
`object` does not expand on click since `v2.0.0-rc.60`

**Expected behavior**
`object` is expanded on click

**Minimal reproducible OpenAPI snippet(if possible)**
See the [JS Bin demo](https://jsbin.com/hupesiquni/edit?html,output).

The HTML below is the example from https://redoc.ly/docs/redoc/quickstart/#redoc-quickstart-guide
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Redoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700"
      rel="stylesheet"
    />

    <!--
    Redoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <!--
    Redoc element with link to your OpenAPI definition
    -->
    <redoc spec-url="https://redocly.github.io/redoc/openapi.yaml"></redoc>
    <!--
    Link to Redoc JavaScript on CDN for rendering standalone element
    -->
    <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.60/bundles/redoc.standalone.js"></script>
  </body>
</html>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/20135478/151127664-2bf798a2-41d8-4bd4-b2d5-b5317091f620.png)

**Additional context**
It works fine on `v2.0.0-rc.59`

**Comment by ferjul17** [comment]
Is it possible to [purge the cache of `jsdelivr`](https://github.com/jsdelivr/jsdelivr#purge-cache) to deliver the version `2.0.0-rc.62` instead of the version `2.0.0-rc.61` which still have the bug?

**Comment by RomanHotsiy** [comment]
Should be purged now.
