### ISSUE TITLE
Redoc CLI Install Broken

### ISSUE THREAD

**Issue by moretalk** [Redocly/redoc#1882]
**Describe the bug**
package redoc-cli fails to install with: No matching version found for redoc@2.0.0-rc.62 

**Expected behavior**
npm install redoc-cli installs correctly

**Additional context**
Bump redoc-cli dependencies to an available rc of redoc package

**Comment by GalenkoEugene** [comment]
Here the PR with changes: https://github.com/Redocly/redoc/pull/1880

**Comment by simondrake** [comment]
That PR doesn't fix the CLI because the [redoc-cli package.json](https://github.com/Redocly/redoc/blob/master/cli/package.json#L22) hasn't been updated

**Comment by Oprysk** [comment]
What version of node and npm you are using?

**Comment by nekomeowww** [comment]
Running environment: `node v14.17.6`
Tools tested:
 - `pnpm 6.14.7`
 - `npm 6.14.15`
 - `yarn 1.22.4`

All these tools above have reported that `redoc@2.0.0-rc.62` cannot be found when trying to install `redoc-cli`

**Comment by simondrake** [comment]
For me, this is happening on these versions:

```
$ node --version
v14.18.1

$ npm --version
6.14.15
```

It looks like this is happening because the redoc-cli is [referencing a version of redoc](https://github.com/Redocly/redoc/blob/master/cli/package.json#L22) that doesn't exist (or at least doesn't exist in [releases](https://github.com/Redocly/redoc/releases))

**Comment by simondrake** [comment]
It's not in [tags](https://github.com/Redocly/redoc/tags) either6

**Comment by nekomeowww** [comment]
https://github.com/Redocly/redoc/blob/acbc5c7b59a2dc9bddfda0a910257a8428b6f2b9/cli/package.json#L22

This line referenced the `redoc@2.0.0-rc.62` version in `package.json` of `redoc-cli` package where the redoc only has `2.0.0-rc.61` released 14 hours ago. [npn version](https://www.npmjs.com/package/redoc)

**Comment by Oprysk** [comment]
Thank you all for reporting this issue. 
We've found the problem. Fix is on the way

**Comment by Oprysk** [comment]
redoc@2.0.0-rc.62 published https://www.npmjs.com/package/redoc/v/2.0.0-rc.62

**Comment by simondrake** [comment]
Thanks @Oprysk 

Tested and confirmed as working.
