### ISSUE TITLE
left navigation menu doesn't scroll

### ISSUE THREAD

**Issue by IanMadd** [Redocly/redoc#1883]
**Describe the bug**
The left navigation menu doesn't scroll if there are overflowing menu items.

**Expected behavior**
Long left nav menus can scroll

**Minimal reproducible OpenAPI snippet(if possible)**

**Screenshots**

**Additional context**
The `ps` class in 2.0.0-rc.59 has `overflow: hidden !important; overflow-anchor: none; touch-action: auto;`, but this class isn't defined in 2.0.0-rc.62.

**Comment by talking-tortoise** [comment]
@IanMadd - I'm having the same issue as well with any overflow items. Following.

**Comment by talking-tortoise** [comment]
@IanMadd -- I don't know how you've integrated it or what setup you're using, but I had the `@latest` tag on my script. I just reverted to `<script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.23/bundles/redoc.standalone.js"> </script>` and it's working again for me.

**Comment by ideadapt** [comment]
Same issue here, using `<script src="https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js"></script>` (which currently downloads 2.0.0-rc.62).
