### ISSUE TITLE
Failure to serve swagger document when using v0.13.3 of redoc-cli

### ISSUE THREAD

**Issue by gaz77a** [Redocly/redoc#1884]
**Describe the bug**
When we upgrade from v0.13.2 to v0.13.3 of redoc-cli it seems that redoc-cli is failing to serve up the swagger document.

The error we get is
`**attribute  is not of type `object`
com.atlassian.oai.validator.util.OpenApiLoader.loadApi(OpenApiLoader.java:42)`

**Comment by AlexVarchuk** [comment]
@gaz77a Hi! Does it reproduce in v0.13.6?

**Comment by gaz77a** [comment]
@AlexVarchuk 
Unfortunately the same issue occurs using v0.13.6

**Comment by AlexVarchuk** [comment]
@gaz77a Hi! I can't reproduce it. I run `redoc-cli serve /path/to/swagger.yaml` and it works.
Can you help me with reproducing? Add please minimal reproducible OpenAPI, and command with full logs which failed. Thanks.

**Comment by AlexVarchuk** [comment]
@gaz77a  Hi! The versions v0.13.3 and v0.13.4 failed. On 0.13.5-0.13.7, all works fine. But this error is not from our side. We don't use java) Please check this [link](https://bitbucket.org/atlassian/swagger-request-validator/issues/280/validation-of-openapi-schema-fails-with).
This error is from the swagger-request-validator, seems your definition is not valid. 

If you have a question, feel free to reopen this issue.
