### ISSUE TITLE
Pass in x-* as a configuration to redoc element

### ISSUE THREAD

**Issue by onektwenty4** [Redocly/redoc#1890]
**Describe the problem to be solved**
My OpenAPI impl doesn't let me add x-* items into the info section of the openapi response.  
Can I configure things like x-logo in html code instead?

**Describe the solution you'd like**
Ideally I could pass <redoc ... x-logo="{url:'abc.png'}" ... />

**Comment by AlexVarchuk** [comment]
@onektwenty4 Hi! We don't have the implementation to pass the logo to redoc options. You can try using a standalone version, and insert your logo in an HTML file like an image.

**Comment by onektwenty4** [comment]
Ok.  Just a suggestion.  I'm still quite interested in using this library.
