### ISSUE TITLE
t.required indexOf is not a function

### ISSUE THREAD

**Issue by gaoyan198** [Redocly/redoc#1893]
Am getting this bug when trying to load a redoc static page via Flask app. 

Something went wrong...
t.required indexOf is not a function
Stack trace
TypeError: t.required,index0f is not a function
at https://cdn-jsdelivr-net/npm/redoc@lataat/bundlas/redoc-atandalone-je:33:55023
at Array.map (canonymous>)
at https://odn-isdelive.net/npm/radoc@latest/bundles/redoc-atandalone-je+33:55646
at be.init (httpa://cdn. jadelivanet/npm/redoc@latest/bundlea/radoc.standalona.js:33:56317)
at new be (httpa://cdn-jedelivr.nat/npm//radoc@lateat/bundles/radoc.atandalone.je:33:53697)
at new Ac (https://cdn.Jadelivr.nat/mpm/redoc@latest/bundles/redog-standalone.js:33:60690)
at httpe://edn. isdelivr.net/npo/redoc@latast/bundles/redoc-standalone-js:33:55044
at Array.map (canonymous>)
at httpa://cdn-jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone. js+33:55646
at be.init (https://edn_jsdelivr.net/mpm/redoc@latest/bundles/redoc.standalone.js:33:56317)
ReDoc Version: 2.0.0-rc.63
Commit: b474d67

**Comment by AlexVarchuk** [comment]
@gaoyan198 Hi! please check your link to the [CDN package](https://github.com/Redocly/redoc#releases).
```
 https://cdn-jsdelivr-net/npm/redoc@lataat/bundlas/redoc-atandalone-je:33:55023
```

**Comment by gaoyan198** [comment]
@AlexVarchuk thanks for the response. I dont think it is the CDN package because this error only surfaces on a particular OAS3 json file. It works for other files I tested with.

Unfortunately, I am unable to share the file in question as it is for internal use.

**Comment by AlexVarchuk** [comment]
@gaoyan198 HI.

> Unfortunately, I am unable to share the file in question as it is for internal use.

 I try to reproduce it but had no success.
Can you reproduce it in minimal snippets and add it here?

**Comment by AlexVarchuk** [comment]
@gaoyan198 Hi! You can use [openapi](https://www.npmjs.com/package/@redocly/openapi-cli) to lint your definition. 

```
npx @redocly/openapi-cli lint path-to-root-file.yaml
```
If you need our help, please reopen this issue and provide minimal snippets for reproducing. Thanks
