### ISSUE TITLE
Change `Documentation Powered by Redoc` to `API documentation Powered by ReDoc`

### ISSUE THREAD

**Issue by homotechsual** [Redocly/redoc#1895]
**Describe the problem to be solved**
We use Redoc (thanks, it's awesome!) inside Docusaurus, it would be clearer and more accurate for us to have the powered by line read "API documentation powered by ReDoc.

**Comment by RomanHotsiy** [comment]
Hey, unfortunately we can't do it:

- It makes the line too long and will wrap it.
- Most of our OSS users don't use it in Docusarus.
- Needs careful analysis because it can also impact our SEO.

**Comment by homotechsual** [comment]
Ok - thanks for considering it Roman :-)
