### ISSUE TITLE
How does redoc perform at scale? >10,000 concurrent users?

### ISSUE THREAD

**Issue by gaoyan198** [Redocly/redoc#1901]
Hi Redoc team, thanks for open sourcing such a great product for api documentation with minimal setup process. I am having question with how does the custom tag <redoc> perform under scale? Sorry if it is a basic question am not very familiar with custom tags.
Thanks in advance

**Comment by adamaltman** [comment]
What is the custom tag?

**Comment by AlexVarchuk** [comment]
@gaoyan198 Hi! Thanks for the question. 
But sorry, but I don't understand your question. Can you clarify it?

**Comment by AlexVarchuk** [comment]
Please, reopen the issue after adding additional information to the question. Thanks
