### ISSUE TITLE
Api keeps refreshing endlessly ..

### ISSUE THREAD

**Issue by takieddine12** [Redocly/redoc#1904]
I'm using this api in my flutter application but for some reason the data shows and then disappears on its own , i believe the side server keeps sending requests to my application .. and i noticed it drains the free requests fastly .. i start testing once , twice and then requests are over an i started getting error "Too many requests. Your rate limit is 10 requests per minute" , if you can please take a look at the issues i mentioned and fix them , thank you , i could not even get to test the api in my application as data keeps refreshing on its own . Thank you

**Comment by AlexVarchuk** [comment]
@takieddine12 Hi! thanks for the request. Could you provide more data on how you use `redoc` in your application? What do you mean by `API`?

**Comment by AlexVarchuk** [comment]
If you'll have some questions or suggestions about your question feel free to reopen the issue. Thanks.
