### ISSUE TITLE
AuthorAttributes in API documentation is wrong 

### ISSUE THREAD

**Issue by sou1maker** [Redocly/redoc#1907]
**Describe the bug**

AuthorAttributes in API docs don't match actual correspondence .

**Expected behavior**

fix api documentation.

**Minimal reproducible OpenAPI snippet(if possible)**

version: 5.4.17

**Screenshots**

![image](https://user-images.githubusercontent.com/58240137/154545441-3a0471cc-250d-4d5d-a28e-e0cfba62279b.png)

![image](https://user-images.githubusercontent.com/58240137/154545722-8ab304f2-0465-4330-9832-a64baa3cda4b.png)

**Additional context**

**Comment by RomanHotsiy** [comment]
We can't understand this issue. How is Redoc related?

**Comment by AlexVarchuk** [comment]
@sou1maker Hi! Can you provide OpenAPI snippet, witch reproduces this issue? Thanks

**Comment by AlexVarchuk** [comment]
no problem. If you'll have a question about `redoc`, let know us.
