### ISSUE TITLE
URI Malformed error when building yaml file

### ISSUE THREAD

**Issue by videaputri** [Redocly/redoc#1921]
Hi, please help. I don't know what causes this, buat when i try to run my redocs openapi documentation, it appears like this : 
![image](https://user-images.githubusercontent.com/98309475/157226664-3c79b3ed-74e3-4811-ad15-cb89e105e90d.png)

<br>

i've checked my docs with openapi lint and it's valid, and build is successful: 
![image](https://user-images.githubusercontent.com/98309475/157227723-1d574581-f0a1-4536-b8db-8d1184fbdbb3.png)

so i really dont know what causes this. about 3 hours before i still can run my docs in my local server. **please help, thankyou**

**Comment by AlexVarchuk** [comment]
@videaputri Hi! Thanks for the request. 
Do you try to start your definition using [HTML template](https://github.com/Redocly/redoc#tldr-final-code-example)?

**Comment by videaputri** [comment]
yes, this is my index.html looks like:

![image](https://user-images.githubusercontent.com/98309475/157231875-d3c5f7ac-6caa-4283-9dd9-4e1e677e8142.png)

<br> 
is there something wrong with this file?

**Comment by videaputri** [comment]
fyi, i have 2 yaml file: 

[file1](https://drive.google.com/file/d/1T9VVVrs5g_6GdUK9JMRyomBYdtJ9m-Sc/view?usp=sharing): build is successful with this one, and the docs is showing properly
[file2:](https://drive.google.com/file/d/1aKg8Mi8g3BnDIMf-FahHmGJF32yvU3k5/view?usp=sharing) although build was successful but when i try npm start, it appears URI malformed. 

2 files are valid, but i dont know why the second file cannot showing properly (URI malformed error)

**Comment by AlexVarchuk** [comment]
> [file2:](https://drive.google.com/file/d/1aKg8Mi8g3BnDIMf-FahHmGJF32yvU3k5/view?usp=sharing) although build was successful but when i try npm start, it appears URI malformed.

What run the `npm start` script?

**Comment by videaputri** [comment]
openapi preview-docs 

![image](https://user-images.githubusercontent.com/98309475/157235499-9ed9dc19-a7cb-4996-84e0-fe4357fbb783.png)

**Comment by videaputri** [comment]
even when i try using [redoc demo](https://redocly.github.io/redoc/), the first file is successfully generated, but the second file is error. 

but i'm testing it also on swagger for the second file and it runs well.

**Comment by AlexVarchuk** [comment]
try to pass path to yaml file into your start script
```
openapi preview-docs /path/to/definition.yaml
```

**Comment by AlexVarchuk** [comment]
More details you can find [here](https://redoc.ly/docs/cli/commands/preview-docs/)

**Comment by AlexVarchuk** [comment]
I tested your second file.
It works well for me
`openapi preview-docs ./dist.yml`
<img width="1769" alt="Screenshot 2022-03-08 at 14 19 11" src="https://user-images.githubusercontent.com/14113673/157236960-cce3ed30-507e-4134-bbcd-7d308e5ae044.png">

**Comment by AlexVarchuk** [comment]
Hi @videaputri. If you'll have more questions please reopen PR. Thanks
