### ISSUE TITLE
Cannot import { RedocStandalone } from 'redoc'

### ISSUE THREAD

**Issue by vicodinvic1** [Redocly/redoc#1926]
It is not possible to `import { RedocStandalone } from 'redoc'`

All required dependencies are installed:
`react react-dom mobx styled-components core-js`

It returns an error:  `Cannot read properties of undefined (reading 'merge')`

<img width="647" alt="Screenshot 2022-03-11 at 11 30 48" src="https://user-images.githubusercontent.com/13731447/157840336-36c8cbf8-23fe-458a-a11f-8aedf7333c57.png">
<img width="1439" alt="Screenshot 2022-03-11 at 11 44 24" src="https://user-images.githubusercontent.com/13731447/157842622-8cdb3711-3f42-4612-876a-e69d986165cb.png">

**Comment by AlexVarchuk** [comment]
@vicodinvic1 Hi! Thanks for the issue. 
I trying to reproduce it, but cannot.
Can you send a link to github repo for reproducing?

**Comment by vicodinvic1** [comment]
I can't share a link since this is private repo.

And I can't even make it work in the blank `create-react-app` project, but there is another error saying:
`Cannot read properties of undefined (reading 'Renderer')`

**Comment by AlexVarchuk** [comment]
@vicodinvic1 Can you provide a minimal reproducible example for that?

**Comment by vicodinvic1** [comment]
@AlexVarchuk 
I've just tried to make it work in codesandbox. Should it work with no issues there? Did I miss something?

https://codesandbox.io/embed/nice-gauss-su8z4o?fontsize=14&hidenavigation=1&theme=dark

There are another errors anyway...

**Comment by AlexVarchuk** [comment]
@vicodinvic1 Seems it bad definition link. Change to https://redocly.github.io/redoc/openapi.yaml. It works ok for me.

**Comment by vicodinvic1** [comment]
@AlexVarchuk
I've just located where is `merge` is missing it is in the `@redocly/openapi-core/lib/js-yaml/index.js`

I'm trying to render RedocStandalone right in the entry point to avoid any side effects of the wrappers I have in project

<img width="1552" alt="Screenshot 2022-03-11 at 15 10 26" src="https://user-images.githubusercontent.com/13731447/157872824-ebcb0702-5a2f-4317-8298-b779d2d36a57.png">
![Screenshot 2022-03-11 at 15 13 11](https://user-images.githubusercontent.com/13731447/157873307-90143338-f9e3-4d57-a14b-e9ba282deb2e.png)

**Comment by AlexVarchuk** [comment]
@vicodinvic1 Can you validate your definition. You can use [openapi-cli](https://www.npmjs.com/package/@redocly/openapi-cli):
```
npx @redocly/openapi-cli lint path-to-root-file.yaml
```

**Comment by vicodinvic1** [comment]
@AlexVarchuk

"redoc": "^2.0.0-rc.64",
"webpack": "^5.69.1"

**Comment by AlexVarchuk** [comment]
@vicodinvic1 Do you use create-react-app@5.0.0?

**Comment by vicodinvic1** [comment]
No, I'm using a custom webpack boilerplate, and I had the same error with webpack v4 as well.

I mentioned create-react-app just to say that there is error too, but different one

**Comment by AlexVarchuk** [comment]
What `target` do you use in webpack config options?

**Comment by vicodinvic1** [comment]
here is my webpack config

`const CopyWebpackPlugin = require('copy-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const TerserPlugin = require('terser-webpack-plugin')
const webpack = require('webpack')
const { CleanWebpackPlugin } = require('clean-webpack-plugin')
const { DuplicatesPlugin } = require('inspectpack/plugin')
const { join, resolve } = require('path')
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')

const STAGES = require('./stages.json')

const ENV = process.env.NODE_ENV || 'development'
const DEV = ENV === 'development'
const PROD = ENV === 'production'

const ROOT_DIR = resolve(__dirname)
const SRC_DIR = join(ROOT_DIR, 'src')
const DIST_DIR = join(ROOT_DIR, 'dist')
const NODE_MODULES_DIR = join(ROOT_DIR, 'node_modules')

const HOST = process.env.HOST || '0.0.0.0'
const PORT = process.env.PORT || 8000

const DEFAULT_STAGE = 'dev'
const DEFAULT_BRAND = 'default'

const STAGE = process.env.STAGE || DEFAULT_STAGE
const STAGE_CONFIG = STAGES[STAGE]

const BRAND = process.env.BRAND || DEFAULT_BRAND
const BRAND_DIR = join(ROOT_DIR, 'brand', BRAND)
const BRAND_STATIC_DIR = join(BRAND_DIR, 'static')

const BRAND_BY_STAGE_CONFIG = STAGE_CONFIG.BRAND[BRAND]

const PUBLIC_PATH = process.env.PUBLIC_PATH || '/'

const config = {
  mode: ENV,
  context: SRC_DIR,
  entry: {
    app: SRC_DIR
  },
  output: {
    chunkFilename: '[id].[chunkhash].js',
    filename: '[name].[contenthash].js',
    hashDigestLength: 16,
    path: DIST_DIR,
    publicPath: PUBLIC_PATH
  },
  optimization: {
    runtimeChunk: {
      name: 'vendor'
    },
    moduleIds: 'named',
    splitChunks: {
      chunks: 'all',
      minSize: 1e5,
      name: false,
      cacheGroups: {
        defaultVendors: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendor',
          enforce: true,
          chunks: 'all'
        }
      }
    }
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          cacheDirectory: true,
          plugins: ['react-hot-loader/babel']
        }
      },
      {
        test: /\.css/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          }
        ]
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 2048
            }
          },
          {
            loader: 'image-webpack-loader',
            options: {}
          }
        ]
      },
      {
        test: /\.(woff|woff2|swf|ttf|eot|otf|mp4|ogv|webm)$/i,
        loader: 'file-loader'
      }
    ]
  },
  resolve: {
    alias: {
      cx: 'clsx',
      brand: BRAND_DIR,
      'react-dom': '@hot-loader/react-dom'
    },
    modules: [
      SRC_DIR,
      NODE_MODULES_DIR
    ],
    fallback: {
      path: require.resolve('path-browserify'),
      fs: false
    }
  },
  plugins: [
    new webpack.DefinePlugin(mapStageConfigToDefinePlugin({
      ...STAGE_CONFIG,
      ...BRAND_BY_STAGE_CONFIG,
      DEFAULT_BRAND,
      BRAND,
      PUBLIC_PATH: process.env.PUBLIC_PATH
    })),

    new NodePolyfillPlugin(),
    new webpack.ProvidePlugin({
      Buffer: ['buffer', 'Buffer']
    }),

    new HtmlWebpackPlugin({
      title: BRAND_BY_STAGE_CONFIG.title,
      template: join(SRC_DIR, 'index.ejs'),
      meta: [{
        name: 'robots', content: 'noindex,nofollow'
      }],
      minify: {
        collapseWhitespace: true,
        conservativeCollapse: true,
        preserveLineBreaks: true,
        useShortDoctype: true,
        html5: true
      },
      mobile: true
    }),

    new CopyWebpackPlugin([
      {
        from: BRAND_STATIC_DIR,
        force: true
      }
    ])
  ],
  stats: {
    children: false
  }
}

if (DEV) {
  config.devtool = 'inline-source-map'
  config.devServer = {
    compress: true,
    contentBase: DIST_DIR,
    headers: {
      'X-Content-Type-Options': 'nosniff',
      'X-Frame-Options': 'DENY'
    },
    historyApiFallback: true,
    host: HOST,
    hot: true,
    inline: true,
    noInfo: false,
    overlay: {
      warnings: false,
      errors: true
    },
    port: PORT,
    publicPath: PUBLIC_PATH
  }

  config.plugins.push(
    new webpack.ProgressPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new DuplicatesPlugin()
  )
}

if (PROD) {
  config.optimization.minimizer = [
    new TerserPlugin({
      sourceMap: true
    })
  ]

  config.plugins.push(
    new CleanWebpackPlugin(),

    new webpack.LoaderOptionsPlugin({
      options: {
        context: SRC_DIR
      }
    })
  )
}

function mapStageConfigToDefinePlugin (config) {
  const definePluginObject = {}

  Object.keys(config).forEach(key => {
    definePluginObject[`process.env.${key}`] = JSON.stringify(config[key])
  })
  return definePluginObject
}

module.exports = config`

**Comment by AlexVarchuk** [comment]
Thanks, we are trying to reproduce it. But no success.
