### ISSUE TITLE
Error occurs when using trailing slash on path

### ISSUE THREAD

**Issue by videaputri** [Redocly/redoc#1937]
![image](https://user-images.githubusercontent.com/98309475/159209789-23267811-e601-4339-9851-053a99eb7b53.png)

Would you please tell me how to add trailing slash on path? because my developers said that the url should contain the trailing slash so it may run well. Please help. Thank you.

**Comment by RomanHotsiy** [comment]
You can disable the rule in `.redocly.yaml` file in the root of your repo: https://redocly.com/docs/cli/configuration/configuration-file/

```
lint:
  rules:
    no-path-trailing-slash: off
```

**Comment by videaputri** [comment]
ok thank you so much!
