### ISSUE TITLE
Outdated minimist version 1.2.5 as dependency

### ISSUE THREAD

**Issue by krzysztofmeler** [Redocly/redoc#1941]
**Describe the bug**

`minimist` package has a security bug in versions up to 1.2.5. New and compatible version 1.2.6 was published and is described as free of this issue.
https://github.com/substack/minimist
https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795

**Expected behavior**

I expected version 1.2.6 of `minimist` to be installed but I see that version 1.2.5 is specified as resolved in `package-lock.json` and npm's shrinkwrap.

**Minimal reproducible OpenAPI snippet(if possible)**

Create a new project, run `npm init -y` and `npm install redoc-cli`, then check minimist package with `npm why minimist`.

**Screenshots**
```
> npm why minimist@1.2.5
minimist@1.2.5 dev
node_modules/redoc-cli/node_modules/minimist
  minimist@"^1.2.5" from handlebars@4.7.7
  node_modules/redoc-cli/node_modules/handlebars
    handlebars@"^4.7.7" from redoc-cli@0.13.9
    node_modules/redoc-cli
      dev redoc-cli@"^0.13.9" from the root project
    handlebars@"*" from @types/handlebars@4.1.0
    node_modules/redoc-cli/node_modules/@types/handlebars
```

**Additional context**

`Minimist` is required by `handlebars`, `handlebars` package is dependency of `redoc-cli`, but this package has version 1.2.5 as minimal, so this repository requirements probably causes this problem.

**Comment by AlexVarchuk** [comment]
@krzysztofmeler Hi! Thank you for the issue. We'll fix it in the next release.
