### ISSUE TITLE
<no summary> showing when optional field is missing

### ISSUE THREAD

**Issue by druid03** [Redocly/redoc#1946]
**Describe the bug**
It seems to be a similar issue to https://github.com/Redocly/redoc/issues/1270
Left sidebar does not include names or paths to the functions, just a "no summary"

**Expected behavior**
Summary or path should be displayed

**Comment by AlexVarchuk** [comment]
@druid03 Hi! Thank you for your request. You can use `sideNavStyle: path-only` for displaying the path of operation.
