### ISSUE TITLE
Cannot change color background in reference docs

### ISSUE THREAD

**Issue by videaputri** [Redocly/redoc#1948]
I try to theme my API docs, btw i'm using redoc community edition, I want to change the white background into other colors: 
![image](https://user-images.githubusercontent.com/98309475/160762054-30e8e2c2-2536-436f-83d7-e69ed5596f22.png)

then i set the the configuration as you see below:
![image](https://user-images.githubusercontent.com/98309475/160762168-9a6ce57b-01e1-4b92-80cb-1d549da3ef9c.png)

but when i try to run  'npm run build', the color is still not changing, so what should i do?
because i read that it is supposed to be supported in redoc ce
![image](https://user-images.githubusercontent.com/98309475/160762728-9cf63830-10ea-492f-a3b4-8fa596762615.png)

**Comment by AlexVarchuk** [comment]
@videaputri Hi! `redoc` doesn't support the configuration file. Instead, you can pass options to [redoc object](https://redocly.com/docs/redoc/deployment/html/#the-redoc-object)
or use [`openapi-cli preview-docs`](https://redocly.com/docs/cli/commands/preview-docs/#preview-docs) and pass the config file.

**Comment by videaputri** [comment]
![image](https://user-images.githubusercontent.com/98309475/160797108-7b5d843d-80fb-4dfe-87bf-1a3ab46c79c2.png)

have tried it, but nothing change. is the code wrong?

**Comment by AlexVarchuk** [comment]
try to customize the background color of rightPanel.
```
theme: {
    rightPanel: { backgroundColor: 'red' },
  }
```

**Comment by videaputri** [comment]
ok thank you

**Comment by videaputri** [comment]
it works! hehe
