### ISSUE TITLE
Markdown headers render weird when CRLF is used in OpenAPI description json 

### ISSUE THREAD

**Issue by kstolte** [Redocly/redoc#1952]
**Describe the bug**
When CRLF(`\r\n`) are used within the info.description the rendering of the markdown component gets a bit wonky. All the Content of the markdown excluding headers get rendered below the last header. This would more than likely impact anyone that is using a windows computer for drafting markdown files and incorporating those markdown files using the cli tool. 

**Expected behavior**
Shouldn't matter if `\r\n` is used or `\n`.

**Minimal reproducible OpenAPI snippet(if possible)**
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Minimal Example JSON",
    "description": "# Getting Started\r\n## Authentication\r\nAll API Requests _must_ contain an Authorization Header with a valid access token",
    "contact": {
      "name": "Name",
      "email": "email@example.com"
    },
    "version": "v3.0: 3.10.0.0"
  }
}
```
**Screenshots**
The above json was uploaded as a file to https://redocly.github.io/redoc/ for testing purposes.
![image](https://user-images.githubusercontent.com/20091146/160947565-55943829-3ca2-4b46-94a6-025630b12e5c.png)

**Additional context**

Ran into this while upgrading from Swashbuckle.AspNetCore.ReDoc 6.2.3 to 6.3.0.  6.2.3 used redoc-ui 2.0.0-rc.40 and 6.3.0 bumped it up to 2.0.0-rc.63. Was able to narrow it down through local testing to being introduced between version rc.59 and rc.60. 

commit that seems to introduce this bug is https://github.com/Redocly/redoc/pull/1845/commits/33a6e4398659680a55d7d3e6badf65f083d87ccf in PR #1845

**Comment by AlexVarchuk** [comment]
@kstolte Hi! Thank you for reporting the issue. We start working on that, after review pr it'll be included in to release.

**Comment by kstolte** [comment]
Hi Alex, Thanks much! I was going to submit a pr this morning with exactly your change. Appreciate what you did! 

Since this will more than likely affect the DotNet users I'll create a pr over there to version bump to this version when it is released.
