### ISSUE TITLE
Horizontal scrollbar for path and query parameters

### ISSUE THREAD

**Issue by majoshi1** [Redocly/redoc#1958]
**Describe the bug**
A horizontal scrollbar is missing for path and query parameters. So, large text is cut and not visible.

**Expected behavior**
A horizontal scrollbar should be shown for path and query parameters.

**Minimal reproducible OpenAPI snippet(if possible)**
Try with larger lines or words.

**Screenshots**
NA

**Additional context**
NA

**Comment by AlexVarchuk** [comment]
@majoshi1 Hi! Thank you for your request. We'll try to reproduce it.
If you provide some screenshots or API snippets it helps us so much.

**Comment by majoshi1** [comment]
Screenshot 1: Updated petstore spec in [redoc demo](https://redocly.github.io/redoc/) to have longer description and examples.
Screenshot 2: Example and description getting cut.
It fails to wrap for example with 60 or more characters. You may need to keep browser at 100% zoom and a smaller size e.g. 1361X1000.


Screenshot 1:
![image](https://user-images.githubusercontent.com/292394/165408875-aa35cfb2-9d78-47e2-9872-1c7b2b358fd7.png)


Screenshot 2:
![image](https://user-images.githubusercontent.com/292394/165408718-dfa32dd6-77ea-4b37-a3fa-97bc0cde7cf7.png)
