### ISSUE TITLE
How do I use the `code` variation of the `openIdConnect` security configuration?

### ISSUE THREAD

**Issue by SeeSharpCode** [Redocly/redoc#1965]
**Describe the bug**
The authentication table in the [Try It documentation](https://redocly.com/docs/api-reference-docs/guides/try-it-console/) indicates full support for the `code` variation of `openIdConnect`.

Below the table is this snippet

> openIdConnect - OAuth2 implicit flow UI (it works only for OpenID servers that support the token response_type ). **Redocly will support code once we add support for authorizationCode oauth2 flow.**

1. The bolded sentence is a bit confusing given the table indicating full support. Is it actually supported?
2. If so, how do I use the `code` variation? The Try It console defaults to the `implicit` flow, but I would like to use `authorizationCode`.

**Comment by AlexVarchuk** [comment]
Closed. 
Reason not related to redoc.

**Comment by RomanHotsiy** [comment]
@SeeSharpCode if you have questions about our commercial offering, contact team@redocly.com please.

Thanks!
