### ISSUE TITLE
Publish a redoc image compatible with linux/arm64/v8 (Apple M1)

### ISSUE THREAD

**Issue by goldfrapp04** [Redocly/redoc#1966]
**Describe the problem to be solved**
The current official [redoc image](https://hub.docker.com/r/redocly/redoc/) does not work with Apple M1 computers. 

When trying to `docker run` something with the `redoc` image as is on an M1 computer, this error occurs:
```
The requested image’s platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

If you add argument `--platform linux/arm64/v8` to the command, another reasonable error occurs:
```
docker: Error response from daemon: image with reference redocly/redoc was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64.
```

**Describe the solution you'd like**
Redocly publishes an image that's compatible with `linux/arm64/v8`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anastasiia-developer** [comment]
Hi, such an warning exists but the docker continues to work 
I run such a command on the Apple M1 
```
docker run -it --rm -p 80:80 \
  -v $(pwd)/demo/swagger.yaml:/usr/share/nginx/html/swagger.yaml \
  -e SPEC_URL=swagger.yaml redocly/redoc
```
  and I also have a warning but on the http://localhost/  it works
  We will fix this warning after release redoc 2.0.0
