### ISSUE TITLE
OpenAPI reference not working in combination with example

### ISSUE THREAD

**Issue by lukaswindisch** [Redocly/redoc#1967]
**Describe the bug**
A reference in component - schemas is not working in combination with an example. The example does not describe the keys the reference is referring to.

**Expected behavior**
The reference is resolved and the object it is referring to is used as if it would be defined at this position. The example underneath the reference can then define the values described in the referred object.

**Minimal reproducible OpenAPI snippet(if possible)**
Codeblock 1: The way it should look like (with workaround):
```yaml
openapi: "3.0.2"
info:
  title: Test
  version: "1.0.0"
servers:
  - url: https://localhost:8080/api/v1
paths:
  /test/{documentId}:
    get:
      summary: Summary
      operationId: operation
      parameters:
        - name: documentId
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: Resources successfully deleted.
        404:
          description: Not found
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/DocumentNotExistentError"
                  - $ref: "#/components/schemas/DocumentDeletedError"
components:
  schemas:
    ResponseError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    DocumentNotExistentError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      example:
        code: "404_1"
        message: Document not found.
    DocumentDeletedError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      example:
        code: "404_2"
        message: Document has been deleted.
```

Codeblock 2: The code that doesn't lead to the expected result:
```yaml
openapi: "3.0.2"
info:
  title: Test
  version: "1.0.0"
servers:
  - url: https://localhost:8080/api/v1
paths:
  /test/{documentId}:
    get:
      summary: Summary
      operationId: operation
      parameters:
        - name: documentId
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: Resources successfully deleted.
        404:
          description: Not found
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/DocumentNotExistentError"
                  - $ref: "#/components/schemas/DocumentDeletedError"
components:
  schemas:
    ResponseError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    DocumentNotExistentError:
      $ref: "#/components/schemas/ResponseError"
      example:
        code: "404_1"
        message: Document not found.
    DocumentDeletedError:
      $ref: "#/components/schemas/ResponseError"
      example:
        code: "404_2"
        message: Document has been deleted.
```
**Screenshots**
Codeblock 1 - this is what is generated with the workaround where the object is defined for every sub-schema. On the right side you see the example values:
![image](https://user-images.githubusercontent.com/102792328/164698083-24a9d448-36c0-4ee1-8814-41a6b2e4be3d.png)

Codeblock 2 - this is where the reference is used. Everything works fine except that the example values are no longer displayed.
![image](https://user-images.githubusercontent.com/102792328/164698951-9ca84bd2-c6c9-4fbe-a637-9ca625f92e57.png)

**Additional context**
It is miserable to find a nice solution to define error responses with OpenAPI. I have researched a lot and there is not really a good way of solving the problem. This is my own solution which would theoretically be nice but doesn't work.
I don't know if the OpenAPI standard says this should not work for references. If so, it is miserable. It would definitely be nice to support it in the generated html file even if the standard doesn't necessarily say it should be supported. 

Anyways - could you please implement this or do you know any other great solution for defining error responses? 

Kind regards
Lukas

**Comment by AlexVarchuk** [comment]
@lukaswindisch Hi. Thank you for the issue. We'll fix it after releasing 2.0.

**Comment by lukaswindisch** [comment]
> @lukaswindisch Hi. Thank you for the issue. We'll fix it after releasing 2.0.

Hi @AlexVarchuk. Thank you a lot for your answer and the fix in 2.0.

**Comment by AlexVarchuk** [comment]
@lukaswindisch Hi! I check this issue again. 
`$ref` doesn't support overriding sibling property in OpenApi 3.0.2.
Try to update the version of your `Codeblock 2` to `3.1`.
I tested that and it works for me.

**Comment by lukaswindisch** [comment]
Hi @AlexVarchuk !
Thanks for your response.
I tested it with openapi version 3.1 and no it still doesn't work:
![image](https://user-images.githubusercontent.com/102792328/167135202-de06f2c6-7052-41cc-a736-01df108b1f22.png)
Here the generated examples only use "string" instead of the examples that are provided.

**Comment by AlexVarchuk** [comment]
@lukaswindisch what version of redoc do you use?

**Comment by lukaswindisch** [comment]
> @lukaswindisch what version of redoc do you use?

@AlexVarchuk Wow it actually works! I updated my version and it is generated perfectly now.
Thank you!

**Comment by AlexVarchuk** [comment]
@lukaswindisch If you'll have some additional questions feel free to open new issues.
