### ISSUE TITLE
Merge schemase with allOf

### ISSUE THREAD

**Issue by lukaswindisch** [Redocly/redoc#1976]
**Describe the bug**
When using allOf in the schema definitions, the schemas are not merged but rather not recognized.

**Expected behavior**
The schemas mentioned below allOf should be merged as it would be done in a request body.

**Minimal reproducible OpenAPI snippet(if possible)**
```yaml
openapi: "3.0.1"
info:
  title: Test
  version: "1.0.0"
servers:
  - url: https://localhost:8080/api
paths:

  /globalLogs:
    get:
      summary: Logs
      operationId: getLogs
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                title: GlobalLogsResponse
                allOf:
                  - $ref: "#/components/schemas/LogEntryCustomer"
                  - $ref: "#/components/schemas/LogEntry"

components:
  schemas:
    ResourceId:
      type: string
      format: uuid
    CustomerNumber:
      type: string
    CustomerName:
      type: string
    GenericCustomer:
        allOf:
          - $ref: "#/components/schemas/ResourceId"
          - type: object
            properties:
              userNumber:
                type: string
              customerNumber:
                $ref: "#/components/schemas/CustomerNumber"
    LogEntry:
      type: object
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        critical:
          type: boolean
    LogEntryCustomer:
      allOf:
        - $ref: "#/components/schemas/GenericCustomer"
        - $ref: "#/components/schemas/CustomerName"
```
     
**Screenshots**
![image](https://user-images.githubusercontent.com/102792328/166197685-f4b84517-9487-4a1a-a21c-5152acc8e13a.png)
![image](https://user-images.githubusercontent.com/102792328/166197749-9fd78cf4-8a4a-4cf4-956f-4a32c8dad7cd.png)

**Additional context**
On the last screenshot can be seen, that the resourceId is missing. The allOf keyword in the request body works fine but in the components/schema area it won't merge the ResourceId schema and the custom properties specified below. This is a big problem because the only way to resolve it is by copy/pasting the objects and thus having multiple instances of the same code.
Could you please solve this issue?

**Comment by AlexVarchuk** [comment]
@lukaswindisch Hi! Thank you for your request.
The incompatible warning means we can't merge allOf. 
The reason is that we don't know a direct way to merge two schemas that have different types. In your case, it is object and string.
Adding string properties as part of an object is not the right solution. It can be confusing.
To fix this behavior you can refactor `ResourceId` and `CustomerName` to object schemas. And It should work.

```yaml
ResourceId:
      type: object
      properties:
        resourceId:
          type: string
          format: uuid
CustomerName:
      type: object
      properties:
        customerName:
          type: string
```

<img width="722" alt="Screenshot 2022-05-03 at 10 27 38" src="https://user-images.githubusercontent.com/14113673/166417687-023598ef-0e32-40aa-905a-62e82eca590d.png">

**Comment by lukaswindisch** [comment]
Alright, makes sense to me. Thank you for clarification.

**Comment by AlexVarchuk** [comment]
@lukaswindisch if you'll have some questions, feel free to ask or open an issue.

**Comment by rfelgent** [comment]
hello,

how does the "bundle" task merge all "allOf"s ? is there a special config needed ?
