### ISSUE TITLE
patternProperties not being displayed

### ISSUE THREAD

**Issue by Adrian-Hirt** [Redocly/redoc#1983]
**Describe the bug**
Using redoc 2.0.0-rc.67, `patternProperties` are not rendered. 

**Expected behavior**
OpenAPI 3.1.0 supports the `patternProperties` keyword in objects to declare properties which follow a regex pattern (see https://github.com/OAI/OpenAPI-Specification/issues/687). Using the snippet below, I'd expect redoc to render it next to the normal object properties,  however these `patternProperties` are just ignored and not rendered at all.

**Minimal reproducible OpenAPI snippet(if possible)**

```yaml
openapi: 3.1.0
info:
  title: Sample API
paths:
  /users:
    get:
      responses:
        '200':
          description: A description
          content:
            application/json:
              schema:
                patternProperties:
                  ^S_:
                    type: string
                    minLength: 2
                    description: A pattern property
                properties:
                  foo:
                    type: string
```

**Screenshots**
Output from the ReDoc demo which also matches the behaviour I'm seeing locally:

![image](https://user-images.githubusercontent.com/13788379/167127002-a037d3bb-b855-4e07-92a1-5f9495ef3b3f.png)

For comparision, here's the output from the Stoplights demo:

![image](https://user-images.githubusercontent.com/13788379/167127347-42a56c2b-c99d-4a5c-a39a-e766db18077c.png)

Thanks for looking into it, and let me know if you need any other informations.

**Comment by adamaltman** [comment]
Related to https://github.com/Redocly/reference-docs/issues/743
