### ISSUE TITLE
Weird Symbols in arrays or objects

### ISSUE THREAD

**Issue by EmillkaakillmE** [Redocly/redoc#1984]
**Describe the bug**
A weird symbol appears every time there is collapsed object or array. And it desappears when object or array is expanded

**Screenshots**
![image](https://user-images.githubusercontent.com/68506597/167128803-87323a65-5adf-4bc6-89f4-2a3660466b20.png)
![image](https://user-images.githubusercontent.com/68506597/167128873-5824fa5f-9dfc-4a32-957c-734b88857ea4.png)
![image](https://user-images.githubusercontent.com/68506597/167128899-f82eb2b8-5eff-4a67-9b1e-bb38ac18f281.png)

Hope you'll let me know if it's possible to fix!
Thank you

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/redoc/issues/29, https://github.com/Redocly/redoc/issues/213 https://github.com/Redocly/redoc/issues/885

https://github.com/Redocly/redoc/issues/213#issuecomment-282761418
