### ISSUE TITLE
Dropdown to switch between multiple forms of authentication with auto rendering of code sample

### ISSUE THREAD

**Issue by MichellePeruskie** [Redocly/redoc#1998]
**Describe the problem to be solved**
We have multiple forms of authentication available to our users. The auto code sample only allows one display option if you're **not** using the try-it feature.  

**Describe the solution you'd like**
An automatic rendering of a code sample that changes with a toggle or dropdown between varying forms of authentication. Available in all languages listed. Example: We have basic auth and OAuth2.0. Rather than only displaying the first listed auth type in the code sample, have a dropdown menu near the top of each sample that allows the user to switch between authentication types. 

**Describe alternatives you've considered**
We are currently documenting each method separately in our portal. Our code samples only show basic auth. It works fine, especially since users would typically be using our code samples only to test before production, but I think it would make our site look more well-rounded if all auth types available could be easily switched out on the auto-generated code samples depending on their preference.

**Comment by AlexVarchuk** [comment]
Hi @MichellePeruskie, thank you for the issue.
Can you provide more details (mockup/screenshot) on how you imagine that?
