### ISSUE TITLE
OpenAPI Object with oneOf has no example in Payload Request sample

### ISSUE THREAD

**Issue by lucianojs** [Redocly/redoc#1999]
**Describe the bug**

When I have a OpenAPI like this:

```
openapi: 3.0.3
info:
  title: A minimal OpenAPI document
  version: 0.0.1
paths:
  /sample:
    put:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                responsavel:
                  type: object
                  properties:
                    cnpj:
                      type: string
                      title: CNPJ
                      example: '00000000000191'
                    cpf:
                      type: string
                      title: CPF
                      example: '00000000191'
                  oneOf:
                    - required:
                        - cpf
                    - required:
                        - cnpj
      responses:
        '200':
          description: Updated
```

I don't see a valid sample API request because the body example is malformed.

```
{
  "responsavel": {  }
}
```

**Expected behavior**
I'd expect the should show up as an example on the right, like:

```
{
  "responsavel": {
    "cnpj": "00000000000191",
  }
}
```
or

```
{
  "responsavel": {
    "cpf": "00000000191"
  }
}
```

**Minimal reproducible OpenAPI snippet(if possible)**

**Screenshots**
![localhost_8080_api_v1_redoc html](https://user-images.githubusercontent.com/5367385/167974179-46a3c0a7-8d36-40d1-99b1-9793760a7a47.png)

**Additional context**

**Comment by AlexVarchuk** [comment]
Hi @lucianojs. Thank for bug reporting.

I think the expected result should be like that
```json
{
  "responsavel": {
    "cnpj": "00000000000191",
    "cpf": "00000000191"
  }
}
```
The sampler does not support displaying only the required values, and its behavior is correct. In the future maybe make sense to add options to change behavior(show only required values) but not sure does really need it.

We'll fix it in the next release.

**Comment by AlexVarchuk** [comment]
Hi @lucianojs, key `not` doesn't show the key does not exist.
You can think about that as a validation check. For example:
```json
{
  "responsavel": {
    "cnpj": "00000000000191",
    "cpf": "00000000191"
  }
}
```
this JSON is valid by this JSON Schema? I think yes.
One possible solution to this problem is adding an option or custom extension which means we should show only the `required` value in examples.
But how useful is this option?

I'll try to investigate how we can cover this problem.

**Comment by lucianojs** [comment]
Hi @AlexVarchuk, you are right again.

I supposed the samples would update when I changed the oneOf options and understood the not keyword
