### ISSUE TITLE
How to use with AJV?

### ISSUE THREAD

**Issue by sdotson** [Redocly/redoc#2007]
Hi, I'm curious how to use redoc with [ajv](https://github.com/Redocly/ajv)? It looks like redoc requires a fully generated json/yaml file. How do I get from point A to point B?

**Comment by AlexVarchuk** [comment]
Hi @sdotson, thanks for the question. Can you add more information on why you need `ajv`? `ajv` is a JSON Schema validator. JSON Schema is only part of the definition OpenApi.
