### ISSUE TITLE
python sample

### ISSUE THREAD

**Issue by dma61** [Redocly/redoc#2016]
**Describe the bug**
Using the python sample: GET/{market}/candles =>

`from python_bitvavo_api.bitvavo import Bitvavo

bitvavo = Bitvavo()
response = bitvavo.candles('BTC-EUR', '1m', {})
print (response)
for candle in response ['candles']:
  print('Timestamp', candle[0], ' open', candle[1], ' high', candle[2], ' low', candle[3], ' close', candle[4], ' volume', candle[5])`

We got the message: **TypeError: list indices must be integers or slices, not str**

**Expected behavior**
It should give something like:
[
  [
    1538784000000,
    "4999",
    "5012",
    "4999",
    "5012",
    "0.45"
  ]
]

What should be changed?

**Comment by AlexVarchuk** [comment]
If it doesn't work please add the full definition for reproducing and reopen it. Thanks
