### ISSUE TITLE
Lost functionality over weekend (worked on Friday) `oneOf` names not working and lost drop examples

### ISSUE THREAD

**Issue by cleverly87** [Redocly/redoc#2017]
**Describe the bug**
oneOf functionality not displaying the tag names of the correct schema that it references to. 
Also the drop down JSON examples that had been hard coded are no long available in the third column.

**Expected behavior**

**Minimal reproducible OpenAPI snippet(if possible)**
I will copy a trail of the links as the API doc is huge.

PATH
"/localSolutions/GB/identitysearch": {
      "post": {
        "tags": [
          "GB Consumers and AML"
        ],
        "summary": "Submits a GB Consumer or AML Search",
        "description": "Submits a GB Consumer or AML depnding on the Product provided. Validates criteria for each individual search before submitting, and may return a list of error strings instead." ,
        "parameters": [
          {
            "$ref": "#/components/parameters/authToken"
          }
        ],
        "requestBody": {
            "$ref": "#/components/requestBodies/Identity" 
                              },
        

  "requestBodies": {
      "Identity": {
        "description": "Select the `products` tab for the request body for each of the products `AML` and `Consumer`",
          "content": {
              "application/json": {
                  "schema": {
                      "allOf": [
                        {
                         "description": "Identity Search",
                              "title": "Identity"
                        },
                        {
                          "$ref": "#/components/schemas/Connect.GBConsumer"
                        }
                      ]
      }
              
    }
  }               
 }
},

 "Connect.GBConsumer": {
        "type":	"object",       
          "description":	"Select product type for object parameters and example body.\n\n Options for an `AML Search` or `Consumer Search`",
               "oneOf": [
                {
                  "$ref" :	"#/components/schemas/AMLSearch"
                },
                {
                   "$ref": "#/components/schemas/consumerSearch"
                }
            ]        
          },      

      "AMLSearch": {
        "description":	"Search parameters for AML product",
        "properties":	{   
          "UniqueId":	{
            "type":	"string",
            "nullable":	true
          },
          "common": {
            "description": "Person search criteria",	
            "allOf":	[
            {
              "$ref":	"#/components/schemas/Connect.Identity.CommonSearchCriteria"
            }                      
          ]  
        }, 
          "consumer": {
            "description": "Second person search option",
            "$ref": "#/components/schemas/Connect.Identity.ConsumerSearchCriteria"
        },      
          "iDAml":	{
            "description":	"Reference to bank account detail search",
            "allOf":	[
              {
              "$ref": "#/components/schemas/Connect.Identity.AmlSearchCriteria"
            }
            ]            
        },
          "products": {
              "type": "string",
              "description": "Enter `AML` for this product search",
              "example": "AML"
          }
        },        
        "example": {
          "common": {
            "person": {
                "currentName": {
                    "title": "",
                    "forename": "John",
                    "otherNames": "",
                    "surname": "Murphy",
                    "suffix": ""
                },
                "dateOfBirth": "1974-07-07",
                "gender": "",
                "addresses": {
                    "current": {
                        "buildingNo": "",
                        "buildingName": "Stadium Plaza",
                        "street": "Wood Street",
                        "city": "Cardiff",
                        "postCode": "CF10 1LA"
                    }
                }
            },
            "reference": ""
        },
          "idAml": {
            "landlineNumber": "",
            "exDirectory": false,
            "sortCode": "",
            "bankAccountNumber": ""
      },
      "products": [
          "Aml"
      ]
        }
      },
**Screenshots**
The oneOf Tag should look like this 
![image](https://user-images.githubusercontent.com/63611461/169768093-5882b089-197c-487d-9b1c-de7e1a3ef222.png)

But now looks like this:
![image](https://user-images.githubusercontent.com/63611461/169768262-ab9530f4-8667-4395-8c30-4a6956f70342.png)

The JSON examples should have this drop down:
![image](https://user-images.githubusercontent.com/63611461/169768385-37a23b77-0b17-47ca-ab19-06b358ead160.png)

Now they have completely gone
![image](https://user-images.githubusercontent.com/63611461/169768461-c0b21d5f-4831-46d2-af8e-abf337ee287e.png)

**Additional context**
I notice there was an update to the `oneOf` function on friday by one of the devs - please bare in mind im not fully coding experienced so be gentle and try to keep the sarcasm to a minimum.

@anastasiia-developer This something to do with your update Friday?

**Comment by RomanHotsiy** [comment]
We're actively working on a fix right now. Thanks for reporting.

**Comment by AlexVarchuk** [comment]
related to https://github.com/Redocly/redoc/pull/1939

**Comment by cleverly87** [comment]
Just an update to myside for you to know because I don't know if you have done anything: 

I have removed the 'GB consumer' component and referenced the 'oneOf' directly in the request body. 

Not sure if this what caused the changed (even thought it worked on Friday) but perhaps overwriting rules in the stack?) here's how it looks now: 
![image](https://user-images.githubusercontent.com/63611461/169798972-a210d072-68a5-47f2-b39d-8fd4aae31695.png)

and the example piece:
![image](https://user-images.githubusercontent.com/63611461/169799038-cf0cc413-33bb-4e74-83fe-de69e801032d.png)

As it should do, and it is now discriminating the JSON examples as per selection.

**Comment by AlexVarchuk** [comment]
@cleverly87 Hi. We are going to make release it next week.
