### ISSUE TITLE
HTTP request from Kubernetes pod results in Failed to connect: Connection refused

### ISSUE THREAD

**Issue by sshtel** [Redocly/redoc#2019]
**Describe the bug**

Deployed redocly server within k8s
within other pod, I requested HTTP to the server pod where the Redocly is running

```
curl: (7) Failed to connect to 10.8.39.47 port 8080 after 0 ms: Connection refused
```

If I port-forward the Redocly server and access it from my local web browser, it is working fine.
```
kubectl port-forward  service/redocly 8080:8080
```

This was working at v0.12.1
But it is not working in latest version (maybe it started from earlier version)

**Expected behavior**
Redocly server should be accessible from other POD within K8s cluster

**Additional context**
https://stackoverflow.com/questions/56051884/port-forward-is-working-but-not-able-to-access-the-port-from-other-pods-in-the

Refer to this. Maybe this is related to host binding issue.

**Comment by RomanHotsiy** [comment]
We have 0 experience in k8s. We would appreciate if you could help us understand what to fix. Thanks.

**Comment by lornajane** [comment]
We didn't get any more information on this one and it's quite old, so I'll close it. Please update to our newer tools and open a new issue if there's something we could still improve.
