### ISSUE TITLE
Redocly-CLI Question？

### ISSUE THREAD

**Issue by Luo-Yuwen** [Redocly/redoc#2024]
We have a issue about the product "Redocly-CLI".
Is there any possibility that "Redocly-CLI" will conflict with Bootstrap 5.0?
If so, could you tell us how to deal with it?
Or which version is it compatible with?
Thank you.

**Comment by RomanHotsiy** [comment]
@Luo-Yuwen I think you confused this project with redoc-cli here: https://github.com/Redocly/redoc

I moved the issue.
