### ISSUE TITLE
Error callback not called if specs are not found

### ISSUE THREAD

**Issue by meden** [Redocly/redoc#2025]
**Describe the bug**
Error callback not called if specs are not found.

**Expected behavior**
The error callback being called even in this case, so to be able to recover.

**Minimal reproducible OpenAPI snippet(if possible)**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/824351/170670468-6e929895-0597-48d3-bdfc-13928ff761d8.png)

**Additional context**
I faced this problem by using a minimal Redoc HTML file, initializing Redoc manually. If the spec URL is wrong, I get a stack trace, and the component dies.

I'd like to be able to re-init the component with the right URL (I'm using a select to switch specs).

I think the issue is because of an uncaught error in a promise, preventing (or better said, not triggring) the callback execution.

![image](https://user-images.githubusercontent.com/824351/170670925-21ec15c1-6a44-4fc5-bc79-8c96e20044a8.png)

Maybe this is related to #1686, or #690 (similar behavior, but different cause).

**Comment by AlexVarchuk** [comment]
@meden @meden Hi! thanks for bug reporting.
We'll fix that.
