### ISSUE TITLE
minProperties and maxProperties support for additionalProperties with dynamic propertynames (no fixed property names) in redoc 

### ISSUE THREAD

**Issue by ilanuk** [Redocly/redoc#2037]
minProperties and maxProperties under additionalProperties are not supported when the properties are random dynamic strings

Like minItems and maxItems in the array, I want the minProperties and maxProperties are also supported by redoc when the properties are just strings ( no fixed names, the property names are dynamic strings, just minProperties of for example 3 and maxProperties of 5)

**Describe alternatives you've considered**
Right now the redoc is not  displaying the minProperties and maxProperies in case of additionalProperties like OpenAPI 3.0.  It is causing confusion to the user as the specification is missing the details.  Alternatively we have a swagger UI where this OpenAPI 3.0 is displayed correctly whereas the corresponding redoc is not showing it correctly.

Example:
`
  ```
{
    "type": "array",
    "minItems": 1,
    "maxItems": 3,
    "items": {
	  {
	    "type": "object",
	    "properties": {},
	    "additionalProperties":{ 
		  "type": "string",
		  "minProperties": 3,
		  "maxProperties": 5
	     }
	  }
    }
  }

````

**Comment by anastasiia-developer** [comment]
Hi
We supported the minProperties and maxProperies
I tried your case and it works

![Screenshot 2022-06-02 at 14 13 09](https://user-images.githubusercontent.com/28001084/171617329-b289d289-9879-420e-a490-cb4a07e7651c.png)
