### ISSUE TITLE
Headers in tags are displayed twice

### ISSUE THREAD

**Issue by atruskot** [Redocly/redoc#2041]
**Describe the bug**
This issue is a duplicate of issue 1150 which was closed as fixed.  The `description` of a `tag` renders incorrectly. Headers are duplicated. Only the first header is used as an anchor for the sidebar.

This issue isn't present in `redoc-cli@0.13.3` but is present in `redoc-cli@0.13.5` and later. 

**Expected behavior**
See the screenshot from `0.13.3`.  

**Minimal reproducible OpenAPI snippet(if possible)**
A snippet I used for the screenshots: 
```
openapi: 3.1.0
servers:
  - url: http://server.com
    description: the server
info:
  title: Issue
  version: 1.0.0
  description: minimum spec
tags: 
  - name: Example
    description: >-
      This section describes things.
    
    
      ## A 
    
      A text.
    
    
      <SchemaDefinition schemaRef="#/components/schemas/model"/>
    
    
      ## B 
    
      B text.
    
    
      <SchemaDefinition schemaRef="#/components/schemas/model"/>
    
    
      ## C 
    
      C text.
    

      <SchemaDefinition schemaRef="#/components/schemas/model"/> 
components:
  schemas:
    model:
      type: object
      properties:
        value:
          type: string
          description: a value
          pattern: >-
            [ \r\n\t\S]+
```

**Screenshots**
`redoc-cli@0.13.3` (Works as expected)
![image](https://user-images.githubusercontent.com/95640878/171759139-483e6452-e166-4263-9182-3338aa21318d.png)

`redoc-cli@0.13.5` (Duplicated headers)
![image](https://user-images.githubusercontent.com/95640878/171759176-d9684511-79fb-411d-9b7a-0ca554234cfd.png)

**Comment by nickdnk** [comment]
Just ran into this as well. Any news here?

**Comment by AlexVarchuk** [comment]
already fixed here https://github.com/Redocly/redoc/pull/2119
