### ISSUE TITLE
Siblings of $ref do not override the referenced object

### ISSUE THREAD

**Issue by atruskot** [Redocly/redoc#2042]
**Describe the bug**
Note: this is a duplicate of https://github.com/Redocly/redoc/issues/1727.  I'm not sure if this community prefers to reopen closed issues or create a new issue after closing the original. Feel free to close this issue if the preference is to reopen the original.

I'm still able to reproduce this issue in `redoc-cli@0.13.16`. Seeing the base description rather than the sibling/overridden one. Will see the sibling description if the base has no description. 

Worth noting, the issue isn't specific to description, any base property will render if it exists. So base examples can't be overridden either, for example. I'm not sure if the expectation is for the derived object to be arbitrarily override any base property or if Redoc is expected to only override specific properties (such as `description`). 

**Expected behavior**
When there are siblings of $ref, it is expected that the siblings override any properties that are also founded in the referenced object. 

**Minimal reproducible OpenAPI snippet(if possible)**
Described in https://github.com/Redocly/redoc/issues/1727.

**Comment by AlexVarchuk** [comment]
The 3.1 include JSON Schema draft 2020-12 which allow all keywords siblings inside schema object. But the sibling keywords do not override the keywords in the referenced schema, they add to them. [Link to issue ](https://github.com/OAI/OpenAPI-Specification/issues/2744).
