### ISSUE TITLE
Array of models not showing expansion in UI

### ISSUE THREAD

**Issue by stephenliberty** [Redocly/redoc#2044]
**Describe the bug**

When an model property is array of models, the documentation doesn't expand to show the model

**Expected behavior**

I would expect that the documentation generated would treat the array of models in the same way as other singular models.

**Minimal reproducible OpenAPI snippet(if possible)**

I tried to trim this out of a much, much larger yaml doc

```yaml
components:
  schemas:
    BasicPaginated:
      properties:
        nextPage:
          type: string
        previousPage:
          type: string
    SalesOrderResponse:
      allOf:
        - $ref: '#/components/schemas/BasicPaginated'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/SalesOrderModel'
    SalesOrderModel:
      properties:
        order:
          $ref: '#/components/schemas/SalesOrder'
    SalesOrder:
      properties:
         salesOrderLines:
          items:
            $ref: '#/components/schemas/SalesOrderLine'
          type: array
          x-go-name: SalesOrderLines
    SalesOrderLine:
      properties:
        unitPrice:
          format: double
          type: number
          x-go-name: UnitPrice
```

The entire document is, per https://editor.swagger.io/, valid openapi 3.0.0, and the UI there DOES show the 'sales order line' as an array of sales order line 

**Screenshots**
![image](https://user-images.githubusercontent.com/1056391/172423832-68c53c75-cf09-478b-83f3-e50e3b0f115b.png)

![image](https://user-images.githubusercontent.com/1056391/172426772-28e8ad18-1ff0-453b-a405-4d43d026de2a.png)

**Additional context**

**Comment by AlexVarchuk** [comment]
We had something similar at [#2034](https://github.com/Redocly/redoc/issues/2034).
I cannot reproduce it now. Please, make sure you are using the latest version of Redoc.
If the bug is still produced, provide a more extended OpenApi snippet for reproducing.

**Comment by stephenliberty** [comment]
Confirmed fixed with latest version. Thank you @AlexVarchuk .
