### ISSUE TITLE
Empty Schema Object in content response not detected

### ISSUE THREAD

**Issue by roukmoute** [Redocly/redoc#2046]
**Describe the bug**
Here it is an example:

```yml
post:
  responses:
    '422':
      description: Unprocessable Entity.
      content:
        'application/json':
          schema:
```

**Expected behavior**
It should return an error.

Swagger proposes `should be object` and stoplight studio proposes `"schema" property type must be object.`

**Additional context**

The correct empty fix for that should be:

```yml
post:
  responses:
    '422':
      description: Unprocessable Entity.
      content:
        'application/json': {}
```

It comes from: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#operation-object-example

**Comment by roukmoute** [comment]
Ok visibly it is already implemented but I think there is some "miss".

With that example:

```yml
post:
  operationId: foobar
  tags:
    - Foo
  summary: Create a foo bar.
  description: Create a foo bar.
  responses:
    '201':
      description: Foo bar successful.
      content:
        'application/json': {}
    '403':
      description: Access Denied.
      content:
        'application/json':
          schema:
    '404':
      description: Not found
      content:
        'application/json':
          schema:

```

I've got only one error:
```sh
doc/api/foo/bar.yaml:
  16:11  error    spec  Expected type `Schema` (object) but got `null`
```

**Comment by AlexVarchuk** [comment]
Hi @roukmoute, thank you for your request.
`redoc` handles this issue by displaying `Schema is not provided`. I think it is related to [redocly-cli](https://github.com/Redocly/redocly-cli), don't you?

**Comment by roukmoute** [comment]
Oh yes!

I'm recreating this issue on the good repository, sorry.
