### ISSUE TITLE
Mis-nesting of aria roles on sidebar navigation

### ISSUE THREAD

**Issue by ryan-garrett** [Redocly/redoc#2048]
The sidebar navigation uses `menuItem` but without the correct grouping parent role, instead using a `navigation` role.
The use of the `navigation` role on the `ul` also changes the role of that element from an implicit list to an explicit non-list, so rendering the implicit child list items without a correctly named parent.

<img width="705" alt="Screenshot 2022-06-10 at 14 49 35" src="https://user-images.githubusercontent.com/25553660/173080025-685a765d-3e7d-4f70-96f2-0c94618b36d7.png">

**Comment by AlexVarchuk** [comment]
Hi @ryan-garrett, thank you for the issue.
Can you provide some OpenApi snippett for reproducing?

**Comment by AlexVarchuk** [comment]
@ryan-garrett Please check our  [contribution guide](https://github.com/Redocly/redoc/blob/master/.github/CONTRIBUTING.md). And if you'll have some questions or improvements ideas about it feel free to write.

**Comment by ryan-garrett** [comment]
@AlexVarchuk Sorry, forked and created a PR: https://github.com/Redocly/redoc/pull/2049

**Comment by ryan-garrett** [comment]
Sorry @AlexVarchuk, my git messed up so I redone the pull request: https://github.com/Redocly/redoc/pull/2050

**Comment by AlexVarchuk** [comment]
@ryan-garrett Thank you for your contribution. 🙌  Merged.
