### ISSUE TITLE
Get spec-url locally from different project

### ISSUE THREAD

**Issue by testgagaga** [Redocly/redoc#2052]
Hi!

Is it possible to point a spec-url to a json file that is present in a different folder/project locally?

I tried doing this: 

```
<redoc spec-url='file:///Deskptop/spec.json'></redoc>
<script src="node_modules/redoc/bundles/redoc.standalone.js"> </script>
```

but get this error:
![image](https://user-images.githubusercontent.com/37312976/173390215-3fb49dfd-c6b9-44cc-8c46-52a2a439914c.png)

Please let me know how to fix this issue, thanks!

**Comment by AlexVarchuk** [comment]
Hi @testgagaga, thank you for the question. 
I think your local server doesn't have access to the file. You can create a symlink to the file or try to use CLI.

```bash
npx @redocly/cli@latest preview-docs ~/Desktop/spec.yaml
```
or with your template
```bash
npx redoc-cli serve ~/Desktop/spec.yaml -t cli/template.hbs
```

**Comment by RomanHotsiy** [comment]
Local files do not work due to same-origin policy restrictions: https://github.com/Redocly/redoc/issues/149

**Comment by arLevi** [comment]
In my case it's behind a proxy ... I can't use a sym-link, and forcing users to download a 3rd party from a CDN w/o a verification has, it's a bit not secure ...

```
<script src="https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js"> </script>
```

I think, that this row:
```
<redoc spec-url='/api/v2/swagger.json' suppressWarnings=true></redoc>
```
Should take the URL it came from vs using a relative path to `swagger.json` file ...
