### ISSUE TITLE
redoc-cli options page broken

### ISSUE THREAD

**Issue by testgagaga** [Redocly/redoc#2053]
When going to the page:
https://redocly.com/docs/redoc/deployment/cli/

And clicking on the redoc options link:
![image](https://user-images.githubusercontent.com/37312976/173585322-fd9ff801-4799-4d05-bec7-89db6ca9afc4.png)

It redirects to a broken page:

![image](https://user-images.githubusercontent.com/37312976/173585433-5b0dbd74-9646-4ce9-88e6-bfb6eed85f96.png)

**Comment by AlexVarchuk** [comment]
Hi @testgagaga, thank you for the issue. We'll fix it.

**Comment by AlexVarchuk** [comment]
@testgagaga You can read about options [functionality options](https://redocly.com/docs/api-reference-docs/configuration/functionality) or [theme options](https://redocly.com/docs/api-reference-docs/configuration/theming) pages.
