### ISSUE TITLE
Injection security definitions is not working

### ISSUE THREAD

**Issue by TheM1984** [Redocly/redoc#2054]
The `<!-- ReDoc-Inject: <security-definitions> -->` is no longer injecting the security definitions.

Currently we use the `noAutoAuth` option and inject the security definitions at the place we like it to be.

This is all done according to the readme: 
https://github.com/Redocly/redoc#security-definition-location
https://github.com/Redocly/redoc/blob/v2.0.0-rc.72/docs/security-definitions-injection.md

**Expected behavior**
The security definitions are included as stated.

**Minimal reproducible OpenAPI snippet(if possible)**
I extracted some minimal openapi where you can see the issue.

Within `src/components/tags.yaml` the injection is being performed.
[src.zip](https://github.com/Redocly/redoc/files/8909271/src.zip)

**Screenshots**
"redoc-cli": "0.13.10" shows it correctly:
![image](https://user-images.githubusercontent.com/13640063/173822977-ca3438db-fe5c-4d4a-951a-3e1aa5fd4c89.png)

"redoc-cli": "0.13.16" doesn't show it at the given location
![image](https://user-images.githubusercontent.com/13640063/173823187-768b8121-abb7-4b13-8710-2d619c91d33e.png)

**Additional context**
My guess that this has to do with the new feature where the noAutoAuth  is deprecated.

And I guess the security definitions are now shown with every endpoint, however I do feel that is a lot of duplicate content. And without the security definitions shown in the global text, there is no way of linking to it a specific authentication.

**Comment by AlexVarchuk** [comment]
Hi @TheM1984, thank you for your issue. 
You can add to `Authentication` -> `description`  add redoc tag.
```
<SecurityDefinitions />
```
It adds security to your tag.


After that, we can add `hideSecuritySection: true` options. It disables showing auth section in every endpoint.
<img width="954" alt="Screenshot 2022-06-16 at 12 04 11" src="https://user-images.githubusercontent.com/14113673/174035455-684b9c56-a597-4f3a-9591-de42a7cec028.png">
<img width="884" alt="Screenshot 2022-06-16 at 12 04 58" src="https://user-images.githubusercontent.com/14113673/174035462-1948ec4b-3a5e-428a-9d8b-7b679cd9cf50.png">

**Comment by ArthurFlageul** [comment]
I have the same problem, expect I simply use the Redoc CLI with `preview-docs`. My swagger file (not OAS3) does contain my security definition. I worked perfectly until today 🙂

**Comment by AlexVarchuk** [comment]
Hi @ArthurFlageul, we moved the security section to Operations. To use the old behavior, check my message above.

**Comment by AlexVarchuk** [comment]
We return the old variant of injecting security definition for better backward compatibility.
```
<!-- ReDoc-Inject: <security-definitions> -->
```

**Comment by TheM1984** [comment]
> Hi @TheM1984, thank you for your issue. You can add to `Authentication` -> `description` add redoc tag.
> 
> ```
> <SecurityDefinitions />
> ```
> 
> It adds security to your tag.
> 
> After that, we can add `hideSecuritySection: true` options. It disables showing auth section in every endpoint. <img alt="Screenshot 2022-06-16 at 12 04 11" width="954" src="https://user-images.githubusercontent.com/14113673/174035455-684b9c56-a597-4f3a-9591-de42a7cec028.png"> <img alt="Screenshot 2022-06-16 at 12 04 58" width="884" src="https://user-images.githubusercontent.com/14113673/174035462-1948ec4b-3a5e-428a-9d8b-7b679cd9cf50.png">
> 
> Please verify it.

I can hereby confirm that your solution works.

Only 1 note that with `hideSecuritySection: true` the security section in the endpoints is removed completely, so it is not completely backwards compatible with the "old" usage.

However we now have the security section separate and can link to it in other texts, so we are happy now :).

**Comment by sl-nigelalmada** [comment]
Thanks for restoring the previous behaviour

I would suggest for next time this kind of changes are made, to include it into a dedicated section of the release's changelog

**Comment by AlexVarchuk** [comment]
We added it to the general [changelog](https://github.com/Redocly/redoc/releases/tag/v2.0.0-rc.74). 

Sorry, but I am not fully understood the dedicated section. Can you share the link with an example? It can be helpful for us.

**Comment by sl-nigelalmada** [comment]
I am talking about the orignal change

For me the original change was more akin to a "breaking" one. I understand that breaking change are perfectly acceptable in a rc release, no worries about that

I don't know if the change was introduced with the `2.0.0-rc71` release, but the included changelog line 

```
add hideSecuritySection option allowing to disable the Security panel (https://github.com/Redocly/redoc/issues/2027) ([49cc11d](https://github.com/Redocly/redoc/commit/49cc11d91795653ca870e9276a1e0cd617964e25))
``` 

was probably not enough (unless the change was involuntary and it was just a regression)

I suggest to have in this case to either

-  have a "Removed" section if it's considered as a feature removal. 
-  have the complete explanations on the impact of the change (need to add `<SecurityDefinitions />` to the doc to have the previous behaviour)

I usually use the [Keep A changelog](https://keepachangelog.com/en/1.0.0/) format because it provides better granularity in the changes log 😀
