### ISSUE TITLE
Non-JSON response examples are syntax highlighted

### ISSUE THREAD

**Issue by fgabolde** [Redocly/redoc#2056]
**Describe the bug**
Response examples are syntax highlighted as (probably) JSON even when the Content-Type is defined as a different MIME type. This is Redoc v2.0.0-rc.30, as well as the latest release.

**Expected behavior**
Response examples are syntax highlighted as JSON only if the MIME type matches (e.g. `application/json`).

**Minimal reproducible OpenAPI snippet(if possible)**
```yaml
responses:
  "200":
    content:
      text/csv:
        example: |
          ,,,,,,56,80,2022-06-20T13:39:38Z
          2011,attack of the clone,Include1,tea,1.00000,100.00000,,,
```

**Screenshots**
![redoc-response-example-syntax-highlighting](https://user-images.githubusercontent.com/912215/174617736-b244e43c-2a0d-4225-8a85-c48d3312eaea.png)

**Additional context**
It'd be awesome to have appropriate syntax highlighting for lots of different possible content types; but at the very least, responses that are explicitly documented as not being JSON should not be highlighted as JSON. When the content type is not handled, Redoc should fall back to displaying the example as plain text.

**Comment by AlexVarchuk** [comment]
merged. It is included in the next release.
