### ISSUE TITLE
error ?

### ISSUE THREAD

**Issue by huqiuyun** [Redocly/redoc#2057]
<img width="764" alt="WX20220620-223003@2x" src="https://user-images.githubusercontent.com/3490039/174624423-948ac54e-37fb-4db8-b55e-14f9e5296ee4.png">

**Comment by AlexVarchuk** [comment]
Hi @huqiuyun. What HTTP code do you have in your definition? Redoc allows a range (100; 599) of codes?

**Comment by huqiuyun** [comment]
I don't know a code for business， why it belong to http code?   is the two code need to same?
a code for business only allows a range 100-599?
