### ISSUE TITLE
How do I introduce OpenAPI in MarkDown

### ISSUE THREAD

**Issue by test-bv-1** [Redocly/redoc#2058]
![image](https://user-images.githubusercontent.com/106662312/174765409-859f5f53-d794-4d17-8007-48535a37b79e.png)
How do I introduce OpenAPI in MarkDown so that text can be added to the right

**Comment by AlexVarchuk** [comment]
Hi @test-bv-1. Thank you for your question.  Redoc doesn't allow adding markdown to the right column. The right column includes request details.
