### ISSUE TITLE
enum values not intersected in oneOf+properties or oneOf inside allOf

### ISSUE THREAD

**Issue by liskin** [Redocly/redoc#2059]
**Describe the bug**
In the following two examples, a generic StringField enum property `"field"` is further restricted in the `oneOf` branches to be of only one specific enum value. In the first example, this is done by "factoring" the generic properties out of `oneOf`, in the second there is an explicit `allOf`. Both examples, however, render the possible enum values for the `"field"` property as a union/concatenation of the common properties and the selected `oneOf` variant instead of an intersection, resulting in something like `field … Enum: "A" "A" "B" "C"`. The first example actually rendered correctly (`field … Enum: "A"`) with redoc 2.0.0-rc.69, but this may be accidental, as the second (`allOf`) example rendered as `field … Enum: "A" "B" "C"`.

Also note that the examples are incorrect (`"field": "A"` must have `"A…"` in `"values": […]`) everywhere except for openapi-allof.yaml rendered with redoc 2.0.0-rc.70+.

**Minimal reproducible OpenAPI snippet(if possible)**

openapi-factored.yaml:
```
openapi: 3.0.0
info: { version: 1.0.0, title: Sample API }
paths:
  /list:
    post:
      requestBody: { content: { application/json: { schema: { $ref: '#/components/schemas/StringFilter' } } } }
      responses: { '200': {} }
components:
  schemas:
    StringField: { type: string, title: StringField, enum: [A, B, C] }
    FieldA: { type: string, title: FieldA, enum: [A1, A2, A3] }
    FieldB: { type: string, title: FieldB, enum: [B1, B2, B3] }
    FieldC: { type: string, title: FieldC, enum: [C1, C2, C3] }
    StringFilter:
      title: StringFilter
      type: object
      properties:
        type: { type: string, enum: [STRING] }
        field: { $ref: '#/components/schemas/StringField' }
      required: [type, field, values]
      oneOf:
        - properties:
            field: { type: string, enum: [A] }
            values: { type: array, items: { $ref: '#/components/schemas/FieldA' } }
        - properties:
            field: { type: string, enum: [B] }
            values: { type: array, items: { $ref: '#/components/schemas/FieldB' } }
        - properties:
            field: { type: string, enum: [C] }
            values: { type: array, items: { $ref: '#/components/schemas/FieldC' } }
```

openapi-allof.yaml:
```
openapi: 3.0.0
info: { version: 1.0.0, title: Sample API }
paths:
  /list:
    post:
      requestBody: { content: { application/json: { schema: { $ref: '#/components/schemas/StringFilter' } } } }
      responses: { '200': {} }
components:
  schemas:
    StringField: { type: string, title: StringField, enum: [A, B, C] }
    FieldA: { type: string, title: FieldA, enum: [A1, A2, A3] }
    FieldB: { type: string, title: FieldB, enum: [B1, B2, B3] }
    FieldC: { type: string, title: FieldC, enum: [C1, C2, C3] }
    StringFilter:
      title: StringFilter
      type: object
      allOf:
        - properties:
            type: { type: string, enum: [STRING] }
            field: { $ref: '#/components/schemas/StringField' }
          required: [type, field, values]
        - oneOf:
            - properties:
                field: { type: string, enum: [A] }
                values: { type: array, items: { $ref: '#/components/schemas/FieldA' } }
            - properties:
                field: { type: string, enum: [B] }
                values: { type: array, items: { $ref: '#/components/schemas/FieldB' } }
            - properties:
                field: { type: string, enum: [C] }
                values: { type: array, items: { $ref: '#/components/schemas/FieldC' } }
```

**Screenshots**
openapi-factored rendered by redoc-cli 0.13.13 (redoc 2.0.0-rc.69) - correct "field" docs, incorrect example:
![openapi-factored-0.13.13](https://user-images.githubusercontent.com/300342/174907482-a5adb92e-f02f-49ec-9aa8-f94de6d29ff6.png)
openapi-factored rendered by redoc-cli 0.13.14 (redoc 2.0.0-rc.70) - incorrect "field" docs, incorrect example:
![openapi-factored-0.13.14](https://user-images.githubusercontent.com/300342/174907483-f833839b-8820-4a72-be56-1054a7622688.png)
openapi-allof rendered by redoc-cli 0.13.13 (redoc 2.0.0-rc.69) - incorrect "field" docs, incorrect example:
![openapi-allof-0.13.13](https://user-images.githubusercontent.com/300342/174907475-c93a7e77-9004-4134-8bd4-8cc909297f8d.png)
openapi-allof rendered by redoc-cli 0.13.14 (redoc 2.0.0-rc.70) - incorrect "field" docs, correct example:
![openapi-allof-0.13.14](https://user-images.githubusercontent.com/300342/174907481-1f0d81f8-09e5-40ed-b4f1-97fcfa3c41cd.png)

Note that redoc-cli 0.13.16 (redoc 2.0.0-rc.72) produces the same output as redoc-cli 0.13.14 (redoc 2.0.0-rc.70).

**Expected behavior**
I'd expect the properties documentation (left half) of both openapi-factored and openapi-allof to look like in openapi-factored rendered by redoc-cli 0.13.13 (redoc 2.0.0-rc.69), that is `field … Enum: "A"`:
![openapi-factored-0.13.13](https://user-images.githubusercontent.com/300342/174907482-a5adb92e-f02f-49ec-9aa8-f94de6d29ff6.png)
I'd also expect the example (right half) of both inputs to look like in openapi-allof rendered by redoc-cli 0.13.14 (redoc 2.0.0-rc.70), i.e. `"field" matching the "values"`:
![openapi-allof-0.13.14](https://user-images.githubusercontent.com/300342/174907481-1f0d81f8-09e5-40ed-b4f1-97fcfa3c41cd.png)

**Comment by AlexVarchuk** [comment]
Hi @liskin, thank you for your issue.
I don't completely agree with you. `oneOf` doesn't mean merge or sub-plural of enum in this case.
`oneOf` means some data (request/response) must be valid against exactly one of the given subschemas.
Varian with enum: [A, B, C] is correct too. And if enum equals A valid for both schemas. 

Here is the specification https://json-schema.org/understanding-json-schema/reference/combining.html#oneof.

Duplication is bad behavior and we must fix that(PR in progress). Also, we should fix examples.

If you have some thinks or questions, feel free to discuss them.

**Comment by AlexVarchuk** [comment]
@liskin , thank you for your response. I'll try to explain the idea.
For example, you have the definition:
```yaml
  StringFilter:
      title: StringFilter
      type: object
      properties:
        type: { type: string, enum: [STRING] }
        field: { type: string, title: StringField, enum: [D, E, F] }
      required: [type, field, values]
      oneOf:
        - properties:
            field: { type: string, enum: [A] }
            values: { type: array, items: { type: string, title: FieldA, enum: [A1, A2, A3] } }
        - properties:
            field: { type: string, enum: [B] }
            values: { type: array, items: { type: string, title: FieldB, enum: [B1, B2, B3] } }
        - properties:
            field: { type: string, enum: [C] }
            values: { type: array, items: { type: string, title: FieldC, enum: [C1, C2, C3] } }
```
What did you expect here?
I think we should display `[D,E,F]+oneOf`
<img width="881" alt="Screenshot 2022-07-20 at 20 58 00" src="https://user-images.githubusercontent.com/14113673/180050554-04b9359f-5815-466d-bead-1fc0501968fb.png">

If you want limits the` field` value you should remove `field` from properties:
```yaml
...
  StringFilter:
      title: StringFilter
      type: object
      properties:
        type: { type: string, enum: [STRING] }
      required: [type, field, values]
      oneOf:
        - properties:
            field: { type: string, enum: [A] }
            values: { type: array, items: { type: string, title: FieldA, enum: [A1, A2, A3] } }
        - properties:
            field: { type: string, enum: [B] }
            values: { type: array, items: { type: string, title: FieldB, enum: [B1, B2, B3] } }
        - properties:
            field: { type: string, enum: [C] }
            values: { type: array, items: { type: string, title: FieldC, enum: [C1, C2, C3] } }
``` 
and the result will show as you expected and with the correct example:
<img width="1512" alt="Screenshot 2022-07-20 at 21 08 32" src="https://user-images.githubusercontent.com/14113673/180052361-4302a4c8-f599-473e-a9a3-9e3cc6a1b3af.png">

**Comment by liskin** [comment]
Sorry for the late reply, I've been busy moving home the past few days.

> What did you expect here?

Let me backtrack a bit. In the `oneOf` nested in `allOf` example, I definitely expected that if one branch of the `allOf` allows all of A, B and C, but the other branch (the one with `oneOf`) restricts it further, I'd see the intersection of the two, i.e. the restricted version (just A, or just B, or just C, but not all of them). I hope we can agree that's the semantics of `allOf`—intersection of the schemas. But even this doesn't work, the `allOf` example still shows A/B/C as possible values for `field`.

Now with the other example, the semantics are less obvious. The only mention in the docs that hints to what should happen if an object has both `properties` and `oneOf`/`anyOf`/`allOf` is this one here: <https://json-schema.org/understanding-json-schema/reference/conditionals.html#implication>. The example there has a definition of `restaurantType` in `properties` which is then further restricted to disallow the `sit-down` value in one branch of the `anyOf`. So that seems to suggest that there is an implicit `allOf` doing a schema conjunction/intersection between `properties` and the `oneOf`/`anyOf`/`allOf`. Am I interpreting this wrong?
