### ISSUE TITLE
Search is broken in static redoc page 

### ISSUE THREAD

**Issue by mulder999** [Redocly/redoc#2076]
**Describe the bug**
1. Generate static page using latest redoc-cli
2. Open the static page generated (irrelevant if as a local file or server hosted).
3. Start typing 3 characters or more in search field (for eg: `jso`)
4. **BUG**: The whole page turns into a complete blank screen instead of displaying any results

**Expected behavior**
Get a preview of entry points matching the search criteria

**Remark**
With static page, the search behave as expected only when no result at all exists.

**Comment by brettgoss** [comment]
I am encountering this as well with the latest redoc-cli. Downgrading to 0.12.3 resolved the issue, though there may be working versions in between 0.12.3 and 0.13.16 - I just jumped down to the last minor version.

**Comment by brettgoss** [comment]
@AlexVarchuk Just did some testing and 0.13.10 works whereas 0.13.11 and any version after does not.

**Comment by AlexVarchuk** [comment]
Hi folks. Thank you for the issue and investigation comments. I tried to reproduce it, but without result.
In my case, all works correctly.

https://user-images.githubusercontent.com/14113673/179937872-c5becf35-0006-4eea-bde4-631c80fcae4d.mov


steps:
1. npx redoc-cli@latest build petstore.yaml
2. npx http-server -c-1 -f redoc-static.html(or open redoc-static.html in browser)

I think it is related to the definition. Can you add your test definition?  
@mulder999 @brettgoss

**Comment by brettgoss** [comment]
@AlexVarchuk I did some more testing, and was able to isolate the issue to running `redoc-cli bundle` with the `--cdn` flag. Removing the `--cdn` flag seems to avoid the search issue. Potentially because the CDN version is almost 8 months behind (`2.0.0-rc.58`)?

**Comment by AlexVarchuk** [comment]
Hi @brettgoss, we updated the `next` tag in npm. We appreciate your help.
