### ISSUE TITLE
[question/help wanted] Redoc htmlTemplate example

### ISSUE THREAD

**Issue by maria-mcparland** [Redocly/redoc#2078]
Hi,

In the configuration docs it mentions htmlTemplate option which 'Sets the path to the optional HTML file used to modify the layout of the reference docs page. Supported in Redoc CE.' ([https://redocly.com/docs/api-reference-docs/configuration/functionality/](https://redocly.com/docs/api-reference-docs/configuration/functionality/))

Does anyone have an example of how this works? We can't find any other mention of it

**Comment by AlexVarchuk** [comment]
Hi @maria-mcparland. You can use the template in `redoc-cli` with template options:
```
$ redoc-cli build [spec] -t custom.hbs --templateOptions.metaDescription "Page meta description"
```
Here you can find default [template file](https://github.com/Redocly/redoc/blob/master/cli/template.hbs).

**Comment by lrobledo** [comment]
@AlexVarchuk 

Can I pass the handlebars template in the redoc theme file as well? [This file](https://redocly.com/docs/api-reference-docs/configuration/functionality/) makes it seem like I can. 

Instead of
```
$ redoc-cli build [spec] -t custom.hbs"
```

Can I run

```
$ redoc-cli build [spec] --options=src/redoc-theme.json
```

with redoc-theme.json:
```
{
  "htmlTemplate": "custom.hbs",
  "theme": {...}
}
```

Those two should be equivalent, right?

**Comment by robbieaverill** [comment]
@AlexVarchuk the link to the default template in your previous comment is now dead, do you have an updated example? Thanks.
