### ISSUE TITLE
redoc-cli Performance / Busy Idle in Debian 11

### ISSUE THREAD

**Issue by iekadou** [Redocly/redoc#2082]
**Describe the bug**
When using redoc-cli in Debian 10 the computation of my swagger file takes about 500ms.
When using redoc-cli in Debian 11 the bundle task takes about 22 seconds. (It seems like a busy wait for me)

**Expected behavior**
redoc-cli should be as fast in Debian 11 as in Debian 10.

**Minimal reproducible OpenAPI snippet(if possible)**
redoc-cli bundle -t openapi/template/template.hbs -o public/docs/test.openapi.html openapi/test.yaml

**Additional context**
My .yaml file is referenced to multiple yaml files but I think as its fast in Debian 10 it's not relevant?

**Comment by m00ncr4wler** [comment]
same issues with version is 0.13.10

**Comment by iekadou** [comment]
As i just discovered it's a problem regarding NodeJs 12.X with the newest version it is fixed. 👍

**Comment by lornajane** [comment]
This looks like it is fixed, and also it relates to the older `redoc-cli` tool so I'll close this issue.
