### ISSUE TITLE
Injection security definition doesn't work anymore

### ISSUE THREAD

**Issue by luboblaho** [Redocly/redoc#2084]
**Describe the bug**
Previously I used the injection of the security definition:
```
<!-- ReDoc-Inject: <security-definitions> -->
```
Source: https://github.com/Redocly/redoc/blob/master/docs/security-definitions-injection.md

But this feature doesn't work anymore. I found in your example documentation the following solution that works:
```
<SecurityDefinitions />
```

**Additional context**
I couldn't find a new syntax of the injection in docs. Is the old syntax supported or not? Thank you!

**Comment by AlexVarchuk** [comment]
Hi @luboblaho. Thank you for the issue. 
We return previous behavior [PR](https://github.com/Redocly/redoc/pull/2075). It includes in the next release. 
But you can use a new syntax with `<SecurityDefinitions />`
