### ISSUE TITLE
Endpoint URLs are malformed after refreshing a statically generated page via redoc-cli with an anchor present in the URL

### ISSUE THREAD

**Issue by Rush** [Redocly/redoc#2090]
**Describe the bug**
- Click on a specific API endpoint so that an anchor is added to the URL:
![image](https://user-images.githubusercontent.com/115926/180060032-ac8bcecb-9102-4344-9f74-fc5df6cd79d9.png)
- Now refresh the page
- The links to API endpoints are malformed 
![image](https://user-images.githubusercontent.com/115926/180060162-c3fe30b5-6dab-49ab-b966-5496d673cea9.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/115926/180059868-d535a3a4-92f6-4933-b21a-2f088e222bec.png)

**Minimal reproducible OpenAPI snippet(if possible)**
```
openapi: 3.1.0
info:
  title: API
  version: 1.0.0

servers:
  - url: /api

security:
  - bearerAuth: []

paths:
  /profile:
    get:
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
```

**Additional context**
Happening also when opening the static file directly in Chrome:
![image](https://user-images.githubusercontent.com/115926/180060524-047785bb-a2ec-4a93-a06b-470eb79dfb5e.png)

**Comment by AlexVarchuk** [comment]
Hi @Rush. Thank you for the reporting issue and the steps to reproduce. We'll investigate it.
