### ISSUE TITLE
Search and navigation is broken in `v2.0.0-rc.67` and later

### ISSUE THREAD

**Issue by mickmister** [Redocly/redoc#2107]
**Describe the bug**

Our site hosted at https://api.mattermost.com was having issues with:

- Searching - React app crashes due to `undefined` arg passed to `Object.create`. See stack trace and code snippet below.
- Navigation - Clicking on the doc entries on the left hand side results in no automatic scrolling

We were using the `--cdn` flag in `redoc-cli`, and the version at `@next` was causing issues on our site. We were fetching `v2.0.0-rc.72` at the time. I've tested with earlier versions, and the two issues occur with  `rc.67` but not `rc.66`.

**Expected behavior**

Using the search should show search results, instead of crashing the webpage.

Clicking the entries in the left hand side should navigate to the intended section of the docs.

**Minimal reproducible OpenAPI snippet(if possible)**

Downloadable at the top of this page https://api.mattermost.com

**Screenshots**

Error occurs when you try to search. Crashes the webpage

<img width="500" alt="image" src="https://user-images.githubusercontent.com/6913320/181618567-72a474f3-7eec-4226-815d-23bc63b25a66.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/6913320/181613440-b3d3067f-f293-4d54-8f41-5f79fc727cba.png">

**Additional context**

**Comment by mickmister** [comment]
Other than the underlying issue with the specific versions of redoc, there's also the issue of automatic dependency bumping through using the `--cdn` flag. Could `redoc-cli` support a `--version` flag to choose what version to use with the CDN?

**Comment by AlexVarchuk** [comment]
Hi @mickmister, thanks for your issue.
Can you reproduce it on the latest version of `redoc-cli`?

Seems it work ok in my side.
My steps:
1. `npm i -g redoc-cli`
2. `redoc-cli build path/to/definition.yaml`
3. `npx http-server redoc-static.html`

I attach the video below. 

https://user-images.githubusercontent.com/14113673/181726906-b1c7bdfd-5695-44aa-ad29-7be2021ad647.mov

Can you provide all steps to reproduce it?

**Comment by m-mohr** [comment]
We have the same issue at https://api.openeo.org

**Comment by AlexVarchuk** [comment]
Hi @m-mohr. Seems you have recursion in your definition. Reference `#/components/schemas/json_schema`. Please check it.
```json
"json_schema": {
...
  "items": {
            "description": "Specifies schemas for the items in an array according to [JSON Schema draft-07](https://json-schema.org/draft-07/json-schema-validation.html#rfc.section.6.4.1).",
            "anyOf": [
              {
                "type": "array",
                "minItems": 1,
                "items": {
                  "$ref": "#/components/schemas/json_schema"
                }
              },
              {
                "$ref": "#/components/schemas/json_schema"
              }
            ]
          },
  }
```

**Comment by m-mohr** [comment]
@AlexVarchuk Yes, that's true and valid as per OpenAPI spec, I think. JSON Schema per definition is recursive and it worked before in redoc so I think this is a bug in redoc. I can't change my schemas, unfortunately.

**Comment by AlexVarchuk** [comment]
@m-mohr  Yes, you are right. It is a bug in redoc.
Broken search issue related to this recursion.
I think it is not the same case.
Thank you for reporting the new issue.

**Comment by m-mohr** [comment]
Just to make this clear: Before the recursion issue kicked in, I also had the issue with the navigation, so rc.73 I think should show the same behavior that is reported above by the author of this issue.

**Comment by mickmister** [comment]
> Hi @mickmister, thanks for your issue. Can you reproduce it on the latest version of `redoc-cli`?
> 
> Seems it work ok in my side. My steps:
> 
> 1. `npm i -g redoc-cli`
> 2. `redoc-cli build path/to/definition.yaml`
> 3. `npx http-server redoc-static.html`
> 
> I attach the video below.
> 
>  Screen.Recording.2022-07-29.at.12.10.21.mov 
> Can you provide all steps to reproduce it?

Hi @AlexVarchuk, thanks for your response. Here are repro steps:

- Clone https://github.com/mattermost/mattermost-api-reference
- Checkout commit `5413c61`, which is just before https://github.com/mattermost/mattermost-api-reference/pull/711
- Run `make` to build the HTML document
- Serve from the `v4/html` directory, i.e. `python3 -m http.server --directory ./v4/html`

**Comment by AlexVarchuk** [comment]
Hi @mickmister, thanks for the detailed information about reproduction.
Please try to update `redoc-cli` to the latest version. I checked it. It works for me.
