### ISSUE TITLE
Include Redoc logo in package

### ISSUE THREAD

**Issue by Fdawgs** [Redocly/redoc#2108]
**Describe the problem to be solved**
From redoc `2.0.0-rc73` onwards, Redoc's logo has been added to the Redoc UI. However, on a network without internet access the logo will not load as it is retrieved from a CDN, making the UI look unsightly.

`2.0.0-rc72`:
![image](https://user-images.githubusercontent.com/43814140/181721494-d6f17d17-48f9-4a76-a7af-712e65549b55.png)

`2.0.0-rc73`:
![image](https://user-images.githubusercontent.com/43814140/181721411-49acedd6-5fd4-41d7-971c-24b76f6ce329.png)
 

**Describe the solution you'd like**
For the logo to be included and loaded locally by the UI, or for the option to toggle the logo on and off.

**Comment by eht16** [comment]
While the change in #2109 handles errors on loading the logo, it is still loaded from the CDN.

I still would vote for another or additional solution.
For privacy reasons, it is preferable to *not* load just a logo from a CDN.

There are a couple of solutions I think:
- add an option to toggle loading the logo on or off
- add an option to specify an alternative URL to the logo, so users can override it with a self-hosted variant
- bundle the logo and deliver it from the Redoc installation

I don't mind much which solution is best as long as one can prevent connecting to a CDN just for a logo.

Use cases are as mentioned by the OP a client without an internet connection and privacy policies.

Thank you.

**Comment by seanking2919** [comment]
> While the change in #2109 handles errors on loading the logo, it is still loaded from the CDN.
> 
> I still would vote for another or additional solution. For privacy reasons, it is preferable to _not_ load just a logo from a CDN.
> 
> There are a couple of solutions I think:
> 
>     * add an option to toggle loading the logo on or off
> 
>     * add an option to specify an alternative URL to the logo, so users can override it with a self-hosted variant
> 
>     * bundle the logo and deliver it from the Redoc installation
> 
> 
> I don't mind much which solution is best as long as one can prevent connecting to a CDN just for a logo.
> 
> Use cases are as mentioned by the OP a client without an internet connection and privacy policies.
> 
> Thank you.

I concur. I would like to see it not loaded from the CDN.

**Comment by pinguin999** [comment]
This Issue is marked as Closed, but the Fix from @BenediktSeidl was never merged. @AlexVarchuk can you reopen this issue please.
