### ISSUE TITLE
Sidebar menu in devportal

### ISSUE THREAD

**Issue by rameshsamy92** [Redocly/redoc#2110]
I want to create sidebar menu. Now i am adding it manually  inside sidebar.yml. Instead of that i need to create group and menu links automatically based on folder name. suppose one folder name is retail, all json inside that folder should have menu group as retail.

**Comment by AlexVarchuk** [comment]
Hi @rameshsamy92. Thank you for your issue. 
Please, contact [team@redocly.com](mailto:team@redocly.com) for our commercial product support.
