### ISSUE TITLE
Optional authentication not rendered properly

### ISSUE THREAD

**Issue by arvidfm** [Redocly/redoc#2117]
**Describe the bug**
The [recommended way](https://github.com/OAI/OpenAPI-Specification/issues/14#issuecomment-297457320) of representing optional authentication on an endpoint is something like:
```yaml
security:
  - {}
  - basic: []
```

Unfortunately this doesn't render properly in Redoc.

**Expected behavior**
The "authorizations" section of the endpoint documentation should clearly communicate that it is an optionally authenticated endpoint.

**Minimal reproducible OpenAPI snippet(if possible)**
```yaml
openapi: 3.1.0
info:
  title: Optional auth
  version: 1.0.0
paths:
  /info:
    get:
      summary: Get info
      operationId: getInfo
      security:
        - {}
        - basic: []

components:
  securitySchemes:
    basic:
      scheme: basic
      type: http
```

**Screenshots**
![image](https://user-images.githubusercontent.com/885076/182637515-f1a5ac8c-9f85-4fb4-a3b5-c4f813a6312a.png)

![image](https://user-images.githubusercontent.com/885076/182637596-1eb4af52-7283-4c88-9da4-0c4874ae5973.png)

**Additional context**

**Comment by AlexVarchuk** [comment]
closed via https://github.com/Redocly/redoc/pull/2134
