### ISSUE TITLE
Question regarding menu in ReactStandalone

### ISSUE THREAD

**Issue by vasi-mh** [Redocly/redoc#2120]
Hi,

I am trying to use the ReactStandalone component in an existing React application.

I would like to take the menu items from what is generated by the component, and add them to an existing side menu. Is this something that is supported and is available to retrieve?

**Comment by AlexVarchuk** [comment]
Hi @vasi-mh, thank you for the question. No, we don't support the menu component for now. You can control the menu using the options `x-tagGroups` and tags section in your definition.
