### ISSUE TITLE
Sidebar does not stick on 2.0.0-rc.74

### ISSUE THREAD

**Issue by megharathorepto** [Redocly/redoc#2122]
**Describe the bug**
Redoc sidebar appears only on the first page, if I scroll down below first page my sidebar does not stick and I have to scroll back all the way up to view sidebar

**Expected behavior**
Sidebar should stick to all the pages.

**Minimal reproducible OpenAPI snippet(if possible)**
loadRedocDocumentation() {
    const elem = this.element.nativeElement.querySelector('.redoc-container');
    const options = { 
      theme: { colors: { primary: { main: '#0C7696' } } }
    };
    this.apiDocsService.getApiDocs().subscribe((res) => Redoc.init(res, options, elem));
  }

**Screenshots**
![redoc issue](https://user-images.githubusercontent.com/75132168/183179536-d021741c-9850-44ab-91e8-3cef125d2b53.png)
![redoc issue 2](https://user-images.githubusercontent.com/75132168/183180275-179274ed-7580-4a9d-aab8-ddd0cc6d0f5e.png)

**Additional context**

**Comment by AlexVarchuk** [comment]
Hi @megharathorepto. 
Can you provide more information(demo page, definition, etc) for reproducing this case?
Thanks

**Comment by AlexVarchuk** [comment]
Hi @megharathorepto. Seems we reproduced a case related to your issue. It'll fix in https://github.com/Redocly/redoc/pull/2116
