### ISSUE TITLE
redoc-cli bundle left navigation click operations are not scrolling to the content

### ISSUE THREAD

**Issue by JSSAggie** [Redocly/redoc#2123]
**Describe the bug**
Using https://www.npmjs.com/package/redoc-cli/v/0.13.16
Running `redoc-cli bundle --cdn openapi-json --output pet-store.html --options.showExtensions=true`
I get a bundled html file but when I click on the operations like `pet-store.html#tag/pet/operation/deletePet` the browser does not scroll to that section.

I have included the pet store json and the html output.
[pet-store.zip](https://github.com/Redocly/redoc/files/9284536/pet-store.zip)

**Expected behavior**
When you click on an operation in the left navigation the browser would navigate to that section of the specification.

**Comment by AlexVarchuk** [comment]
Hi @JSSAggie. I tried to reproduce it in versions latest and 0.13.16. It works ok.
Your HTML file looks very weird.
<img width="852" alt="Screenshot 2022-08-09 at 16 38 35" src="https://user-images.githubusercontent.com/14113673/183664218-3e634db6-c1ec-419c-81bc-123d3b690fb5.png">

Did you try to customize UI?

**Comment by JSSAggie** [comment]
@AlexVarchuk weird I need to dig in more now because you are correct.  I pushed up a repo and could not reproduce it.

**Comment by AlexVarchuk** [comment]
Hi @JSSAggie, no problem. If you find something, please, reopen this issue.
