### ISSUE TITLE
Is x-tags supposed to be implemented?

### ISSUE THREAD

**Issue by michaelgwelch** [Redocly/redoc#2148]
**Describe the problem to be solved**
Implement x-tags as documented already: [x-tags](https://redocly.com/docs/api-reference-docs/specification-extensions/x-tags/)

In testing we've found it not to work and the README does not list it as an extension (so I assume it's not actually been implemented?):
https://github.com/Redocly/redoc#openapi-specification-extensions

**Describe the solution you'd like**
As documented.

**Describe alternatives you've considered**
We're using `<SchemaDefinition>` but then when used with redocly it triggers the `no-unused-components` inspection rule.

**Comment by michaelgwelch** [comment]
This was answered by @adamaltman in https://github.com/Redocly/redocly-cli/issues/838. Apparently this is in the premium product only.

**Comment by adamaltman** [comment]
Let's leave this open here so we can discuss implementing it in Redoc.

**Comment by RomanHotsiy** [comment]
Let's implement it.

cc @AlexVarchuk

**Comment by lornajane** [comment]
This feature has been merged now (thanks @AlexVarchuk !), so you'll find it on the main branch. It will be in Redoc itself at the next release.
