### ISSUE TITLE
Add Access-Control-Allow-Origin: * to the headers of requests for files from ReDoc's CDN

### ISSUE THREAD

**Issue by kentatwabbi** [Redocly/redoc#2150]
**Describe the problem to be solved**
A clear and concise description of what problem to be solved

If you include the ReDoc JS file via CDN as [shown in the example](https://github.com/Redocly/redoc#tldr-final-code-example) from the docs...:
```
 <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"> </script>
```
... this works fine.  But if you add and integrity and crossorigin attributes to the script tag ...:
```
<script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js" integrity="sha384-uRA8Y7rACl0JawWNYt/rJAGS0VImxzhV8U0evFRci24ifCwrg6sdpc+X9s2py8ur" crossorigin="anonymous"> </script>
```
... the script will fail to load since the request to get the script file is not marked as being able to be downloaded from any origin.

**Describe the solution you'd like**

If you configure the CDN to include a Access-Control-Allow-Origin header to allow anyone to download this file: ...
```
Access-Control-Allow-Origin: *
```
.. then users can securely download the file from your CDN.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by AlexVarchuk** [comment]
Hi @kentatwabbi, we'll do that.

**Comment by AlexVarchuk** [comment]
Hi, @kentatwabbi, please verify. It works for me.

**Comment by kentatwabbi** [comment]
Verified. Thank you.
