### ISSUE TITLE
SVG Arrow wrapping issue for smaller screen sizes

### ISSUE THREAD

**Issue by Chattox** [Redocly/redoc#2152]
**Describe the bug**
The arrow used for collapsible sections wraps onto the next line while collapsed on smaller screen sizes.

**Expected behavior**
This wrapping should ideally not occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/33847899/188432590-fc6ac366-1b62-413a-be69-929e158d110a.png)
Collapsed

![image](https://user-images.githubusercontent.com/33847899/188432899-1d48d81e-6751-4f1e-8f6f-a449c26d43b8.png)
Expanded

**Additional context**
Being able to disable the collapsing behaviour would be a great option as well.

**Comment by AlexVarchuk** [comment]
Hi @Chattox, thank you for the issue. Seems you use the old version of Redoc.
The current behaviour is:
**Collapsed:**
<img width="304" alt="Screenshot 2022-10-12 at 17 35 00" src="https://user-images.githubusercontent.com/14113673/195371798-c921a949-0965-4686-afc6-108341fa64c6.png">
**Expanded:**
<img width="285" alt="Screenshot 2022-10-12 at 17 35 24" src="https://user-images.githubusercontent.com/14113673/195371885-51e51a72-eea2-4e26-b914-c5ded53eb918.png">

The behavior when the arrow moves into the next line happens on 210px. I think it is too small a screen for support.
If you wanna contribute, please reopen this issue.

We always support contributions to Redoc. We will be happy to consider your PR.
