### ISSUE TITLE
Need to change button description text

### ISSUE THREAD

**Issue by sathithyayogi05** [Redocly/redoc#2169]
currently description title is "Download OpenAPI specification", how to change this text ?

**Comment by thomasgilmore95** [comment]
I can work on this. What do you want the text changed to?

**Comment by AlexVarchuk** [comment]
Hi @sathithyayogi05, we don't have opportunities to change the text 'Download OpenAPI specification'. Try to fix it using custom CSS. Thanks

**Comment by sathithyayogi05** [comment]
Hey, this is fixed, thanks for your support
