### ISSUE TITLE
TS compilation error: Cannot find name 'GenericObject'

### ISSUE THREAD

**Issue by mrginglymus** [Redocly/redoc#2171]
**Describe the bug**
Using redoc in a project with `skipLibCheck: false` , I get the following error:

```
.yarn/__virtual__/redoc-virtual-0d2672ebad/1/build/node/cache/redoc-npm-2.0.0-f00948f5d8-8.zip/node_modules/redoc/typings/services/OpenAPIParser.d.ts:15:20 - error TS2304: Cannot find name 'GenericObject'.

15     validate(spec: GenericObject): void;
                      ~~~~~~~~~~~~~
```

It presumably refers to the definition here: 
https://github.com/Redocly/redoc/blob/16f542bbfe856e5ae5eb40636ac79421fa2f397b/custom.d.ts#L27

but as things stand, either I'm holding it wrong or the shipped typescript stubs are faulty.

**Expected behavior**
No errors on typescript compilation

**Additional context**
Typescript 4.6.3, redoc 2.0.0

**Comment by AlexVarchuk** [comment]
Hi @mrginglymus.
I cannot reproduce it on CRA with a typescript template and added `skipLibCheck: false`. Like in documentation https://redocly.com/docs/redoc/deployment/react/

Can you provide additional steps to reproduce? It will be very useful for us.
Thanks

**Comment by mrginglymus** [comment]
hi @AlexVarchuk, I've created a minimal repro repo here: https://github.com/mrginglymus/redoc-type-bug

I don't use CRA myself, but I think I've got everything right there.

I'm going to raise a PR to inline usages of genericobject, so that the shipped types are complete.
