### ISSUE TITLE
how i got the brand with my store

### ISSUE THREAD

**Issue by yzmdd** [Redocly/redoc#2181]
the brand api list all the brand on otto marketplace ,but i just want my brand . what should i do,thanks

**Comment by AlexVarchuk** [comment]
Hi, @yzmdd. Can you little bit clarify your question?

**Comment by yzmdd** [comment]
How to obtain the brand of this store

**Comment by yzmdd** [comment]
It was published successfully through the interface, but how long does it take for the status of the product to change from restricted to online? It takes me more than four hours to test. Does it take this long

**Comment by AlexVarchuk** [comment]
@yzmdd Can you share some screenshots or links for understanding additional context? Thanks

**Comment by yzmdd** [comment]
![image](https://user-images.githubusercontent.com/53429284/195594489-7fbfa13b-ca62-411c-b933-0baeba7f7e4d.png)
this product It took more than four hours for the status of this product to change from restricted to online

**Comment by AlexVarchuk** [comment]
Redoc doesn't have any relation to this market. Do you have some additional questions?

**Comment by yzmdd** [comment]
thank you very much
