### ISSUE TITLE
Logo margin configuration is not being read

### ISSUE THREAD

**Issue by pedrotambo** [Redocly/redoc#2183]
**Describe the bug**
In the documentation of the configuration of the theme (https://redocly.com/docs/developer-portal/configuration/theme/) it says that the logo accepts a `margin` value, but it's not being read.

**Expected behavior**
The `margin` value is read from the configuration and set for the logo component.

**Comment by AlexVarchuk** [comment]
Hi @pedrotambo, thank for the issue. But seems it not related to Redoc.

Please, contact [team@redocly.com](mailto:team@redocly.com) for our commercial product support.
