### ISSUE TITLE
Callback function not called on error

### ISSUE THREAD

**Issue by Nareznoy** [Redocly/redoc#2195]
**Describe the bug**
 When an invalid reference to the json file is entered, the callback function is not called.

**Expected behavior**
The documentation says that on errors, a callback function is called with the error as the first argument.  
![image](https://user-images.githubusercontent.com/48029980/197500151-3ce435a2-7258-40f5-b54e-946e7d988179.png)

**Minimal reproducible OpenAPI snippet**
```
<script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js">
</script>

<div id="redoc-container">
</div>

<script>
    Redoc.init('https://petstore.swagger.io/v2/swaggerERROR.json', {
        scrollYOffset: 50
    }, document.getElementById('redoc-container'), function(error) {
        var str = error;
    })
</script>
```

**Comment by AlexVarchuk** [comment]
Hi @Nareznoy, thank you for the issue. I believe it is the same https://github.com/Redocly/redoc/issues/2025 and it was fixed in https://github.com/Redocly/redoc/pull/2182. It will be included in the next release.

**Comment by Nareznoy** [comment]
Thanks @AlexVarchuk! Also, can you tell me, please, when is the next release date planned?
