### ISSUE TITLE
Redoc crashing when loading huge swagger.json

### ISSUE THREAD

**Issue by benyuenvisma** [Redocly/redoc#2211]
**Describe the bug**
Browser displaying the code: Out of Memory. When trying to display a big swagger.json. Loading it using SwaggerUI works great though!

**Expected behavior**
Expect redoc to load it

I can provide the swagger.json if needed.

**Comment by sagayakwad26** [comment]
I'm having the same problem with large JSON or YAML files, but after some debugging, we discovered that it's the nested references we used that are causing the browser to crash. We are still investigating.

**Comment by c69-addepar** [comment]
Seems like Redoc might be struggling with recursive types (`... -> .a -> .b -> .a -> b -> ...`), as it tries to render them all in one run, it seems ? Of course it can not, so the tab just crashes with error. Stoplight handles is fine, though, as it renders the tree lazily.

ps: i could be wrong, had not investigated fully.

**Comment by lornajane** [comment]
Do you have an example of the recursive/nested descriptions that cause the problem? I think it would help us to understand the problem(s) each of you is seeing.
