### ISSUE TITLE
Missing styles when building the specs

### ISSUE THREAD

**Issue by Pritilender** [Redocly/redoc#2212]
**Describe the bug**

When trying to build the docs via `build` command, the output HTML is rendered without styles (see screenshot).
It seams like the issue started popping up on `redoc-cli` version `0.13.12` because `0.13.11` gives me a proper HTML with styles.

**Expected behavior**

The expected behaviour is properly rendered HTML.

**Minimal reproducible OpenAPI snippet(if possible)**

**Screenshots**

![image](https://user-images.githubusercontent.com/11322211/203784199-185fa396-bfab-4267-b0a6-00e8a16860d4.png)

**Additional context**

I'm running the command as `redoc-cli build dist.yaml --config internal.config.yaml -t docs/index.html`, where `dist.yaml` is generated beforehand via `@redocly/cli`.

**Comment by emcintyre-hpe** [comment]
I'm running into this as well. If I start with a [clean template](https://github.com/Redocly/openapi-starter), the static doc builds fine. As soon as I bring my own OAS into it, the build breaks. Note that the dynamically-generated live preview still works fine.

The following are the generated snippets that replace the `{{{redocHead}}}` placeholder:

```html
<!-- From a working build of the template -->
  <script src="https://cdn.redoc.ly/redoc/v2.0.0/bundles/redoc.standalone.js"></script><style data-styled="true" data-styled-version="5.3.3">.fcjMZs{width:calc(100% - 40%);padding:0 40px;}/*!sc*/
@media print,screen and (max-width:75rem){.fcjMZs{width:100%;padding:40px 40px;}}/*!sc*/
.frutYI{width:calc(100% - 40%);padding:0 40px;}/*!sc*/
<!-- ... snip ... -->
</style>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">
```

```html
<!-- From a build of my own spec -->
  <script src="https://cdn.redoc.ly/redoc/v2.0.0/bundles/redoc.standalone.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">
```

Also note that, even though the `<style>` tag is missing, the HTML contains the generated CSS classes, e.g.:

```html
<div class="sc-dvwKko fCcCBY redoc-wrap">...</div>
```

**Comment by emcintyre-hpe** [comment]
Well, I rescind my comment 😄  On one hand, I just realized there's a separate repo for the CLI, and this all probably belongs there now. On the other hand, after downgrading and upgrading to a bunch of different `@redocly/cli` versions, trying to find the best one, it's working again, even on the latest beta.

**Comment by AlexVarchuk** [comment]
Hi. Sorry for the huge delay. `redoc-cli` is deprecated. Instead of that try to use [@redocly-cli](https://github.com/Redocly/redocly-cli).

**Comment by Enet4** [comment]
I am reproducing this exact same issue with redoc 2.0.0 against the latest version of `@redocly/cli` (^1.0.0-beta.126) using the `build-docs` command, although the deprecated `redoc-cli bundle` worked well. Any idea on how one should troubleshoot and where to report this?

**Comment by lornajane** [comment]
@Enet4 The repo for the newer package is https://github.com/Redocly/redocly-cli/ - open an issue and tell us what command you're running, and what you get back. If you can share your config settings and  OpenAPI description (or a small sample showing the same error), that will also help us to help you. Thanks in advance :)
