### ISSUE TITLE
WCAG 1.4.1 - Links are not clearly identifiable

### ISSUE THREAD

**Issue by dagfs** [Redocly/redoc#2225]
**Describe the problem to be solved**

In markdown rendered in ReDoc, text-decoration is set to `auto`. This seems to be an allowed value, but I can not find it in the doc.

According to WCAG 1.4.1 this breaks the function can not be communicated only trough color rule.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/26817802/205935524-278b5ae6-664c-46f7-99cc-46ac2fc41c3a.png">

**Describe the solution you'd like**
I suggest setting the default for the default template to `text-decoration: underline;` as to promote accessability.

**Describe alternatives you've considered**
- I considered just changing this in our theme. But I think it is better if the default theme has this change.

**Additional context**

This issue is related to my previous issue #2223 as part of the same improvments

This issue relates to the tracking WCAG issue https://github.com/Redocly/redoc/issues/1279

**Comment by RomanHotsiy** [comment]
I don't think that using underline as default is a good solution.

I'm closing it.
