### ISSUE TITLE
[Bug] got ukraine text by @id

### ISSUE THREAD

**Issue by remco-pc** [Redocly/redoc#2258]
![image](https://user-images.githubusercontent.com/8077908/215767499-ab449f40-a1c1-44c4-924f-17d85842bd22.png)

Used the latstest redoc.standalone.js .
my local on windows is ENG - US, browsers: chrome & edge.

It looks like it gets translated somehow, how to disable that / change back to english ? the rest of the page is in english so is the json provided.

**Comment by RomanHotsiy** [comment]
We need to upgrade the package and release a new version https://github.com/Redocly/openapi-sampler/commit/122ea09c595031932183cb95341d345f7555175c

cc @AlexVarchuk
