### ISSUE TITLE
Some markdown not being rendered

### ISSUE THREAD

**Issue by moshefordi** [Redocly/redoc#2266]
**Describe the bug**
I am editing .py files.
Some of the markdown is working; some not.
For example:
description=(
            "The type of the transaction. There are three options: "

            " * **EVM raw transaction**: receives raw data and is for general transactions; "
            " * EVM transfer: for transferring native currency or a token; "
            " * EVM revoke allowance: for revoking a spender's allowance for a specific token. "

            "The required fields vary for each transaction type."
        ),
- open lines seem to have no effect.
- the asterisk marking the beginning of a bulleted item is not being rendered.
- the two asterisks before and after are being rendered bold.

**Expected behavior**
That markdown annotations should work across the board.

**Minimal reproducible OpenAPI snippet(if possible)**

**Comment by AlexVarchuk** [comment]
Hi, @moshefordi. I am not well familiar with python and your use case. Please provide steps to reproduce that. Thanks.

**Comment by lornajane** [comment]
Closing as we don't have enough information to replicate a problem
