### ISSUE TITLE
support SSR on standalone component

### ISSUE THREAD

**Issue by wangpin34** [Redocly/redoc#2270]
**Describe the problem to be solved**
The standalone component is used in my nextjs app which is actully a document website. For SEO purpose, I'd like to having redoc rendered in the output of html instead of loading on the fly that the component currently works. I tried with spec object but it still not SSR.

**Describe the solution you'd like**
I hope the standalone component could rendered with the spec object synchronized which does make more sense.

**Describe alternatives you've considered**
No for now.

**Additional context**
No for now.

**Comment by AlexVarchuk** [comment]
Hi @wangpin34. In that case, maybe useful for you to use `npx @redocly/cli build-docs <spec>` for that. Please check the [documentation](https://redocly.com/docs/cli/commands/build-docs/) of this command.

**Comment by wangpin34** [comment]
@AlexVarchuk Thank you for your response. While using CLI may work to enable SSR, unfortunately, it does not suit my case as I would like to render the document in NextJS.  

After hours of searching the web, I finally found a solution that works for me. It's actually quite simple and just involves using another component that is exposed from redoc. Here is the code snippet:
```typescript
// spec is a string of yaml content, json is ok as well
const specObj = yaml.load(spec)
const store = new AppStore(specObj, undefined, options)
```
Anyway, thanks for your reponse.

**Comment by yulyasystem** [comment]
@wangpin34 did you manage to use it app router in Next.js?

**Comment by wangpin34** [comment]
> @wangpin34 did you manage to use it in app router in Next.js?

Not yet, I'm pretty new to react server component and haven't try redoc + server component.

**Comment by erajasekar** [comment]
@wangpin34 @yulyasystem where you able to make it work with app router. I have same use and looking for code examples.
