### ISSUE TITLE
Sidebar navigation doesn't work

### ISSUE THREAD

**Issue by aditya-docs** [Redocly/redoc#2272]
The sidebar navigation doesn't work, the path changes on the url but the page doesn't scroll

Docs Here -> https://capi-prework.netlify.app/#tag/Authentication

You can download the OAS YAML from the button at the top.

**Comment by AlexVarchuk** [comment]
Hi @aditya-docs. Please provide more information about reproducing(browser and version, OS, etc). I attached a recording of how it works on my side. 



https://user-images.githubusercontent.com/14113673/223202842-5d6501cf-1d78-4bcf-b32d-b0d5bd8d6d3d.mov

**Comment by aditya-docs** [comment]
@AlexVarchuk Hey, I fixed it and found the issue with it. It was because of bootstrap. I removed bootstrap and the sidebar started working

**Comment by Boldbayar** [comment]
Is there any way to use it without bug with bootstrap? I'm having same issues but I need bootstrap

**Comment by volkandkaya** [comment]
@Boldbayar did you find a fix?

Also is it something to do with onclick? I'm not using Bootstrap but Versoly UI which has some extra JS.

**Comment by frobnitzem** [comment]
This same issue can be seen here: <https://frobnitzem.github.io/psik_api/>
On Firefox, as I scroll, the left nav-bar opens.  However, any click on the left navbar results in scrolling up by a fixed amount, rather than scrolling to a definite location in the API spec.
