### ISSUE TITLE
In developer portal, using Sticky navigation scrollYOffset Option not working properly and while clicking the current active menu, the dropdown is not opening.

### ISSUE THREAD

**Issue by Siva22695** [Redocly/redoc#2277]
In portal, using Sticky navigation scrollYOffset Option not working properly and while clicking the current active menu, the dropdown is not opening.

**Comment by AlexVarchuk** [comment]
Hi @Siva22695 Thank for the issue but it doesn't related to Redoc.
Please, contact [team@redocly.com](mailto:team@redocly.com) for our commercial product support.
