### ISSUE TITLE
String field example displayed as number

### ISSUE THREAD

**Issue by miquelvir** [Redocly/redoc#2278]
**Describe the bug**
When a string field has an example that could be parsed as a number, it is displayed as a number.

**Expected behavior**
String fields are always represented as strings.

**Minimal reproducible OpenAPI snippet(if possible)**
```
openapi: 3.0.0
info:
  title: Foo API
  version: 1.0.0
paths:
  /foo:
    get:
      operationId: foo
      responses:
        200:
          description: Hello
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
components:
  schemas:
    Foo:
      type: object
      properties:
        bad:
          type: string
          description: A string
          example: 1.0
        good:
          type: string
          description: A string
          example: hello
        alsoGood:
          type: string
          description: A string
          example: 1.0_

```

**Screenshots**
![image](https://user-images.githubusercontent.com/41950283/223872426-0fcd727b-846e-4f5f-8935-b0bcae973ac1.png)

**Additional context**
NA

**Comment by AlexVarchuk** [comment]
Hi @miquelvir. Thank you for the issue. I believe Redoc shouldn't format your example regarding [specifications](https://spec.openapis.org/oas/v3.0.0#fixed-fields-19). It is a bad idea.
Also some problem has YAML parser. For avoid it you can use JSON format for your definition.

```
Example
A free-form property to include an example of an instance for this schema. 
To represent examples that cannot be naturally represented in JSON or YAML, 
a string value can be used to contain the example with escaping where necessary.
```
