### ISSUE TITLE
Sidebar is not keyboard accessible

### ISSUE THREAD

**Issue by kburk1997** [Redocly/redoc#2283]
**Describe the bug**
When I press Tab to navigate through the page, the sidebar is completely skipped.
Repro steps:
1. Go to Redoc demo
2. Press Tab until "Search" on left hand side is focused
3. Press Tab again

**Expected behavior**
Focus moves to sidebar.

**Actual behavior**
Focus moves to bottom link.

**Screenshots**
Screen recording (with keystrokes): 

https://user-images.githubusercontent.com/11298269/225959800-c539321e-d7a6-42e4-9bc2-5639048a1c68.mov

**Comment by AlexVarchuk** [comment]
closed via https://github.com/Redocly/redoc/pull/2361

**Comment by kburk1997** [comment]
I can now tab to the sidebar elements. However, when I press Enter, nothing happens. Should I file a separate issue or reopen this issue?

**Comment by kburk1997** [comment]
> I can now tab to the sidebar elements. However, when I press Enter, nothing happens. Should I file a separate issue or reopen this issue?

This appears related to #1090 actually
