### ISSUE TITLE
usage help request: JWT/auth token renewal while browsing generated documentation

### ISSUE THREAD

**Issue by jspraul** [Redocly/redoc#2293]
Is there a convenient way to extend the client-side script so that a JWT token needed to access the documentation can be refreshed as needed along with normal interaction?

**Comment by AlexVarchuk** [comment]
Hi. Please, add additional information about your use case.
Why do you need to generate JWT token for Redoc?

**Comment by jspraul** [comment]
Thank you for responding to my question.

The site under which the documentation is hosted requires authentication. From my understanding the documentation is entirely statically generated and thus entirely browsable client side, but I do not want the authenticated session to timeout while doing so.

From a high level, I would like to tie into redoc in such a way that I can refresh the authentication token as needed.

**Comment by AlexVarchuk** [comment]
@jspraul Redoc doesn't use tokens for authentication. I believe you use [Openapi docs](https://redocly.com/reference/).

Please, contact [team@redocly.com](mailto:team@redocly.com) for our commercial product support. Thanks.

**Comment by jspraul** [comment]
To be clear: all I'm looking for is some type of client-side JavaScript callback when there is user interaction with the generated redoc site.

It sounds like this hasn't been needed; thanks again for your time.
