### ISSUE TITLE
$ref in nested example not being rendered

### ISSUE THREAD

**Issue by velser** [Redocly/redoc#2295]
**Describe the bug**
When using $ref for response example nested value (like paginated items), content is not rendered, instead $ref and path are returned. It works in regular swagger with swagger-ui-watcher for example. Looks like it does not respect the $ref in nested example value and just renders raw content

**Expected behavior**
Show render content instead of path

**Minimal reproducible OpenAPI snippet(if possible)**

Example ref content:
```
abc:
  items:
    - id: id1
    - id: id2
```

Example1. Works with swagger watcher but not redocly(returns "$ref": "#/abc/items") :

```            
example:
  count: 5,
  pages: 1,
  page: 1,
  limit: 100,
  items:
    $ref: '#/abc/items'
```

Example2. Works bad with watcher(overwrites other values). Works fine with redocly(returns proper content):
```
example:
  count: 5,
  pages: 1,
  page: 1,
  limit: 100,
  $ref: '#/abc'
```

Example3. Same as example 1, but referencing separate array elements. Does not work also:
```
abc:
  items:
    item1:
      id: id1
    item2:
      id: id2
```

```            
example:
  count: 5,
  pages: 1,
  page: 1,
  limit: 100,
  items:
    - $ref: '#/abc/items/item1'
    - $ref: '#/abc/items/item2'
```

**Screenshots**
Example1:
<img width="581" alt="Screenshot 2023-04-05 at 12 12 13" src="https://user-images.githubusercontent.com/10587651/230036687-c6c703b6-7002-4d4f-b0bf-fb2261ac0278.png">

Example2:
<img width="590" alt="Screenshot 2023-04-05 at 12 11 52" src="https://user-images.githubusercontent.com/10587651/230036693-f419a981-f600-491d-bb80-4db0a4d43c8f.png">

Example3 redocly:
<img width="583" alt="Screenshot 2023-04-05 at 12 19 01" src="https://user-images.githubusercontent.com/10587651/230038662-1b3522e5-cf9b-486d-a9d1-ad998bc119da.png">

Example3 swagger watcher:
<img width="998" alt="Screenshot 2023-04-05 at 12 22 39" src="https://user-images.githubusercontent.com/10587651/230039245-d973efd0-b7be-4aa3-9029-7b7686c9c67e.png">

**Additional context**
"@redocly/cli": "^1.0.0-beta.124",

**Comment by RomanHotsiy** [comment]
In OpenAPI, examples do not support references at all. Examples are the direct values as is. Why? If my API returns a payload with $ref field. How could I specify an example for it the $ref were resolved?

Because this is so common confusion I believe we made an exception (but I'm not sure) for root-level $ref (se you can $ref whole example, but not part of it).

Dup of https://github.com/Redocly/redoc/issues/845
