### ISSUE TITLE
The property hide-hostname doesn't work well

### ISSUE THREAD

**Issue by efimatica** [Redocly/redoc#2296]
**Describe the bug**
I load the redoc app using hide-hostname property like this:
`<redoc spec-url="./api" hide-hostname hide-fab sort-operations-alphabetically sort-tags-alphabetically></redoc>`

**Expected behavior**
I think that hide hostname should remove the schema, basepath and port on all references, but when I check the generated URL in any request, redoc shows the host http://localhost:8084. Example
`http://localhost:8084/property/{property_id}/complement`

![Screenshot 2023-04-05 at 11 29 41](https://user-images.githubusercontent.com/95849747/230040930-5c4fa040-cb9c-4ef6-89ab-ca4068647189.png)

**Comment by romanpryshliak** [comment]
Hi @efimatica,

Please specify the hide-hostname option like is shown in the example below and let me know whether it works properly for you:

```
<redoc spec-url="./api" hide-hostname='true' hide-fab sort-operations-alphabetically sort-tags-alphabetically></redoc>
```

**Comment by efimatica** [comment]
Hi @romanpryshliak,
Yes, adding true works right. 
Thanks you for your attention.

**Comment by Sandrakay49** [comment]
It's saying social worker find out because my laptop and phone has been
hack ND I would like to know who it is
