### ISSUE TITLE
Has redocly.github.io stopped updating?

### ISSUE THREAD

**Issue by ayame113** [Redocly/redoc#2297]
I'm new to this project so sorry if I'm misunderstanding.

Deploying to redocly.github.io appears to have stopped 7 months ago.

![image](https://user-images.githubusercontent.com/40050810/230542599-0c60d7b1-216d-4735-8ce6-ec7de1d24f31.png)

Also, it looks like the fix made in #2220 is not reflected.
Maybe a new version of the demo site needs to be deployed on github.io?

**Comment by ZyzychO** [comment]
CC: @AlexVarchuk

**Comment by AlexVarchuk** [comment]
Hi, @ayame113. Thank you for your question.
We publish that page when publishing the new version. The last version is `2.0.0`, and the page `redocly.github.io` is relevant for now.
We do not have the date of the next release. 
But when it happens we will release the last version of that page.

**Comment by ayame113** [comment]
Thank you for telling me about it :+1:
