### ISSUE TITLE
Query  incorporating release version number 

### ISSUE THREAD

**Issue by Freedisch** [Redocly/redoc#2301]
**Describe the problem**
We are currently moving our doc generation from Swagger to Redocly, and I wanted to know if there is any way to incorporate the release version number in our docs. We are using the redocly cli to generate the docs from what I saw in the documentation there is nothing allowing to do so.

**Comment by Orest-Yastremskyy** [comment]
Hi @Freedisch.

Kindly note, that in case you are having questions regarding our premium product, Redocly, I would suggest contacting us via email, team@redocly.com.

Thank you for understanding.
