### ISSUE TITLE
React 18.x support

### ISSUE THREAD

**Issue by trevor-tocchet-picket** [Redocly/redoc#2303]
Is there a timeline on support for react 18?

**Comment by Orest-Yastremskyy** [comment]
Hi @trevor-tocchet-picket 

As of now, unfortunately, we can not provide you with any timelines regarding the support for React 18.

Thank you for understanding.

**Comment by lornajane** [comment]
Follow #2164 for updates when we do pick up and start working on this feature - as Orest says, it's planned but not scheduled yet.
