### ISSUE TITLE
MacOS: Cmd+K shortcut to open search bar

### ISSUE THREAD

**Issue by kraktus** [Redocly/redoc#2304]
Thank you for developing redoc, with use it at lichess.org/api for many years and are happy about it.

A nice to have would to add the `Cmd+K` shortcut which is common to open search bar on MacOS for developers, for example GitHub and https://brew.sh implement it.

**Comment by Orest-Yastremskyy** [comment]
Hi @kraktus,

Thank you for taking the time to share this idea with us.

I have added it to our list of ideas so that our Product Team can evaluate how it fits our roadmap.

We cannot guarantee that it will be approved nor can provide you with any timelines.

**Comment by lornajane** [comment]
Thanks for the suggestion, but we decided not to implement this feature.

**Comment by Valpich** [comment]
Hello,

I would like to request that you reconsider implementing this feature. As the AI-powered search is currently highly beneficial, it would be advantageous to have this shortcut that enhances the user experience.

For reference, Shopify has implemented a similar feature: https://shopify.dev/docs/api/admin-graphql
