### ISSUE TITLE
Request: Add consistent class names for granular custom styling in API documentation

### ISSUE THREAD

**Issue by mustafaj17** [Redocly/redoc#2308]
Hello Redoc Team,

First of all, thank you for creating such a fantastic tool for rendering API documentation. It has been extremely helpful for many users, including myself and my team.

I have a request regarding custom styling in Redoc. Currently, Redoc uses styled components, which generate class names at build time. This makes it difficult to apply custom CSS, as the class names can change, and targeting elements becomes quite challenging.

I understand that Redoc allows users to pass a configuration object to customize various aspects of the design, such as background, fonts, etc. However, this approach does not meet our requirements, as we need more granular control over the styling of specific elements, like the code blocks, status codes, URLs, and parameters section.

To make custom styling more accessible, it would be incredibly helpful if consistent class names could be added to the elements rendered in the API spec. This would allow users to easily target specific elements without relying on brittle methods like nth-child selectors.

For example, adding consistent class names to the example request and response sections, the code blocks, the status codes, the URLs, and the parameters section would enable users to apply granular custom styling to those parts of the documentation by using custom style sheets.

To illustrate the current limitations, here's a snippet of my CSS code that uses nth-child selectors to target these elements:

```
// API Spec Pages styles
.redoc-wrap {
  // API Content Section
  .api-content {
    // Individual operation/paths sections
    div[id^='operation\/'],
    div[id^='tag\/'] > div,
    div[id^='\/paths\/'] > div,
    div[id^='\/paths\/'] {
      // Left section (API fields)
      & > div:nth-of-type(1) {
        // API fields data
        table tr {
          div {
            background-color: white !important;
          }
          td[kind='additionalProperties'],
          td[kind='field'] {
            // Make the API field property names monospace
            span.property-name {
              font-family: var(--ifm-font-family-monospace);
              background-color: var(--color-api-spec-parameter-name-background);
              padding: 4px;
              border-radius: 4px;
            }
          }
        }
      }
    }
  }
}

```
As you can see, this approach is brittle and may break if the structure of the generated HTML changes.

I understand that this may require some changes to the current implementation, but I believe it would greatly improve the customisation experience for users who need more control over the appearance of their API documentation.

Thank you for considering this request. I'm looking forward to hearing your thoughts on this issue.

Best regards,

Mustafa J

**Comment by Orest-Yastremskyy** [comment]
Hi @mustafaj17,

Thank you for taking the time to share this idea with us.

I have added it to our list of ideas so that our Product Team can evaluate how it fits our roadmap.

We cannot guarantee that it will be approved nor can provide you with any timelines.

Thank you for understanding.

**Comment by AlexVarchuk** [comment]
Hi @mustafaj17 thanks for feedback. We appreciate it. 🙌 
We know that problem. But if we do that we'll have a big problems with maintenance(the part of discussion you can find [here](https://github.com/Redocly/redoc/pull/2159)).

**Comment by AlexVarchuk** [comment]
I closed it, regarding we do not implement that way in future.

**Comment by Sandrakay49** [comment]
Got any names

**Comment by Sandrakay49** [comment]
https://docs.digitalocean.com/products/networking/firewalls/how-to/configure-rules/#add-update-or-remove-rules-from-a-firewall-using-the-cli hey got any names
