### ISSUE TITLE
Generated examples are not valid when using regular expression patterns

### ISSUE THREAD

**Issue by albertored** [Redocly/redoc#2312]
Generated examples are not valid when using regular expression patterns.
In this case, the example is simply `"string"` without honoring the regular expression.

Maybe something like https://github.com/fent/randexp.js can be used for this

**Comment by albertored** [comment]
Take this OA as an example:

```yaml
openapi: 3.0.3
info:
  version: 1.0.0
  title: Test
  description: Test
servers:
  - url: "/api/1"
paths:
  /test:
    get:
      operationId: Test
      summary: Test
      description: Test
      responses:
        "200":
          description: Test
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: string
                    pattern: "^[0-9]{5,8}$"

```

This is rendered like this

![image](https://user-images.githubusercontent.com/5650488/235916584-3bdd1d8c-fe57-4948-8d88-e386ea369414.png)

As you can see the example is rendered as `{"test": "string"}` that is not valid against the schema.

I was planning to open a PR on the https://github.com/Redocly/openapi-sampler repository for generating examples using `randexp` but I saw in the readme that

> Deterministic (given a particular input, will always produce the same output)

so I stop :smile:

**Comment by Sandrakay49** [comment]
I want to know who doing this and I want name and everything on these
people who are hacking into my stuff because they are hacking into my other
stuff this makes 2 or 3  times you guys has sent me something saying that
am doing it
I don't understand everything on that site am new at. It and am hardly ever
on there
So find out who doing this to me and I want name
Thanks you

sandra Rice

**Comment by Orest-Yastremskyy** [comment]
Hi @albertored 
I will reopen this issue in the openapi-sampler repository and close this one. Thank you so much for reporting this.

**Comment by AlexVarchuk** [comment]
Hi @albertored, thanks for the issue.  OpenAPI sampler does not support  it for now, but I believe may. We'll discuss it.
For now you can use `example` field for provide value to right panel.
