### ISSUE TITLE
Middle panel is scrolled up automatically after about a minute

### ISSUE THREAD

**Issue by ambient-okada** [Redocly/redoc#2316]
**Describe the bug**
I'm using RedocStandalone component in react app.  
While click the api at lower in left panel or scroll to the api at lower in middle panel and then hold the scroll position for about a minute, the scroll position is moved upper on its own.

**Expected behavior**
Keep the scroll position when click the api at left panel or scroll down.

**Comment by romanpryshliak** [comment]
Hi @ambient-okada,

I have made an attempt to reproduce this issue, but I have been unsuccessful.

Therefore, would you be able to share with us a sample react app where the problem can be recreated, along with a video recording that demonstrates how to reproduce it?

**Comment by ambient-okada** [comment]
Hi @romanpryshliak
I'm sorry. 
While I investigated in more detail,  the issue I had reported was not caused by Redoc. I could resolve the issue.
Please close this issue.

**Comment by romanpryshliak** [comment]
I appreciate the update @ambient-okada.

Closing as per your comment.
