### ISSUE TITLE
Add custom css and js to the redocly api registry.

### ISSUE THREAD

**Issue by aditya-docs** [Redocly/redoc#2317]
This is not a bug but a question:

With Redoc, adding any custom CSS and js to the index.html file is fairly simple. 

How do we achieve this on the cloud version (API registry)? My css file isn't getting picked up by the redocly cloud api registry service...

**Comment by Orest-Yastremskyy** [comment]
Hi @aditya-docs 

We will reply to you regarding this matter in the corresponding thread.

**Comment by aditya-docs** [comment]
Hi, @Orest-Yastremskyy Which thread exactly?

**Comment by Orest-Yastremskyy** [comment]
@aditya-docs 

We have already replied via email (to your query on May 16)
