### ISSUE TITLE
GraphHopper OpenAPI Spec has migrated

### ISSUE THREAD

**Issue by kayx23** [Redocly/redoc#2322]
![image](https://github.com/Redocly/redoc/assets/39619599/c62fb69a-ac7f-408f-a17d-0b44cd7335c6)

The spec was initially provided in https://github.com/Redocly/redoc/pull/1165

**Comment by kayx23** [comment]
Found https://docs.graphhopper.com, tried `blob:https://docs.graphhopper.com/45822373-dd1b-4b87-a18d-da896fea3f15` but it doesn't work

**Comment by AlexVarchuk** [comment]
Hi @kayx23. Thank you for the issue. We'll check it.
