### ISSUE TITLE
I got symbol instead of drop down arrow .

### ISSUE THREAD

**Issue by rexbti** [Redocly/redoc#2327]
![image](https://github.com/Redocly/redoc/assets/112849237/8cf51d63-5809-4f02-b4e7-37c373e4cadc)

In responses, I got a symbol instead of a dropdown. Also, I want to customize the response code as in the attached file. Please help.

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/redoc/issues/29, https://github.com/Redocly/redoc/issues/213 https://github.com/Redocly/redoc/issues/885, https://github.com/Redocly/redoc/issues/1984

Solution:
https://github.com/Redocly/redoc/issues/213#issuecomment-282761418

**Comment by rexbti** [comment]
I don't have an index.html file. I have integrated in a Python file.
