### ISSUE TITLE
$ref in description is not supported by OpenAPI spec

### ISSUE THREAD

**Issue by HRezaei** [Redocly/redoc#2328]
**Describe the bug**
While we can use $ref in the description of the contract and in the description of operations to refer to a separate markdown file, this tag is not supported by the Open API spec and raises an error, for example in Swagger Editor.

**Expected behavior**
It could be implemented using `x-` prefix which is officially supported. Since this is used widely by redocly, for example for `x-codeSamples`, I'm wondering why the same approach is not followed for adding markdown files to description? Something like `x-additionalDescription`. 

**Minimal reproducible OpenAPI snippet**
```
openapi: 3.0.1
info:
  title: My Web Service
  version: 1.0.0
  description:
     $ref: "/description.md"
```
**Screenshots**
<img width="1280" alt="image" src="https://github.com/Redocly/redoc/assets/657216/309baa88-d48f-4538-ba54-56a41d45fd73">

**Additional context**

Other users have had similar issues:
https://stackoverflow.com/questions/74297572/#comment-131172013

[https://stackoverflow.com/questions/76073137](https://stackoverflow.com/questions/76073137/is-ref-allowed-in-info-description-in-openapi-3-0-3-1-documents)

**Comment by AlexVarchuk** [comment]
Hi @HRezaei. We know that but support $ref in description. If we change that it broke too many definitions. I believe we should not deprecate that feature.

**Comment by lornajane** [comment]
Just jumping in to add that I think it should be possible to create a rule to check this for anyone that does need the strict `$ref` checking. It's not a high priority but it's on the list (assuming nobody else builds it first!)

**Comment by HRezaei** [comment]
Thank you @AlexVarchuk and @lornajane for your replies.
>If we change that it broke too many definitions. I believe we should not deprecate that feature.

Fair enough, but what about adding `x-additionalDescription` or something similar without deprecating `$ref`? I think just adding a new feature doesn't break other things, am I missing something?

**Comment by lornajane** [comment]
If it makes sense for you to keep using $ref in description, the Redocly tools still support that. For an OpenAPI description that needs to be used by other tools, you can drop back to the basic OpenAPI support and use markdown in the OpenAPI file - we added [a rule `spec-strict-refs`] to help keep this approach consistent, which might also help.

An additional vendor extension could definitely be something we look at in the future, but it's not currently on our roadmap.
