### ISSUE TITLE
How to change the layout with a custom template

### ISSUE THREAD

**Issue by Freedisch** [Redocly/redoc#2329]
**Describe the bug**
We are currently using a custom template to modify the output from the generated docs, but there is no documentation or information indicating how to modify the layout of the generated docs with the custom template.

**Screenshots**

![Screenshot 2023-05-31 173645](https://github.com/Redocly/redoc/assets/82499435/a49bfeed-13dd-4669-b108-864725a18b7b)

![image](https://github.com/Redocly/redoc/assets/82499435/41d393d5-67c5-4eee-a69a-d175f9adbe2a)

**Comment by romanpryshliak** [comment]
Hi @Freedisch,

To control the docs functionality and customize their styles, you can use the options by the links below.

Note: Redoc only supports the options with the `Supported in Redoc CE` label.

Configuration options:
https://redocly.com/docs/api-reference-docs/configuration/functionality/

Theming options:
https://redocly.com/docs/api-reference-docs/configuration/theming/

Please see how to pass the options in the HTML element:
https://redocly.com/docs/redoc/deployment/html/#the-redoc-object

and in the React component:
https://redocly.com/docs/redoc/deployment/react/#optional---pass-options

**Comment by Freedisch** [comment]
Hi @romanpryshliak, Thanks for that. It seems that customizing the layout with the open-source version of Redocly is not possible.

![Screenshot 2023-06-05 174026](https://github.com/Redocly/redoc/assets/82499435/11d59db5-7ca9-4483-a3ae-20f403880210)

**Comment by romanpryshliak** [comment]
@Freedisch, unfortunately, since this option is not supported, there is no way to change the layout of Redoc other than modifying it with a custom code or using Redocly API docs.
