### ISSUE TITLE
Migration instructions for redoc-cli to redocly?

### ISSUE THREAD

**Issue by clairestreb** [Redocly/redoc#2330]
We have a simple documentation project that was using redoc-cli, but that no longer installs with the latest npm/node, so I'm wondering how to: 1) Install redocly without a docker or webpack, just a straight file system on Windows, and 2) Build my doc?

**Comment by Orest-Yastremskyy** [comment]
Hi @clairestreb,

Thank you for reporting this. Let us check why the installation of the Redocly CLI fails and get back to you with an update.
