### ISSUE TITLE
Format openapi using Redocly

### ISSUE THREAD

**Issue by Zacama** [Redocly/redoc#2331]
Hello, when I regenerated a manually written openapi single file using split and bundle successively, I found that the order of the elements has changed, so I tried to find formatting commands in the redocly documentation, but I couldn't find it. Excuse me. Does redocly have a command for directly formatting a single file?

**Comment by Orest-Yastremskyy** [comment]
Hi @Zacama 
Please, refer to the article below for detailed information regarding the Redocly bundle command:

https://redocly.com/docs/cli/commands/bundle/

All options for the Redocly bundle command can be found in the Options section:

https://redocly.com/docs/cli/commands/bundle/#options

Hope it helps.

**Comment by lornajane** [comment]
I'd like to add that we recently made a change to the `redocly bundle` command so that the output will always be in a specific order. The order isn't configurable, but it will now always be consistent. Changelog entry is here https://redocly.com/docs/cli/changelog/#100-beta126-2023-05-10
