### ISSUE TITLE
Discriminators combined with arrays entirely break documentation of related properties

### ISSUE THREAD

**Issue by pbdeuchler** [Redocly/redoc#2332]
**Describe the bug**
If I want to accept an array of oneOfs, adding a descriptor breaks the documentation entirely

**Expected behavior**
I would expect the documentation to properly display discriminators and at the very least not break and show incorrect documentation

**Minimal reproducible OpenAPI snippet(if possible)**

```
openapi: 3.0.3

info:
  title: Pet Store

components:
  schemas:
    Dog:
      type: object
      properties:
        fur_color:
          type: string
          maxLength: 16

    Cat:
      type: object
      properties:
        is_outside:
          type: string
          maxLength: 16

    Pet:
      oneOf:
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Cat'
      # discriminator:
      #   propertyName: pet_kind

    PetCreate:
      type: object
      properties:
        resources:
          type: array
          description: ""
          items:
            $ref: '#/components/schemas/Pet'

paths:
  /pet:
    post:
      description: Creates a pet object
      operationId: create
      requestBody:
        description: An array of pets to create
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/PetCreate'
      responses:
        '201':
          description: Pets were created
```

Uncomment out the discriminator definition under `Pet` to see the bug
**Screenshots**
Without discriminator defined:
<img width="1392" alt="Screenshot 2023-06-06 at 10 40 41 PM" src="https://github.com/Redocly/redoc/assets/712346/9726bb5c-66af-42f5-ac89-86afc42a4eaf">

With discriminator defined:
<img width="1392" alt="Screenshot 2023-06-06 at 10 39 36 PM" src="https://github.com/Redocly/redoc/assets/712346/7031ea1c-5149-4337-8400-5fafb31a9e11">

**Additional context**
`1.0.0-beta.127`

**Comment by AlexVarchuk** [comment]
Hi @pbdeuchler, thank you for the issue. I believe you used an invalid discriminator. Please check documentation of [that](https://redocly.com/docs/resources/discriminator/). I try to use valid discriminator and seems behavior is correct.

```yaml

components:
  schemas:
    Dog:
      type: object
      properties:
        fur_color:
          type: string
          maxLength: 16
        pet_kind:
          type: string
          maxLength: 16

    Cat:
      type: object
      properties:
        is_outside:
          type: string
          maxLength: 16
        pet_kind:
          type: string
          maxLength: 16

    Pet:
      oneOf:
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Cat'
      discriminator:
        propertyName: pet_kind

    PetCreate:
      type: object
      properties:
        resources:
          type: array
          description: ""
          items:
            $ref: '#/components/schemas/Pet'
```
<img width="734" alt="Screenshot 2023-07-11 at 14 57 56" src="https://github.com/Redocly/redoc/assets/14113673/ce7119e1-06b7-4ad1-9d00-355aa2743b89">

If you still have a question, please reopen the issue. Thanks
