### ISSUE TITLE
How to fetch schema.yaml from private server?

### ISSUE THREAD

**Issue by 5er9e1** [Redocly/redoc#2341]
Our API server needs token to retrieve OpenAPI specification file and auth is based on `Authentication` header.
And when I'm trying to use `redoc.standalone.js`:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Example API</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='https://api.example.com/schema.yaml'></redoc>
    <script src="redoc.standalone.js"> </script>
  </body>
</html>
```

`https://api.example.com/schema.yaml` can't be downloaded without `Authentication: Bearer Blahblhablah` header.

Is it possible to:
1. extend `redoc.standalone.js`'s download method and add custom `auth` header?
2. download `schema.yaml` by different script and store to `sessionStorage` and after that read `schema.yaml` from storage instead of API server?

Any ideas how to get schema from private server will be appreciated.

**Comment by lornajane** [comment]
Redoc is a documentation renderer, you will need to fetch the schema file yourself and then use Redoc to render it. One approach that might fit is to [use the `redocly build-docs` command](https://redocly.com/docs/cli/commands/build-docs/)  to render the documentation and then publish the HTML. Alternatively, make the OpenAPI description available publicly as a first step, then use the documentation renderer as you are doing.

I hope that one of these suggestions helps; I'm closing the issue as I don't see anything more that's needed from Redoc, but let us know if you have more questions.

**Comment by 5er9e1** [comment]
> I'm closing the issue as I don't see anything more that's needed from Redoc, but let us know if you have more questions.

@lornajane
Yes. The current situation is unsolvable so the issue is may be closed. However, I can see what Redoc team is able to do, and that will be a really good feature. You may add option for retrieving schema. Let's say it may be a file saved into browser's local storage:

```html
<redoc spec-url='localstorage:stored-specs-key'></redoc>
```

This feature will really allow `to fetch the schema file yourself and then use Redoc to render it`
