### ISSUE TITLE
Expand all on Response Sections

### ISSUE THREAD

**Issue by michaelcilibrasi** [Redocly/redoc#2365]
How can I expand all sections in the middle content column?

I know this question has been asked before, and that it's a duplicate several times over, but I can't see the question as ever been actually answered. The other questions got complicated quickly and got off topic.

The issue comes up in two cases. The first is for document reviews. We can create a PDF of the page, but the PDF only includes sections that are expanded. In long or complicated guides, there are too many to manually expand, and we still miss a few when we do. The other case is that the browser-based find function finds only the text in expanded sections; complaints from customers I keep getting.

In the past few years, is there a way to open all the sections and section levels at one time?

**Comment by Orest-Yastremskyy** [comment]
Hi @michaelcilibrasi 
Thank you for reaching out.

Kindly note, that you can expand all responses using the `expandResponses: "all`` setting.
There is no corresponding option for schemas yet though. Thus, it is not possible to expand **all** sections in the middle pane.

Thank you for understanding.
