### ISSUE TITLE
Redocly CSS?

### ISSUE THREAD

**Issue by michaelcilibrasi** [Redocly/redoc#2366]
How can I change the CSS and styling of a Redocly page?

Specifically, there is too much spacing between a header and the subsequent text. I'd like to tighten that. I can't see in the config or theme file that that issue is addressed. It looks like I can change the font and font color, but not the spacing.

**Comment by Orest-Yastremskyy** [comment]
@michaelcilibrasi 

Please note that you can add the CSS to your HTML template in the corresponding section (e.g. title, body, etc.). You can see some CSS added to the title section:

![image](https://github.com/Redocly/redoc/assets/96121440/1d8890d5-86a5-4fae-8d75-036d0e2e0acc)

**Comment by michaelcilibrasi** [comment]
Thanks. However, I don't use the HTML template. I generate directly from Redocly, or save it as a separate HTML file. I could modify that HTML afterwards but I would rather do it during the generation. It's that, or I don't understand what you're referring to.

**Comment by Orest-Yastremskyy** [comment]
Yes, it is described in the Readme for Redoc:

https://github.com/Redocly/redoc#tldr-final-code-example
