### ISSUE TITLE
Individual Pages?

### ISSUE THREAD

**Issue by michaelcilibrasi** [Redocly/redoc#2367]
How can I render a document to have separate pages for each request? 

Instead of having a document with one long scrolling page, I'd like to have each request on it's own page. How is this possible?

**Comment by Orest-Yastremskyy** [comment]
Hi @michaelcilibrasi,

Kindly note, that the pagination setting is not supported in Redoc, thus there is no built-in option to render endpoints as separate pages:

![image](https://github.com/Redocly/redoc/assets/96121440/00a33290-5b01-4709-982f-fd91fd5746c5)
