### ISSUE TITLE
Limited Chinese Search Support in Redoc

### ISSUE THREAD

**Issue by jagerzhang** [Redocly/redoc#2373]
I noticed that Redoc, the OpenAPI documentation generator, has limited support for searching Chinese characters. When using Redoc to generate API documentation for Chinese APIs, the search functionality does not work effectively with Chinese text.

Currently, Redoc's search feature primarily relies on English characters and doesn't provide comprehensive support for searching Chinese characters. This limitation hinders the usability of Redoc for Chinese-speaking users who need to search for specific content within the API documentation.

I would like to request improved support for searching Chinese characters in Redoc. Enhancing the search functionality to include Chinese characters would greatly benefit users who are working with Chinese APIs or documenting APIs in Chinese.

Thank you for your attention to this matter. I appreciate the effort put into developing Redoc, and I believe that improving Chinese search support would make it an even more valuable tool for a wider range of users.

Please let me know if you need any further information or clarification.

**Comment by nalesnichok** [comment]
Hi @jagerzhang 

Thank you for taking the time to share this idea with us.

I have added it to our list of ideas so that our Product Team can evaluate how it fits our roadmap.

We cannot guarantee that it will be approved nor can provide you with any timelines.

**Comment by jagerzhang** [comment]
@nalesnichok Thanks for your reply. Our team has already implemented Chinese search through secondary development. Can we merge this feature into the master branch?

![image](https://github.com/Redocly/redoc/assets/9711651/cccd17e7-6abe-4096-94e4-d1455b6c74fe)
![image](https://github.com/Redocly/redoc/assets/9711651/83ced9f4-ac43-4a50-81be-c3e13109c65e)
![image](https://github.com/Redocly/redoc/assets/9711651/55316e6f-8db1-4276-8adf-e53bd5fc9590)

**Comment by RomanHotsiy** [comment]
@jagerzhang did you open a PR? If not, please open and we'll review it.

**Comment by jagerzhang** [comment]
> @jagerzhang did you open a PR? If not, please open and we'll review it.

My partner has already submitted, please help review.

**Comment by lornajane** [comment]
I'm sorry but we don't have the resources to maintain chinese language support in the Redoc project, so I'm closing the issue.

**Comment by fakeyanss** [comment]
我按照你的提交修改了`SearchWorker.worker.ts`文件，但是本地`npm run start`测试中文搜索没有生效。可以帮助我看一下问题吗？谢谢～

I have made changes to the `SearchWorker.worker.ts` file based on your submission, but the Chinese search has not been effective in the local `npm run start` test. Can you help me look into the issue? Thank you!

<img width="956" alt="image" src="https://github.com/Redocly/redoc/assets/30440198/0f3108fe-0a92-47bd-baa2-66c50b79d19b">
