### ISSUE TITLE
No documentation on how to enable interactivity with REST service for OpenAPI spec

### ISSUE THREAD

**Issue by adriansuarez** [Redocly/redoc#2377]
**Describe the bug**

I spent some time creating a Helm chart for the Redoc that should allow to deploy it alongside the actual REST service that it is documenting and allow the user to interact with the actual REST API.

But there is no documentation on how to enable interactivity, and it does not seem to work by default, even though my spec contains the base URL that the server is reachable by. I am expecting Redoc to have the same functionality as Swagger UI, where I am able to interact with the REST service... Does this not work?

**Expected behavior**

I expect Redoc to allow me to issue requests to the REST service.
Otherwise, creating a web server for Redoc does not add any value beyond what I get from just generating the single page documentation using `redocly` CLI.

**Comment by adriansuarez** [comment]
After searching through some older issues, it looks like the "Try It" thing is a paid feature. I'm not the first person to be confused about this, so it would be good to make the docs clearer.

I think it's a very misleading to have a README in GitHub with the title "Generate interactive API documentation from OpenAPI definitions", and you cannot actually access that functionality via any of the code in GitHub.

**Comment by lornajane** [comment]
Thanks for raising this. To be clear, you are correct and the "Try It" is only available on our hosted platform, not in the open source product. We're working on some changes and docs updates, getting feedback like this really helps!
