### ISSUE TITLE
What parameters are used to decide between a button or dropdown style for polymorphic types?

### ISSUE THREAD

**Issue by seglo** [Redocly/redoc#2380]
I've looked at several different examples and their underlying OpenAPI schemas, but I can't figure how redoc decides which way to render `oneOf` types with discriminator property defined.

**Comment by Orest-Yastremskyy** [comment]
Hi @seglo 
Let us check it, please.

**Comment by Orest-Yastremskyy** [comment]
@seglo 
Please, refer to the articles below for detailed information regarding discriminators:

https://redocly.com/docs/openapi-visual-reference/discriminator/
https://redocly.com/docs/resources/discriminator/

Hope it helps.
