### ISSUE TITLE
Qi.withComponent is not a function while rendering RedocStandalone

### ISSUE THREAD

**Issue by fatmabostan** [Redocly/redoc#2381]
here is the my problem:
`Uncaught runtime errors:
ERROR
Qi.withComponent is not a function
./node_modules/redoc/bundles/redoc.browser.lib.js/</<@http://localhost:3000/static/js/bundle.js:345906:20
./node_modules/redoc/bundles/redoc.browser.lib.js/</<@http://localhost:3000/static/js/bundle.js:349997:6
./node_modules/redoc/bundles/redoc.browser.lib.js/<@http://localhost:3000/static/js/bundle.js:349998:4
./node_modules/redoc/bundles/redoc.browser.lib.js/<@http://localhost:3000/static/js/bundle.js:339075:28
./node_modules/redoc/bundles/redoc.browser.lib.js@http://localhost:3000/static/js/bundle.js:339076:2
options.factory@http://localhost:3000/static/js/bundle.js:364297:31
__webpack_require__@http://localhost:3000/static/js/bundle.js:363742:33
fn@http://localhost:3000/static/js/bundle.js:363954:21
./src/pages/DocsPage/DocsPage.js@http://localhost:3000/static/js/bundle.js:2142:82
options.factory@http://localhost:3000/static/js/bundle.js:364297:31
__webpack_require__@http://localhost:3000/static/js/bundle.js:363742:33
fn@http://localhost:3000/static/js/bundle.js:363954:21
./src/App.js@http://localhost:3000/static/js/bundle.js:423:101
options.factory@http://localhost:3000/static/js/bundle.js:364297:31
__webpack_require__@http://localhost:3000/static/js/bundle.js:363742:33
fn@http://localhost:3000/static/js/bundle.js:363954:21
./src/index.js@http://localhost:3000/static/js/bundle.js:2075:81
options.factory@http://localhost:3000/static/js/bundle.js:364297:31
__webpack_require__@http://localhost:3000/static/js/bundle.js:363742:33
@http://localhost:3000/static/js/bundle.js:364879:56
@http://localhost:3000/static/js/bundle.js:364881:12
`
and my code:

import { RedocStandalone } from "redoc";
const DocsPage = () => {
  return(<RedocStandalone
    specUrl="http://petstore.swagger.io/v2/swagger.json"
    options={{
      nativeScrollbars: true,
      theme: { colors: { primary: { main: '#dd5522' } } },
    }}
  />)
}
export default DocsPage;

I cant fix this, could you help me? Thanks

**Comment by romanpryshliak** [comment]
Hi @fatmabostan,

Can you please share your `package.json` file with us?

**Comment by fatmabostan** [comment]
yes, sorry. Here it is
> {
  "name": "mobiliz-dev-ui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "core-js": "^3.32.0",
    "mobx": "^6.10.0",
    "openapi": "^1.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.10.1",
    "react-router-dom": "^6.14.2",
    "react-scripts": "5.0.1",
    "redoc": "^2.0.0",
    "styled-components": "^6.0.7",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

>

**Comment by romanpryshliak** [comment]
@fatmabostan,

Could you please revert to `styled-components` version 5 instead of 6.0.7 and let me know if it resolves the issue?

E.g.:
`"styled-components": "^5",`

**Comment by fatmabostan** [comment]
Still same @romanpryshliak but I found this ![Ekran görüntüsü 2023-08-10 222536](https://github.com/Redocly/redoc/assets/83615661/96625906-6d1b-45e9-b316-418ec87d4e52)

**Comment by romanpryshliak** [comment]
@fatmabostan,

Thank you for giving it a try.

Unfortunately, I've been able to reproduce this matter in my sample react app only by using the `6.x` version of the `styled-components`. Therefore, would it be possible for you to provide us with a sample project that showcases this issue?

**Comment by rjp44** [comment]
I also hit this issue on a new install of redoc into an existing app to replace swagger-ui. Forcing styled-components to "^5" in package.json immediately resolved it for me too.
