### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by psmoros** [Redocly/redoc#2388]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ilaygoldman) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by lornajane** [comment]
Thanks for reaching out to us, you can find our policy and contact details here https://redocly.com/vulnerability-disclosure-policy/#reporting-a-vulnerability

Also a good point about adding security files, thank you.

**Comment by lornajane** [comment]
I'll close this, but please let us know if further action is needed.
