### ISSUE TITLE
We are facing issues while updating the title and description of the swagger schema.

### ISSUE THREAD

**Issue by mastery-sopan-rathod** [Redocly/redoc#2394]
**Describe the bug**
We are facing issues after updating the title and description of the swagger schema. Locally, it is working, but after deployment, it's not replicating our changes.

**Expected behavior**
It should replicate our updated title and description after deployment.

**Screenshots**
Expected Result
<img width="410" alt="MicrosoftTeams-image (4)" src="https://github.com/Redocly/redoc/assets/118161073/c658b238-b338-4622-8faa-52372b598eb8">

Actual Result
<img width="397" alt="image" src="https://github.com/Redocly/redoc/assets/118161073/336d084a-aca7-4c76-ac68-ea299d781502">

**Additional context**
Swagger Version="6.5.0"

**Comment by Orest-Yastremskyy** [comment]
Hi @mastery-sopan-rathod 
Thank you for reaching out.

Could you provide us with a minimal setup and steps to replicate this matter?

**Comment by lornajane** [comment]
This issue has been open for some time without further engagement, so it will be marked as closed.
