### ISSUE TITLE
Adding JavaScript statements and executing them in a YAML file

### ISSUE THREAD

**Issue by ATUFO** [Redocly/redoc#2418]
**Describe the problem to be solved**

Can JavaScript statements be added and executed in a YAML file? The background is that we only provide YAML files and there is a unified application that renders the YAML (the application probably using the `<redoc>` tag). So we don't have control over the HTML. Is it possible to add some JS statements in the YAML file to perform some personalized operations?

Thanks!

**Comment by ATUFO** [comment]
Thanksfor your response! It seems that Redoc only supports the OpenAPI specification. Does Redoc have its own configuration options in the YAML file to customize the rendering? For example, defaulting to expand all responses which are currently collapsed.

**Comment by lornajane** [comment]
Yes, there's an `expandResponses` option (see docs: https://redocly.com/docs/redoc/config/#expandresponses) which allows you to specify the status codes to expand responses for. It sounds like that can do what you describe.
