### ISSUE TITLE
Server Variables not getting resolved

### ISSUE THREAD

**Issue by e3aa3b** [Redocly/redoc#2429]
As per Open API Spec, we can define server variables. E.g.

openapi: 3.0.2
servers:
  - url: /{basePath}/v3
    variables:
      basePath:
        default: /basepathdefault

However, when I try to access {basePath}, redoc isn't translating it to include the {basePath} under the full path when we click on respective endpoint. The path shows as:

http://localhost:3000/{basePath}/v3/pet/{petId}

instead of:

http://localhost:3000/basepathdefault/v3/pet/{petId}

**Comment by romanpryshliak** [comment]
Hi @e3aa3b, 

It is possible to display the default server variable value by adding the following configuration option:

`expandDefaultServerVariables: true`

Refer to these articles for more details:
https://redocly.com/docs/api-reference-docs/configuration/functionality/#path=expandDefaultServerVariables
https://redocly.com/docs/openapi-visual-reference/server-variables/#visuals

Should you have any additional questions regarding the matter, please reopen this issue.
