### ISSUE TITLE
$ref not rendering descriptions correctly

### ISSUE THREAD

**Issue by monica-m-ps** [Redocly/redoc#2431]
**Describe the bug**
The $ref doesn't render as expected.
So this is what the developer's yaml file looks like:

```
 amount:
     $ref: '#/components/schemas/Money'
     description: >-
         <some text>
  
   cashbackAmount:
      $ref: '#/components/schemas/Money'
      description: <some text>
```

This is what I generated using redocly:

```
  amount:
       description:
           $ref: ../../../prose/parameters/amount.md
       $ref: ./Money.yaml

  cashbackAmount:
      description:
          $ref: ../../../prose/parameters/cashbackAmount.md
      $ref: ./Money.yaml
```

*Money.yaml*

```
title: Money
required:
  - value
  - currencyCode
type: object
properties:
  value:
    format: int32
    description: <some text>
    type: integer
  currencyCode:
    $ref: ./CurrencyCode.yaml
    description:     
      $ref: ../../../prose/parameters/currencyCode.md
    maxLength: 10
    minLength: 1
```

In my output, the descriptions $ref do not populate correctly for 'amount' and 'cashbackAmount'.

As a hack, I've added 'oneOf' like this:

```
 amount:
    description:
      $ref: ../../../prose/parameters/amount.md
    oneOf: 
      - $ref: ./Money.yaml
 cashbackAmount:
    description:
      $ref: ../../../prose/parameters/cashbackAmount.md
    oneOf: 
      - $ref: ./Money.yaml
```

This is logically incorrect because `money` properties cannot be "oneOf". 

**Expected behavior**
       
```
      description:
           $ref: ../../../prose/parameters/amount.md
```

`amount` and `cashbackAmount` descriptions render correctly even without `oneOf`.

**Minimal reproducible OpenAPI snippet(if possible)**
Already added to description above.

**Screenshots**
<img width="782" alt="image" src="https://github.com/Redocly/redoc/assets/94380874/50eb82d2-651f-44d6-8b55-4c39ff5c1536">

**### If I add `oneOf`,**
<img width="740" alt="image" src="https://github.com/Redocly/redoc/assets/94380874/2020d886-4eb3-44b8-a159-dc2e573f132d">

**Comment by jeremyfiel** [comment]
which OpenAPI version are you using?  

in OAS 3.0.x, `$ref` does not allow siblings, such as `description`; they are ignored. If you want to have both properties, they must be defined with `allOf`

```yaml
amount:
  allOf:
    - $ref: "#/components/schemas/Money"
    - description: >-
        <some text>

cashbackAmount:
  allOf:
    - $ref: "#/components/schemas/Money"
    - description: <some text>

```

here's an example of your description
```yaml
openapi: 3.0.3
info:
  title: test
  version: 1.0.0
paths:
  /thing:
    get: 
      responses: 
        '200': 
          description: OK
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/Money'
components:
  schemas:
    Money:
      title: Money
      required:
        - value
        - currencyCode
      type: object
      properties:
        value:
          format: int32
          description: <some text>
          type: integer
        currencyCode:
          allOf:
            - description:
                $ref: ./currency.md
            - $ref: ./CurrencyCode.yaml
          maxLength: 10
          minLength: 1
```

```markdown
// currency.md
# currency.md

## it works

here's some text from currency.md referenced with allOf
```

```yaml
// CurrencyCode.yaml
description: description from the CurrencyCode.yaml
enum:
  - USD
  - CAD
  - EUR
  - MXN
```


![image](https://github.com/Redocly/redoc/assets/32110157/ee03de28-249d-4c7b-b6ac-94160b78f84e)

**Comment by monica-m-ps** [comment]
Ohkay, I see. I'll give this a shot. Thank you so much!

**Comment by jeremyfiel** [comment]
If this solved your issue, please close it. 

thanks for raising this issue, I'm sure others have run into something similar.  Have a great day!

**Comment by monica-m-ps** [comment]
Yes, resolved. Thank you!
