### ISSUE TITLE
Exclude files from indexing

### ISSUE THREAD

**Issue by vtlkvl** [Redocly/redoc#2441]
**Describe the problem to be solved**
Our GitHub project contains various OpenApi specs and not all of them should be exposed in the portal, however it is possible to find them via search.

**Describe the solution you'd like**
We should be able to exclude specific files or directories from being indexed and searchable.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by AlexVarchuk** [comment]
Hi @vtlkvl, seems you aren't using the open-source version on Redoc.

Please, contact [team@redocly.com](mailto:team@redocly.com) for our commercial product support.
