### ISSUE TITLE
Using custom font with the 'redocly build-docs' cli command documentation is missing

### ISSUE THREAD

**Issue by oleksii-threatray** [Redocly/redoc#2458]
**Describe the bug**
There are [docs](https://redocly.com/docs/api-reference-docs/guides/use-custom-fonts/) describing how to use a custom font with Redoc.
N2 step for the `Custom font in  API docs`  option says "Import the font into the HTML template."
For a case of using the cli command  `redocly build-docs` to generate the html from yml there might be no special template used.
In such a case it's not clear what user has to modify to use a custom font.

**Expected behavior**
A clear and concise description of how to use a custom font in a case of using `redocly build-docs` cli command,
including the location of a template to modify.

**Comment by ZyzychO** [comment]
Hello Oleksii,

Thank you for providing your feedback.

Kindly note that information regarding the utilization of the HTML template can be found on the page featuring the 'redocly build-docs' command guide.

https://redocly.com/docs/cli/commands/build-docs/#usage

The following showcases the command and the HTML template that includes imported custom fonts.

redocly build-docs openapi2.yaml --template index2.html

```html

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>API Reference | ReDoc</title>
    <!-- needed for adaptive design -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="favicon.png">


    <!--
    ReDoc uses font options from the parent element
    So override default browser styles
    -->
    <style>
    @font-face {
    font-family: 'YourCustomFont';
    src: url('https://fonts.googleapis.com/css2?family=Dancing+Script&family=Shadows+Into+Light&display=swap') format('woff2');
         
    font-weight: normal;
    font-style: normal;
  }

  body * {
   font-family:'Dancing Script', cursive;
   font-size: 12px;
  }
    </style>
    {{{redocHead}}}
  </head>
  <body>
    {{{redocHTML}}}
  </body>
</html>

```

**Comment by oleksii-threatray** [comment]
@ZyzychO thanks a lot for coming back to me. Separate thanks for providing an example!
I will try it out in a few days.

**Comment by oleksii-threatray** [comment]
Thanks for the help!

**Comment by lornajane** [comment]
@ZyzychO This is very good, could you add the example to the docs page you referenced, please?
