### ISSUE TITLE
Tag long descriptions

### ISSUE THREAD

**Issue by gierschv** [Redocly/redoc#246]
Hey there,

I wanted to use the descriptions of the tags to add more content and context about the different methods available in the tags, however putting long text in the description breaks swagger-ui and the different tools using the description.

Do you think we could add something similar to `x-displayName`? Maybe `x-displayDescription` or `x-longDescription`? If so, let me know, I will be happy to PR.

Thanks,
Vincent

**Comment by lornajane** [comment]
I don't think this extension is needed, the tag descriptions display quite well.
