### ISSUE TITLE
`Try it` console and `generateCodeSamples` with `RedocStandalone`?

### ISSUE THREAD

**Issue by vishalbd** [Redocly/redoc#2462]
Hi, this is probably the wrong place for this, but asking here because I could not find anything regarding this in the docs.

I am trying to create an API docs page in my Next.js app and the `RedocStandalone` component seems to be exactly what I need, but it seems that it is missing a couple of features in its options that are listed for the CLI. Is there any way to use the `Try it` console or generate code sample with the component in React?

**Comment by romanpryshliak** [comment]
Hi @vishalbd,

Enabling the Try-it console and auto-generated code samples isn't possible in Redoc. These functionalities are exclusively available in our premium product - [Redocly API docs](https://redocly.com/reference/).

Should you have any further queries on this topic, feel free to reopen it.
