### ISSUE TITLE
`redocly lint` fails for `exclusiveMinimum` in an OpenAPI 3.0 spec

### ISSUE THREAD

**Issue by jandppw** [Redocly/redoc#2467]
**Describe the bug**
In an OpenAPI spec that says:

```yaml
openapi: 3.0.3
info:
  title: funds
```

`redocly lint` returns

```
[67] […]

Example validation errored: exclusiveMinimum value must be ["number"].

 8 |   required: true
 9 |   schema:
10 |     minimum: 0
11 |     exclusiveMinimum: true
 … |     < 5 more lines >
17 |     example: 1
18 | - name: planLabel
19 |   in: path
```

This is because of a non-backward compatible (!) change from OpenAPI 3.0 to OpenAPI 3.1, as described in [ExclusiveMinimum and ExclusiveMaximum](https://www.apimatic.io/blog/2021/09/migrating-to-and-from-openapi-3-1).

**Expected behavior**

The schema should pass when the OpenAPI spec says it is version 3.0, unless `redoc` no longer supports this version.

**Note**

This creates issues when using `joi-to-json` ≥ 4.1.0 (see https://github.com/kenspirit/joi-to-json/issues/49).

**Comment by jeremyfiel** [comment]
Can you explain why you think this is a Redocly issue? I don't see Redocly used in the Joi package. 

When I try to reproduce it: 


### this is giving me the correct validation
```yaml
openapi: 3.0.3
info:
  title: blah
  version: 1.0.0
servers:
  - url: www.redocly.com
paths:
  /v1/thing:
    get:
      summary: a summary
      description: a description
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                type: number
                minimum: 0
                exclusiveMinimum: true
```

### This throws for  

```bash
Expected type `boolean` but got `integer`.
```

```yaml
openapi: 3.0.3
info:
  title: blah
  version: 1.0.0
servers:
  - url: www.redocly.com
paths:
  /v1/thing:
    get:
      summary: a summary
      description: a description
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                type: number
                exclusiveMinimum: 0
```


```bash
redocly 1.5.0
```

**Comment by jandppw** [comment]
Thank you for the apt response.

(The issue I tried to report has nothing to do with Joi, or any other library. That was just a side note and cross-reference.)

You're tests are undoubtedly correct, and seem to negate my report.

I reported what I encountered, and this shows that I probably missed the boat. I'll try to find the time to dig a little deeper, and report back.

**Comment by jeremyfiel** [comment]
Try updating your redocly package.  

`npm install --global @redocly/cli@latest`

Happy to help if you still encounter the same issue.

**Comment by lornajane** [comment]
It doesn't look like there's anything more for us to do here, so I'll close the issue for now - but do let us know if you need anything else.
