### ISSUE TITLE
DownloadDefinitionUrl for multiple OpenAPI specs

### ISSUE THREAD

**Issue by monica-m-ps** [Redocly/redoc#2478]
**Describe the bug**
Hello. I have 2 OAS files

https://docs.dojo.tech/payments/api
https://docs.dojo.tech/unified-payments/api/

They are part of the same repository. Is there a way to enable downloading of the respective json files separately? If you see, I can only download the json in the first link... 

I have configured `downloadDefinitionUrl` but of course it takes only one file. 

**Expected behavior**
We should be able to download JSON files of multiple openapi specs.

**Additional context**
We are expecting more APIs so this use case will really help. Thank you!

**Comment by ZyzychO** [comment]
Hello @monica-m-ps  I see the download button in both links to OAS. 

Could you please confirm if the issue was resolved?

**Comment by monica-m-ps** [comment]
Yes sorry this is resolved. I had to set the location to ./bundled.json instead of bundled.json. And it can download multiple jsons.
