### ISSUE TITLE
msn@amata.com

### ISSUE THREAD

**Issue by Usermsn** [Redocly/redoc#2517]
**Describe the bug**

**Expected behavior**

**Minimal reproducible OpenAPI snippet(if possible)**

**Screenshots**

**Additional context**

**Comment by Usermsn** [comment]
atfb.co.th.
U104
B 5402072

**Comment by a169074** [comment]
https://maps.app.goo.gl/?link=https://www.google.com/maps/place/Fabbit%2BGlobal%2BGateway,%2B18%2BRatchadaphisek%2BRd,%2BKhlong%2BToei,%2BBangkok%2B10110/data%3D!4m2!3m1!1s0x30e29f264685f777:0xa07253327dd5e54f?utm_source%3Dmstt_1%26entry%3Dgps&apn=com.google.android.apps.maps&afl=https://www.google.com/maps/place/Fabbit%2BGlobal%2BGateway,%2B18%2BRatchadaphisek%2BRd,%2BKhlong%2BToei,%2BBangkok%2B10110/data%3D!4m2!3m1!1s0x30e29f264685f777:0xa07253327dd5e54f?utm_source%3Dmstt_1%26entry%3Dgps&isi=585027354&ibi=com.google.Maps&ius=comgooglemapsurl&ifl=https://www.google.com/maps/place/Fabbit%2BGlobal%2BGateway,%2B18%2BRatchadaphisek%2BRd,%2BKhlong%2BToei,%2BBangkok%2B10110/data%3D!4m2!3m1!1s0x30e29f264685f777:0xa07253327dd5e54f?utm_source%3Dmstt_1%26entry%3Dgps&cid=7702191553177685757&_osl=https://maps.app.goo.gl/pBStafv6XVVWemR96&_icp=1 https://maps.app.goo.gl/?link=https://www.google.com/maps/place/Fabbit%2BGlobal%2BGateway,%2B18%2BRatchadaphisek%2BRd,%2BKhlong%2BToei,%2BBangkok%2B10110/data%3D!4m2!3m1!1s0x30e29f264685f777:0xa07253327dd5e54f?utm_source%3Dmstt_1%26entry%3Dgps&apn=com.google.android.apps.maps&afl=https://www.google.com/maps/place/Fabbit%2BGlobal%2BGateway,%2B18%2BRatchadaphisek%2BRd,%2BKhlong%2BToei,%2BBangkok%2B10110/data%3D!4m2!3m1!1s0x30e29f264685f777:0xa07253327dd5e54f?utm_source%3Dmstt_1%26entry%3Dgps&isi=585027354&ibi=com.google.Maps&ius=comgooglemapsurl&ifl=https://www.google.com/maps/place/Fabbit%2BGlobal%2BGateway,%2B18%2BRatchadaphisek%2BRd,%2BKhlong%2BToei,%2BBangkok%2B10110/data%3D!4m2!3m1!1s0x30e29f264685f777:0xa07253327dd5e54f?utm_source%3Dmstt_1%26entry%3Dgps&cid=7702191553177685757&_osl=https://maps.app.goo.gl/pBStafv6XVVWemR96&_icp=1[accie.pdf](https://github.com/user-attachments/files/18049566/accie.pdf)
