### ISSUE TITLE
Required properties in 3.1.0 spec not working when used as sibling

### ISSUE THREAD

**Issue by josefguenther** [Redocly/redoc#2527]
**Describe the bug**
When referencing another object without nesting in `allOf` (3.0 spec), Open API 3.1 spec allows us to declare required properties as sibling alongside `$ref` like this:

```
components:
  schemas:
    CreateAlbum:
      required: [ Description ]
      $ref: "#/components/schemas/Album"
    Album:
      type: object
      properties:
        Id:
          type: string
          readOnly: true
        Description:
          type: string
```

**Expected behavior**
In route request body, using CreateAlbum should show Description as being required. However, it only works when `$ref` is nested in `allOf`, like this:

```
    CreateAlbum:
      required: [ Description ]
      allOf: 
        - $ref: "#/components/schemas/Album"
```

**Comment by jeremyfiel** [comment]
I tested it and it seems to work as you expect. 

```yaml
openapi: 3.1.0
info:
  title: test
  version: '1'
paths:
  '/thing':
    post: 
      summary: testing a thing
      requestBody: 
        $ref: '#/components/requestBodies/thing_request'
      responses:
        '200':
          $ref: '#/components/responses/200'
components:
  schemas:
    CreateAlbum:
      required: [description]
      $ref: '#/components/schemas/Album'
    Album:
      title: a description
      properties:
        id:
          type: string
          readOnly: true
        description:
          type: string
  responses: 
    '200': 
      description: OK
      content:
        'application/json':
          schema: 
            $ref: '#/components/schemas/CreateAlbum'
  requestBodies: 
    thing_request:
      description: Create a new album
      content:
        'application/json':
          schema: 
            $ref: '#/components/schemas/CreateAlbum'

```

![image](https://github.com/Redocly/redoc/assets/32110157/96cba265-bfd5-45f7-99f1-a149d478501a)

--- 

Give it another shot and see if this example helps you understand where yours isn't working.


Just FYI, you'll find the `readOnly` annotation on `id` doesn't allow it to be visible in the request body, so the only property shown there is `description`.

**Comment by josefguenther** [comment]
Thanks for the response @jeremyfiel !

You are correct, was able to confirm! The issue is in the redoc cli which replaces the entire schema when you bundle and use $ref. I'm posting a bug report over there.
