### ISSUE TITLE
How to search for Chinese in redoc-static.html?

### ISSUE THREAD

**Issue by Bflren** [Redocly/redoc#2535]
**Is your feature request related to a problem? Please describe.**

My English is not very good, how can I search for Chinese in redoc-static.html?
**Describe the solution you'd like**
Search for Chinese in the search box in the upper right corner of redoc-static.html

**Describe alternatives you've considered**

**Additional context**

**Comment by fakeyanss** [comment]
Duplicated, see https://github.com/Redocly/redoc/pull/2379#issuecomment-1824673575

But I rewrote a little code for searching in Chinese. If you want to experience this, you can rely on my fork implementation, with the npm scope package being @fakeyanss/redocly-cli.

**Comment by Bflren** [comment]
@fakeyanss 栓Q
