### ISSUE TITLE
The v2.1.4 defines jest-environment-jsdom as prod dependency

### ISSUE THREAD

**Issue by piotr-cz** [Redocly/redoc#2537]
**Describe the bug**
After upgrading `@redocly/cli` from 1.11.0 to 1.12.0 I've noticed lots of new dependencies.

Turns out that these are pulled along with `jest-environment-jsdom`, which has been added as a *dependency* instead of *devDependency* here: https://github.com/Redocly/redoc/pull/2445/files

**Expected behavior**
Installing `@redocly/cli` or `redoc` package in a project should not install dependencies related to tests such as `jest`

**Minimal reproducible OpenAPI snippet(if possible)**

```
npm install @redocly/cli@^1.12.0
npm ls jest-environment-jsdom
```

**Screenshots**
-

**Additional context**
Jest Instructions for DOM manipulation testing: https://jestjs.io/docs/next/tutorial-jquery

```
npm install --save-dev jest-environment-jsdom
```

**Comment by AlexVarchuk** [comment]
@piotr-cz thank you for notifying us. PR opened.
