### ISSUE TITLE
Redocly website blocks access to API documentation

### ISSUE THREAD

**Issue by mryellow** [Redocly/redoc#2539]
https://redocly.com/ links to https://redocly.com/reference/ with the text "Explore API Docs".

This page does not contain any "API Docs" as described. Instead it contains more marketing text.

It should contain the API documentation.

I am a developer working for a customer of yours and this imposition by the marketing department has wasted my time.

**Comment by RomanHotsiy** [comment]
Thanks for raising in and sorry for the confusion but the "API Docs" here refers to a name of the product, not our docs.

![image](https://github.com/Redocly/redoc/assets/3975738/8e719505-a993-4b8a-a1d4-e1b81c0f045a)

This is the first time we hear this specific complaint, we will review what can be done there with our marketing.

I'll close this issue as it's unrelated to our open-source product. We also have a direct link to the docs in the README:

![image](https://github.com/Redocly/redoc/assets/3975738/1c3c38a2-c71d-4fe4-9725-80895770603d)
