### ISSUE TITLE
Redocly mangles some property names

### ISSUE THREAD

**Issue by DASPRiD** [Redocly/redoc#2541]
**Describe the bug**
In some cases it seems like Redocly mangles property names for no apparent reason. In the following OpenAPI spec, the property `expiresIn` gets displayed as `expirese`.

**Expected behavior**
Redocly should not mangle property names.

**Minimal reproducible OpenAPI snippet(if possible)**
```yaml
openapi: 3.1.0
info:
  title: Test API
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  expiresIn:
                    type: integer
```

**Screenshots**
![image](https://github.com/Redocly/redoc/assets/233300/2c78b41b-9c3a-4443-a151-a79ba3fb4c57)

**Comment by DASPRiD** [comment]
I tracked this down a little bit further, and it seems like the correct name makes it all the way down to React in `components/Fields/Field.tsx`. So I assume this might be a React bug.

I see that Redocly is stuck on React `17.0.2`. Since that is the latest release of that major version, and if this is actually not some configuration issue in Redocly's usage of React, the only way to fix this issue would be to upgrade the React dependency.

Just FYI, the name shows up correctly through the `title` attribute of the cell, but the name gets mangled as a text node of the `span` in React's `createElement()` somehow.

**Comment by AlexVarchuk** [comment]
Hi @DASPRiD, I tried to test it, and cannot reproduce it. I have correct field name `expiresIn`.
<img width="1192" alt="Screenshot 2024-05-23 at 12 27 41" src="https://github.com/Redocly/redoc/assets/14113673/1f93f4e8-6378-4d3c-aaec-da3b3c8fe404">

Please, provide additional information about reproducing it and we'll try to help you.

**Comment by DASPRiD** [comment]
Oh, I just figured out that one of my browser extensions was at fault, sorry for the noise, closing.

In case anyone else stumbles upon this, this is the extension in question: https://addons.mozilla.org/en-US/firefox/addon/binnen-i-be-gone/
