### ISSUE TITLE
The field "Upload File" doesn´t show

### ISSUE THREAD

**Issue by monique77** [Redocly/redoc#2542]
Hello,

I need a help please. I executed: docker run -p 8080:80 redocly/redoc   but the field "Upload file" in the top of page didn´t show, but in your redocly it shows.  In Redoc this option "Upload file" doesn´t exist? 
  
  And for me see mys apis I need put in SPEC_URL where they are? I understood that the Redoc doesn´t have database, because in this case I can put in SPEC_URL where the apis are? Redoc can do integration with api gateway?  like kong or others? 

![meuRedoc](https://github.com/Redocly/redoc/assets/7231409/815aa14d-2674-4e8a-a1b8-863f0312dafd)
![redoc](https://github.com/Redocly/redoc/assets/7231409/c0a320f7-1506-475e-919d-25c20f7a7251)l'

**Comment by AlexVarchuk** [comment]
hi @monique77, thank you for your question.
The `Upload a file` place we have only in preview Redoc page. It helps provide URL to OpenAPI description.
In docker container you should use `SPEC_URL`. And put correct URL to your OpenAPI description. You can host your definition where you want and pass it to docker.

```
docker run -p 8080:80 -e SPEC_URL=https://api.example.com/openapi.json redocly/redoc
```

If you have more questions feel free to ask.

**Comment by monique77** [comment]
@AlexVarchuk Tks for your answering
