### ISSUE TITLE
Disable "Response samples" section

### ISSUE THREAD

**Issue by gituserjava** [Redocly/redoc#2545]
Is there a way to disable the generation of the black vertical content (screenshot below) on the right side of the page that shows "Response samples" ?

![image](https://github.com/Redocly/redocly-cli/assets/64553468/1f1d843d-e186-4386-acfe-687896631ea4)

**Comment by AlexVarchuk** [comment]
Hi @gituserjava, you cannot disable Response samples using options. But you can write [custom decorators](https://redocly.com/docs/cli/custom-plugins/custom-decorators/#decorators-in-plugins) to remove samples.

You use the commercial products of Redocly. If you have more questions, please, contact [team@redocly.com](mailto:team@redocly.com) for our commercial product support.
