### ISSUE TITLE
Property `htmlTemplate` is not expected here.

### ISSUE THREAD

**Issue by mykelscappin** [Redocly/redoc#2553]
**Describe the bug**
When executing `redocly build-docs -o output.php` on terminal, i get this unexpected output
```
[1] redocly.yaml:26:5 at #/theme/openapi/htmlTemplate

Property `htmlTemplate` is not expected here.

24 | theme:
25 |   openapi:
26 |     htmlTemplate: redoc_template/index.php
27 |

Warning was generated by the configuration spec rule.


⚠️ Your config has 1 warning.
Found redocly.yaml and using theme.openapi options
```

**Expected behavior**
This error should not be happening - that configuration in `redocly.yaml` seems to be correct and supported as per all the documentation.

**Minimal reproducible OpenAPI snippet(if possible)**
n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by AuroraJMP** [comment]
I'm seeing the same with pathInMiddlePanel

**Comment by tcamise-gpsw** [comment]
I'm seeing this with several options after moving from 1.12.0 to 1.17.0. Was there some type of configuration overhaul? I don't see anything in the docs.

**Comment by lornajane** [comment]
Thanks for letting us know about this. We did change something in the config parsing - I recommend you pin to an older version for now for using existing configuration, I expect 1.14 to be a good version, but please report back if that doesn't help! We'll keep you posted with more information when we have it.

**Comment by KernelFolla** [comment]
I have the same issue with version 1.17.1. It doesn't work with version 1.17.0, but it operates correctly with version 1.16.0 .

**Comment by lornajane** [comment]
Could you try updating your CLI versions to the latest (1.18 or 1.19), please? Let us know if you still see anything that you didn't expect to, and if possible, could you share the configuration files you are using (or a snippet)

**Comment by tcamise-gpsw** [comment]
This seems to work for me on 1.22. Thanks!

**Comment by AlexVarchuk** [comment]
Closed based on 

> This seems to work for me on 1.22. Thanks!
