### ISSUE TITLE
Upgrade webpack to latest (5.94.0)

### ISSUE THREAD

**Issue by gheorghe-stefan** [Redocly/redoc#2581]
**Describe the problem to be solved**
We're using redoc-cli and via the redoc npm package it brings up the webpack 5.74. This package contains a vulnerability which got fixed in WebPack >= 5.94.0
<img width="631" alt="image" src="https://github.com/user-attachments/assets/c73678ca-7ea0-45ae-aa39-1a388e7837f0">

**Describe the solution you'd like**
Update used webpack in redoc to at least 5.94.0

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Dxuian** [comment]
[done](https://github.com/Redocly/redoc/pull/2583

**Comment by gheorghe-stefan** [comment]
Cool, thanks!
Waiting then for the approval, merge, and hopefully a new release including this ;)

**Comment by AlexVarchuk** [comment]
closed via
