### ISSUE TITLE
Upgrade DOMPurify to latest (2.5.4)

### ISSUE THREAD

**Issue by stefan-gheorghe-leica** [Redocly/redoc#2595]
**Describe the problem to be solved**
We're using redoc-cli and via the redoc npm package it brings up the dompurify 2.2.2. This package contains a vulnerability which got fixed in version >= 2.5.4
<img width="950" alt="image" src="https://github.com/user-attachments/assets/958169f8-0771-47d5-a85e-d1d19a7daa0b">

**Describe the solution you'd like**
Update used dompurify in redoc to at least 2.5.4

**Comment by stefan-gheorghe-leica** [comment]
See related https://github.com/Redocly/redoc/issues/2581

**Comment by AlexVarchuk** [comment]
closed via https://github.com/Redocly/redoc/pull/2602

**Comment by gheorghe-stefan** [comment]
Hi @AlexVarchuk , any news about https://github.com/Redocly/redoc/issues/2581 ?
Also when we could have a release of redocly including these 2 upgraded packages?
Thanks in advance.

**Comment by AlexVarchuk** [comment]
Hi @gheorghe-stefan, [dompurify](https://github.com/Redocly/redoc/pull/2602/files) already released  but [webpack](https://github.com/Redocly/redoc/pull/2583) have not merged yet.
I believe [webpack](https://github.com/Redocly/redoc/pull/2583) author of PR will merge it soon and we have it before the next release.
