### ISSUE TITLE
Is there an equivalent of redoc-cli's --cdn flag in Redocly CLI?

### ISSUE THREAD

**Issue by linouk23** [Redocly/redoc#2628]
**Describe the problem to be solved**
When we use the deprecated `redoc-cli`, we can see there was a `--cdn` flag:
```
➜  example-display-name git:(master) ✗ redoc-cli build --help
redoc-cli build <spec>

build definition into zero-dependency HTML-file [deprecated]

Positionals:
  spec  path or URL to your spec                                      [required]

Options:
      --help               Show help                                   [boolean]
...
      --cdn                Do not include ReDoc source code into html page, use
                           link to CDN instead        [boolean] [default: false]
```

We are in the process of migrating from `redoc-cli` to Redocly CLI by following https://redocly.com/docs/cli/guides/migrate-from-redoc-cli.

**Before**:
```
redoc-cli build <spec> --cdn
```

**After**:
```
redocly build-docs <spec> ?
```

![Image](https://github.com/user-attachments/assets/7b3e3e62-487b-4fbf-a325-630586b289d3)

However, I can't find `--cdn` as a supported option in https://redocly.com/docs/cli/commands/build-docs#options:

![Image](https://github.com/user-attachments/assets/6a12ce5a-7bd4-41e0-8132-2e571aedad1c)

**Describe the solution you'd like**
What flag should we use instead of `--cdn` in the redocly build-docs command?

Thank you!

**Comment by AlexVarchuk** [comment]
Hi @linouk23. Thank you for the question.
For now `redocly-cli` don't have a `--cdn` flag.The reason that supporting compatibility of different versions is very complicated.
Before we received a lot of issues like `redoc@x` version didn't work in `reodcly-cli@x` version.

But on `redocly-cli` already has opened an issue about that. You can follow it [here](https://github.com/Redocly/redocly-cli/pull/1835).

**Comment by shreelakshmijoshi** [comment]
> Hi [@linouk23](https://github.com/linouk23). Thank you for the question. For now `redocly-cli` don't have a `--cdn` flag.The reason that supporting compatibility of different versions is very complicated. Before we received a lot of issues like `redoc@x` version didn't work in `reodcly-cli@x` version.
> 
> But on `redocly-cli` already has opened an issue about that. You can follow it [here](https://github.com/Redocly/redocly-cli/pull/1835).

Hi @AlexVarchuk , does redocly-cli allow generating apidoc.html without cdn now? Is there any way in which we can avoid calling CDN due to IP leaks. We tried downloading the standalone.js file locally and tried self hosting it. Is there any other way to solve this issue? (either by redocly or redocly-cli)

**Comment by AlexVarchuk** [comment]
Hi @. You could try to use self-host dependency. 
https://redocly.com/docs/redoc/deployment/html#self-host-dependencies

**Comment by shreelakshmijoshi** [comment]
> Hi @. You could try to use self-host dependency. https://redocly.com/docs/redoc/deployment/html#self-host-dependencies

thanks for the quick reply @AlexVarchuk
