### ISSUE TITLE
Possibility of using the combination of API Method and API Path as URL fragment for navigating to particular API

### ISSUE THREAD

**Issue by harishav** [Redocly/redoc#2629]
Hi Team, 

We see that OperationId can be used as URL fragment to navigate the user to the particular API within the API Documentation page as mentioned in this [page](https://redocly.com/blog/operationid-is-api-design). 

I wanted to check if there is an option to use the combination of the API Method and API Path as an URL fragment to navigate ? 

Reason being, if i want to point out the user to a particular API on the API Doc page from some user documentation page, i need to explicitly check the operation id and use that in the doc. Instead, it would be easy to just use the method and path, so that explicit mapping is not needed to be maintained. 

**Example:** 
If API is, `GET /v1/products/{id}`

Can the URL fragment be, `#path/GET%20/v1/products/{id}` ??

Thanks in Advance!

**Comment by AlexVarchuk** [comment]
Hi @harishav, thank you for the question.
The Redoc doesn't have options to change the navigation path. Actually, it is not easy, and supporting multiple navigation strategies is very complicated.

**Comment by AlexVarchuk** [comment]
If you have any more questions feel free to reopen that issue. Thanks
