### ISSUE TITLE
Multiple ReDoc instances on single page

### ISSUE THREAD

**Issue by jenniferwang2000** [Redocly/redoc#278]
Thanks for this great [feature](https://github.com/Rebilly/ReDoc/blob/master/demo/examples/multiple-apis/index.html). I played around with it. 

I set up three individual instances(swagger1.yaml for instance1, swagger2.yaml for instance2, swagger3.yaml for instance3), and integrate them on a single page. I used markdown format to show **unordered bullets** in`description` in swagger3, the markdown bullets can be displayed in the separate instance 3 but can not be displayed in the integrated single page. 

Can we make the markdown bullets displayed in integrated single page?

I set the instance 1 as the API that is initially rendered. The instances 2 and 3 share the same URL with instance 1. I can get links to operations in instances 2/3, but these links only direct you to the initially rendered API tab, that is instance1, not the specific operation in instance 2/3. 

Can we use different URLs for instance 2 and 3, and make the links to operations in instance 2/3 work?

**Comment by RomanGotsiy** [comment]
@jenniferwang2000 

> Can we make the markdown bullets displayed in integrated single page?
I do not understand this. Can you explain better?

> Can we use different URLs for instance 2 and 3, and make the links to operations in instance 2/3 work?

to achieve this you can just have your each separate instance on the separate page so they will not share URL. Or you can setup client-side routing via push/pop state.
This is not the feature of ReDoc. This is just an example of how you can use it. I will try to update the example to add routing when I have some time

**Comment by philsturgeon** [comment]
Yeah I noticed this same thing. When it's on the same page it's going to share the same URL, so I just built a little ruby script that made different `foo.html` pages from a template. That's potentially easier than messing with the URL, but JavaScript _could_ do it.

**Comment by philsturgeon** [comment]
I opened up a very rough version of my Ruby logic which folks are welcome to hack and use or whatever. https://github.com/philsturgeon/redocaholic/blob/master/README.md

**Comment by RomanGotsiy** [comment]
@philsturgeon awesome tool and name 😆

@jenniferwang2000 is this question still open for you? Do you need routing example?

**Comment by marcelstoer** [comment]
I guess this should be closed by now but the redocaholic repo appears to be at https://github.com/workivate/redocaholic now.
