### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by bernieh-atlnz** [Redocly/redoc#280]
Hi there,

I just wanted to ask about a couple of potential usability issues:

1. The menu categories in the sidebar are able to be manually expanded but not collapsed. This is a problem if the category contains many items, because it means that you have to scroll a long way down to the next category in the sidebar before you are able to expand it.
2. The sidebar view automatically drills down to the method/RPC currently being viewed in the main area of the page. This is potentially disorienting for the user since the sidebar is used for navigation of the main view, but not vice versa. Similar to the issue above, it also means that the user has to manually scroll the sidebar back to the original position if they want to resume browsing from that location.

Is it possible that these points might be addressed at some stage? Perhaps `<redoc>` tag attributes could be added to customize these specific behaviours.

Thanks!

**Comment by RomanGotsiy** [comment]
@bernieh-atlnz thanks for suggestions!

I will consider them!

**Comment by RomanHotsiy** [comment]
> Scrolling issues are the number 1 usability issue we hear from our API customers.

@arian-kh could you open a separate issue for this?

Closing this.
