### ISSUE TITLE
Add the capability to add footer

### ISSUE THREAD

**Issue by zucher** [Redocly/redoc#344]
It would be nice to have the capability to add footer in the code like for existing header, in markdown, with associated left menu

**Comment by RomanGotsiy** [comment]
@zucher, thanks for the suggestion.
How do you envision the way to configure this? Some vendor extension (aka `x-*` field) in the spec or ReDoc option?

**Comment by zucher** [comment]
and x-footer seems reasonable and not to hard to implement. With markdown support too as for heading

**Comment by lornajane** [comment]
Not a candidate for development, because most of our customers use the description, or developer portals with additional supporting information.
