### ISSUE TITLE
redoc-cli: test script to run on user-supplied openapi spec

### ISSUE THREAD

**Issue by IvanGoncharov** [Redocly/redoc#36]
It would be useful to have script or tool to run in browser tests on user's Swagger spec.
It could be as simple as running a headless browser and check that there is no errors or warnings.
Would be the ideal test to integrate into CI just before deploying Swagger spec.
Important thing is to output banner which explains that this errors could be unrelated to Swagger spec but purely ReDoc issues and if so ask user to open issue in ReDoc repo.

**Comment by RomanGotsiy** [comment]
accidentally closed by wrong commit-message

**Comment by lornajane** [comment]
Closing this since `redoc-cli` is deprecated. Users should [migrate to Redocly CLI](https://redocly.com/docs/cli/guides/migrate-from-redoc-cli/).
