### ISSUE TITLE
Discriminator does not show up on intermediate type

### ISSUE THREAD

**Issue by weirdan** [Redocly/redoc#369]
Consider the following type hierarchy:

![parallel inheritance - page 1](https://user-images.githubusercontent.com/57403/32400637-62af7be4-c10b-11e7-9de2-83ea737cc248.png)

which is fairly classic example of a "diamond inheritance", possible in languages that support multiple inheritance.
It could be expressed with `allOf` & `enum` in the following way:
```json
  "definitions": {
    "BaseRef": {
      "type": "object",
      "discriminator": "type",
      "required": [ "type" ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [ "BaseRef",  "Base", "ChildRef", "Child" ]
        }
      }
    },
    "Base": {
      "allOf": [
        { "$ref": "#/definitions/BaseRef" },
        {
          "type": "object",
          "required": [ "type" ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [ "Base", "Child" ]
            }
          }
        }
      ]
    },
    "ChildRef": {
      "allOf": [
        { "$ref": "#/definitions/BaseRef" },
        {
          "type": "object",
          "required": [ "type" ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [ "ChildRef", "Child" ]
            }
          }
        }
      ]
    },
    "Child": {
      "allOf": [
        { "$ref": "#/definitions/ChildRef" },
        { "$ref": "#/definitions/Base" },
        {
          "type": "object",
          "required": [ "type" ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [ "Child" ]
            }
          }
        }
      ]
    }
  }
```
When `Base` is referenced I'd expect it to display selector for `type` field, as `Base` is a part of inheritance hierarchy, listing everything `BaseRef` selector would list, additionally filtered by `enum` list. Basically, selector should be inherited.

It might be tempting to constraint the selector by the current and all "descendant" types, as to not require `enum`s, but that would prevent using definitions as genuine constraints (which they really are), ruling out the possibility to use something like this:
```json
    "RefOnly": {
      "allOf": [
        { "$ref": "#/definitions/BaseRef" },
        {
          "type": "object",
          "required": [ "type" ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [ "BaseRef", "ChildRef" ]
            }
          }
        }
      ]
    }
```
Here, `RefOnly` ensures that wherever it's used only `BaseRef` and `ChildRef` are accepted (forbidding `Child` and `Base`, even though they are compatible with `BaseRef`), it's not used as a subclass. If the selector would show descendants here it would show nothing, as `BaseRef` could not be made to "inherit" `RefOnly`, as that would create circular dependency.

[Live demo](https://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/weirdan/9d842459f6f9c7790713e5c1962db1fc/raw/5db2799078bd78ea630be7006b714a108f4fd24e/diamond-inheritance.json#tag/Test%2Fpaths%2F~1object-ref%2Fget)

[swagger.json](https://gist.githubusercontent.com/weirdan/9d842459f6f9c7790713e5c1962db1fc/raw/5db2799078bd78ea630be7006b714a108f4fd24e/diamond-inheritance.json)

**Comment by RomanGotsiy** [comment]
@weirdan thanks for the very detailed bug report and for the minimal reproducible sample! This is the best ReDoc issue report so far 🥇!

This is a valid issue but I have to complete "CS143: Compilers" course in order to fix it 😂 

On the serious side, this is a pretty complicated use case. I will try to fix this but after releasing ReDoc 2.0 (React rewrite).

**Comment by weirdan** [comment]
Any ideas on when react-rewrite could land? On the orders of magnitude scale, is that months or years?

**Comment by RomanGotsiy** [comment]
I would say weeks! You can track this issue to staying tuned: https://github.com/Rebilly/ReDoc/issues/327

**Comment by RomanHotsiy** [comment]
Closing as stale. Please reopen if this still is actual for you.
