### ISSUE TITLE
[openapi3] Links support

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redoc#437]

**Comment by cupofcoffe** [comment]
sorry can not assist with design, but rather an example , i think links can be implemented similar with swaggerHub implementation, it just show links info in a response panel, 3 columns view : Code (200), description (schema, example), links (0:m rows). What would be better , if it can implement a hyperlink by following operationId provided with the links properties so you can quickly navigate to other endpoint within the documentation. E.g, if links operationId is detected as local swagger operation, try to add navigation hyperlink there. mouse hover event can show some tooltip about a hyperlink operationId -description, parameters, etc, without actually redirecting to it.

**Comment by InTheCloudDan** [comment]
Did Link support ever get added in?

**Comment by lornajane** [comment]
Closing. Links isn't widely used enough for us to prioritize this feature.
