### ISSUE TITLE
Inject change log

### ISSUE THREAD

**Issue by slavcodev** [Redocly/redoc#440]
In similar manner how we can inject security definition, I propose to inject change log (or may be other markdown files). 

For example:

~~~yaml
info:
  description:
    # Introduction
    <!-- include: README.md --> 
    # Change log
    <!-- include: CHANGELOG.md --> 
~~~

**Comment by mattaylor** [comment]
+1

**Comment by gavinkalika** [comment]
+1

**Comment by neluzhin** [comment]
I can't realize how this should work.

I serve my OpenAPI JSON file from `api.example.com/docs` and I host ReDoc on another server for example at `redoc.example.com`. 

Questions:

1. Where ReDoc should look for injectable file? At `redoc.example.com/EXAMPLE.md` or inside current working directory?
2. If I don't own `api.example.com/docs`, what will happen if JSON will contain include instructions for some project-related files such as internal JavaScript files? That's not secure.
3. What should happen if file doesn't exist?

Also it's seems a bit useless for guys who run ReDoc inside Docker.

I suggest you include these markdown files at documentation compilation time, not at runtime. This practice will bread OpenAPI specification idea: documentation that you can parse and use everywhere.

**Comment by gavinkalika** [comment]
> I suggest you include these markdown files at documentation compilation time

How do I do that? I don't see any references in the redoc lib

**Comment by neluzhin** [comment]
@gavinkalika, compile JSON documentation programmatic way using any tools. For example, you can take a look at my library [specificator](https://github.com/neluzhin/specificator) (or similar tools), but it's in early development now. 

For example, at my work we concatenate README.md and CHANGELOG.md files and place this content to `info.description` field.

**Comment by gavinkalika** [comment]
well that might work. I think we can close this issue.
