### ISSUE TITLE
Auto expand the examples response

### ISSUE THREAD

**Issue by inovacode** [Redocly/redoc#479]
I apologize if this has been answered but couldn't find a clear answer.  I see the expand-response="200,201" re-doc option we can add which works great to expand the schema but what I need is to have the examples response expanded by default as shown in the attached image.  I need the full example response showing.  Is there a setting I can enable for this?

![image](https://user-images.githubusercontent.com/12768947/39447848-587f5670-4c80-11e8-8419-450ab699de12.png)

**Comment by RomanGotsiy** [comment]
@cffiebigc yes a separate external option is what I expected!

**Comment by oponder** [comment]
@cffiebigc do you still intend on picking up this task?

I came across this issue because I was looking for this feature myself too :)

Would be happy to contribute, but don't want to step on any toes

**Comment by cffiebigc** [comment]
@oponder please go ahead! I never found the time to take this. :+1:

**Comment by alex-karo** [comment]
Hello, @RomanHotsiy !
I've sent PR with this feature, could you check it?

**Comment by inovacode** [comment]
@alex-karo you're awesome thanks!

Yes, @RomanHotsiy please review PR.

**Comment by RomanHotsiy** [comment]
I reviewed it. Requested some minor changes

cc @alex-karo, @inovacode

**Comment by alex-karo** [comment]
Thanks, I'll fix it in the near future
