### ISSUE TITLE
Supporting x-oas-draft-alternate-schema 

### ISSUE THREAD

**Issue by philsturgeon** [Redocly/redoc#482]
So, the folks at OpenAPI are attempting to solve the OpenAPI Schema Object <> JSON Schema Object problem with [alternate schemas](https://github.com/OAI/OpenAPI-Specification/issues/1532).

This approach can allow vendors to chose which formats from a predefined list they chose to support:

```
openapi: 3.0.2
info:
  title: A sample using real JSON Schema and xsd
  version: 1.0.0
paths:
  /cat:
    get:
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
              x-oas-draft-alternateSchemas:
                - type: json-schema
                  externalValue: ./cat-schema-draft-08.json
                - type: json-schema
                  externalValue: ./cat-schema-draft-05.json
                - type: json-content-rules
                  externalValue: ./cat-JCRschema.json
            application/xml:
              x-oas-draft-alternateSchemas:
                - type: xml-schema
                  externalValue: ./cat-schema.xsd
                - type: relax-ng
                  externalValue: ./cat-schema.ng
                - type: schematron
                  externalValue: ./cat-schema.st
```

Folks would not need to support everything, but allow their tooling to be suplimented and extended. Of course supporting JSON Schema would be a default expectation for many, and XML Schema might be nice to chuck in their too. 

Check out the OpenAPI issue for more information, but we should start supporting this like its a feature, and give them any feedback with stuff that goes wrong.

**Comment by handrews** [comment]
Note that this is being promoted to a full keyword, `alternativeSchema`, in OAS 3.1

https://github.com/OAI/OpenAPI-Specification/pull/1736

**Comment by lornajane** [comment]
It's overdue, but thanks for raising this when you did! I don't think we need to do anything more on it at this stage, but still. Thanks!
