### ISSUE TITLE
Console warnings shown in Alpha 17

### ISSUE THREAD

**Issue by jonavila** [Redocly/redoc#488]
Mobx observer: You are using 'observer' on React.PureComponent. These two achieve two opposite goals and should not be used together

[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0

Is there a way to specify the spec type to prevent this warning?

**Comment by RomanGotsiy** [comment]
@jonavila it can't be suppressed for now.
I will add an option before 2.0 release though

**Comment by sam-birdi** [comment]
Did you ever add the option?

**Comment by snyaggarwal** [comment]
The conversion is taking too much time >30sec. Is there a way to pre-generate this conversion or stop it?

**Comment by RomanHotsiy** [comment]
Outdated.
