### ISSUE TITLE
UI Responsiveness for response

### ISSUE THREAD

**Issue by sonasingh46** [Redocly/redoc#497]
![image](https://user-images.githubusercontent.com/24835120/40184581-3d15d4fe-5a0e-11e8-8541-f7ee0b613e04.png)
As you can see, the keys`  'creationTimestamp' description is not being shown completely.
Is there anyway we can make it right.?

**Comment by RomanGotsiy** [comment]
could you provide some more details? Is it with some specific window width?

**Comment by sonasingh46** [comment]
what more details ? Like ?
The window width is 1286 ( A laptops' one)

**Comment by RomanGotsiy** [comment]
Like full-width page screenshot for the beginning so I can see the context. Because it's hard to understand the issue from the screenshot you sent.
Thanks!

**Comment by sonasingh46** [comment]
How about following ?
![image](https://user-images.githubusercontent.com/24835120/40226371-2a0b6ab8-5aa9-11e8-9da3-5d3eac471555.png)

**Comment by RomanGotsiy** [comment]
Now I can see the issue.
Which version of ReDoc do you use? It looks like v1.x

**Comment by sonasingh46** [comment]
I am using Version: "1.22.0" 
What version should I use?

**Comment by lornajane** [comment]
Closing this issue, we released Redoc 2.0 some time ago, please open a new issue if there's still something that doesn't look right.
