### ISSUE TITLE
Don't use deprecated properties in samples

### ISSUE THREAD

**Issue by cmeeren** [Redocly/redoc#502]
Currently, as shown in the screenshot, deprecated properties are included in samples. I think it would be logical to exclude them from samples.

![image](https://user-images.githubusercontent.com/7766733/40468779-aa771ace-5f2e-11e8-963d-53e712d2b2f0.png)

**Comment by SebastianStehle** [comment]
How can you demonstrate then, how deprecated properties look like?

**Comment by cmeeren** [comment]
The first thing that comes to mind is "why would you?", since they shouldn't be used. But that likely comes from lack of experience on my part.

How about rendering the samples with a strikethrough, like on the left?

**Comment by svart-riddare** [comment]
The deprecated property shown here is required ?

**Comment by cmeeren** [comment]
That's true. Does it influence the result? (Can't test now)

**Comment by lornajane** [comment]
Closing. This has been inactive for a while and it's not clear that there's a change that will be the right thing for every situation.

**Comment by jdeniau** [comment]
Hi,

I do find this post having the same "issue".
I think too that the example should not display deprecated data, or at least do something to mark them deprecated in the example rendering.

I investigate a little : 
Removing the deprecated data from the example would probably require a new option `skipDeprecated` in the [openapi-sampler](https://github.com/Redocly/openapi-sampler/tree/main?tab=readme-ov-file#usage), probably in https://github.com/Redocly/openapi-sampler/blob/1b6adcbe0f202c225e1bd23f2dd2308aad4554bf/src/traverse.js#L67 we might add something like:

```ts
if (referenced.deprecated && options.skipDeprecated) {
  return;
}
```

We might then add this option to the [`generateExample` method](https://github.com/Redocly/redoc/blob/c04b4c8fecbb07826cadf0ee599b82c11e2568a9/src/services/models/MediaType.ts#L54-L59).

Having a "flag" on the example (maybe an information point and a less visible color) is probably doable too, but might require a further investigation as we do have only the example, and not the context while rendering in [Examples.ts](https://github.com/Redocly/redoc/blob/c04b4c8fecbb07826cadf0ee599b82c11e2568a9/src/components/Fields/Examples.tsx) but it should probably be doable too.

To be honest, as the responses data are closed by default, and the example is visible, I use the example all the type, and nearly didn't ses that I could open the 200 response !
![image](https://github.com/user-attachments/assets/98edbc84-b645-447d-8d39-592222d78a6e)

If you are OK with this, I am willing to help and open a PR in the direction that works the best according to your vision.
