### ISSUE TITLE
support to show extension labels

### ISSUE THREAD

**Issue by ingoclaro** [Redocly/redoc#522]
would be good to have an easy way to render the extension information that the different entities have (the x-* extensions).

For example swagger-ui shows them if you pass `?showExtensions=true`, like this:
![swagger_ui](https://user-images.githubusercontent.com/1280277/40799567-d1ed8784-64c2-11e8-8fa8-e254bc7666bf.jpg)

For ReDoc I was thinking on having a configuration option and be able to either pass a list of which extensions to render, maybe with an `all` option that shows them all; or just a simple setting to only render the ones not used by ReDoc. eg:

```
config: {
  renderExtensions: true
}
```
It could be rendered under the description:

![redoc](https://user-images.githubusercontent.com/1280277/40799938-ce0554de-64c3-11e8-906b-098e06bc50ce.jpg)

This makes it simple to show that information.

---

A much more involved feature could be to pass in a react component to handle the rendering of the extensions, like this:
```
options = {
  extensionComponent: MyExtensionComponent
}
```
which could receive as props the node and the extension name. The component could delegate the rendering to a different component if needed or just return null if you don't want to be rendered.

In any case, I think this is far more advanced than what I actually need, but wanted to mention it as some food for thought that would allow for a rich customization of ReDoc.

**Comment by ingoclaro** [comment]
by the way, if you like the idea I could implement this. I want to agree on the approach before coding.

**Comment by zucher** [comment]
Hi @ingoclaro, 

Your Extension solution seems fine.
I'm not fan of the query activation method, but the usage of javascript embedded options activation looks better.

**Comment by ingoclaro** [comment]
The query param is how swagger-ui does it

**Comment by RomanGotsiy** [comment]
Hey @ingoclaro,

thanks for your feature request. It looks reasonable.

> I was thinking on having a configuration option and be able to either pass a list of which extensions to render, maybe with an all option that shows them all

I think it will be a good start.

The one thing I am not sure about is the location of the information. E.g. for your docs it's logical to have vendor extensions rendered below the field description/operation name but for someone's else it may be opposite... We can't satisfy everyone for sure though.

PRs are welcome

**Comment by lornajane** [comment]
This has been inactive and I think it will be difficult to generalise about what the right behaviour is for everyone, so I'm closing it as something we could revisit after the next release.
