### ISSUE TITLE
Document theme options in readme

### ISSUE THREAD

**Issue by imnotashrimp** [Redocly/redoc#523]
I'd like to volunteer to write usage of the `theme` options. 

Any chance you can give me some guidance on how to use it so I can get started?

**Comment by RomanGotsiy** [comment]
@imnotashrimp awesome! Thanks!

The preferred way to use a theme is to pass it in the options of `Redoc.init` call: https://github.com/Rebilly/ReDoc#advanced-usage-of-standalone-version:

```js
Redoc.init('http://petstore.swagger.io/v2/swagger.json', {
  theme: {
    main: '#ff0000'
  }
}, document.getElementById('redoc-container'))
```

See the default theme for details: https://github.com/Rebilly/ReDoc/blob/master/src/theme.ts#L3

note you can use functions in the theme e.g.:

https://github.com/Rebilly/ReDoc/blob/63ae2e8e943b1cf2838db20c6c567156a2bfac45/src/theme.ts#L35

Theme can't be used on `<redoc>` tag attributes yet.


Feel free to ask additional question!

**Comment by jjylha** [comment]
So did I understand correctly that you can not theme ReDoc by using <redoc theme=""> at all the moment?

You have to use React component or Redoc.init to actually be able to theme anything?

**Comment by ShaneGMamet** [comment]
@imnotashrimp Any updates on this?

**Comment by KimThibault** [comment]
Following

**Comment by adeelibr** [comment]
Following

**Comment by AlbertSuarez** [comment]
Following

**Comment by sid22** [comment]
Following

**Comment by alifya786** [comment]
Hi Roman, I am currently trying to use the theme option to reduce the whitespacing between the sections. I can see the spacingUnit var in the documentation . When I try modify that value nothing seems to happen. Is there a trivial way to use the theme option to do this?

**Comment by kscheirer** [comment]
PR for this opened here https://github.com/Redocly/redoc/pull/1438

**Comment by kscheirer** [comment]
PR was merged, I think this ticket can be closed.

**Comment by rbruggem** [comment]
I am a bit confused.
From https://github.com/Redocly/redoc#tldr, how do I apply https://github.com/Redocly/redoc#redoc-theme-object ?

**Comment by siarhei-kurhuzenkau-idf** [comment]
@RomanHotsiy , hello

Can <redoc theme=""> be used  on <redoc> tag attributes?

**Comment by lornajane** [comment]
Documentation for the configuration, including theme options, has been updated. Find it here: https://redocly.com/docs/redoc/config/
