### ISSUE TITLE
poor performance

### ISSUE THREAD

**Issue by bartkummel** [Redocly/redoc#545]
We have a pretty large OpenAPI 3 spec, see https://developer.opentripmodel.org/4.2.0-b2/index.html for the rendered version. It takes very long to render, often to the point where Firefox begins to ask if the user wants to wait or stop the script. I tried pre-rendering via `redoc-cli`, but that doesn't seem to help. Even the pre-rendered version takes very long to render.

**Comment by felzan** [comment]
The 2.x version of ReDoc which supports OAS 3 don't have the _lazyRendering_ option.
When it have, i think will help on loading time

**Comment by bartkummel** [comment]
@felzan I guess that would help, although it would even be better if the rendering itself just was a bit snappier.

**Comment by franklin-ross** [comment]
We see this too, also with a large OpenAPI 3 spec. Just expanding a response body takes over 16 seconds for recalculating style. Typing in the search box is like a slideshow. Is there any movement on this lazy rendering? Cheers!

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/redoc/issues/1615
