### ISSUE TITLE
Improve spacing, color and style

### ISSUE THREAD

**Issue by neumayr** [Redocly/redoc#548]
Hey @RomanHotsiy 👋 

ReDoc is awesome API spec tool!! Thank you so much for building it. 💛💜💙
Due to the long making, it has some edges which got dusty.
It could get some fresh make up 😉 to feel good in a modern environment.

[VuePress](https://vuepress.vuejs.org/) has a pretty nice style composition, but this is just a [good] example about matching typo and colors. [Open-Color](https://yeun.github.io/open-color/) is another great resource about a harmonized color palette.

Be awesome ✌️

📝 https://vuepress.vuejs.org/
👨‍🎨 https://tailwindcss.com/
🎨 https://yeun.github.io/open-color/

**Comment by jerzyn** [comment]
I think a great improvement would be to make it easier to customize the theme - not only the css generated but also the html components so that the documentation can be easily incorporated into some existing documentation sites.

**Comment by RomanHotsiy** [comment]
@neumayr for some super strange reason I just received another email notification about this issue 😱
 	
<img width="845" alt="Screen Shot 2019-07-08 at 3 48 34 PM" src="https://user-images.githubusercontent.com/3975738/60811531-263acf00-a198-11e9-83b5-caf2dd6c9ce6.png">

It's been open for more than a year!

I don't think this is actionable now. It is too broad. Closing this.
Thanks!
