### ISSUE TITLE
Search content keyword not bring into view

### ISSUE THREAD

**Issue by chapelloise** [Redocly/redoc#562]
Search a keyword which in the right side main content via the upper left search box. 
Let's take Rebilly as an example.(https://rebilly.github.io/RebillyAPI/) Search for "customerId", the word is found on several places, but they are not brought into view. Need to manually scroll down to see them as highlighted.

**Comment by arnonzooz** [comment]
Hi. I experience the same. Moreover, collapsable nodes are not expanded if includes a found item. The overall experience using ReDoc is great, but the search functionality seems to be somewhat limited.

**Comment by karussell** [comment]
We developed fixes for this issue (try [here](https://docs.graphhopper.com/) e.g. type "avoid"). The improved search also requires to point via links deeper into the document. I think these changes would be also of interests for others. Unfortunately only a few PRs seem to be merged. @RomanHotsiy would you have time to take a look into the first required PR #979 from @thisismo?

**Comment by lornajane** [comment]
This should be fixed in newer versions of Redoc. I'm closing the issue, but please don't hesitate to let us know if you're still seeing a problem - it would be best to open a new issue with the version you're using and any other information you think we need.
