### ISSUE TITLE
Formatting of code is not wrapped in <code>

### ISSUE THREAD

**Issue by rcrooks** [Redocly/redoc#578]
I tried adding the Google Translate widget to our references (I know that seems crazy, but it was a demand). The results were disastrous, so I went digging and discovered there are no &lt;codeGGT tags in the source -- all formatting is done with spans and many classes instead. Just curious as to why we're not just using code tags...

**Comment by RomanGotsiy** [comment]
Good point!

PR's are welcome!

**Comment by AndriyTykhan** [comment]
I will try to do it
