### ISSUE TITLE
Try Out feature similar to SwaggerUI

### ISSUE THREAD

**Issue by DeeGeeMan** [Redocly/redoc#582]
I would be nice to **Try Out** the API requests directly in ReDoc with authentication similar to Swagger UI.

**Comment by tomer** [comment]
dupe of #53?

**Comment by wll8** [comment]
- [👉 View video](https://cdn.jsdelivr.net/gh/wll8/static/Video_20200518145834_redoc_show.mp4)
- [👉 online preview](https://wll8.github.io/redoc-try/index.html)

Add `Try it out` function like [swagger](https://petstore.swagger.io/) on [redoc](https://github.com/Redocly/redoc).

![re-doc try](https://github.com/wll8/redoc-try/raw/master/redoc_show.png)
