### ISSUE TITLE
List of Open API 3.0 features that are not supported by redoc@2.0.0-alpha.32 ( Release 2.0.0-alpha.32 )

### ISSUE THREAD

**Issue by somayaji1983** [Redocly/redoc#592]
Dear Team,
   Please help us with information on open api 3.0 features that are not supported by 
   redoc@2.0.0-alpha.32 ( Release 2.0.0-alpha.32 ) version.

Thanks 
Ramesh

**Comment by chatelao** [comment]
Links ?

**Comment by RomanGotsiy** [comment]
Would be great if anyone can help with this...
PR's are welcome

**Comment by somayaji1983** [comment]
Dear Team,
After testing with latest release version of ReDoc ( release 2.0.0.-alpha.36 ), here are the list of API 3.0 features which are not supported in ReDoc and some issues that are observed.

This is just a consolidated list with observations.

S.No | Issue Description
-- | --
1 | ReDoc has no option to navigate through all   templated servers, ReDoc rendering computed URLs with default or first   enumerated values
2 | ReDoc unable to generating example for response   content type with “application/xml”.
3 | ReDoc rendering failed and throw error, when   “scope” is not defined inside OAuth2 security scheme .
4 | ReDoc GUI is scattered some time when   rendering conditions like anyOf, oneOf in requestBody or responses
5 | ReDoc not supporting Open API 3.0 Links features
6 | ReDoc not supporting Open API 3.0 Callbacks features
7 | ReDoc unable to render external link   reference through externalValue in example section
8 | ReDoc GUI is scattered when description   field with HEADING level string is written under Info object.

Thanks
Ramesh

**Comment by yinchanted** [comment]
@RomanGotsiy Is the support for Open API 3.0 Links and Callbacks feature in the roadmap?

**Comment by trinh-ngo-ntq** [comment]
> @RomanGotsiy Is the support for Open API 3.0 Links and Callbacks feature in the roadmap?

IMHO, possible no.
This feature had been added to OA3.0 long time but Redoc still does not support it, till today

**Comment by RomanGotsiy** [comment]
> Is the support for Open API 3.0 Links and Callbacks feature in the roadmap?

@yinchanted yes it is.

> This feature had been added to OA3.0 long time but Redoc still does not support it, till today

@trinh-ngo-ntq 	Your PR's are welcome!

**Comment by forivall** [comment]
Callbacks were added via #1224

**Comment by RomanHotsiy** [comment]
I just checked the points from the table again and I am going to close this issue:

> 1. ReDoc has no option to navigate through all templated servers, ReDoc rendering computed URLs with default or first enumerated values

It has. Once you click on the server you will see a popover with all the servers.

> 2. ReDoc unable to generating example for response content type with “application/xml”

Dup of https://github.com/Redocly/redoc/issues/492


> 3. ReDoc rendering failed and throw error, when “scope” is not defined inside OAuth2 security scheme

Scope is `REQUIRED` in OAuth2 security scheme (empty array works too), won't fix


> 4. ReDoc GUI is scattered some time when rendering conditions like anyOf, oneOf in requestBody or responses

Not actionable. I need specific issues.


5. ReDoc not supporting Open API 3.0 Links features

Dup of https://github.com/Redocly/redoc/issues/437


> 7. ReDoc unable to render external link reference through externalValue in example section

It should be able. Open a separate issue with the reproduction steps.


> 8. ReDoc GUI is scattered when description field with HEADING level string is written under Info object.

It needs more details.
