### ISSUE TITLE
Render LaTeX

### ISSUE THREAD

**Issue by uipo78** [Redocly/redoc#630]
To start: I *love* this tool.

If you all have time, a really nice addition (one that I'd personally use often) would be LaTeX rendering (for example, within description sections). I'm sure that the ML/Data Science community would love this as well.

Let me know whether or not this is feasible.

Thanks!

**Comment by mm-gmbd** [comment]
Now that [Github supports LaTeX expressions](https://github.blog/changelog/2022-05-19-render-mathematical-expressions-in-markdown/), maybe this is more feasible?

From the blog post:

> GitHub's math rendering capability uses MathJax; an open source, JavaScript-based display engine. MathJax supports a wide range of LaTeX macros and a number of useful accessibility extensions. For more information, see the [MathJax documentation](http://docs.mathjax.org/en/latest/input/tex/index.html#tex-and-latex-support) and the [MathJax Accessibility Extensions documentation](https://mathjax.github.io/MathJax-a11y/docs/#reader-guide).

**Comment by lornajane** [comment]
This is a nice idea, but OpenAPI specifies that only a particular markdown flavour is supported, so we'll keep our tool aligned with the specification on this.
