### ISSUE TITLE
Partial Rendering: Render only some tags

### ISSUE THREAD

**Issue by chatelao** [Redocly/redoc#637]
Would be great to provide partial rendering of some tags:

e.g.: 
* Tagging all changed APIs to produce Release Notes
* Tagging APIs for specific User Groups and extracting for them
* ...

**Comment by RomanGotsiy** [comment]
Could you explain it further? I can't fully understand your feature request.

**Comment by chatelao** [comment]
Let's say, I have 3 tags:

- Administration
- User
- SuperUser

And I would like to render only the "User" part using an option.

Is there any way to do this?

**Comment by lornajane** [comment]
This is possible, try adapting either this guide https://redocly.com/docs/cli/guides/hide-apis/ , or the more advanced one that uses a custom plugin to hide extensions. The basic idea is to use decorators to filter your OpenAPI description to just what you want to show in docs, then produce the docs. Hope that helps (I realise this issue has been around a while and you probably already solved this!)
