### ISSUE TITLE
#opertion and #tag display in endpoint url if host is not specified

### ISSUE THREAD

**Issue by chapelloise** [Redocly/redoc#649]
Steps to reproduce:
1. Do not specify "host" in your spec yaml/json file.
2. Open the redoc generated HTML file or host on a server.
3. Navigate doc to some endpoint to see the sample url .
<img width="446" alt="good" src="https://user-images.githubusercontent.com/41279957/45722318-a2f4b200-bb60-11e8-92e6-8894bf5640bc.png">
Notice at this point, url in browser is something like "http://localhost:4300/doc/#operation/getUser"(getUser is the operationId)

4. Refresh page and check the endpoint url example
<img width="439" alt="bad" src="https://user-images.githubusercontent.com/41279957/45722379-e4855d00-bb60-11e8-92f5-c27b2aad2b05.png">
"#opertion" or "#tag" is included in the url.

**Comment by AlexVarchuk** [comment]
fixed in [PR](https://github.com/Redocly/redoc/pull/2081)
