### ISSUE TITLE
Default host/basePath should not include documentation endpoint subpath

### ISSUE THREAD

**Issue by lafrech** [Redocly/redoc#686]
https://swagger.io/docs/specification/2-0/api-host-and-base-path/

> For example, if Swagger UI-based documentation is hosted at https://api.example.com/apidocs/index.html, "try it out" API calls will be directed to https://api.example.com.

Our spec file contains no host/basePath. We're hosting the docs at `http://domain.tld/api-docs/redoc` and all the sample urls contain the `/api-docs/` subdirectory.

This happens with redoc 2 (next) but not redoc 1 (latest).

**Comment by lafrech** [comment]
I forgot to mention I'm using OpenAPI v2 (implicit since `basePath` does not exist in v3).

This does not happen when if `basePath` is specified. In other words, when specifying only `basePath` and not `host`, the `/api-docs/` subdirectory does not appear.

Maybe internally it is not the default `host` that is wrong but the default `basePath`.

**Comment by lafrech** [comment]
> This does not happen when if basePath is specified. In other words, when specifying only basePath and not host, the /api-docs/ subdirectory does not appear.

Let me take that back. It also occurs when `basePath` is specified.

**Comment by RomanGotsiy** [comment]
Could you share the minimal reproducible spec so I can save time debugging it?

Thanks!

**Comment by redoz** [comment]
I think I just ran into this issue using OAS3, my oas spec is hosted at `example.com/v1/openapi.json` and redoc at `example.com/v1/docs` and it puts `v1` in the URLs twice:
![image](https://user-images.githubusercontent.com/1670030/63329690-b5f4a100-c332-11e9-9ebc-ede33cc7fcd9.png)

Note that my `openapi.json` doesn't contain any server urls.

**Comment by thiloilg** [comment]
Any fixes yet? I have the same problem.

**Comment by lornajane** [comment]
The best approach here is to add the server information (or basepath for older API descriptions), so that Redoc can correctly display it. If you need to add or change these fields in an existing API description, try this [guide to changing server information](https://redocly.com/docs/cli/guides/replace-servers-url/), and then render the documentation from the corrected OpenAPI/swagger document.
