### ISSUE TITLE
Add content to right example column that corresponds to additional menu items added via markdown in the description

### ISSUE THREAD

**Issue by debri174** [Redocly/redoc#692]
I have added menu items via markdown in the description. I would like to add content to the right-most example column that corresponds. Is this possible?

![image](https://user-images.githubusercontent.com/32558006/47669492-9eb0b100-db70-11e8-8948-91ba36f1b342.png)

**Comment by debri174** [comment]
Thanks for your response @RomanGotsiy!

**Comment by RomanGotsiy** [comment]
@debri174 I think we have a way to accomplish it in ReDoc Pro which is in private beta right now. Write to founders@redoc.ly if you are interested.

**Comment by contra** [comment]
@RomanGotsiy Ah that simple - thanks!

**Comment by lornajane** [comment]
This question was answered.
