### ISSUE TITLE
Suggestion: "Read more" button for long description

### ISSUE THREAD

**Issue by exoego** [Redocly/redoc#694]
Sometimes `description` field of API and/or Component can be quite long.
I think long description makes browsing API Doc browsy a little.

It would be helpful if we can split `description` into "always-shown section" and "more section", and add `Read more` button to toggle "more section" visibility.

Something like this.

```yaml
/foo/{bar}:
  get:
    summary: get Bar from Foo
    description: |
       Yay.

       These lines are visible always.
       <!-- READMORE -->
       These lines are visible only if "Read More" is enabled.
       ...very very very long
```

**Comment by RomanGotsiy** [comment]
Great idea! Thanks!

**Comment by janzankowski** [comment]
For anyone who comes across this issue: it is already possible to add an expand-collapse section using plain Markdown, like this:

```
<details>
  <summary>Click to expand!</summary>
  
  Some text
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>
```

**Comment by exoego** [comment]
Closing since browsers have native support of details/summary tag.
