### ISSUE TITLE
Request URL Dropdown hidden < 1361px

### ISSUE THREAD

**Issue by felixfrtz** [Redocly/redoc#704]
When going below 1361px in width, the sidebar moves into the main content, that is fine.
However, the URL dropdowns don't have enough space in their dark containers, see:

![image](https://user-images.githubusercontent.com/15911990/48201110-7b9cb300-e361-11e8-9972-c1cfd6194b5b.png)

**Comment by AlexVarchuk** [comment]
Seems it is fixed. Cannot reproduce it. Sorry for the huge delay. 🙈
