### ISSUE TITLE
Search feature stops working with large markdown content in description

### ISSUE THREAD

**Issue by ankitkatiyar91** [Redocly/redoc#711]
I have created a ReDoc using swagger JSON. I bundled it with the redoc-cli tool.  I wanted a few extra menu options so added a large markdown in the description tag. After doing it the search feature stops working. Also, I noticed that the markdown table is not working in this section. 

Is there any alternative to do the same? Having a large markdown with menus? 
Can I import an external markdown file in this section or implement it in another manner that doesn't break redoc?

**Comment by lornajane** [comment]
This is an old issue and the search feature was much improved in the 2.0 release. I'm therefore closing this issue, but if you're still seeing a problem, then please open a new issue and we can take another look
