### ISSUE TITLE
redoc-cli: Watcher ignore configurable

### ISSUE THREAD

**Issue by ghost** [Redocly/redoc#717]
As mentioned in PR #716, I'm considering where to make the ignored files configurable.
I have no preference, therefore would like to get consensus on:

- Should we only allow the ignore list configurable as this would be the most used case to be able to tailor to different editors
- And if so, should we use package.json or a separate configuration file
- If there's interest to support all watchOptions, same thing: where to put it

**Comment by lornajane** [comment]
I'll close this since the original user isn't around, and `redoc-cli` was replaced by Redocly CLI (which has a config file).
