### ISSUE TITLE
Question: Why is my prerendered HTML file different from normal rendering?

### ISSUE THREAD

**Issue by pbkh-jimmy** [Redocly/redoc#742]
For example, in normal rendering, the keys in request sample and response sample is white, but in prerendered, both keys and values in request sample and response sample are green. Another example is the response code in normal rendering has description to it whereas response code in prerendered just show the code number.

Did I bundle it incorrectly? Or do I need to pass some attributes to it when bundling it?

Thanks

**Comment by lornajane** [comment]
I'm going to assume this isn't a problem, 4.5 years later. Please open a new issue if you need something from us!
