### ISSUE TITLE
Messed up headers in commonmark handling

### ISSUE THREAD

**Issue by floggle** [Redocly/redoc#744]
I have this description:

```
"description": "\nAmet quis porro quia ducimus voluptatem. Autem voluptatem perspiciatis repudiandae distinctio omnis odio inventore ipsam. Eveniet ut doloremque ad omnis autem dolore illum reprehenderit. Nihil cum earum quia mollitia. Repellendus voluptatibus veniam rerum.\n\nGlossary\n--------\nThere is a glossary of the various terms here: (example.com)[https://example.com]\n\nOpenAPI based\n-------------\nThis API is documented using the standardised OpenAPI 3.x specification.\n\n",
```

This is what it should look like:
https://spec.commonmark.org/dingus/?text=Amet%20quis%20porro%20quia%20ducimus%20voluptatem.%20Autem%20voluptatem%20perspiciatis%20repudiandae%20distinctio%20omnis%20odio%20inventore%20ipsam.%20Eveniet%20ut%20doloremque%20ad%20omnis%20autem%20dolore%20illum%20reprehenderit.%20Nihil%20cum%20earum%20quia%20mollitia.%20Repellendus%20voluptatibus%20veniam%20rerum.%0A%0AGlossary%0A--------%0AThere%20is%20a%20glossary%20of%20the%20various%20terms%20here%3A%20(example.com)%5Bhttps%3A%2F%2Fexample.com%5D%0A%0AOpenAPI%20based%0A-------------%0AThis%20API%20is%20documented%20using%20the%20standardised%20OpenAPI%203.x%20specification.%0A

Instead, I get a page that looks something like:

> Amet quis porro quia ducimus voluptatem. Autem voluptatem perspiciatis repudiandae distinctio omnis odio inventore ipsam. Eveniet ut doloremque ad omnis autem dolore illum reprehenderit. Nihil cum earum quia mollitia. Repellendus voluptatibus veniam rerum.
> Glossary
> 
> There is a glossary of the various terms here: (example.com)[https://example.com]
> OpenAPI based
> 
> This API is documented using the standardised OpenAPI 3.x specification.
> Glossary
> OpenAPI based
> 
> Amet quis porro quia ducimus voluptatem. Autem voluptatem perspiciatis repudiandae distinctio omnis odio inventore ipsam. Eveniet ut doloremque ad omnis autem dolore illum reprehenderit. Nihil cum earum quia mollitia. Repellendus voluptatibus veniam rerum.
> Glossary
> 
> There is a glossary of the various terms here: (example.com)[https://example.com]
> OpenAPI based
> 
> This API is documented using the standardised OpenAPI 3.x specification.
> 

As you can see, the headers are appearing 3 times.

2.0.0rc0

**Comment by floggle** [comment]
Header level 1 (====) is just as broken as header level 2.

Workaround - have to use the "#" and "##" method of declaring headers rather than underscores.

**Comment by lornajane** [comment]
Thanks for sharing the workaround. Since this applies to an older version of the tool, I'll close this issue for now.
