### ISSUE TITLE
example/default ignored when using ref

### ISSUE THREAD

**Issue by floggle** [Redocly/redoc#745]
I have the following:

```
    "components": {
        "schemas": {
            "error_model": {
                "properties": {
                    "success": {
                        "default": false,
                        "example": false,
                        "$ref": "#/components/schemas/success_flag"
                    },
				}
			},
            "success_flag": {
                "description": "A flag indicating whether the request was successfully completed or not.\n\n**Note**: A successful request does _not_ mean results were returned. Check the `total_results` field for that",
                "type": "boolean"
            }
		}
	}
}
```

The `default` and `example` flags are both being ignored and I'm seeing "success: true" on the redoc example.

I expected that the parent's properties would be the ones exemplified, similar to how "description" uses the highest level one.

**Comment by m-mohr** [comment]
You can't set properties on the same level as a $ref. $ref replaces everything on the same level. So it works as expected by OpenAPI.

**Comment by floggle** [comment]
Ok, thanks. I'm running this OpenAPI file through three OpenAPI linters and while I don't have the code any more, I'm fairly sure I wouldn't have reported this if they were complaining about my spec.

That said, the OpenAPI 3 spec (what I'm using) appears to agree with you - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#referenceObject
"This object cannot be extended with additional properties and any properties added SHALL be ignored."
I guess the linters need some work!
Thanks!

**Comment by ymarillet** [comment]
you can use allOf feature though

**Comment by RomanHotsiy** [comment]
Closing this. Thanks @m-mohr for answering here 🙇 !
