### ISSUE TITLE
Scrolling for description section

### ISSUE THREAD

**Issue by monolithed** [Redocly/redoc#746]
Please set some min-width or add scrolling for description section:

<img width="1026" alt="screenshot 2018-12-16 at 16 01 54" src="https://user-images.githubusercontent.com/803674/50053794-fb315500-014b-11e9-9d2b-e18511ecbf67.png">

**Comment by lornajane** [comment]
Outdated issue, this refers to an older version of the tool (but please let us know if you update and something still doesn't look right!)
