### ISSUE TITLE
Add option to always show operation ID in sidebars

### ISSUE THREAD

**Issue by axnsan12** [Redocly/redoc#753]
If an Operation object contains a summary, this is used as its label in the sidebar instead of the operation id. 

This is not always desired because a summary is not necessarily the same as a title/label, so I think there should be an option to disable this behavior.

**Comment by axnsan12** [comment]
> the same applies to the operationId. operationId is not the same as a title/label.

That's true, but it's generally something you'd use as a function name for the Operation, which IMO is a better label for an Operation than a summary of its description. The id also tends to be shorter, while the summary can be up to 120 characters long according to spec.

**Comment by lornajane** [comment]
The current functionality is the expected behaviour. I think this is a good suggestion and would make sense in some APIs, but not in others, so it doesn't make sense to make changes.

**Comment by dougbreaux** [comment]
> good suggestion and would make sense in some APIs

Seems a good reason to make it an option, no?
