### ISSUE TITLE
Error messages are insufficiently descriptive

### ISSUE THREAD

**Issue by jimcullenaus** [Redocly/redoc#769]
# Observed behaviour

On an API documentation that I am working on, it passes all validation [when pasted in to the swagger.io online editor](https://editor.swagger.io/?_ga=2.21362494.427804145.1546824490-2119191931.1530165076), but fails when redoc attempts to parse it. Instead, it displays the following page:

> # Something went wrong...

> Invalid reference token: allOf

> Stack trace

```
> Error: Invalid reference token: allOf
>     at Function.o.get (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:47:17125)
>     at e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:47:25289)
>     at n.allOfSample (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:47:18972)
>     at e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:47:25577)
>     at Object.n.sample (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:47:20493)
>     at e.generateExample (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:107:46192)
>     at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:107:45648)
>     at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:107:46559
>     at Array.map (<anonymous>)
>     at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:107:46508)
> 
> ReDoc Version: 2.0.0-rc.0 
> Commit: a47a4b8
```

As the API uses "allOf" many times, this message is insufficient to diagnose the perceived problem.

# Expected Behaviour

The error messages that appear should provide a definitive indication of where they occur. At a minimum, which `path` and method should be revealed, but ideally the complete description of the error location.

So, for example, "/api/v1/route -> GET -> responses -> content -> application/json -> schema -> properties -> arrayOne -> objectTwo contains invalid allOf reference", or similar.

**Comment by RomanGotsiy** [comment]
Totally agree!
PRs are welcome!

**Comment by lornajane** [comment]
This has been improved in Redocly CLI, which is the current tool that we recommend for linting. I will close this issue as I don't think it's useful here, but more feedback is always welcome.
