### ISSUE TITLE
multiple object in an array

### ISSUE THREAD

**Issue by ghost** [Redocly/redoc#770]
hi, I want to create interactive drop menu something like this(photo from README)
![image](https://user-images.githubusercontent.com/13827579/50752712-48b06600-12a3-11e9-98ab-0e53e90224c9.png)

So when I nested single ref it works.
```
options:
   type: array
   items:
     $ref: '#/schemas/mAccount/create/options'
```
![image](https://user-images.githubusercontent.com/13827579/50752768-772e4100-12a3-11e9-8223-965e9af243ec.png)

but if I nested multiple ref it doesn't work. 
are there any way get around this?
```
options:
   type: array
   items:
     - $ref: '#/schemas/mAccount/create/options'
     - $ref: '#/schemas/mAccount/create/options2'
     - $ref: '#/schemas/mAccount/create/options3'
```
![image](https://user-images.githubusercontent.com/13827579/50752827-a8a70c80-12a3-11e9-972d-eb9333d7b073.png)

**Comment by lornajane** [comment]
Inactive issue and missing user, closing.
