### ISSUE TITLE
Rendering multipleOf constraint

### ISSUE THREAD

**Issue by viralanomaly** [Redocly/redoc#771]
I don't see any update to #42  - Is multipleOf going to be rendered on the screen?  I'm using it to limit a number to two decimal places, and that seems like a pertinent detail to give to my API users.

**Comment by RomanGotsiy** [comment]
It is going to be rendered.
How do you envision it? Just `Multiple of: 0.01`? Maybe you have some better idea?

**Comment by viralanomaly** [comment]
Yeah, I think that is roughly what I was picturing!

**Comment by lornajane** [comment]
This was implemented already :tada:
