### ISSUE TITLE
Redoc disabled display on second loading. 

### ISSUE THREAD

**Issue by mourinf** [Redocly/redoc#772]
Hello!
I have a problem with Redoc. I use it in an angular app. 
When I load my redoc page for the first time, every thing is fine and works properly.
But when I go on previous page and go on redoc page again, all menu items are disabled, and all parts are empty (there are only titles).
I have to refresh each time. 
Does someone have an idea please?
Have a nice day!

**Comment by fsidhoum** [comment]
Hello @mourinf 

I have the exact same problem.

Do you have found a solution ?

**Comment by mourinf** [comment]
Not yet.. I saw in Redoc source files that the css class 'disabled' is used because my menu items are not "ready"... Don't know why at the moment (and why everything is fine at the first time).

I try to install an older Redoc version with npm, because I know everything worked properly with v1.17.0.
But for a reason I don't understand, I am not able to install an older version than 1.22.0

I keep working on it!

**Comment by mourinf** [comment]
Hello,
Thanks for your reply. I use redoc 1.22.0, the version installed when I run command npm install redoc. 
The problem occurs when I use routerlink to go on my redoc page. So I used href instead. As the page is reloading, it solves the problem (even if the best solution for me should be avoiding reload).
Maybe there is a conflict with the rest of my code, but the browser console is clean.

**Comment by lornajane** [comment]
Please try upgrading to Redoc 2.0 or later, which should resolve this problem. If something still doesn't look right, let us know!

**Comment by mnx1y** [comment]
f
