### ISSUE TITLE
Discriminator is turning my Post request Null

### ISSUE THREAD

**Issue by rqdzs** [Redocly/redoc#781]
I'm having a problem when i try to use discriminator in OAS 3.0. 
OBS: my documentation has many files, so i decidided to put in specific folder for each case. 

I would like to know what am i doing wrong, i've tried many ways to make it work but it didn't... I'm putting some pictures for make it easy to understand.

![mainobject](https://user-images.githubusercontent.com/19806884/50970203-838ee580-14bf-11e9-8429-8406a8b9df79.PNG)
1 - This first picture is showing the object that is configurated to use the discriminator. 

![representationofconfig1](https://user-images.githubusercontent.com/19806884/50970264-b638de00-14bf-11e9-88b0-34dea7afc681.PNG)
2 - This is the guy that i created for de the mapping 

The first file is in a folder and the second one is in another one.

The result i am having on ReDoc is this
![postrequest](https://user-images.githubusercontent.com/19806884/50970502-4d9e3100-14c0-11e9-8106-f56f88251027.PNG)

The version script i'm using is : https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js

I'm attaching the image that i user in de post request 

![inkedmainfile_li](https://user-images.githubusercontent.com/19806884/50970606-9b1a9e00-14c0-11e9-9517-47124c4c039d.jpg)

**Comment by lornajane** [comment]
This has been open a while, sorry. My best recommendation is to try bundling the OpenAPI description into a single file before using with Redoc and discriminator.
