### ISSUE TITLE
Extension Labels instead of keys

### ISSUE THREAD

**Issue by theomega** [Redocly/redoc#787]
The extension support is nice, but it uses the key from the openapi spec as label. It would be nice to have the possibility to change the label in ReDoc. 

Example:
<img width="564" alt="screenshot 2019-01-17 at 09 29 14" src="https://user-images.githubusercontent.com/905977/51305159-6cf60a80-1a3a-11e9-8268-48c2a629c8b9.png">

I'd love to replace `x-olt-permissions` with something more descriptive in ReDoc.

Is there a possibility to do so? Or anyone having implemented something like that?

**Comment by RomanGotsiy** [comment]
It's not possible to do it right now. But I think we can implement an option for this.

@ingoclaro PR would be appreciated 😉

**Comment by theomega** [comment]
> Maybe supplying a map of key value as an option to ReDoc?

I was thinking the same, although I could decide on what should be the key and the values:
"Description" -> "YAML Field" or
"YAML Field" -> Description

The second one makes more sense IMHO as the "YAML Field" is definitively unique, but the Description could not be unique...

**Comment by lornajane** [comment]
Out of scope for the project at this time, but we're open to pull requests for specific tag support.
