### ISSUE TITLE
Choose what to display in a Tag

### ISSUE THREAD

**Issue by Druwww** [Redocly/redoc#788]
Hi ! First, thanks for reDoc it works very well !

I looked if this option exist or if this issue was already there but I didn't find anything...
I would like to hide in my documentation some stuff in a Tag.

For example, in my file .yml : 

```
/travel/plan/cancel :
   post : 
      tags : 
          -....
      summary :  Subscribe to a flight delay insurance policy
      ...
   options:
      consumes:
          -.....
       ....
```
In my documentation I have in fact the POST show but also the OPTS display
![image](https://user-images.githubusercontent.com/33511073/51391728-2801cf00-1b33-11e9-8a3e-dc14414d76fd.png)

So is it possible to choose to not display some content in a Tag ? is there a option ?

To help, I use redeco-cli : 
`redoc-cli bundle path/product.yml --options.hideDownloadButton --options.expandResponses="all"`

Sorry if it's already open or answer in the doc, I start to develop very recently ^^' 
Thanks again for this project and your time !

**Comment by lornajane** [comment]
You could try using the [guide for hiding internal fields](https://redocly.com/docs/cli/guides/hide-apis/) and adapt it to exclude the options endpoints.
