### ISSUE TITLE
Deprecation warning "Using unescaped '#' characters in a data URI body is deprecated"

### ISSUE THREAD

**Issue by MartinFalatic** [Redocly/redoc#793]
Using redoc.min.js v1.22.2 (also with v1.19.0), I'm seeing the following deprecation warning in Chrome (71.0.3578.98 (Official Build) (64-bit)) (via the Developer Tools console pane):

`[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.`

The JSON I'm passing to `Redoc.init()` doesn't have any '#' chars, and in the elements the only instances are as part of hrefs, as part of color specifications, in the CSS as part of `#resources-nav[_ngcontent-c4]`, and in some data-hints (all of them look like `data-hint="Parameters that are appended to the URL. For example, in /items?id=###, the query parameter is id"`)

I don't see any other issues open or closed about this so I wonder if anyone else is seeing this?

**Comment by lornajane** [comment]
We haven't seen any activity for a while so I'm closing this . Please try Redoc v2.0 or later, and let us know if you still see a problem?
