### ISSUE TITLE
Pass options as JSON to redoc-cli

### ISSUE THREAD

**Issue by lezhnev74** [Redocly/redoc#797]
I am using `redoc-cli` to create a zero-dependency file for our API documentation portal. 
I read that I can tweak the styles by customizing the file `https://github.com/Rebilly/ReDoc/blob/master/src/theme.ts`. I downloaded the file and changed it a bit.

How do I run `redoc-cli` and pass this updated file in? I just can't find the documentation about this.

Thanks a lot!

**Comment by jdillard** [comment]
I think pointing to a customized template has been documented in the `recod-cli` [README](https://github.com/Rebilly/ReDoc/blob/master/cli/README.md) now:

```redoc-cli bundle [spec] -t custom.hbs```

This can probably be closed.

**Comment by RomanGotsiy** [comment]
@lezhnev74 sorry for later reply.

You can use `--options` and pass a JSON string:

E.g. `--options = '{"theme": {"colors": {"primary": {"main": "#ff0000" }}}}'`

**Comment by lezhnev74** [comment]
Thank you for the example!

**Comment by jdillard** [comment]
I'm not sure if it is user error, but that example isn't working for me in `redoc-cli` v0.8.3. Nothing changes if I do:

```redoc-cli bundle [spec] --options = '{"theme": {"colors": {"primary": {"main": "#ff0000" }}}}'```

Although, the options example in the README works:

```redoc-cli bundle [spec] --options.theme.colors.primary.main=#ff0000```

**Comment by bkhablenko** [comment]
I confirm that passing options as JSON doesn't seem to work.

```bash
redoc-cli serve --options='{"theme":{"colors":{"primary":{"main":"orange"}}}}' petstore.yaml
```

The command above generates an HTML page with the following line in its source code:

```js
Redoc.init("spec.json", "{\"theme\":{\"colors\":{\"primary\":{\"main\":\"orange\"}}}}", container);
```

However, passing the color as a single option does work:

```bash
redoc-cli serve --options.theme.colors.primary.main=orange petstore.yaml
```

The resulting page has a slightly different line:

```js
Redoc.init("spec.json", {"theme":{"colors":{"primary":{"main":"orange"}}}}, container);
```

So unless I'm doing something wrong, my guess is that there might be a bug in the CLI. Even though this issue was closed, could you please take a look? @RomanHotsiy

**Comment by RomanHotsiy** [comment]
Sorry, I confused this. There is no support for JSON string.
PR would be appreciated!

**Comment by adeelibr** [comment]
@RomanHotsiy how can you pass theme to `docker` command?

**Comment by knidarkness** [comment]
> Sorry, I confused this. There is no support for JSON string.
> PR would be appreciated!

Here it is @RomanHotsiy :  https://github.com/Redocly/redoc/pull/1047
