### ISSUE TITLE
Unexpected error - Unauthorized, status code 401

### ISSUE THREAD

**Issue by robogeek** [Redocly/redoc#803]
I'm kicking the tires, and attempting to use ReDoc with a couple OpenAPI specs I wrote in 2017.  They're of course written to OpenAPI v2 because of the age.  They were at the time successfully used with Swagger UI.

With both spec's I get the same behavior - an error page along with status code 401.  I've included the smaller of the two specs below.

It is running under Node.js 10.14, with redoc-cli@0.7.0 installed, on macOS 10.13.6, displaying into Chrome.

At the CLI:

```shell
$ redoc-cli  serve ../../../api-temperature.yaml 
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0

Server started: http://127.0.0.1:8080
```

In my browser window I see this:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Feb 01 01:47:06 GMT 2019
There was an unexpected error (type=Unauthorized, status=401).
Unauthorized
```

The api-temperature.yaml is:

```yaml
swagger: '2.0'
info:
  description: |
    Interface REST to backend MODBUS service.
  version: "0.1.0"
  title: "Modbus Temperature REST"
  contact:
    email: "david@davidherron.com"
schemes:
  - "http"
paths:
  /temperature:
    get:
      summary: "Get the current temperature"
      description: "Get the current temperature from the MODBUS temperature sensor"
      operationId: "getTemperature"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
              type: object
              properties:
                  timestamp:
                      type: string
                      description: Timestamp string in ISO date format
                  temperature:
                      type: number
                      description: Current temperature
```

(The other spec is huge)

**Comment by robogeek** [comment]
In case my spec was at fault - I found that in the git repository for the OpenAPI spec, there are examples, and picked one out at random, and got the same error.

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/uspto.yaml

**Comment by RomanHotsiy** [comment]
Can't reproduce. For me works nicely.

Must be something with your setup. Feel free to provide more details here if the issue still happens for you
