### ISSUE TITLE
References are not resolved in the swagger.json embed into the generated HTML

### ISSUE THREAD

**Issue by birdofpreyru** [Redocly/redoc#811]
When OpenAPI HTML is generated from a multifile YAML source, the `swagger.json` file, that can be fetched from that HTML via the _Download_ button right under the document title, is broken as relative links to other files are not resolved inside it.

**Comment by lornajane** [comment]
I'm closing this inactive issue, but please let us know if you're still seeing this problem?

**Comment by PiOliver** [comment]
This is still broken. As a workaround, you can use another tool to generate a file which dereferences any linked files to a singular. And then serve this file, adding a download link to your description section using some html to replace the existing button.

Not an elegant solution in the slightest but good enough.
