### ISSUE TITLE
Titleize tag names in the HTML view

### ISSUE THREAD

**Issue by dcu** [Redocly/redoc#813]
My tags look like a title in lowercase when rendered in ReDoc and it doesn't look good and it's inconsistent with the `Authentication` which is also at the same level

**Comment by lornajane** [comment]
Try using the `x-displayName` extension for tags: https://redocly.com/docs/api-reference-docs/specification-extensions/x-display-name/ This lets you specify how Redoc should display the tag, and I think will solve this problem. I'm closing this issue, but let us know if you need anything else.
