### ISSUE TITLE
[Question] How to read current swagger json 

### ISSUE THREAD

**Issue by d913334** [Redocly/redoc#825]
Hi ,

My requirement is doing some UI update after redoc loaded. I don't want to get json again, But I couldn't find any exposed method or property that I can access to the current swagger object? 

Does anyone know any method to access this data ? workaround now is fetching JSON again using ajax.

**Comment by RomanGotsiy** [comment]
How do you init ReDoc? Do you use it in the React app? Or do you use a standalone bundle?

**Comment by lornajane** [comment]
We didn't get a response, so I'll close this issue.
