### ISSUE TITLE
[Feature Request] Is it possible to make x-tagGroups collapsible

### ISSUE THREAD

**Issue by lordrhodos** [Redocly/redoc#826]
I was wondering if there is any option to enable the tag groups to be collapsible and be collapse by default? 

The [documentation](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-tagGroups) does not show any hints about this and I can not find anything in the repository about it. 

We have very large collection of endpoints and it would improve the usability a lot.

If this is not supported yet I am happy to look into this and provide a PR to add this feature.

**Comment by RomanGotsiy** [comment]
This is not supported. Your PR would be appreciated!

**Comment by bradennapier** [comment]
@lordrhodos i put this together day when i needed it and submitted a PR.  Let me know if it isn't what you were thinking!

**Comment by lordrhodos** [comment]
@bradennapier thanks for your effort on this issue. 

I started a couple of days ago on an own implementation and I chose to follow a slightly different approach. I introduced a new configuration parameter `collapseTagGroups` which defaults to `false` leaving everything as is now. 

If set to `true` it would add collapseble and expandable feature on the model and use a different styling. I still need to figure out some injection parts in the `styled.elements.ts` components though. I am not a React/Typescript pro ;-)

I like your approach adding the collapsible support for groups on a single group level, although I prefer to have only one central configuration switch. And I like the visual integration of the collabsible group menu item, but I am not sure if we need a highlight for active (expanded) groups. This would also need some adjustments for the padding I guess as changing the background color for highlighting does not look nice.

Will look into this soon and be back with some more feedback.

**Comment by bradennapier** [comment]
Can you expand on what you mean with the highlighting issue? Not sure I see any issue there but it’s likely a very simple css thing.  

A whole new switch and model seems excessive.  This solutions primary benefit imo is that it actually needs to do very little to achieve the goal and doesn’t need to add any new concepts or configuration.

**Comment by lordrhodos** [comment]
@bradennapier yes I agree this to rather a css issue. If you add highlighting via background colour for `:hover` and `active` state you probably want to change the bottom padding as well I guess.

> A whole new switch and model seems excessive. This solutions primary benefit imo is that it actually needs to do very little to achieve the goal and doesn’t need to add any new concepts or configuration.

I agree that a global switch is debatable. I rather prefer to set a configuration setting than duplicating a setting in the spec for `n` group tags ;-)

A new model is not needed, it is rather extending already existing case checks. I have pushed my current `wip` which you can see here (far from being PR ready ;-)):

https://github.com/Rebilly/ReDoc/compare/master...lordrhodos:toggle-tag-groups?expand=1

**Comment by lornajane** [comment]
This seems to have stalled, so I'll close the issue. Let us know if this still seems like something that would be useful!

**Comment by cleverly87** [comment]
This would be extremely useful - a collapsible x-tagGroup will greatly improve the overall UX with big API's I am desperately looking for a solution like this - It will allow for extremely neat and tidy compartmentalising of products with TAGS - PLEASE PLEASE PLEASE get this feature up and running

**Comment by StianOek** [comment]
I totally agree with @cleverly87 This would be greatly appriciated to have this option

**Comment by davide-stefanini** [comment]
I'm trying to enrich my API documentation with some additional sections using x.traitTag, and I think this could be very useful to better organize them.

**Comment by Nahuel-LCvista** [comment]
Hi @lornajane, I came across this feature request from a long time ago, and it seems to be not implemented yet.
It would be great to have a collapsible x-tagGroup, with the option to have each tagGroup collapsed by default individually, so the documentation doesn't look like a giant open accordion and only shows what we want it to show when loading. 

@bradennapier [submitted a PR](https://github.com/Redocly/redoc/pull/853) with the feature a couple years ago, but it was flagged as out of scope and rejected. Is there any chance we can see this implemented in the near future?

Thanks in advance!
