### ISSUE TITLE
Customising redoc with css/js

### ISSUE THREAD

**Issue by imjeremyhi** [Redocly/redoc#827]
What's the recommended approach to customising redoc via css/js?

My understanding is we can just include our own css files that target specific dom elements. That's generally working - I'm not sure if that is recommended.

I want to do some customisation after the redoc has properly loaded. I'm exploring `Redoc.init`'s callback but it gets executed while the document is still in a Loading state (ie. with the loading spinner), not when the api content is actually rendered. I'm looking at customising some behaviour via jquery but can't get to the actual DOM elements as the callback gets executed too early. I'm also not sure this is the recommended approach.

**Comment by jamiek-acl** [comment]
I wish reDoc had a better way to manage colours, as adding my own stylesheet with rules like the below is cumbersome, and not all elements can be targeted:

    .api-content .react-tabs__tab-panel > div > div:nth-of-type(2) > div > div:first-of-type {
      opacity: 1;
    }

These changes are necessary for accessibility (redoc fails many AA requirements - here I am trying to resolve colour contrast errors).

**Comment by lornajane** [comment]
Much of this changed with the 2.0 release, which also included accessibility improvements, so I'm closing this issue. Please do open new issues though if you have more styling questions.
