### ISSUE TITLE
[Feature Request] Example in the description

### ISSUE THREAD

**Issue by vikrantk365** [Redocly/redoc#829]
### Atm, we only get description here and example is shown in the payload section
![image](https://user-images.githubusercontent.com/5028204/53583109-c8a6ce00-3b78-11e9-8789-bb21a169b2a7.png)

### It would be good to schema example in the description as well for primitive types

![image](https://user-images.githubusercontent.com/5028204/53583319-4074f880-3b79-11e9-945b-79008d0799af.png)

**Comment by lornajane** [comment]
For short examples like you show here, it could be nice to have it in the documentation. However many more complex APIs may have large JSON objects as their examples, so overall this isn't a change that would benefit all users.
