### ISSUE TITLE
Feature request: document redoc-cli command-line options in readme

### ISSUE THREAD

**Issue by RichardCullen** [Redocly/redoc#830]
Feature request: redoc-cli supports `-p nnnn` to specify the port that a spec is served from, but it's not listed in the readme. Please add documentation for these other commandline options. Thanks!

**Comment by nanov** [comment]
[there is one](https://github.com/Rebilly/ReDoc/blob/70faca17b68a3aa3e78a51a238d8090535ae1961/cli/index.ts#L50)

**Comment by RichardCullen** [comment]
@nanov yes there is. Very useful! Including the cmdline options in the readme would be a Good Thing (tm). Updated the title to reflect the request.

**Comment by Zadagu** [comment]
It would be nice to add redoc-cli to the deployement options. I needed some time to find out that there is a command line interface at all.

**Comment by lornajane** [comment]
Please note that `redoc-cli` is has been replaced by `redocly-cli`. There is a guide to help you [migrate to Redocly CLI](https://redocly.com/docs/cli/guides/migrate-from-redoc-cli/).
