### ISSUE TITLE
Add build tests for redoc-cli

### ISSUE THREAD

**Issue by skwashd** [Redocly/redoc#851]
redoc-cli 0.8.1 shipping with a broken dependency (see #848). redoc-cli 0.8.2 that was supposed to fix the issues in 0.8.1 also shipped with broken dependencies (see #850). 

Travis should at least build the cli package to confirm that it isn't broken.

**Comment by RomanGotsiy** [comment]
Yes. Makes total sense.

But Travis does build the package. The deps that were missing were included transitively in dev-deps.

We need a proper test with build + remove node_modules + `install --prod` and run it.

PRs are welcome!

**Comment by lornajane** [comment]
Closing this since `redoc-cli` is deprecated. Users should [migrate to Redocly CLI](https://redocly.com/docs/cli/guides/migrate-from-redoc-cli/).
