### ISSUE TITLE
[Feature Request] Let us theme the Path

### ISSUE THREAD

**Issue by wizacedric** [Redocly/redoc#860]
Hello, and thank you for ReDoc. 

I have an issue where I'm using a nice font for the headings of the document, but that font does not display code very well. Since the same font is used in the "path" sections (eg. GET /users/{userId}), they are not very legible.

I would like to see a theming option under typography, named "paths", which would inherit from headings for backward-compatibility purposes, and would let me change the fontFamily and fontWeight of the "path" sections in the document independantly from the "headings".

Would you accept a PR?

**Comment by RomanGotsiy** [comment]
Ah. Why this font is used for "path" in the first place?. Should be a mistake!

I think [here](https://github.com/Rebilly/ReDoc/blob/2f65f051e0ede6d786d510cc1ddad2889ab9d367/src/components/Endpoint/styled.elements.ts#L10) is better to use `code` font: https://github.com/Rebilly/ReDoc/blob/master/src/theme.ts#L109

PR would be appreciated!
