### ISSUE TITLE
Field properties dont merged

### ISSUE THREAD

**Issue by ArcheeNic** [Redocly/redoc#861]
I use this code
```yaml
openapi: 3.0.1
servers:
  - url: 'https://example.loc'
info:
  version: 3.0.0
  title: Example
tags:
  - name: orders
    description: Работа с заказами
paths:
  /orders:
    get:
      responses:
        '400':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/error'
                properties:
                  code:
                    example: 400
components:
  schemas:
    error:
      description: Response error
      properties:
        code:
          type: integer
          format: int32
          example: 200
        title:
          type: string
          format: string
        description:
          type: string
          format: string
```

In Swagger UI example field changed
![изображение](https://user-images.githubusercontent.com/22499333/54729158-0359c000-4b93-11e9-9f07-c57a587a582d.png)

In Redoc example dont change
![изображение](https://user-images.githubusercontent.com/22499333/54729402-57b16f80-4b94-11e9-83ac-d7517146632e.png)

I'm waiting for the value in the example to change from 200 to 400

**Comment by almero** [comment]
I have the same issue with allOf referencing 2 "#/components/schemas/xxx".
The response schema displayed is correct, but the **examples** inside my 2 "#/components/schemas/xxx" are not merged.

**Comment by neluzhin** [comment]
@ArcheeNic, as I can see, your `#/components/schemas/error` schema is invalid. That's what OpenAPI 3.0.2 specification says ([Composition and Inheritance (Polymorphism)](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#composition-and-inheritance-polymorphism)):

> The OpenAPI Specification allows combining and extending model definitions using the `allOf` property of JSON Schema, in effect offering model composition. `allOf` takes an array of object definitions that are validated *independently* but together compose a single object.

That mean each item in `allOf` should be a valid OpenAPI schema object. Your object is invalid because it's missing `type: object` property.

Also your `paths -> /orders -> get -> responses -> '400' -> content -> application/json -> schema` contains invalid OpenAPI schema too (it's missing `type: object` property).

ReDoc has more strict parser than Swagger UI, that's because behavior differs.

**Comment by RomanGotsiy** [comment]
> Your schema is invalid because it's missing type: object definition.

@neluzhin that's not correct. `type: object` is not required according to the spec.

@ArcheeNic in ReDoc `allOf` is applied on top of the existing schema so `example: 400` gets overwritten. Try this:

application/json:
  schema:
    allOf:
      - $ref: '#/components/schemas/error'
      - properties:
          code:
            example: 400

**Comment by almero** [comment]
Hello,

Here is a test specification showing my problem:

````
openapi: "3.0.0"
info:
  title: Test API
  description: Test API specification
  version: "1.1.0"
servers:
  - description: |
      Local test server.
    url: http://localhost:50500/
paths:

  /my/path/:
    get:
      tags:
        - test
      summary: This is a test spec
      responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/MySchema1"
                  - $ref: "#/components/schemas/MySchema2"
components:
  schemas:
    MySchema1:
      properties:
        exception:
          type: object
      example:
        {
          "exception": {
             todo: abc
          }
        }

    MySchema2:
      required:
        - status
      properties:
        status:
          type: string
          enum: [
            "Error2"
          ]
      example:
        {
          "status": "Error2"
        }
````



Below is attached the specification:
[test_api.zip](https://github.com/Rebilly/ReDoc/files/3196716/test_api.zip)

When using it with swagger editor, I can see the following example value:
![image](https://user-images.githubusercontent.com/8070487/58003544-4e377b80-7ae1-11e9-8ba5-fe3fe78c91e7.png)

When using it with ReDoc, I can see the following example value:
![image](https://user-images.githubusercontent.com/8070487/58003590-60191e80-7ae1-11e9-87a1-d9cc78fa5c86.png)

It seems the examples from my two schemas are not correctly merged.
I would expect to see the same example as in swagger editor.

**Comment by lornajane** [comment]
I think this was fixed in newer versions of Redoc, could you please upgrade and let us know if there's still something that doesn't look right?
