### ISSUE TITLE
Pagination of tags

### ISSUE THREAD

**Issue by imjeremyhi** [Redocly/redoc#867]
Is it possible to render each `data-section` defined by `tags`, onto a separate page. The `rebilly` and `zuora` example docs are able to do this but I could not find documentation for this. I've also looked into the codebase and I could not find how this feature is enabled. 

The project I'm working on has a large set of endpoints. From a design perspective, it would be a better UX if I could split each tag section into separate pages - rather than all on the same page (which is the current default format).

**Comment by amcgaw07** [comment]
wondering this as well

**Comment by lornajane** [comment]
This feature is available in our commercial hosted offering, which are a bit more tailored to those larger API descriptions; I'm afraid it's not supported in open source Redoc.
