### ISSUE TITLE
Refactor repository's Markdown files

### ISSUE THREAD

**Issue by flaksp** [Redocly/redoc#890]
I'd like to refactor all Markdown files in the projects. I want to achieve these goals:

1. Improve texts and its structure. At this moment docs contain a lot of useless info (such as roadmap). 
2. Completely remove HTML from Markdown files. I'm sure Markdown format designed to be readable without rendering (e.g. via console) should not contain HTML even if GitHub supports it.
3. Remove useless badges from main [README.md](https://github.com/Rebilly/ReDoc/blob/master/README.md) file. I want to keep only these:

    * [![Build Status](https://travis-ci.org/Rebilly/ReDoc.svg?branch=master)](https://travis-ci.org/Rebilly/ReDoc) - as we use external CI solution, we should see when it's going wrong.
    * [![Docker Build Status](https://img.shields.io/docker/build/redocly/redoc.svg)](https://hub.docker.com/r/redocly/redoc/) - if Docker isn't building properly, we should notice this too.

    About other badges:

    * [![Coverage Status](https://coveralls.io/repos/Rebilly/ReDoc/badge.svg?branch=master&service=github)](https://coveralls.io/github/Rebilly/ReDoc?branch=master) - not really sure we need coverage badge because it means nothing for ReDoc users and contributors. I'm not sure somebody takes a care about coverage when contributing to ReDoc. At least we can place it inside [CONTRIBUTING.md](https://github.com/Rebilly/ReDoc/blob/master/.github/CONTRIBUTING.md) file.
    * [![dependencies Status](https://david-dm.org/Rebilly/ReDoc/status.svg)](https://david-dm.org/Rebilly/ReDoc) [![devDependencies Status](https://david-dm.org/Rebilly/ReDoc/dev-status.svg)](https://david-dm.org/Rebilly/ReDoc#info=devDependencies) - again, as ReDoc user and contributor I'm not interested in this information. I'd like to recommend you install [Renovatebot](https://renovatebot.com/) instead who will automatically create pull requests with updated dependencies (I use it within my personal projects and it works like a charm), it's free for open source.
    * [![npm](http://img.shields.io/npm/v/redoc.svg)](https://www.npmjs.com/package/redoc) - I can visit [Releases](https://github.com/Rebilly/ReDoc/releases) page or [CHANGELOG.md](https://github.com/Rebilly/ReDoc/blob/master/CHANGELOG.md) file to see the latest version.
    * [![License](https://img.shields.io/npm/l/redoc.svg)](https://github.com/Rebilly/ReDoc/blob/master/LICENSE) - most users are not interested in this. But people who interested may see at the top of GitHub repository (it contains license name) or visit [LICENSE](https://github.com/Rebilly/ReDoc/blob/master/LICENSE) file for details.
    * [![bundle size](http://img.badgesize.io/https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js?compression=gzip&max=300000)](https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js) - ReDoc is not a library like jQuery or React where size matters.
    * [![](https://data.jsdelivr.com/v1/package/npm/redoc/badge)](https://www.jsdelivr.com/package/npm/redoc) - amount of hits from CDN also doesn't seem useful for anyone. 
    * [![npm](https://img.shields.io/npm/dm/redoc.svg)](https://www.npmjs.com/package/redoc) - this is the only one badge I'm not sure I want to remove, but this one is also some useless kind of "coolness". ReDoc served not only as a npm package, but also via CDN and Docker Hub, so npm statistics says nothing useful. 

4. All texts will have consistent Markdown formatting.
5. All images that point via HTTP will use relative path to file (e.g. `https://raw.githubusercontent.com/Rebilly/ReDoc/master/docs/images/redoc-logo.png` → `./docs/images/redoc-logo.png`).
6. Are links "ReDoc as a service" and "Custom development" still actual? Maybe we can remove them? 

If everything is OK I will create pull request this/next week with all changes.

**Comment by RomanGotsiy** [comment]
Hi @neluzhin.

You're welcome to open a PR! Although I'm not sure about some of your points.

> 1. Improve texts and its structure. At this moment docs contain a lot of useless info (such as roadmap).

Do it. Not sure about useless info though. We can discuss it after you open a PR.

> 2. Completely remove HTML from Markdown files. I'm sure Markdown format designed to be readable without rendering (e.g. via console) should not contain HTML even if GitHub supports it.

Why do you need it? Do you face any particular issues because of HTML in md? There is very little of HTML (basically for centering content only)


> 3. Remove useless badges from main README.md file.

Here I do not agree. While you find them useless, someone can find them useful. I, personally, always pay attention to badges while evaluating OSS projects

> 6. Are links "ReDoc as a service" and "Custom development" still actual? Maybe we can remove them?

They are still actual.

------

Thanks for your time!

**Comment by lornajane** [comment]
This went stale, we can revisit it in the future.
