### ISSUE TITLE
Use monospace font for values, paths, properties, etc

### ISSUE THREAD

**Issue by neluzhin** [Redocly/redoc#909]
For better readability I suggest using monospaced font everywhere, when non-human readable text rendered. Examples with `font-family: monospace` are below.

I'm not sure I have covered all places where it may be implemented.

## Paths

Before: 

![image](https://user-images.githubusercontent.com/12474739/57487665-bf915600-72b9-11e9-9611-2dac04b5e2f0.png)

After:

![image](https://user-images.githubusercontent.com/12474739/57487685-cd46db80-72b9-11e9-8143-042d7eb3a3b9.png)

## `pattern` schema property

Before:

![image](https://user-images.githubusercontent.com/12474739/57487106-5a893080-72b8-11e9-95b1-abcd718302aa.png)

After:

![image](https://user-images.githubusercontent.com/12474739/57487098-5230f580-72b8-11e9-8c27-5502b076a7e3.png)

## Field / property / header/ parameter names

Before:

![image](https://user-images.githubusercontent.com/12474739/57487224-b0f66f00-72b8-11e9-9a72-170538953514.png)

After:

![image](https://user-images.githubusercontent.com/12474739/57487996-8d342880-72ba-11e9-8479-48ebcecae9c9.png)

## MIME Types

Before:

![image](https://user-images.githubusercontent.com/12474739/57487271-d08d9780-72b8-11e9-86ac-fe995fc40320.png)

After:

![image](https://user-images.githubusercontent.com/12474739/57488075-b6ed4f80-72ba-11e9-809c-09a07be0a769.png)

## Enum values

Before:

![image](https://user-images.githubusercontent.com/12474739/57487367-10547f00-72b9-11e9-91fc-ad342220fb53.png)

After:

![image](https://user-images.githubusercontent.com/12474739/57487404-25311280-72b9-11e9-9c41-ad84819e8a9b.png)

![image](https://user-images.githubusercontent.com/12474739/57487500-6e816200-72b9-11e9-9dfc-d206135a6a12.png)

## What's I'm not sure should be monospaced, but maybe it should be discussed

1. Schema type 
2. Schema title

**Comment by RomanGotsiy** [comment]
Great suggestion. PR would be appreciated!

**Comment by Hollister009** [comment]
I will work on this one

**Comment by Hollister009** [comment]
https://github.com/Redocly/redoc/pull/866/files <-- fixed endpoint

**Comment by Hollister009** [comment]
@RomanHotsiy PR: https://github.com/Redocly/redoc/pull/1063
