### ISSUE TITLE
204 with empty body is missing from response samples

### ISSUE THREAD

**Issue by benbro** [Redocly/redoc#922]
I see 204 in Responses but not in Response Samples on the right.
```yaml
delete:
  summary: Delete a user
  operationId: deleteUser
  tags:
    - user
  parameters:
    - name: id
      in: path
      required: true
      description: The id of the user to delete
      schema:
        type: string
  responses:
    '204':
      description: Empty response when the user is deleted
```

**Comment by thomasplevy** [comment]
I believe this is probably expected behavior since a `204` (by definition) has no content there's no sample response to show.

**Comment by benbro** [comment]
It's still a response with empty body.
Excluding it from response samples make it look like it's not a possible response.

**Comment by m-mohr** [comment]
The response is shown in the corresponding "Responses" chapter, but not shown in the examples (as there's no example). I think this is really expected behaviour. You shouldn't base your assumptions on examples, but on the actual specification. This could be a new feature, but I would not see this as a bug.

**Comment by RomanHotsiy** [comment]
@m-mohr is correct. There is no example. The response is shown in the middle panel.

**Comment by dylantack** [comment]
You can work around it with:

```yaml
            responses:
                '204':
                    description: deleted
                    content:
                        text/html:
                            example: ''
```

But I agree that it would be an improvement to include this automatically, it can be confusing to readers when the 204 response example is missing.
