### ISSUE TITLE
 how to stop scrolling between each pagination section. ( redoc / react / js /json)

### ISSUE THREAD

**Issue by hadriensoumoy** [Redocly/redoc#923]
Hello,

I'm trying to stop scrolling through the pagination.

On my redoc, scrolling does not stop. I'm trying to stop scrolling through each section title. I want to show the text "next to ..." followed by the title of the section. (As in the API demo and my screenshot).

![tempsnip](https://user-images.githubusercontent.com/43204245/58205882-d08d8e80-7cdf-11e9-8e29-cc473debe674.png)

I thought I had to change just a part of my json file, which I did but to no avail.

I work on redoc using react.
my api is in json.

It's been two days since I'm trying to change that.
I looked at the documentation, forums, and file inspector to find out what was changing in my API and in the demo.

I hope someone can help me find a solution.
Thank you.

link demo : https://rebilly.github.io/RebillyAPI/#section/Expand-to-Include-Embedded-Objects

**Comment by stueynz** [comment]
The event attached to the button concerned comes from redocproc-standalone.min.js so one is left assuming that this is a feature of the Pro version of reDoc.

**Comment by KyleHeLi** [comment]
Hi @hadriensoumoy, I wonder how did you do the pagination with ReDoc? I tried to find some document about it, but no luck. Thank you.

**Comment by RomanHotsiy** [comment]
This is a feature of the Pro version of Redoc. 
We will do a public release soon. Subscribe to [@redocly](https://twitter.com/redocly) for updates.
