### ISSUE TITLE
Display infinity and NaN for YAML

### ISSUE THREAD

**Issue by eu42** [Redocly/redoc#928]
I know that OpenAPI does not support infinity values as it is not supported by JSON, but since YAML supports `.inf`, `-.inf`, and `.NAN`, what about rendering them instead of displaying `null`? Simply displaying `Infinity`, `-Infinity`, and `NaN` would be enough I guess.

As an example that this can be done this way, Swagger UI displays these values as I suggested.

**Comment by lornajane** [comment]
Closing since this issue seems inactive (tell us if this still seems important though!)
