### ISSUE TITLE
`/spec.json` endpoint broken in docker

### ISSUE THREAD

**Issue by Teelevision** [Redocly/redoc#931]
Version: v2.0.0-rc.8-1

**Steps to reproduce:**
  1. `wget https://raw.githubusercontent.com/Rebilly/ReDoc/v2.0.0-rc.8-1/demo/swagger.yaml`
  2. `docker run -it --rm -p 80:80 -v $(pwd)/swagger.yaml:/usr/share/nginx/html/swagger.yaml -e SPEC_URL=swagger.yaml redocly/redoc:v2.0.0-rc.8-1`
  3. Get `http://localhost:80/spec.json`

**Expected behaviour:**
Server returns the api spec in json format.

**Observed behaviour:**
Server returned 404, reports

> open() "/usr/share/nginx/html/spec.json" failed (2: No such file or directory)

in the console.

**Why I think this is a bug**
It used to work previously when I used the CLI. As far as I can see the CLI still supports it: https://github.com/Rebilly/ReDoc/blob/v2.0.0-rc.8-1/cli/index.ts#L160

**Comment by RomanHotsiy** [comment]
Why do you expect `/spec.json` to return API spec in json format? Is this behavior documented anywhere?

**Comment by Teelevision** [comment]
> Is this behavior documented anywhere?

Not that I know.
