### ISSUE TITLE
[Suggestion] Add support for mimetype application/x-ndjson 

### ISSUE THREAD

**Issue by lagonnebula** [Redocly/redoc#940]
Hello,
I saw that for now Redoc 2.0 only support XML and JSON, Is it possible to support nd-json as well for requestBodies  and requestBody ?

For example: 
```yaml
requestBody:
  content: 
    application/x-ndjson:
      schema:
         $ref: '#/components/schemas/ClassicJsonSchema'
      example: 
         value: 
            - example: true
            - example: true
               secondeLine: yup
            - example: true
               line: ImTheThird
```

The value is an array, but when formated, the array is converted to a ndjson.
Specs of ndjson: http://ndjson.org/

```json
{"example":true}
{"example":true, "secondeLine":"yup"}
{"example":true, "line": "ImTheThird"}
```

I tried to make it myself, but i had issue with adding $ref in each line (the value key didn't key mapped with $ref)

**Comment by RomanHotsiy** [comment]
Unfortuanatelly this is out of scope of ReDoc. We can't add each mimetype support. Try to workaround it somehow. 

The easist way is just put human-readalbe description.

**Comment by stevapple** [comment]
Given that NDJSON and JSONL are gaining popularity especially in streaming APIs, we would like to suggest revist this feature request. Would like to offer help on the topic.
