### ISSUE TITLE
Schemas under components are completely ignored

### ISSUE THREAD

**Issue by chinciusan** [Redocly/redoc#954]
I have multiple schemas under components and nothing is rendered. 
```yaml
components:
  schemas:
    PartialUserRepresentation:
      description: A partial user representation consists of a subset of attributes from
        the MyUserSchema and CustomUserSchema
      allOf:
        - $ref: "#/components/schemas/MyUserSchema"
        - $ref: "#/components/schemas/CustomUserSchema"
      example:
        id: 52103b45-ca78-40b3-bae2-7a5c497d19a6
        primary_email: bob@email.com
        home_email: bob@email.com
        work_email: bob@work.com
```

Using the same code in swagger editor, everything is output correctly 
![image](https://user-images.githubusercontent.com/5501918/60266140-1eee0880-98f0-11e9-97c0-338b983915ad.png)

**Comment by RomanHotsiy** [comment]
ReDoc doesn't render components separately. USe your schema in operation request body or response and it will render.

See also: https://github.com/Redocly/redoc/pull/681 https://github.com/pollination/api/issues/5
