### ISSUE TITLE
Style conflict with CSS framework

### ISSUE THREAD

**Issue by aleung** [Redocly/redoc#957]
I embed the Redoc standalone in a website which uses [Bulma](https://bulma.io/) CSS framework. Some styles in Redoc aren't shown correctly. There are two kind of issues I found so far:

1. Redoc set some classes on element. There classes are styled by Bulma. For example, class `delete`, `number` are styled by Bulma.
2. Bulma changes style of some HTML tags, e.g. `<h3>``<li>``<strong>`. Redoc doesn't set style to these elements and then they're displayed in Bulma style.

![image](https://user-images.githubusercontent.com/271538/60329800-a9536c80-99c3-11e9-8332-e0aa1b86b231.png)

I searched around and couldn't find a solution to exclude an HTML element from Bulma's style sheet. The promising solution is shadow DOM. I tried to put Redoc in a shadow DOM but all styles were gone. It's because Redoc uses styled-component which inserts style into HTML `<head>`, so these styles are also isolated from shadow DOM.

I come here to check if anybody has a solution to embed Redoc into website which is using a CSS framework? Right now the last chance for me seems to be using `iframe`. But I really don't like to use it.

**Comment by RomanHotsiy** [comment]
Could you just put Redoc into the separate page where Bulma CSS is not loaded?

There is no way those issues can be resolved on Redoc side. There are tons of CSS frameworks around.

**Comment by aleung** [comment]
#1548
