### ISSUE TITLE
Unable to run `Docker build` locally

### ISSUE THREAD

**Issue by davidanrod** [Redocly/redoc#960]
Hi, 

running this from project root:

`docker build -t redocly/redoc:custom -f config/docker/Dockerfile .`

got every time this: 

`The command '/bin/sh -c npm run bundle:standalone' returned a non-zero code: 2`

Am i doing something wrong?

Thanks.

**Comment by RomanHotsiy** [comment]
Any other logs? Did you change something in the code?

**Comment by davidanrod** [comment]
Hi @RomanHotsiy,

sorry.. my mistake.. it was an syntax error originated by some modifications that i did..
my apologies for this issue..

Thanks,
David.
