### ISSUE TITLE
add an option to control `Documentation Powered by ReDoc` show or hide

### ISSUE THREAD

**Issue by evalizhangli** [Redocly/redoc#961]
provide an option to control the bottom link `Documentation Powered by ReDoc` show or hide

**Comment by RomanHotsiy** [comment]
Redoc is provided for free and we spend lots of time working on it. The white-label helps us gain recognition.

We're not going to add such option

**Comment by evalizhangli** [comment]
ok. I see.  thanks~

**Comment by jchook** [comment]
Would you allow removing the attribution for a fee or donation?

**Comment by RomanHotsiy** [comment]
We are about to release our paid product which will have the option to remove the attribution. You can subscribe at https://redoc.ly for the updates.

**Comment by jchook** [comment]
@RomanHotsiy congrats!!

**Comment by Paxa** [comment]
Is it possible with paid product and keep our content on our servers? (sorry oot)

```html
<style>
a[href="https://github.com/Redocly/redoc"] {
  opacity: 0;
}
</style>
```
