### ISSUE TITLE
How to represent to send on field or another

### ISSUE THREAD

**Issue by raderio** [Redocly/redoc#962]
For example in our API in the request should be sent userId(if exist) **or** user(as object with full details).
How this can be represented in ReDoc?

An example can be https://www.marqeta.com/api/docs/Vh7jxx0AAB4A17SS/transfers#create_fee_transfer
you can check 
```
user_token 
OR 
business_token
```
in the request body

**Comment by RomanHotsiy** [comment]
There is no way to do that as this is not supported by OpenAPI.
I recommend adding this to the field description.
