### ISSUE TITLE
Fail compile redoc standalone js

### ISSUE THREAD

**Issue by gogocat** [Redocly/redoc#964]
I got these error when running bundle:standalone

I have not touch the code. just clone redoc > npm install > npm run bundle:standalone

ERROR in D:\tmp\redoc\src\utils\highlight.ts
[tsl] ERROR in D:\tmp\redoc\src\utils\highlight.ts(65,10)
      TS2554: Expected 3 arguments, but got 2.

ERROR in D:\tmp\redoc\src\services\ClipboardService.ts
[tsl] ERROR in D:\tmp\redoc\src\services\ClipboardService.ts(28,7)
      TS2531: Object is possibly 'null'.

**Comment by RomanHotsiy** [comment]
Use `yarn` instead of `npm` for local development. Must be some `typescript` update.
