### ISSUE TITLE
Separate examples using same `$ref` don't render correctly

### ISSUE THREAD

**Issue by AnthonyPorthouse** [Redocly/redoc#967]
Given a spec:

```yaml
openapi: 3.0.0
info:
  title: Example Fail
  version: 0.0.1
paths:
  /example1:
    get:
      responses:
        200:
          description: Example 1
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
              examples:
                basic:
                  value:
                    $ref: ./example.json
  /example2:
    get:
      responses:
        200:
          description: Example 2
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
              examples:
                basic:
                  value:
                    $ref: ./example.json
```

and a file `example.json` in the same directory with the contents:
```json
{
  "key": "value"
}
```

When served via redoc-cli with `npx redoc-cli serve openapi.yaml` outputs the following in the response examples:
<img width="505" alt="Screenshot 2019-07-08 at 09 46 11" src="https://user-images.githubusercontent.com/5079595/60796447-48ffc000-a165-11e9-9c33-c8d19b971f7d.png">

The second example shows only the reference name instead of the actual resolved reference content.

**Comment by RomanHotsiy** [comment]
You can't use $ref inside example value. Value is meant to be presented as is. Example: what if your payload has `$ref` property?

The fact that Redoc resolves $ref in the first example is another bug though.

Related to https://github.com/Redocly/redoc/issues/840

**Comment by AnthonyPorthouse** [comment]
Thanks @RomanHotsiy, after reading the other issue I can see the way you suggest doing it which is fine for my use case.
