### ISSUE TITLE
Incorrectly serialized parameter examples when using hyphens

### ISSUE THREAD

**Issue by lgellrich** [Redocly/redoc#969]
After upgrading ReDoc from 2.0.0-rc.8 I noticed that examples for parameters in my OpenAPI Specification got rendered incorrectly in case that parameter names contain a hyphen.

**ReDoc React**
Using ReDoc as React component the example values display as _**?parameter-name}**_

**redoc-cli**
Serving the same specification via redoc-cli the examples are rendered as if processed by JSON.stringify(). As mentioned in #504 

With the current React behavior the examples become useless, while the redoc-cli behavior enables the workaround of specifying the example as a string myself.

Affected ReDoc versions: 2.0.0-rc.9, 2.0.0-rc.10
Tested redoc-cli versions: 0.8.4, 0.8.5

### References

**Render from redoc-cli 0.8.5**
![redoc-cli_0 8 5_sample](https://user-images.githubusercontent.com/1510470/60926287-5bcdde00-a2a6-11e9-866c-c5a75775d6b1.PNG)

**Render via ReDoc Live Demo:**
![redoc-live_sample](https://user-images.githubusercontent.com/1510470/60926290-5d97a180-a2a6-11e9-9e46-a62fa3f6129d.PNG)

**OpenAPI sample:**
```
---
openapi: 3.0.0
info:
  title: "API"
  version: "1.0.0"
paths:
  /demo/{myId}/{my-id}:
    get:
      summary: Demo ReDoc Example Values
      parameters:
        - name: myId
          in: path
          schema:
            type: number
          example: 1
        - name: my-id
          in: path
          schema:
            type: number
          example: 1
        - name: my-parameter-with-hyphen
          in: query
          schema:
            type: string
          example: sampleValue
        - name: myParameterWithHyphen
          in: query
          schema:
            type: string
          example: sampleValue
        - name: my-array-parameter
          in: query
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
          example:
            - a
            - b
            - c
        - name: myArrayParameter
          in: query
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
          example:
            - a
            - b
            - c
```

**Comment by cyril1929** [comment]
Redoc-cli must define an explicit version of the dependency redoc. And thus avoid having a different behavior depending on when redoc-cli was installed.

**Comment by cyril1929** [comment]
I have the same problem with redoc-cli 0.8.5.
Examples are not correct, when the parameter name contains one '-' character.

**Comment by RomanHotsiy** [comment]
fixed by https://github.com/Redocly/redoc/commit/f7dd658a01158fb038fe3a7cea210657dcebff52

**Comment by RomanHotsiy** [comment]
will be released in the new version today
