### ISSUE TITLE
Left menu anchor links position content under fixed header

### ISSUE THREAD

**Issue by lasithalokuge** [Redocly/redoc#970]
I'm using redoc within a 'fixed header' HTML and left menu links are placing content underneath the header.
![fixed-navbar](https://user-images.githubusercontent.com/13149757/60962391-bca9f480-a340-11e9-8608-7c91b7c340a3.png)

**Comment by RomanHotsiy** [comment]
use `scrollYOffset`, see [options](https://github.com/Redocly/redoc#redoc-options-object)

**Comment by lasithalokuge** [comment]
> use `scrollYOffset`, see [options](https://github.com/Redocly/redoc#redoc-options-object)

Works like a charm... thank you so much for the quick reply.
