### ISSUE TITLE
Markdown table description issue

### ISSUE THREAD

**Issue by jadamon42** [Redocly/redoc#972]
When creating a table using markdown in the description field, everything after the table is added to the table. This is not what I want. It's even worse if you try to put something before the table, the table shows up as what was written, character for character, as if it were no longer markdown.

Example:

description: |
                   I want to give some details about the table here
                   | value                                                  | description |
                   |-----------|-------|
                   | example1                                           | blah1          |
                   | example2                                           | blah2          |
                   | example3                                           | blah3          |
                   | example4                                           | blah4          |
                   Now I want to say something here
                   Maybe even give a list:
                   - Item 1
                   - Item 2

This simply does not work. However, it does work for me elsewhere. For example, I came from swagger-ui, and this worked there. Redoc is almost perfect, but this really causes a problem for me.

**Comment by RomanHotsiy** [comment]
Per OpenAPI spec, all descriptions should be in common mark syntax. So tables are not supposed to work in markdown at all.

Although, I enabled tables as this is a useful feature. The markdown parser used in Redoc requires newline before and after the table:

```yaml
description: |
  I want to give some details about the table here

  | value | description |
  |-----------|-------|
  | example1 | blah1 |
  | example2 | blah2 |
  | example3 | blah3 |
  | example4 | blah4 |

  Now I want to say something here
  Maybe even give a list:
  - Item 1
  - Item 2
```

**Comment by coderbec** [comment]
Hi, I'm having an issue trying to render a table. 

I'm using this ```
      | Name and preview | Template ID |
      |------------------|-------------|
      | ![image](Https://developers.messagemedia.com/wp-content/templates/Template1.png) | 7614456e-844f-4d83-bdfe-20c17ce0f97c |
      | ![image](Https://developers.messagemedia.com/wp-content/templates/Template2.png) | f56b5806-f732-4693-b87a-90b66a7d7bfc |
      | ![image](Https://developers.messagemedia.com/wp-content/templates/template3.png) | c9d7ce1d-20c4-4228-9ba1-6da2a3b4e5e0 |
```

with new line before and after but it's only rendering part of it as a table with the rest of it all skewiff. What am I missing?
