### ISSUE TITLE
Incorrect "Response samples" rendering

### ISSUE THREAD

**Issue by 907th** [Redocly/redoc#974]
In 2.0.0-rc.10

When page loads first time:

![before](https://user-images.githubusercontent.com/800362/61296872-72b78780-a7f4-11e9-8032-f52b7a5b9162.png)

When I click on 401 sample and then click on 200 sample again:
![after](https://user-images.githubusercontent.com/800362/61296871-72b78780-a7f4-11e9-8ffd-5c7a73c90287.png)

**Comment by RomanHotsiy** [comment]
I can't reproduce it. Could you provide any other details? Do you use redoc-cli? DO you use any css framework? Could you share the link to the docs?

**Comment by 907th** [comment]
redoc 2.0.0-rc.10
redoc-cli 0.8.5

This is the command I use to generate docs:
```
node_modules/redoc-cli/index.js bundle public/partners_api/docs/v2/swagger.json -o public/partners_api/docs/v2/index.html --cdn -t swagger/partners_api_redoc.hbs --options.theme.colors.primary.main=#374D6B --options.theme.rightPanel.backgroundColor=#374D6B --options.theme.colors.error.main=#FF3C54 --options.theme.typography.links.color=#00B4D5
```
Files:
- [swagger.json](https://pastebin.com/Rwu5DSqz)
- [partners_api_redoc.hbs](https://pastebin.com/ZzSUta2L)
- [Resulting index.html file](https://pastebin.com/kb47Fe3r)

**Comment by 907th** [comment]
@RomanHotsiy It is very strange but after adding more APIs and regenerating docs the issue is no longer  happening. Closing this issue for now. Thanks for your attention!
