### ISSUE TITLE
Responses section has accordion icons reversed

### ISSUE THREAD

**Issue by jackthomasatl** [Redocly/redoc#975]
The icons for when a response section is in expanded / collapsed state are reversed.
<img width="1095" alt="Screen Shot 2019-07-15 at 2 14 03 PM" src="https://user-images.githubusercontent.com/1810715/61299332-dc607300-a7ad-11e9-94f9-3d5c821204f0.png">

**Comment by RomanHotsiy** [comment]
That's subjective.
I've seen both variants in the wild and find this more logical and intuitive.

**Comment by jackthomasatl** [comment]
A control should always display be the current state of an object, not a future state. The way these arrows are pointing confuses users. Generally the standard is a right arrow for collapsed and a down arrow for expanded. 

When designing UX controls, you want to make you're consistent with what a user expects a control to do.

An Example, Here's how outlook displays collapsed / expanded areas:
<img width="344" alt="Screen Shot 2019-07-16 at 10 57 33 AM" src="https://user-images.githubusercontent.com/1810715/61305295-9230bf00-a7b8-11e9-82bb-1ccbc623e943.png">

I'll ask you to reconsider, as you're breaking UX norms.

**Comment by jackthomasatl** [comment]
Also, If you look at the left column in redoc. You'll find the arrows using the standard convention.

**Comment by RomanHotsiy** [comment]
Oh, well. I see how it is inconsistent with the left menu...

I will make it consistent with left nav.

**Comment by jackthomasatl** [comment]
Thank you sir.

**Comment by RomanHotsiy** [comment]
I just checked some popular sites and I'm not sure about this particular use case now... 

This is youtube:

![image](https://user-images.githubusercontent.com/3975738/61306253-f1142980-a7f4-11e9-9d16-3cead6caa720.png)
![image](https://user-images.githubusercontent.com/3975738/61306271-f96c6480-a7f4-11e9-8781-c0c6dc9000e7.png)


Gmail have both styles mixed:
![image](https://user-images.githubusercontent.com/3975738/61306366-26207c00-a7f5-11e9-80f7-5cd8b6e0643f.png)

Facebook:

![image](https://user-images.githubusercontent.com/3975738/61306555-844d5f00-a7f5-11e9-9c81-91336bd0a480.png)

But well, I think I will anyway make it consistent with left nav..

**Comment by jackthomasatl** [comment]
Yea. I guess it can be a bit subjective. I think users will learn to user any sort of control we put out, Even if they find it odd. However I believe the standard convention is a right arrow for collapsed and an down arrow for expanded.
