### ISSUE TITLE
Latest ReDoc versions missing at Docker Hub

### ISSUE THREAD

**Issue by neluzhin** [Redocly/redoc#976]
Latest one at [Docker Hub](https://hub.docker.com/r/redocly/redoc/tags) is `v2.0.0-rc.8-1`, but GitHub repository contains `v2.0.0-rc.10` tag as latest at this moment.

**Comment by RomanHotsiy** [comment]
This was caused by repository migration to other org in GitHub. Fixed that. The next tag should appear in docker hub.

Thanks!
