### ISSUE TITLE
Bottom of the docs gets cut-off

### ISSUE THREAD

**Issue by jchook** [Redocly/redoc#980]
Even in the [Live Demo](http://redocly.github.io/redoc/#operation/logoutUser), if you scroll to the very bottom then expand the "Logout" request details:

![image](https://user-images.githubusercontent.com/193530/61500074-abdc2d00-a997-11e9-82ee-0373587388d7.png)

It may have to do with simple requests (like logout) that do not have a lot of extra information returned by the server.

**Comment by thisismo** [comment]
Working just fine for me (tried on Chrome + Firefox).
What browser do you use?

**Comment by jchook** [comment]
Chromium Version 75.0.3770.90 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

![Peek 2019-07-19 20-07 redoc bug](https://user-images.githubusercontent.com/193530/61571362-03929b00-aa61-11e9-80fb-13af26652c6c.gif)

**Comment by BTOdell** [comment]
This is an issue with all drop-downs that overflow out of the operation row.

![DxArjZcMaO](https://user-images.githubusercontent.com/1644309/131756010-0193f929-4427-403c-a92e-ab30b6078ffc.gif)

Pull request #1302 fixes the issue but the question is why were those CSS rules added in the first place? Is there a reason why overflow needs to be hidden?
