### ISSUE TITLE
failed to run a swagger(using nestjs) docs from docker 

### ISSUE THREAD

**Issue by johnico** [Redocly/redoc#982]
steps : 

1- using nestjs i have a link : http://hostname:300/api-json   (from a docker-machine - and I got a 
 valid json if i reach this page also with curl) 
`https://docs.nestjs.com/recipes/swagger 
`
2- Running the redoc docker with 
` SPEC_URL=http://hostname:3000/api-json`

3 . got error :
```
Error downloading http://hostname:3000/api-json Failed to fetch
Stack trace
Error: Error downloading http://hostname:3000/api-json 
Failed to fetch
    at http://hostname:8082/redoc.standalone.js:55:6276
    at http://hostname:8082/redoc.standalone.js:100:35503

TypeError: Failed to fetch

ReDoc Version: 2.0.0-rc.8-1 
Commit:
```

also tried to install curl inside the redoc docker and then curl to the swagger api json and its working so maybe there is an error in the javascript code?

**Comment by RomanHotsiy** [comment]
> Error downloading http://hostname:3000/api-json 

There is something on your side. Check out if cors is enabled.
