### ISSUE TITLE
Add default x-code-samples

### ISSUE THREAD

**Issue by raderio** [Redocly/redoc#984]
Add default parameter for x-code-samples
```
{
  "lang": "JavaScript",
  "source": "console.log('Hello World');",
  "default": true
}
```
In case `default` is `true` than this tab will be preselected and not the `Payload` tab.

**Comment by RomanHotsiy** [comment]
It would be too verbose to annotate the default sample for each operation.
Maybe better add a config option, e.g. `deafultCodeSample`?

**Comment by raderio** [comment]
It also works.

**Comment by damianobarbati** [comment]
Is this currently possible?

**Comment by lornajane** [comment]
Thanks for the suggestion! I'm afraid this isn't currently possible and also isn't planned - I'm closing this issue.
