### ISSUE TITLE
Host joint api path error

### ISSUE THREAD

**Issue by chenmeng111** [Redocly/redoc#985]
Hi Redoc Team,

I try redoc version ^2.0.0-rc.8-1 and found an issue that it will show two slash between host and api path. 

![image](https://user-images.githubusercontent.com/29196565/61775746-1542bc80-ae2c-11e9-967e-9a96a378c869.png)

I try in the http://redocly.github.io/redoc/ use the same data, it show correctly.
![image](https://user-images.githubusercontent.com/29196565/61776438-977fb080-ae2d-11e9-9d12-b777669f0f40.png)

**Comment by RomanHotsiy** [comment]
It is fixed in the latest version 2.0.0-rc.10
