### ISSUE TITLE
[editor] settings / theme

### ISSUE THREAD

**Issue by pointnet** [Redocly/redoc#986]
Hello everyone,

I've just put online a visual settings / theme editor for ReDoc.

[https://github.com/pointnet/redoc-editor](https://github.com/pointnet/redoc-editor)

Live demo: [https://pointnet.github.io/redoc-editor](http://pointnet.github.io/redoc-editor)

Example: [shared config](https://pointnet.github.io/redoc-editor/#/?config=eyJzcGVjVXJsIjoiaHR0cHM6Ly9wb2ludG5ldC5naXRodWIuaW8vcmVkb2MtZWRpdG9yL29wZW5hcGkueWFtbCIsImJhY2tncm91bmRDb2xvciI6IiNmZmZmZmYiLCJvcHRpb25zIjp7InVudHJ1c3RlZFNwZWMiOnRydWUsImRpc2FibGVTZWFyY2giOnRydWUsIm5vQXV0b0F1dGgiOnRydWUsInRoZW1lIjp7ImNvbG9ycyI6eyJwcmltYXJ5Ijp7Im1haW4iOiJyZ2JhKDEzOSwgODcsIDQyLCAxKSIsImxpZ2h0IjoiI2Q2YTQ3OCIsImRhcmsiOiIjMTYwZDA2IiwiY29udHJhc3RUZXh0IjoiI2ZmZiJ9fSwidHlwb2dyYXBoeSI6eyJsaW5rcyI6eyJjb2xvciI6InJnYmEoNzQsIDE0NCwgMjI2LCAxKSIsInZpc2l0ZWQiOiJyZ2JhKDc0LCAxNDQsIDIyNiwgMSkiLCJob3ZlciI6IiNhMmM2ZjAifX0sIm1lbnUiOnsiYmFja2dyb3VuZENvbG9yIjoicmdiYSg3NCwgNzQsIDc0LCAxKSIsInRleHRDb2xvciI6InJnYmEoMjU1LCAyNTUsIDI1NSwgMSkifSwicmlnaHRQYW5lbCI6eyJiYWNrZ3JvdW5kQ29sb3IiOiJyZ2JhKDc0LCA3NCwgNzQsIDEpIn19fX0=)

Hope this helps!

**Comment by grzegorztomasiak** [comment]
gosh... this is amazing! finally i can play with redoc colors quickly! good job man!

**Comment by caffeinatedMike** [comment]
Would it be possible to make the PATH element more prominent (maybe with the ability to change color or something else) when selecting SHOW PATH IN MIDDLE PANEL? Right now you can change the color of the PATH element when it's in its default position (right panel), but not when it's moved to the middle panel. For me, I'd prefer the path in the middle panel, but with how it displays current I feel it isn't as easily spotted like when it's in the right panel.

Default Path shown in right panel:
![Default Path shown in right panel](https://user-images.githubusercontent.com/22151742/75568631-a234a080-5a21-11ea-9689-c4d9e3ce0283.png)

Current display with SHOW PATH IN MIDDLE PANEL
![Current display with SHOW PATH IN MIDDLE PANEL](https://user-images.githubusercontent.com/22151742/75568648-a9f44500-5a21-11ea-8fce-63cdbbdba534.png)

Proposed change to allow custom color when SHOW PATH IN MIDDLE PANEL is selected
![Proposed change to allow custom color when SHOW PATH IN MIDDLE PANEL is selected](https://user-images.githubusercontent.com/22151742/75568653-af518f80-5a21-11ea-9703-77d3b92ff31c.png)

**Comment by lornajane** [comment]
This is great, but I don't see any activity required from our side so I'm closing the issue. Please let us know if I missed something.
