### ISSUE TITLE
Multiple Themes / Theme Selector

### ISSUE THREAD

**Issue by AngellusMortis** [Redocly/redoc#987]
It would be great if there was a way to provide multiple themes, like a dark theme and a light theme (would be really awesome if ReDoc _came_ with a light and a dark theme be default). Then if multiple themes are provided, the user is somewhere given a selector to pick between them and the choice is stored in a cookie/local storage so it is remembered.

**Comment by RomanHotsiy** [comment]
This is out of scope. It can be implemented easily on top of Redoc.
