### ISSUE TITLE
showing all specs in one page like stripe api reference

### ISSUE THREAD

**Issue by sirishayyagari** [Redocly/redoc#988]
I am looking to load multiple specs one below the other, so the actual reference page is just one big page. is there a way to do it.

**Comment by nanov** [comment]
I am not sure what you mean, but you could combine your specs into one with the appropriate tags/tagGroups before using the spec in ReDoc, you can either write a custom pre-processor or use something [like this](https://github.com/Rebilly/swagger-combine).

**Comment by sirishayyagari** [comment]
to explain it clearly, we have lot of api references, for which we would like to have one documentation page which will list all the api references from multiple specs. after using swagger-combine, i am getting an error 


`SyntaxError: Error resolving $ref pointer "references.json#/components/schemas/AccountVerificationResponse1". 
Token "components" does not exist.
    at Function.syntax (redoc.standalone.js:40)
    at u.resolve (redoc.standalone.js:40)
    at o.resolve (redoc.standalone.js:40)
    at a._resolve (redoc.standalone.js:84)
    at s (redoc.standalone.js:84)
    at redoc.standalone.js:84
    at Array.forEach (<anonymous>)
    at a (redoc.standalone.js:84)
    at redoc.standalone.js:84
    at Array.forEach (<anonymous>)`

**Comment by nanov** [comment]
Well, it's not my library and I don't know how exactly you use it. You could always combine those manually.

**Comment by sirishayyagari** [comment]
i am doing a mix of both.. got it.. i will look for alternative

**Comment by RomanHotsiy** [comment]
Closing this issue. Out of scope.

P.S. There is multiple specs support in Redocly API Reference (aka Redoc Pro). It is still in private beta. Contact us at team@redoc.ly for more details.
