### ISSUE TITLE
Discriminator enum dropdown not fully shown - overlayed by the next model panel

### ISSUE THREAD

**Issue by dmitrymurashenkov** [Redocly/redoc#989]
Simple layout issue - if discriminator property is shown last in particular model and dropdown has many values - then expanded dropdown is not fully shown because is gets overlayed by the next model panel.

Screenshot:
https://drive.google.com/open?id=1TRSCFIjnP-TMOx4SCDOHgYRbHyqcg9Ih

**Comment by neluzhin** [comment]
Duplicate #913.

**Comment by RomanHotsiy** [comment]
Thanks @neluzhin
