### ISSUE TITLE
[#814] Unfixed problem, dependency 'core-js/es6/promise' is missing

### ISSUE THREAD

**Issue by eau-de-la-seine** [Redocly/redoc#997]
Hi, I still have the problem declared in the [issue number 814](https://github.com/Redocly/redoc/issues/814)

**Problem**:
```
Failed to compile
./node_modules/redoc/bundles/redoc.lib.js
Module not found: Can't resolve 'core-js/es6/promise' in '/home/gekinci/projects/pmu/pmu-redoc/node_modules/redoc/bundles'
```

**My dependencies** (package.json):
```
  "dependencies": {
    "core-js": "^3.1.4",
    "es6-promise": "^4.2.8",
    "mobx": "^4.13.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1",
    "redoc": "^2.0.0-rc.10",
    "styled-components": "^4.3.2"
  }
```

Installed with:
```
npm install mobx@^4.2.0 styled-components core-js es6-promise
npm install redoc --save
```

So I've installed the following dependency: `core-js` but nothing has changed. So I've looked into your Redoc code in `/node_modules/redoc/bundles/redoc.lib.js`:
```
module.exports = require("core-js/es6/promise");
```

But what you're looking for  with `core-js` is installed here: `core-js/es/promise`, not here: `core-js/es6/promise`

**Workaround**:
So my **workaround** was to copy/paste the existing `/node_modules/core-js/es` folder and rename it to `/node_modules/core-js/es6`. Is this a bug or did I miss something during the installation of Redoc with npm?

**Comment by eau-de-la-seine** [comment]
I don't understand why you have closed this issue without indicating what the problem was, or what I've had to do to resolve it.
The best workaround I've found was to install this old version of `core-js`: **2.6.8** because it contains `es6` (also `es5` and `es7`) folders.

**Comment by qw-in** [comment]
I updated `2.0.0-rc.12 => 2.0.0-rc.14` and ran into this issue. Reverting for now but +1

**Comment by RomanHotsiy** [comment]
@eau-de-la-seine Just upgrading redoc to rc.14 and core-js to version 3 should work.

@qw-in 	could you provide more details? Have you upgraded core-js to version 3?

**Comment by qw-in** [comment]
@RomanHotsiy will give that a shot, thanks

Maybe corejs@3 should be added [here](https://github.com/Redocly/redoc#usage-as-a-react-component)?

**Comment by eau-de-la-seine** [comment]
> 
> 
> @RomanHotsiy will give that a shot, thanks
> 
> Maybe corejs@3 should be added [here](https://github.com/Redocly/redoc#usage-as-a-react-component)?

Yes, and there too: https://www.npmjs.com/package/redoc#usage-as-a-react-component ;)

**Comment by transitive-bullshit** [comment]
@RomanHotsiy please reopen this issue until #1018 or another fix is resolved.

Thanks!

**Comment by MarcusCemes** [comment]
I opened an issue [here](https://github.com/gatsbyjs/gatsby/issues/17136) when encountering this problem with Gatsby (*does not occur with skeleton Webpack config*).

I didn't find this originally as it was closed, this issue should be open.

@RomanHotsiy Can confirm a similar error occurs with `core-js 3.2.1` and `redoc 2.0.0-rc.14`.

I get `Module not found: Error: Can't resolve 'core-js/es/promise'` (and not `es6`), which *is* a valid export, more context is available in the above Gatsby issue.

While on the subject, would it not be easier creating a `redoc-react` package which includes all the required peer dependencies instead of clogging up package.json with extra requirements?

**Comment by thovden** [comment]
@MarcusCemes Gatsby currently will hardcode `core-js@2` causing this error https://github.com/gatsbyjs/gatsby/issues/17136 . I agree though that redoc should not require a specific `core-js` version externally.

**Comment by donysukardi** [comment]
I used [patch-package](https://github.com/ds300/patch-package) as a workaround to get Gatsby working with redoc by changing the import to `core-js/es6/promise`

**Comment by seanlaff** [comment]
#1018 Was just a documentation change, is the a reason this dep wasn't added as a real peerDependency?

**Comment by israteneda** [comment]
[This answer](https://github.com/gatsbyjs/gatsby/issues/17136#issuecomment-568036690) solves the issue for my documentation with Gatsby.

**Comment by adamsoffer** [comment]
I'm still encountering this error. Can we reopen?

**Comment by RomanHotsiy** [comment]
@adamsoffer any details?
