### ISSUE TITLE
If the escape sequence is a string, the backslash is doubled.

### ISSUE THREAD

**Issue by yamamotoshuto** [Redocly/redoc#999]
If I write such an example to express an escape sequence like `\n` or `\t` as a string in the sample,

```
example: 'foo \n bar'
```

The sample is output like this.

```
{
    "test": "foo \\n bar"
}
```

There is no way to express this sample.

```
{
    "test": "foo \n bar"
}
```

**Comment by RomanHotsiy** [comment]
In the upcoming version of Redoc (coming a bit later today) use: 

```yaml
example: "foo \n bar"
```
